INSERT INTO words (word, level, language_code) VALUES
('casa', 'A1', 'pt'),
('porta', 'A1', 'pt'),
('janela', 'A1', 'pt'),
('mesa', 'A1', 'pt'),
('cadeira', 'A1', 'pt'),
('livro', 'A1', 'pt'),
('caneta', 'A1', 'pt'),
('escola', 'A1', 'pt'),
('professor', 'A1', 'pt'),
('estudante', 'A1', 'pt'),
('maçã', 'A1', 'pt'),
('água', 'A1', 'pt'),
('comida', 'A1', 'pt'),
('carro', 'A1', 'pt'),
('ônibus', 'A1', 'pt'),
('rua', 'A1', 'pt'),
('amigo', 'A1', 'pt'),
('família', 'A1', 'pt'),
('mãe', 'A1', 'pt'),
('pai', 'A1', 'pt'),
('irmã', 'A1', 'pt'),
('irmão', 'A1', 'pt'),
('dia', 'A1', 'pt'),
('noite', 'A1', 'pt'),
('manhã', 'A1', 'pt'),
('noite', 'A1', 'pt'),
('olá', 'A1', 'pt'),
('adeus', 'A1', 'pt'),
('por favor', 'A1', 'pt'),
('obrigado', 'A1', 'pt'),
('sim', 'A1', 'pt'),
('não', 'A1', 'pt'),
('vermelho', 'A1', 'pt'),
('azul', 'A1', 'pt'),
('verde', 'A1', 'pt'),
('branco', 'A1', 'pt'),
('preto', 'A1', 'pt'),
('pequeno', 'A1', 'pt'),
('grande', 'A1', 'pt'),
('bom', 'A1', 'pt'),
('ruim', 'A1', 'pt'),
('quente', 'A1', 'pt'),
('frio', 'A1', 'pt'),
('café', 'A1', 'pt'),
('chá', 'A1', 'pt'),
('dinheiro', 'A1', 'pt'),
('trabalhar', 'A1', 'pt'),
('lar', 'A1', 'pt'),
('comprar', 'A1', 'pt'),
('mercado', 'A1', 'pt'),
('comida', 'A1', 'pt'),
('bebida', 'A1', 'pt'),
('cidade', 'A1', 'pt'),
('parque', 'A1', 'pt'),
('rua', 'A1', 'pt'),
('ponto de ônibus', 'A1', 'pt'),
('trem', 'A1', 'pt'),
('estação', 'A1', 'pt'),
('hotel', 'A1', 'pt'),
('sala', 'A1', 'pt'),
('cama', 'A1', 'pt'),
('doutor', 'A1', 'pt'),
('hospital', 'A1', 'pt'),
('escola', 'A1', 'pt'),
('universidade', 'A1', 'pt'),
('computador', 'A1', 'pt'),
('telefone', 'A1', 'pt'),
('televisão', 'A1', 'pt'),
('música', 'A1', 'pt'),
('canção', 'A1', 'pt'),
('filme', 'A1', 'pt'),
('jogo', 'A1', 'pt'),
('futebol', 'A1', 'pt'),
('bola', 'A1', 'pt'),
('água', 'A1', 'pt'),
('chuva', 'A1', 'pt'),
('sol', 'A1', 'pt'),
('céu', 'A1', 'pt'),
('árvore', 'A1', 'pt'),
('flor', 'A1', 'pt'),
('animal', 'A1', 'pt'),
('gato', 'A1', 'pt'),
('cachorro', 'A1', 'pt'),
('pássaro', 'A1', 'pt'),
('peixe', 'A1', 'pt'),
('homem', 'A1', 'pt'),
('mulher', 'A1', 'pt'),
('criança', 'A1', 'pt'),
('pessoas', 'A1', 'pt'),
('rua', 'A1', 'pt'),
('lugar', 'A1', 'pt'),
('tempo', 'A1', 'pt'),
('ano', 'A1', 'pt'),
('mês', 'A1', 'pt'),
('semana', 'A1', 'pt'),
('hoje', 'A1', 'pt'),
('amanhã', 'A1', 'pt'),
('ontem', 'A1', 'pt'),
('nome', 'A1', 'pt'),
('endereço', 'A1', 'pt'),
('número', 'A1', 'pt'),
('aeroporto', 'A2', 'pt'),
('voo', 'A2', 'pt'),
('bilhete', 'A2', 'pt'),
('passaporte', 'A2', 'pt'),
('viagem', 'A2', 'pt'),
('feriado', 'A2', 'pt'),
('jornada', 'A2', 'pt'),
('bagagem', 'A2', 'pt'),
('estação', 'A2', 'pt'),
('plataforma', 'A2', 'pt'),
('restaurante', 'A2', 'pt'),
('café', 'A2', 'pt'),
('café da manhã', 'A2', 'pt'),
('almoço', 'A2', 'pt'),
('jantar', 'A2', 'pt'),
('vegetais', 'A2', 'pt'),
('fruta', 'A2', 'pt'),
('carne', 'A2', 'pt'),
('frango', 'A2', 'pt'),
('carne bovina', 'A2', 'pt'),
('peixe', 'A2', 'pt'),
('pão', 'A2', 'pt'),
('arroz', 'A2', 'pt'),
('macarrão', 'A2', 'pt'),
('sopa', 'A2', 'pt'),
('açúcar', 'A2', 'pt'),
('sal', 'A2', 'pt'),
('pimenta', 'A2', 'pt'),
('óleo', 'A2', 'pt'),
('compras', 'A2', 'pt'),
('roupas', 'A2', 'pt'),
('camisa', 'A2', 'pt'),
('calça', 'A2', 'pt'),
('vestir', 'A2', 'pt'),
('sapato', 'A2', 'pt'),
('chapéu', 'A2', 'pt'),
('jaqueta', 'A2', 'pt'),
('casaco', 'A2', 'pt'),
('clima', 'A2', 'pt'),
('neve', 'A2', 'pt'),
('vento', 'A2', 'pt'),
('tempestade', 'A2', 'pt'),
('hotéis', 'A2', 'pt'),
('convidado', 'A2', 'pt'),
('serviço', 'A2', 'pt'),
('recepção', 'A2', 'pt'),
('chave', 'A2', 'pt'),
('reserva', 'A2', 'pt'),
('praia', 'A2', 'pt'),
('mar', 'A2', 'pt'),
('natação', 'A2', 'pt'),
('piscina', 'A2', 'pt'),
('montanha', 'A2', 'pt'),
('aldeia', 'A2', 'pt'),
('país', 'A2', 'pt'),
('linguagem', 'A2', 'pt'),
('estrangeiro', 'A2', 'pt'),
('exame', 'A2', 'pt'),
('teste', 'A2', 'pt'),
('trabalho de casa', 'A2', 'pt'),
('sala de aula', 'A2', 'pt'),
('assunto', 'A2', 'pt'),
('matemática', 'A2', 'pt'),
('história', 'A2', 'pt'),
('ciência', 'A2', 'pt'),
('biblioteca', 'A2', 'pt'),
('livraria', 'A2', 'pt'),
('computador', 'A2', 'pt'),
('Internet', 'A2', 'pt'),
('e-mail', 'A2', 'pt'),
('mensagem', 'A2', 'pt'),
('carta', 'A2', 'pt'),
('publicar', 'A2', 'pt'),
('banco', 'A2', 'pt'),
('dinheiro', 'A2', 'pt'),
('Cartão de crédito', 'A2', 'pt'),
('preço', 'A2', 'pt'),
('barato', 'A2', 'pt'),
('caro', 'A2', 'pt'),
('pergunta', 'A2', 'pt'),
('responder', 'A2', 'pt'),
('explicar', 'A2', 'pt'),
('ajuda', 'A2', 'pt'),
('problema', 'A2', 'pt'),
('solução', 'A2', 'pt'),
('saúde', 'A2', 'pt'),
('medicamento', 'A2', 'pt'),
('doutor', 'A2', 'pt'),
('enfermeira', 'A2', 'pt'),
('paciente', 'A2', 'pt'),
('encontro', 'A2', 'pt'),
('febre', 'A2', 'pt'),
('tosse', 'A2', 'pt'),
('experiência', 'B1', 'pt'),
('aventura', 'B1', 'pt'),
('opinião', 'B1', 'pt'),
('discussão', 'B1', 'pt'),
('argumento', 'B1', 'pt'),
('decisão', 'B1', 'pt'),
('razão', 'B1', 'pt'),
('oportunidade', 'B1', 'pt'),
('desafio', 'B1', 'pt'),
('sucesso', 'B1', 'pt'),
('falha', 'B1', 'pt'),
('meta', 'B1', 'pt'),
('plano', 'B1', 'pt'),
('projeto', 'B1', 'pt'),
('conhecimento', 'B1', 'pt'),
('habilidade', 'B1', 'pt'),
('habilidade', 'B1', 'pt'),
('melhoria', 'B1', 'pt'),
('treinamento', 'B1', 'pt'),
('Entrevista de emprego', 'B1', 'pt'),
('aplicativo', 'B1', 'pt'),
('carreira', 'B1', 'pt'),
('gerente', 'B1', 'pt'),
('colega', 'B1', 'pt'),
('reunião', 'B1', 'pt'),
('tarefa', 'B1', 'pt'),
('responsabilidade', 'B1', 'pt'),
('viagem de férias', 'B1', 'pt'),
('cultura', 'B1', 'pt'),
('tradição', 'B1', 'pt'),
('personalizado', 'B1', 'pt'),
('festival', 'B1', 'pt'),
('celebração', 'B1', 'pt'),
('desempenho', 'B1', 'pt'),
('concerto', 'B1', 'pt'),
('teatro', 'B1', 'pt'),
('exposição', 'B1', 'pt'),
('pintura', 'B1', 'pt'),
('escultura', 'B1', 'pt'),
('museu', 'B1', 'pt'),
('Livro de História', 'B1', 'pt'),
('ficção', 'B1', 'pt'),
('poema', 'B1', 'pt'),
('romance', 'B1', 'pt'),
('personagem', 'B1', 'pt'),
('trama', 'B1', 'pt'),
('história', 'B1', 'pt'),
('jornal', 'B1', 'pt'),
('revista', 'B1', 'pt'),
('artigo', 'B1', 'pt'),
('relatório', 'B1', 'pt'),
('apresentação', 'B1', 'pt'),
('palestra', 'B1', 'pt'),
('educação', 'B1', 'pt'),
('universidade', 'B1', 'pt'),
('grau', 'B1', 'pt'),
('diploma', 'B1', 'pt'),
('Certificado', 'B1', 'pt'),
('ambiente', 'B1', 'pt'),
('natureza', 'B1', 'pt'),
('reciclagem', 'B1', 'pt'),
('poluição', 'B1', 'pt'),
('mudança climática', 'B1', 'pt'),
('Aquecimento global', 'B1', 'pt'),
('energia', 'B1', 'pt'),
('tecnologia', 'B1', 'pt'),
('inovação', 'B1', 'pt'),
('invenção', 'B1', 'pt'),
('dispositivo', 'B1', 'pt'),
('máquina', 'B1', 'pt'),
('programa de computador', 'B1', 'pt'),
('site', 'B1', 'pt'),
('aplicativo', 'B1', 'pt'),
('mídia social', 'B1', 'pt'),
('comunicação', 'B1', 'pt'),
('conversa', 'B1', 'pt'),
('interação', 'B1', 'pt'),
('relação', 'B1', 'pt'),
('amizade', 'B1', 'pt'),
('casado', 'B1', 'pt'),
('vida familiar', 'B1', 'pt'),
('felicidade', 'B1', 'pt'),
('raiva', 'B1', 'pt'),
('temer', 'B1', 'pt'),
('ter esperança', 'B1', 'pt'),
('sonhar', 'B1', 'pt'),
('ambição', 'B1', 'pt'),
('motivação', 'B1', 'pt'),
('confiança', 'B1', 'pt'),
('curiosidade', 'B1', 'pt'),
('paciência', 'B1', 'pt'),
('inovação', 'B2', 'pt'),
('desenvolvimento', 'B2', 'pt'),
('pesquisar', 'B2', 'pt'),
('análise', 'B2', 'pt'),
('interpretação', 'B2', 'pt'),
('argumentação', 'B2', 'pt'),
('comparação', 'B2', 'pt'),
('hipótese', 'B2', 'pt'),
('teoria', 'B2', 'pt'),
('experimentar', 'B2', 'pt'),
('evidência', 'B2', 'pt'),
('método', 'B2', 'pt'),
('conclusão', 'B2', 'pt'),
('observação', 'B2', 'pt'),
('perspectiva', 'B2', 'pt'),
('suposição', 'B2', 'pt'),
('contexto', 'B2', 'pt'),
('Critérios', 'B2', 'pt'),
('princípio', 'B2', 'pt'),
('prioridade', 'B2', 'pt'),
('complexidade', 'B2', 'pt'),
('eficiência', 'B2', 'pt'),
('produtividade', 'B2', 'pt'),
('investimento', 'B2', 'pt'),
('economia', 'B2', 'pt'),
('financiar', 'B2', 'pt'),
('negociação', 'B2', 'pt'),
('acordo', 'B2', 'pt'),
('contrato', 'B2', 'pt'),
('política', 'B2', 'pt'),
('governo', 'B2', 'pt'),
('política', 'B2', 'pt'),
('eleição', 'B2', 'pt'),
('democracia', 'B2', 'pt'),
('liberdade', 'B2', 'pt'),
('justiça', 'B2', 'pt'),
('igualdade', 'B2', 'pt'),
('lei', 'B2', 'pt'),
('crime', 'B2', 'pt'),
('pena', 'B2', 'pt'),
('punição', 'B2', 'pt'),
('segurança', 'B2', 'pt'),
('conflito', 'B2', 'pt'),
('guerra', 'B2', 'pt'),
('paz', 'B2', 'pt'),
('violência', 'B2', 'pt'),
('terrorismo', 'B2', 'pt'),
('Globalização', 'B2', 'pt'),
('integração', 'B2', 'pt'),
('diversidade', 'B2', 'pt'),
('identidade', 'B2', 'pt'),
('migração', 'B2', 'pt'),
('refugiado', 'B2', 'pt'),
('comunidade', 'B2', 'pt'),
('rede', 'B2', 'pt'),
('organização', 'B2', 'pt'),
('instituição', 'B2', 'pt'),
('liderança', 'B2', 'pt'),
('gerenciamento', 'B2', 'pt'),
('planejamento', 'B2', 'pt'),
('estratégia', 'B2', 'pt'),
('iniciativa', 'B2', 'pt'),
('criatividade', 'B2', 'pt'),
('colaboração', 'B2', 'pt'),
('trabalho em equipe', 'B2', 'pt'),
('responsabilidade', 'B2', 'pt'),
('responsabilidade', 'B2', 'pt'),
('sustentabilidade', 'B2', 'pt'),
('Proteção Ambiental', 'B2', 'pt'),
('energia renovável', 'B2', 'pt'),
('processo de inovação', 'B2', 'pt'),
('pensamento crítico', 'B2', 'pt'),
('resolução de problemas', 'B2', 'pt'),
('tomando uma decisão', 'B2', 'pt'),
('Gerenciamento de tempo', 'B2', 'pt'),
('autodisciplina', 'B2', 'pt'),
('adaptação', 'B2', 'pt'),
('resiliência', 'B2', 'pt'),
('independência', 'B2', 'pt'),
('cooperação', 'B2', 'pt'),
('confiar', 'B2', 'pt'),
('respeito', 'B2', 'pt'),
('empatia', 'B2', 'pt'),
('lealdade', 'B2', 'pt'),
('integridade', 'B2', 'pt'),
('ética', 'B2', 'pt'),
('moralidade', 'B2', 'pt'),
('filosofia', 'B2', 'pt'),
('psicologia', 'B2', 'pt'),
('sociologia', 'B2', 'pt'),
('biologia', 'B2', 'pt'),
('química', 'B2', 'pt'),
('física', 'B2', 'pt'),
('Análise crítica', 'C1', 'pt'),
('raciocínio lógico', 'C1', 'pt'),
('interpretação', 'C1', 'pt'),
('comparação profunda', 'C1', 'pt'),
('Conclusão científica', 'C1', 'pt'),
('hipótese complexa', 'C1', 'pt'),
('teoria avançada', 'C1', 'pt'),
('experimento profundo', 'C1', 'pt'),
('Avaliação abrangente', 'C1', 'pt'),
('discussão filosófica', 'C1', 'pt'),
('argumento forte', 'C1', 'pt'),
('evidência tangível', 'C1', 'pt'),
('evidência contraditória', 'C1', 'pt'),
('conceito abstrato', 'C1', 'pt'),
('posição ética', 'C1', 'pt'),
('valor supremo', 'C1', 'pt'),
('princípio fundamental', 'C1', 'pt'),
('Prioridade superior', 'C1', 'pt'),
('grande responsabilidade', 'C1', 'pt'),
('decisão crucial', 'C1', 'pt'),
('gerenciamento complexo', 'C1', 'pt'),
('planejamento estratégico', 'C1', 'pt'),
('desenvolvimento sustentável', 'C1', 'pt'),
('inovação moderna', 'C1', 'pt'),
('criatividade avançada', 'C1', 'pt'),
('nova descoberta', 'C1', 'pt'),
('invenção inovadora', 'C1', 'pt'),
('Análise econômica', 'C1', 'pt'),
('Relatório Financeiro', 'C1', 'pt'),
('Projeto em larga escala', 'C1', 'pt'),
('negociações internacionais', 'C1', 'pt'),
('acordo formal', 'C1', 'pt'),
('estratégia eficaz', 'C1', 'pt'),
('Instituição Global', 'C1', 'pt'),
('Centro de Pesquisa', 'C1', 'pt'),
('Estudo científico avançado', 'C1', 'pt'),
('revisão crítica', 'C1', 'pt'),
('interpretação filosófica', 'C1', 'pt'),
('abordagem sistemática', 'C1', 'pt'),
('teoria moderna', 'C1', 'pt'),
('pesquisa aplicada', 'C1', 'pt'),
('experimento prático', 'C1', 'pt'),
('avaliação objetiva', 'C1', 'pt'),
('resultados detalhados', 'C1', 'pt'),
('debate avançado', 'C1', 'pt'),
('estudo comparativo', 'C1', 'pt'),
('pesquisa de campo', 'C1', 'pt'),
('Recomendação prática', 'C1', 'pt'),
('habilidade avançada', 'C1', 'pt'),
('estrutura conceitual', 'C1', 'pt'),
('planejamento preciso', 'C1', 'pt'),
('estratégia de longo prazo', 'C1', 'pt'),
('avaliação de risco', 'C1', 'pt'),
('Revisão Acadêmica', 'C1', 'pt'),
('Projeto de pesquisa', 'C1', 'pt'),
('Inovação científica', 'C1', 'pt'),
('desenvolvimento tecnológico', 'C1', 'pt'),
('Análise literária', 'C1', 'pt'),
('descobertas científicas', 'C1', 'pt'),
('interpretação avançada', 'C1', 'pt'),
('visão holística', 'C1', 'pt'),
('plano de implementação', 'C1', 'pt'),
('decisão estratégica', 'C1', 'pt'),
('Gerenciamento de recursos', 'C1', 'pt'),
('desafios complexos', 'C1', 'pt'),
('soluções inovadoras', 'C1', 'pt'),
('abordagem abrangente', 'C1', 'pt'),
('Análise de dados', 'C1', 'pt'),
('Teste de hipótese', 'C1', 'pt'),
('Estudo de caso', 'C1', 'pt'),
('Trabalho de campo avançado', 'C1', 'pt'),
('Revisão filosófica', 'C1', 'pt'),
('Projeto de pesquisa aplicada', 'C1', 'pt'),
('discussão acadêmica', 'C1', 'pt'),
('Avaliação estratégica', 'C1', 'pt'),
('Recomendações práticas', 'C1', 'pt'),
('plano de trabalho', 'C1', 'pt'),
('gerenciamento de projetos', 'C1', 'pt'),
('Publicação acadêmica', 'C1', 'pt'),
('descoberta científica', 'C1', 'pt'),
('inovação aplicada', 'C1', 'pt'),
('desenvolvimento contínuo', 'C1', 'pt'),
('Análise de dados aprofundada', 'C1', 'pt'),
('Experiência de pesquisa', 'C1', 'pt'),
('Interpretação científica', 'C1', 'pt'),
('perspectiva crítica', 'C1', 'pt');
