INSERT INTO words (word, level, language_code) VALUES
('casă', 'A1', 'ro'),
('uşă', 'A1', 'ro'),
('fereastră', 'A1', 'ro'),
('masă', 'A1', 'ro'),
('scaun', 'A1', 'ro'),
('carte', 'A1', 'ro'),
('stilou', 'A1', 'ro'),
('şcoală', 'A1', 'ro'),
('profesor', 'A1', 'ro'),
('student', 'A1', 'ro'),
('măr', 'A1', 'ro'),
('apă', 'A1', 'ro'),
('mâncare', 'A1', 'ro'),
('mașină', 'A1', 'ro'),
('autobuz', 'A1', 'ro'),
('stradă', 'A1', 'ro'),
('prieten', 'A1', 'ro'),
('familial', 'A1', 'ro'),
('mamă', 'A1', 'ro'),
('tată', 'A1', 'ro'),
('sora', 'A1', 'ro'),
('frate', 'A1', 'ro'),
('zi', 'A1', 'ro'),
('noapte', 'A1', 'ro'),
('dimineaţă', 'A1', 'ro'),
('seară', 'A1', 'ro'),
('Buna ziua', 'A1', 'ro'),
('La revedere', 'A1', 'ro'),
('Vă rog', 'A1', 'ro'),
('Mulțumesc', 'A1', 'ro'),
('Da', 'A1', 'ro'),
('nu', 'A1', 'ro'),
('roşu', 'A1', 'ro'),
('albastru', 'A1', 'ro'),
('verde', 'A1', 'ro'),
('alb', 'A1', 'ro'),
('negru', 'A1', 'ro'),
('mic', 'A1', 'ro'),
('mare', 'A1', 'ro'),
('bun', 'A1', 'ro'),
('rău', 'A1', 'ro'),
('fierbinte', 'A1', 'ro'),
('rece', 'A1', 'ro'),
('cafea', 'A1', 'ro'),
('ceai', 'A1', 'ro'),
('bani', 'A1', 'ro'),
('lucru', 'A1', 'ro'),
('acasă', 'A1', 'ro'),
('magazin', 'A1', 'ro'),
('piaţă', 'A1', 'ro'),
('mâncare', 'A1', 'ro'),
('bea', 'A1', 'ro'),
('oraş', 'A1', 'ro'),
('parc', 'A1', 'ro'),
('stradă', 'A1', 'ro'),
('staţie de autobuz', 'A1', 'ro'),
('tren', 'A1', 'ro'),
('stație', 'A1', 'ro'),
('hotel', 'A1', 'ro'),
('cameră', 'A1', 'ro'),
('pat', 'A1', 'ro'),
('doctor', 'A1', 'ro'),
('spital', 'A1', 'ro'),
('şcoală', 'A1', 'ro'),
('universitate', 'A1', 'ro'),
('calculator', 'A1', 'ro'),
('telefon', 'A1', 'ro'),
('televiziune', 'A1', 'ro'),
('muzică', 'A1', 'ro'),
('cântec', 'A1', 'ro'),
('film', 'A1', 'ro'),
('joc', 'A1', 'ro'),
('fotbal', 'A1', 'ro'),
('Mingea', 'A1', 'ro'),
('apă', 'A1', 'ro'),
('ploaie', 'A1', 'ro'),
('soare', 'A1', 'ro'),
('cer', 'A1', 'ro'),
('copac', 'A1', 'ro'),
('floare', 'A1', 'ro'),
('animal', 'A1', 'ro'),
('pisică', 'A1', 'ro'),
('câine', 'A1', 'ro'),
('pasăre', 'A1', 'ro'),
('peşte', 'A1', 'ro'),
('om', 'A1', 'ro'),
('femeie', 'A1', 'ro'),
('copil', 'A1', 'ro'),
('oameni', 'A1', 'ro'),
('stradă', 'A1', 'ro'),
('loc', 'A1', 'ro'),
('timp', 'A1', 'ro'),
('an', 'A1', 'ro'),
('lună', 'A1', 'ro'),
('săptămână', 'A1', 'ro'),
('astăzi', 'A1', 'ro'),
('mâine', 'A1', 'ro'),
('ieri', 'A1', 'ro'),
('nume', 'A1', 'ro'),
('adresa', 'A1', 'ro'),
('număr', 'A1', 'ro'),
('aeroport', 'A2', 'ro'),
('zbor', 'A2', 'ro'),
('bilet', 'A2', 'ro'),
('paşaport', 'A2', 'ro'),
('voiaj', 'A2', 'ro'),
('vacanţă', 'A2', 'ro'),
('călătorie', 'A2', 'ro'),
('bagaje', 'A2', 'ro'),
('stație', 'A2', 'ro'),
('platformă', 'A2', 'ro'),
('restaurant', 'A2', 'ro'),
('cafenea', 'A2', 'ro'),
('mic dejun', 'A2', 'ro'),
('prânz', 'A2', 'ro'),
('cină', 'A2', 'ro'),
('legume', 'A2', 'ro'),
('fructe', 'A2', 'ro'),
('carne', 'A2', 'ro'),
('pui', 'A2', 'ro'),
('vită', 'A2', 'ro'),
('peşte', 'A2', 'ro'),
('pâine', 'A2', 'ro'),
('orez', 'A2', 'ro'),
('paste', 'A2', 'ro'),
('supă', 'A2', 'ro'),
('zahăr', 'A2', 'ro'),
('sare', 'A2', 'ro'),
('piper', 'A2', 'ro'),
('ulei', 'A2', 'ro'),
('cumpărături', 'A2', 'ro'),
('haine', 'A2', 'ro'),
('cămaşă', 'A2', 'ro'),
('pantaloni', 'A2', 'ro'),
('rochie', 'A2', 'ro'),
('pantofi', 'A2', 'ro'),
('pălărie', 'A2', 'ro'),
('sacou', 'A2', 'ro'),
('haina', 'A2', 'ro'),
('vreme', 'A2', 'ro'),
('zăpadă', 'A2', 'ro'),
('vânt', 'A2', 'ro'),
('furtună', 'A2', 'ro'),
('hoteluri', 'A2', 'ro'),
('oaspete', 'A2', 'ro'),
('serviciu', 'A2', 'ro'),
('recepţie', 'A2', 'ro'),
('cheie', 'A2', 'ro'),
('rezervare', 'A2', 'ro'),
('plajă', 'A2', 'ro'),
('mare', 'A2', 'ro'),
('înot', 'A2', 'ro'),
('piscină', 'A2', 'ro'),
('munte', 'A2', 'ro'),
('sat', 'A2', 'ro'),
('ţară', 'A2', 'ro'),
('limbă', 'A2', 'ro'),
('străin', 'A2', 'ro'),
('examen', 'A2', 'ro'),
('test', 'A2', 'ro'),
('teme pentru acasă', 'A2', 'ro'),
('sala de clasă', 'A2', 'ro'),
('subiect', 'A2', 'ro'),
('Matematică', 'A2', 'ro'),
('istorie', 'A2', 'ro'),
('ştiinţă', 'A2', 'ro'),
('bibliotecă', 'A2', 'ro'),
('librărie', 'A2', 'ro'),
('calculator', 'A2', 'ro'),
('Internet', 'A2', 'ro'),
('e-mail', 'A2', 'ro'),
('mesaj', 'A2', 'ro'),
('scrisoare', 'A2', 'ro'),
('post', 'A2', 'ro'),
('bancar', 'A2', 'ro'),
('bani', 'A2', 'ro'),
('Card de credit', 'A2', 'ro'),
('preţ', 'A2', 'ro'),
('ieftin', 'A2', 'ro'),
('scump', 'A2', 'ro'),
('întrebare', 'A2', 'ro'),
('răspuns', 'A2', 'ro'),
('explica', 'A2', 'ro'),
('Ajutor', 'A2', 'ro'),
('problemă', 'A2', 'ro'),
('soluţie', 'A2', 'ro'),
('sănătate', 'A2', 'ro'),
('medicament', 'A2', 'ro'),
('doctor', 'A2', 'ro'),
('asistentă', 'A2', 'ro'),
('pacient', 'A2', 'ro'),
('numire', 'A2', 'ro'),
('febră', 'A2', 'ro'),
('tuse', 'A2', 'ro'),
('experienţă', 'B1', 'ro'),
('aventură', 'B1', 'ro'),
('opinie', 'B1', 'ro'),
('discuţie', 'B1', 'ro'),
('argument', 'B1', 'ro'),
('decizie', 'B1', 'ro'),
('motiv', 'B1', 'ro'),
('Oportunitate', 'B1', 'ro'),
('provocare', 'B1', 'ro'),
('succes', 'B1', 'ro'),
('eșec', 'B1', 'ro'),
('obiectiv', 'B1', 'ro'),
('plan', 'B1', 'ro'),
('proiect', 'B1', 'ro'),
('cunoştinţe', 'B1', 'ro'),
('abilitate', 'B1', 'ro'),
('capacitate', 'B1', 'ro'),
('îmbunătăţire', 'B1', 'ro'),
('instruire', 'B1', 'ro'),
('Interviu de muncă', 'B1', 'ro'),
('aplicație', 'B1', 'ro'),
('carieră', 'B1', 'ro'),
('manager', 'B1', 'ro'),
('coleg', 'B1', 'ro'),
('întâlnire', 'B1', 'ro'),
('sarcină', 'B1', 'ro'),
('responsabilitate', 'B1', 'ro'),
('Călătorie de vacanță', 'B1', 'ro'),
('cultură', 'B1', 'ro'),
('tradiţie', 'B1', 'ro'),
('obicei', 'B1', 'ro'),
('festival', 'B1', 'ro'),
('celebrare', 'B1', 'ro'),
('performanţă', 'B1', 'ro'),
('concert', 'B1', 'ro'),
('teatru', 'B1', 'ro'),
('expoziţie', 'B1', 'ro'),
('pictură', 'B1', 'ro'),
('sculptură', 'B1', 'ro'),
('muzeu', 'B1', 'ro'),
('Cartea de istorie', 'B1', 'ro'),
('ficţiune', 'B1', 'ro'),
('poem', 'B1', 'ro'),
('roman', 'B1', 'ro'),
('caracter', 'B1', 'ro'),
('complot', 'B1', 'ro'),
('poveste', 'B1', 'ro'),
('ziar', 'B1', 'ro'),
('revistă', 'B1', 'ro'),
('articol', 'B1', 'ro'),
('raport', 'B1', 'ro'),
('prezentare', 'B1', 'ro'),
('curs', 'B1', 'ro'),
('educaţie', 'B1', 'ro'),
('universitate', 'B1', 'ro'),
('grad', 'B1', 'ro'),
('diplomă', 'B1', 'ro'),
('certificat', 'B1', 'ro'),
('mediu', 'B1', 'ro'),
('natură', 'B1', 'ro'),
('Reciclare', 'B1', 'ro'),
('poluare', 'B1', 'ro'),
('Schimbările climatice', 'B1', 'ro'),
('încălzire globală', 'B1', 'ro'),
('energie', 'B1', 'ro'),
('tehnologie', 'B1', 'ro'),
('inovaţie', 'B1', 'ro'),
('invenţie', 'B1', 'ro'),
('dispozitiv', 'B1', 'ro'),
('maşină', 'B1', 'ro'),
('Program de calculator', 'B1', 'ro'),
('site -ul web', 'B1', 'ro'),
('aplicație', 'B1', 'ro'),
('Social media', 'B1', 'ro'),
('comunicare', 'B1', 'ro'),
('conversaţie', 'B1', 'ro'),
('interacţiune', 'B1', 'ro'),
('relaţie', 'B1', 'ro'),
('prietenie', 'B1', 'ro'),
('căsătorie', 'B1', 'ro'),
('Viața de familie', 'B1', 'ro'),
('fericire', 'B1', 'ro'),
('furie', 'B1', 'ro'),
('frică', 'B1', 'ro'),
('speranţă', 'B1', 'ro'),
('vis', 'B1', 'ro'),
('ambiţie', 'B1', 'ro'),
('motivație', 'B1', 'ro'),
('încredere', 'B1', 'ro'),
('curiozitate', 'B1', 'ro'),
('răbdare', 'B1', 'ro'),
('inovaţie', 'B2', 'ro'),
('dezvoltare', 'B2', 'ro'),
('cercetare', 'B2', 'ro'),
('analiză', 'B2', 'ro'),
('interpretare', 'B2', 'ro'),
('argumentare', 'B2', 'ro'),
('comparaţie', 'B2', 'ro'),
('ipoteză', 'B2', 'ro'),
('teorie', 'B2', 'ro'),
('experiment', 'B2', 'ro'),
('dovezi', 'B2', 'ro'),
('metodă', 'B2', 'ro'),
('concluzie', 'B2', 'ro'),
('observare', 'B2', 'ro'),
('perspectivă', 'B2', 'ro'),
('presupunere', 'B2', 'ro'),
('context', 'B2', 'ro'),
('criterii', 'B2', 'ro'),
('principiu', 'B2', 'ro'),
('prioritate', 'B2', 'ro'),
('complexitate', 'B2', 'ro'),
('eficienţă', 'B2', 'ro'),
('productivitate', 'B2', 'ro'),
('investiții', 'B2', 'ro'),
('economie', 'B2', 'ro'),
('finanţa', 'B2', 'ro'),
('negociere', 'B2', 'ro'),
('acord', 'B2', 'ro'),
('contracta', 'B2', 'ro'),
('politică', 'B2', 'ro'),
('guvern', 'B2', 'ro'),
('politică', 'B2', 'ro'),
('Alegeri', 'B2', 'ro'),
('democraţie', 'B2', 'ro'),
('libertate', 'B2', 'ro'),
('justiţie', 'B2', 'ro'),
('egalitate', 'B2', 'ro'),
('drept', 'B2', 'ro'),
('crimă', 'B2', 'ro'),
('penalizare', 'B2', 'ro'),
('pedeapsă', 'B2', 'ro'),
('securitate', 'B2', 'ro'),
('conflict', 'B2', 'ro'),
('război', 'B2', 'ro'),
('pace', 'B2', 'ro'),
('violenţă', 'B2', 'ro'),
('terorism', 'B2', 'ro'),
('globalizare', 'B2', 'ro'),
('integrare', 'B2', 'ro'),
('diversitate', 'B2', 'ro'),
('identitate', 'B2', 'ro'),
('migrație', 'B2', 'ro'),
('refugiat', 'B2', 'ro'),
('comunitate', 'B2', 'ro'),
('reţea', 'B2', 'ro'),
('organizare', 'B2', 'ro'),
('instituţie', 'B2', 'ro'),
('conducere', 'B2', 'ro'),
('management', 'B2', 'ro'),
('planificare', 'B2', 'ro'),
('strategie', 'B2', 'ro'),
('iniţiativă', 'B2', 'ro'),
('Creativitate', 'B2', 'ro'),
('colaborare', 'B2', 'ro'),
('Muncă în echipă', 'B2', 'ro'),
('responsabilitate', 'B2', 'ro'),
('responsabilitate', 'B2', 'ro'),
('sustenabilitate', 'B2', 'ro'),
('Protecția mediului', 'B2', 'ro'),
('energie regenerabilă', 'B2', 'ro'),
('proces de inovare', 'B2', 'ro'),
('Gândire critică', 'B2', 'ro'),
('Rezolvarea problemelor', 'B2', 'ro'),
('luarea deciziilor', 'B2', 'ro'),
('Managementul timpului', 'B2', 'ro'),
('Autodisciplină', 'B2', 'ro'),
('adaptare', 'B2', 'ro'),
('Rezistență', 'B2', 'ro'),
('independenţă', 'B2', 'ro'),
('cooperare', 'B2', 'ro'),
('încredere', 'B2', 'ro'),
('respect', 'B2', 'ro'),
('empatie', 'B2', 'ro'),
('loialitate', 'B2', 'ro'),
('integritate', 'B2', 'ro'),
('etică', 'B2', 'ro'),
('moralitate', 'B2', 'ro'),
('filozofie', 'B2', 'ro'),
('psihologie', 'B2', 'ro'),
('sociologie', 'B2', 'ro'),
('biologie', 'B2', 'ro'),
('chimie', 'B2', 'ro'),
('fizică', 'B2', 'ro'),
('Analiza critică', 'C1', 'ro'),
('raționament logic', 'C1', 'ro'),
('interpretare', 'C1', 'ro'),
('comparație profundă', 'C1', 'ro'),
('Concluzie științifică', 'C1', 'ro'),
('Ipoteză complexă', 'C1', 'ro'),
('Teorie avansată', 'C1', 'ro'),
('Experiment în profunzime', 'C1', 'ro'),
('Evaluare cuprinzătoare', 'C1', 'ro'),
('Discuție filozofică', 'C1', 'ro'),
('argument puternic', 'C1', 'ro'),
('dovezi tangibile', 'C1', 'ro'),
('dovezi contradictorii', 'C1', 'ro'),
('Conceptul abstract', 'C1', 'ro'),
('poziție etică', 'C1', 'ro'),
('valoare supremă', 'C1', 'ro'),
('Principiul fundamental', 'C1', 'ro'),
('Prioritate principală', 'C1', 'ro'),
('Responsabilitatea majoră', 'C1', 'ro'),
('decizie crucială', 'C1', 'ro'),
('management complex', 'C1', 'ro'),
('Planificare strategică', 'C1', 'ro'),
('Dezvoltare durabilă', 'C1', 'ro'),
('inovație modernă', 'C1', 'ro'),
('Creativitate avansată', 'C1', 'ro'),
('Noua descoperire', 'C1', 'ro'),
('invenție inovatoare', 'C1', 'ro'),
('Analiza economică', 'C1', 'ro'),
('Raport financiar', 'C1', 'ro'),
('Proiect la scară largă', 'C1', 'ro'),
('negocieri internaționale', 'C1', 'ro'),
('Acord formal', 'C1', 'ro'),
('Strategie eficientă', 'C1', 'ro'),
('Instituție globală', 'C1', 'ro'),
('Centrul de cercetare', 'C1', 'ro'),
('Studiu științific avansat', 'C1', 'ro'),
('Revizuire critică', 'C1', 'ro'),
('Interpretare filozofică', 'C1', 'ro'),
('Abordare sistematică', 'C1', 'ro'),
('Teoria modernă', 'C1', 'ro'),
('Cercetare aplicată', 'C1', 'ro'),
('Experiment practic', 'C1', 'ro'),
('Evaluare obiectivă', 'C1', 'ro'),
('Rezultate detaliate', 'C1', 'ro'),
('Dezbatere avansată', 'C1', 'ro'),
('Studiu comparativ', 'C1', 'ro'),
('Cercetări de teren', 'C1', 'ro'),
('Recomandare practică', 'C1', 'ro'),
('Abilitate avansată', 'C1', 'ro'),
('Cadru conceptual', 'C1', 'ro'),
('Planificare precisă', 'C1', 'ro'),
('Strategie pe termen lung', 'C1', 'ro'),
('evaluare a riscurilor', 'C1', 'ro'),
('Revizuire academică', 'C1', 'ro'),
('Proiect de cercetare', 'C1', 'ro'),
('inovație științifică', 'C1', 'ro'),
('Dezvoltare tehnologică', 'C1', 'ro'),
('Analiza literară', 'C1', 'ro'),
('Constatări științifice', 'C1', 'ro'),
('Interpretare avansată', 'C1', 'ro'),
('vedere holistică', 'C1', 'ro'),
('Plan de implementare', 'C1', 'ro'),
('decizie strategică', 'C1', 'ro'),
('Gestionarea resurselor', 'C1', 'ro'),
('provocări complexe', 'C1', 'ro'),
('soluții inovatoare', 'C1', 'ro'),
('Abordare cuprinzătoare', 'C1', 'ro'),
('Analiza datelor', 'C1', 'ro'),
('Testarea ipotezei', 'C1', 'ro'),
('Studiu de caz', 'C1', 'ro'),
('Lucrări de teren avansate', 'C1', 'ro'),
('Recenzie filosofică', 'C1', 'ro'),
('Proiect de cercetare aplicat', 'C1', 'ro'),
('Discuție academică', 'C1', 'ro'),
('Evaluare strategică', 'C1', 'ro'),
('Recomandări practice', 'C1', 'ro'),
('Plan de lucru', 'C1', 'ro'),
('management de proiect', 'C1', 'ro'),
('Publicarea academică', 'C1', 'ro'),
('Descoperire științifică', 'C1', 'ro'),
('Inovație aplicată', 'C1', 'ro'),
('Dezvoltare continuă', 'C1', 'ro'),
('Analiza aprofundată a datelor', 'C1', 'ro'),
('experiență de cercetare', 'C1', 'ro'),
('Interpretare științifică', 'C1', 'ro'),
('perspectivă critică', 'C1', 'ro');
