INSERT INTO words (word, level, language_code) VALUES
('māja', 'A1', 'lv'),
('durvīs', 'A1', 'lv'),
('logs', 'A1', 'lv'),
('galotne', 'A1', 'lv'),
('priekšsēdētājs', 'A1', 'lv'),
('grāmata', 'A1', 'lv'),
('pildspalva', 'A1', 'lv'),
('skola', 'A1', 'lv'),
('skolotājs', 'A1', 'lv'),
('students', 'A1', 'lv'),
('ābols', 'A1', 'lv'),
('laistīt', 'A1', 'lv'),
('ēdiens', 'A1', 'lv'),
('automašīna', 'A1', 'lv'),
('autobuss', 'A1', 'lv'),
('iela', 'A1', 'lv'),
('draugs', 'A1', 'lv'),
('ģimene', 'A1', 'lv'),
('māte', 'A1', 'lv'),
('tēvs', 'A1', 'lv'),
('māsa', 'A1', 'lv'),
('brālis', 'A1', 'lv'),
('diena', 'A1', 'lv'),
('naktsmītne', 'A1', 'lv'),
('rīts', 'A1', 'lv'),
('vakars', 'A1', 'lv'),
('labot', 'A1', 'lv'),
('ardievas', 'A1', 'lv'),
('patikt', 'A1', 'lv'),
('Paldies', 'A1', 'lv'),
('jā', 'A1', 'lv'),
('ne', 'A1', 'lv'),
('sarkans', 'A1', 'lv'),
('zils', 'A1', 'lv'),
('zaļš', 'A1', 'lv'),
('baltums', 'A1', 'lv'),
('melns', 'A1', 'lv'),
('mazs', 'A1', 'lv'),
('liels', 'A1', 'lv'),
('labs', 'A1', 'lv'),
('slikts', 'A1', 'lv'),
('karsts', 'A1', 'lv'),
('aukstums', 'A1', 'lv'),
('kafija', 'A1', 'lv'),
('tēja', 'A1', 'lv'),
('nauda', 'A1', 'lv'),
('darbība', 'A1', 'lv'),
('mājas', 'A1', 'lv'),
('iepirkties', 'A1', 'lv'),
('tirgoties', 'A1', 'lv'),
('ēdiens', 'A1', 'lv'),
('dzert', 'A1', 'lv'),
('pilsēta', 'A1', 'lv'),
('parks', 'A1', 'lv'),
('iela', 'A1', 'lv'),
('autobusu pietura', 'A1', 'lv'),
('trenēt', 'A1', 'lv'),
('stacija', 'A1', 'lv'),
('viesnīca', 'A1', 'lv'),
('telpa', 'A1', 'lv'),
('gultasvieta', 'A1', 'lv'),
('ārsts', 'A1', 'lv'),
('slimnīca', 'A1', 'lv'),
('skola', 'A1', 'lv'),
('universitāte', 'A1', 'lv'),
('datora', 'A1', 'lv'),
('telefons', 'A1', 'lv'),
('televīzija', 'A1', 'lv'),
('mūzika', 'A1', 'lv'),
('dziesma', 'A1', 'lv'),
('plēve', 'A1', 'lv'),
('spēle', 'A1', 'lv'),
('futbols', 'A1', 'lv'),
('bumba', 'A1', 'lv'),
('laistīt', 'A1', 'lv'),
('lietus', 'A1', 'lv'),
('saule', 'A1', 'lv'),
('debesis', 'A1', 'lv'),
('koks', 'A1', 'lv'),
('ziedēt', 'A1', 'lv'),
('dzīvnieks', 'A1', 'lv'),
('kaķis', 'A1', 'lv'),
('suns', 'A1', 'lv'),
('putns', 'A1', 'lv'),
('zivis', 'A1', 'lv'),
('cilvēks', 'A1', 'lv'),
('sieviete', 'A1', 'lv'),
('bērns', 'A1', 'lv'),
('tauta', 'A1', 'lv'),
('iela', 'A1', 'lv'),
('izvietot', 'A1', 'lv'),
('laiks', 'A1', 'lv'),
('gads', 'A1', 'lv'),
('mēnesis', 'A1', 'lv'),
('nedēļa', 'A1', 'lv'),
('šodien', 'A1', 'lv'),
('rītdiena', 'A1', 'lv'),
('vakar', 'A1', 'lv'),
('nosaukt', 'A1', 'lv'),
('uzruna', 'A1', 'lv'),
('skaitlis', 'A1', 'lv'),
('lidosta', 'A2', 'lv'),
('lidojums', 'A2', 'lv'),
('biļete', 'A2', 'lv'),
('pase', 'A2', 'lv'),
('ceļojums', 'A2', 'lv'),
('brīvdienas', 'A2', 'lv'),
('ceļojums', 'A2', 'lv'),
('bagāža', 'A2', 'lv'),
('stacija', 'A2', 'lv'),
('platforma', 'A2', 'lv'),
('restorāns', 'A2', 'lv'),
('kafejnīca', 'A2', 'lv'),
('brokastis', 'A2', 'lv'),
('pusdienas', 'A2', 'lv'),
('vakariņas', 'A2', 'lv'),
('dārzeņi', 'A2', 'lv'),
('augļi', 'A2', 'lv'),
('gaļa', 'A2', 'lv'),
('vistas gaļa', 'A2', 'lv'),
('liellopu gaļa', 'A2', 'lv'),
('zivis', 'A2', 'lv'),
('maize', 'A2', 'lv'),
('rīsi', 'A2', 'lv'),
('makaroni', 'A2', 'lv'),
('zupa', 'A2', 'lv'),
('cukurs', 'A2', 'lv'),
('sāls', 'A2', 'lv'),
('piparot', 'A2', 'lv'),
('eļļas', 'A2', 'lv'),
('iepirkšanās', 'A2', 'lv'),
('apģērbs', 'A2', 'lv'),
('krekls', 'A2', 'lv'),
('bikses', 'A2', 'lv'),
('ģērbties', 'A2', 'lv'),
('apavs', 'A2', 'lv'),
('cepure', 'A2', 'lv'),
('apvalks', 'A2', 'lv'),
('apvalks', 'A2', 'lv'),
('laika apstākļi', 'A2', 'lv'),
('sniegs', 'A2', 'lv'),
('vīt', 'A2', 'lv'),
('vētra', 'A2', 'lv'),
('viesnīcas', 'A2', 'lv'),
('viesmīlis', 'A2', 'lv'),
('sakārtošana', 'A2', 'lv'),
('uzņemšana', 'A2', 'lv'),
('atslēga', 'A2', 'lv'),
('rezervācija', 'A2', 'lv'),
('pludmale', 'A2', 'lv'),
('jūra', 'A2', 'lv'),
('peldēšana', 'A2', 'lv'),
('baseins', 'A2', 'lv'),
('kalns', 'A2', 'lv'),
('ciemats', 'A2', 'lv'),
('apvidus', 'A2', 'lv'),
('valoda', 'A2', 'lv'),
('ārzemju', 'A2', 'lv'),
('eksāmens', 'A2', 'lv'),
('pārbaudīt', 'A2', 'lv'),
('mājas darbs', 'A2', 'lv'),
('klase', 'A2', 'lv'),
('priekšmets', 'A2', 'lv'),
('matemātika', 'A2', 'lv'),
('vēsture', 'A2', 'lv'),
('zinātne', 'A2', 'lv'),
('bibliotēka', 'A2', 'lv'),
('grāmatnīca', 'A2', 'lv'),
('datora', 'A2', 'lv'),
('internets', 'A2', 'lv'),
('e -pasts', 'A2', 'lv'),
('ziņot', 'A2', 'lv'),
('burts', 'A2', 'lv'),
('postenis', 'A2', 'lv'),
('krastmala', 'A2', 'lv'),
('nauda', 'A2', 'lv'),
('kredītkarte', 'A2', 'lv'),
('cena', 'A2', 'lv'),
('lēts', 'A2', 'lv'),
('dārgs', 'A2', 'lv'),
('apšaubīt', 'A2', 'lv'),
('atbildēt', 'A2', 'lv'),
('izskaidrot', 'A2', 'lv'),
('palīdzēt', 'A2', 'lv'),
('problēma', 'A2', 'lv'),
('šķīdums', 'A2', 'lv'),
('veselība', 'A2', 'lv'),
('medicīna', 'A2', 'lv'),
('ārsts', 'A2', 'lv'),
('barot', 'A2', 'lv'),
('pacietīgs', 'A2', 'lv'),
('tikšanās', 'A2', 'lv'),
('drudzis', 'A2', 'lv'),
('klepot', 'A2', 'lv'),
('pieredze', 'B1', 'lv'),
('piedzīvojums', 'B1', 'lv'),
('uzskats', 'B1', 'lv'),
('diskusija', 'B1', 'lv'),
('arguments', 'B1', 'lv'),
('lēmums', 'B1', 'lv'),
('iemesls', 'B1', 'lv'),
('izdevība', 'B1', 'lv'),
('izaicināt', 'B1', 'lv'),
('veiksme', 'B1', 'lv'),
('neveiksme', 'B1', 'lv'),
('mērķis', 'B1', 'lv'),
('plānot', 'B1', 'lv'),
('projektēt', 'B1', 'lv'),
('zināšanas', 'B1', 'lv'),
('prasme', 'B1', 'lv'),
('spēja', 'B1', 'lv'),
('uzlabošana', 'B1', 'lv'),
('apmācība', 'B1', 'lv'),
('darba intervija', 'B1', 'lv'),
('pieteikums', 'B1', 'lv'),
('karjera', 'B1', 'lv'),
('vadītājs', 'B1', 'lv'),
('kolēģis', 'B1', 'lv'),
('sapulce', 'B1', 'lv'),
('uzdevums', 'B1', 'lv'),
('atbildība', 'B1', 'lv'),
('brīvdienu brauciens', 'B1', 'lv'),
('kultūra', 'B1', 'lv'),
('tradīcija', 'B1', 'lv'),
('paraža', 'B1', 'lv'),
('festivāls', 'B1', 'lv'),
('svinēšana', 'B1', 'lv'),
('sniegums', 'B1', 'lv'),
('koncerts', 'B1', 'lv'),
('teātris', 'B1', 'lv'),
('izstāde', 'B1', 'lv'),
('gleznošana', 'B1', 'lv'),
('skulptūra', 'B1', 'lv'),
('muzejs', 'B1', 'lv'),
('vēstures grāmata', 'B1', 'lv'),
('daiļliteratūra', 'B1', 'lv'),
('dzejolis', 'B1', 'lv'),
('romāns', 'B1', 'lv'),
('raksturs', 'B1', 'lv'),
('sižets', 'B1', 'lv'),
('sižets', 'B1', 'lv'),
('avīze', 'B1', 'lv'),
('žurnāls', 'B1', 'lv'),
('pants', 'B1', 'lv'),
('ziņot', 'B1', 'lv'),
('prezentācija', 'B1', 'lv'),
('lekcija', 'B1', 'lv'),
('izglītība', 'B1', 'lv'),
('universitāte', 'B1', 'lv'),
('grāds', 'B1', 'lv'),
('diploms', 'B1', 'lv'),
('apliecība', 'B1', 'lv'),
('vide', 'B1', 'lv'),
('raksturs', 'B1', 'lv'),
('pārstrāde', 'B1', 'lv'),
('piesārņojums', 'B1', 'lv'),
('klimata pārmaiņas', 'B1', 'lv'),
('globālā sasilšana', 'B1', 'lv'),
('enerģija', 'B1', 'lv'),
('tehnoloģija', 'B1', 'lv'),
('inovācija', 'B1', 'lv'),
('izgudrojums', 'B1', 'lv'),
('ierīce', 'B1', 'lv'),
('mašīna', 'B1', 'lv'),
('datorprogramma', 'B1', 'lv'),
('vietne', 'B1', 'lv'),
('pieteikums', 'B1', 'lv'),
('sociālie mediji', 'B1', 'lv'),
('sakars', 'B1', 'lv'),
('saruna', 'B1', 'lv'),
('mijiedarbība', 'B1', 'lv'),
('attiecība', 'B1', 'lv'),
('draudzība', 'B1', 'lv'),
('laulības', 'B1', 'lv'),
('Ģimenes dzīve', 'B1', 'lv'),
('laime', 'B1', 'lv'),
('dusmas', 'B1', 'lv'),
('bailes', 'B1', 'lv'),
('cerēt', 'B1', 'lv'),
('sapņot', 'B1', 'lv'),
('mērķis', 'B1', 'lv'),
('motivācija', 'B1', 'lv'),
('pārliecība', 'B1', 'lv'),
('ziņkārība', 'B1', 'lv'),
('pacietība', 'B1', 'lv'),
('inovācija', 'B2', 'lv'),
('attīstība', 'B2', 'lv'),
('izpētīt', 'B2', 'lv'),
('analīze', 'B2', 'lv'),
('interpretācija', 'B2', 'lv'),
('argumentācija', 'B2', 'lv'),
('salīdzinājums', 'B2', 'lv'),
('hipotēze', 'B2', 'lv'),
('teorija', 'B2', 'lv'),
('eksperimentēt', 'B2', 'lv'),
('pierādījums', 'B2', 'lv'),
('metode', 'B2', 'lv'),
('secinājums', 'B2', 'lv'),
('ievērošana', 'B2', 'lv'),
('perspektīva', 'B2', 'lv'),
('pieņēmums', 'B2', 'lv'),
('konteksts', 'B2', 'lv'),
('kritēriji', 'B2', 'lv'),
('princips', 'B2', 'lv'),
('prioritāte', 'B2', 'lv'),
('sarežģītība', 'B2', 'lv'),
('efektivitāte', 'B2', 'lv'),
('produktivitāte', 'B2', 'lv'),
('ieguldījums', 'B2', 'lv'),
('ekonomija', 'B2', 'lv'),
('finanses', 'B2', 'lv'),
('sarunas', 'B2', 'lv'),
('vienošanās', 'B2', 'lv'),
('nolīgums', 'B2', 'lv'),
('politika', 'B2', 'lv'),
('valdība', 'B2', 'lv'),
('politika', 'B2', 'lv'),
('vēlēšanās', 'B2', 'lv'),
('demokrātija', 'B2', 'lv'),
('brīvība', 'B2', 'lv'),
('taisnīgums', 'B2', 'lv'),
('vienlīdzība', 'B2', 'lv'),
('likums', 'B2', 'lv'),
('noziegums', 'B2', 'lv'),
('sods', 'B2', 'lv'),
('sods', 'B2', 'lv'),
('drošība', 'B2', 'lv'),
('pretruna', 'B2', 'lv'),
('karot', 'B2', 'lv'),
('miers', 'B2', 'lv'),
('vardarbība', 'B2', 'lv'),
('terorisms', 'B2', 'lv'),
('globalizācija', 'B2', 'lv'),
('integrācija', 'B2', 'lv'),
('daudzveidība', 'B2', 'lv'),
('identitāte', 'B2', 'lv'),
('migrācija', 'B2', 'lv'),
('bēglis', 'B2', 'lv'),
('kopiena', 'B2', 'lv'),
('tīkls', 'B2', 'lv'),
('organizācija', 'B2', 'lv'),
('iestāde', 'B2', 'lv'),
('vadība', 'B2', 'lv'),
('vadība', 'B2', 'lv'),
('plānošana', 'B2', 'lv'),
('stratēģija', 'B2', 'lv'),
('iniciatīva', 'B2', 'lv'),
('radošums', 'B2', 'lv'),
('sadarbība', 'B2', 'lv'),
('komandas darbs', 'B2', 'lv'),
('atbildība', 'B2', 'lv'),
('amats', 'B2', 'lv'),
('ilgtspējība', 'B2', 'lv'),
('vides aizsardzība', 'B2', 'lv'),
('Atjaunojamā enerģija', 'B2', 'lv'),
('inovācijas process', 'B2', 'lv'),
('kritiskā domāšana', 'B2', 'lv'),
('problēmu risināšana', 'B2', 'lv'),
('lēmumu pieņemšana', 'B2', 'lv'),
('laika pārvaldība', 'B2', 'lv'),
('pašdisciplīna', 'B2', 'lv'),
('pielāgošana', 'B2', 'lv'),
('izturība', 'B2', 'lv'),
('neatkarība', 'B2', 'lv'),
('sadarbība', 'B2', 'lv'),
('uzticēt', 'B2', 'lv'),
('cieņa', 'B2', 'lv'),
('empātija', 'B2', 'lv'),
('lojalitāte', 'B2', 'lv'),
('godīgums', 'B2', 'lv'),
('ētika', 'B2', 'lv'),
('morāle', 'B2', 'lv'),
('filozofija', 'B2', 'lv'),
('psiholoģija', 'B2', 'lv'),
('socioloģija', 'B2', 'lv'),
('bioloģija', 'B2', 'lv'),
('ķīmija', 'B2', 'lv'),
('fizika', 'B2', 'lv'),
('kritiskā analīze', 'C1', 'lv'),
('loģiskā spriešana', 'C1', 'lv'),
('interpretācija', 'C1', 'lv'),
('dziļais salīdzinājums', 'C1', 'lv'),
('zinātnisks secinājums', 'C1', 'lv'),
('sarežģīta hipotēze', 'C1', 'lv'),
('Papildu teorija', 'C1', 'lv'),
('padziļināts eksperiments', 'C1', 'lv'),
('visaptverošs novērtējums', 'C1', 'lv'),
('filozofiska diskusija', 'C1', 'lv'),
('spēcīgs arguments', 'C1', 'lv'),
('taustāmi pierādījumi', 'C1', 'lv'),
('pretrunīgi pierādījumi', 'C1', 'lv'),
('abstraktā koncepcija', 'C1', 'lv'),
('ētiskā nostāja', 'C1', 'lv'),
('Augstākā vērtība', 'C1', 'lv'),
('pamatprincips', 'C1', 'lv'),
('galvenā prioritāte', 'C1', 'lv'),
('Galvenā atbildība', 'C1', 'lv'),
('izšķirošs lēmums', 'C1', 'lv'),
('sarežģīta vadība', 'C1', 'lv'),
('stratēģiskā plānošana', 'C1', 'lv'),
('ilgtspējīga attīstība', 'C1', 'lv'),
('Mūsdienu inovācijas', 'C1', 'lv'),
('uzlabota radošums', 'C1', 'lv'),
('jauns atklājums', 'C1', 'lv'),
('Inovatīvs izgudrojums', 'C1', 'lv'),
('ekonomiskā analīze', 'C1', 'lv'),
('finanšu pārskats', 'C1', 'lv'),
('liela mēroga projekts', 'C1', 'lv'),
('Starptautiskās sarunas', 'C1', 'lv'),
('Formāla vienošanās', 'C1', 'lv'),
('Efektīva stratēģija', 'C1', 'lv'),
('globālā iestāde', 'C1', 'lv'),
('pētniecības centrs', 'C1', 'lv'),
('uzlabots zinātniskais pētījums', 'C1', 'lv'),
('Kritisks pārskats', 'C1', 'lv'),
('filozofiskā interpretācija', 'C1', 'lv'),
('Sistemātiska pieeja', 'C1', 'lv'),
('Mūsdienu teorija', 'C1', 'lv'),
('lietišķie pētījumi', 'C1', 'lv'),
('praktisks eksperiments', 'C1', 'lv'),
('objektīvs novērtējums', 'C1', 'lv'),
('Detalizēti rezultāti', 'C1', 'lv'),
('padziļinātas debates', 'C1', 'lv'),
('salīdzinošais pētījums', 'C1', 'lv'),
('Lauka izpēte', 'C1', 'lv'),
('Praktisks ieteikums', 'C1', 'lv'),
('uzlabota prasme', 'C1', 'lv'),
('Konceptuālais ietvars', 'C1', 'lv'),
('Precīza plānošana', 'C1', 'lv'),
('ilgtermiņa stratēģija', 'C1', 'lv'),
('riska novērtējums', 'C1', 'lv'),
('akadēmiskais pārskats', 'C1', 'lv'),
('pētniecības projekts', 'C1', 'lv'),
('zinātniski jauninājumi', 'C1', 'lv'),
('tehnoloģiskā attīstība', 'C1', 'lv'),
('literārā analīze', 'C1', 'lv'),
('zinātniski atklājumi', 'C1', 'lv'),
('uzlabota interpretācija', 'C1', 'lv'),
('holistisks skats', 'C1', 'lv'),
('ieviešanas plāns', 'C1', 'lv'),
('Stratēģisks lēmums', 'C1', 'lv'),
('resursu pārvaldība', 'C1', 'lv'),
('sarežģīti izaicinājumi', 'C1', 'lv'),
('Inovatīvi risinājumi', 'C1', 'lv'),
('visaptveroša pieeja', 'C1', 'lv'),
('datu analīze', 'C1', 'lv'),
('hipotēzes pārbaude', 'C1', 'lv'),
('gadījuma izpēte', 'C1', 'lv'),
('uzlabots lauka darbs', 'C1', 'lv'),
('filozofisks pārskats', 'C1', 'lv'),
('lietišķās pētniecības projekts', 'C1', 'lv'),
('akadēmiska diskusija', 'C1', 'lv'),
('stratēģiskā novērtēšana', 'C1', 'lv'),
('Praktiski ieteikumi', 'C1', 'lv'),
('darba plāns', 'C1', 'lv'),
('projektu vadība', 'C1', 'lv'),
('akadēmiskā publikācija', 'C1', 'lv'),
('zinātnisks atklājums', 'C1', 'lv'),
('lietišķais jauninājums', 'C1', 'lv'),
('Nepārtraukta attīstība', 'C1', 'lv'),
('padziļināta datu analīze', 'C1', 'lv'),
('pētniecības pieredze', 'C1', 'lv'),
('zinātniska interpretācija', 'C1', 'lv'),
('kritiskā perspektīva', 'C1', 'lv');
