INSERT INTO words (word, level, language_code) VALUES
('dom', 'A1', 'pl'),
('drzwi', 'A1', 'pl'),
('okno', 'A1', 'pl'),
('tabela', 'A1', 'pl'),
('krzesło', 'A1', 'pl'),
('książka', 'A1', 'pl'),
('pióro', 'A1', 'pl'),
('szkoła', 'A1', 'pl'),
('nauczyciel', 'A1', 'pl'),
('student', 'A1', 'pl'),
('jabłko', 'A1', 'pl'),
('woda', 'A1', 'pl'),
('żywność', 'A1', 'pl'),
('samochód', 'A1', 'pl'),
('autobus', 'A1', 'pl'),
('ulica', 'A1', 'pl'),
('przyjaciel', 'A1', 'pl'),
('rodzina', 'A1', 'pl'),
('matka', 'A1', 'pl'),
('ojciec', 'A1', 'pl'),
('siostra', 'A1', 'pl'),
('brat', 'A1', 'pl'),
('dzień', 'A1', 'pl'),
('noc', 'A1', 'pl'),
('Poranek', 'A1', 'pl'),
('wieczór', 'A1', 'pl'),
('Witam', 'A1', 'pl'),
('do widzenia', 'A1', 'pl'),
('Proszę', 'A1', 'pl'),
('Dziękuję', 'A1', 'pl'),
('Tak', 'A1', 'pl'),
('NIE', 'A1', 'pl'),
('czerwony', 'A1', 'pl'),
('niebieski', 'A1', 'pl'),
('zielony', 'A1', 'pl'),
('biały', 'A1', 'pl'),
('czarny', 'A1', 'pl'),
('mały', 'A1', 'pl'),
('duży', 'A1', 'pl'),
('Dobry', 'A1', 'pl'),
('zły', 'A1', 'pl'),
('gorący', 'A1', 'pl'),
('zimno', 'A1', 'pl'),
('kawa', 'A1', 'pl'),
('herbata', 'A1', 'pl'),
('pieniądze', 'A1', 'pl'),
('praca', 'A1', 'pl'),
('dom', 'A1', 'pl'),
('sklep', 'A1', 'pl'),
('rynek', 'A1', 'pl'),
('żywność', 'A1', 'pl'),
('drink', 'A1', 'pl'),
('miasto', 'A1', 'pl'),
('park', 'A1', 'pl'),
('ulica', 'A1', 'pl'),
('przystanek autobusowy', 'A1', 'pl'),
('pociąg', 'A1', 'pl'),
('stacja', 'A1', 'pl'),
('hotel', 'A1', 'pl'),
('pokój', 'A1', 'pl'),
('łóżko', 'A1', 'pl'),
('lekarz', 'A1', 'pl'),
('szpital', 'A1', 'pl'),
('szkoła', 'A1', 'pl'),
('uniwersytet', 'A1', 'pl'),
('komputer', 'A1', 'pl'),
('telefon', 'A1', 'pl'),
('telewizja', 'A1', 'pl'),
('muzyka', 'A1', 'pl'),
('piosenka', 'A1', 'pl'),
('film', 'A1', 'pl'),
('gra', 'A1', 'pl'),
('piłkarski', 'A1', 'pl'),
('piłka', 'A1', 'pl'),
('woda', 'A1', 'pl'),
('deszcz', 'A1', 'pl'),
('słoneczny', 'A1', 'pl'),
('niebo', 'A1', 'pl'),
('drzewo', 'A1', 'pl'),
('kwiat', 'A1', 'pl'),
('zwierzę', 'A1', 'pl'),
('kot', 'A1', 'pl'),
('pies', 'A1', 'pl'),
('ptak', 'A1', 'pl'),
('ryba', 'A1', 'pl'),
('Człowiek', 'A1', 'pl'),
('kobieta', 'A1', 'pl'),
('dziecko', 'A1', 'pl'),
('ludzie', 'A1', 'pl'),
('ulica', 'A1', 'pl'),
('miejsce', 'A1', 'pl'),
('czas', 'A1', 'pl'),
('rok', 'A1', 'pl'),
('miesiąc', 'A1', 'pl'),
('tydzień', 'A1', 'pl'),
('Dzisiaj', 'A1', 'pl'),
('jutro', 'A1', 'pl'),
('Wczoraj', 'A1', 'pl'),
('nazwa', 'A1', 'pl'),
('adres', 'A1', 'pl'),
('numer', 'A1', 'pl'),
('lotnisko', 'A2', 'pl'),
('lot', 'A2', 'pl'),
('bilet', 'A2', 'pl'),
('paszport', 'A2', 'pl'),
('podróż', 'A2', 'pl'),
('wakacje', 'A2', 'pl'),
('podróż', 'A2', 'pl'),
('bagaż', 'A2', 'pl'),
('stacja', 'A2', 'pl'),
('platforma', 'A2', 'pl'),
('restauracja', 'A2', 'pl'),
('kawiarnia', 'A2', 'pl'),
('śniadanie', 'A2', 'pl'),
('obiad', 'A2', 'pl'),
('kolacja', 'A2', 'pl'),
('warzywa', 'A2', 'pl'),
('owoc', 'A2', 'pl'),
('mięso', 'A2', 'pl'),
('kurczak', 'A2', 'pl'),
('wołowina', 'A2', 'pl'),
('ryba', 'A2', 'pl'),
('chleb', 'A2', 'pl'),
('ryż', 'A2', 'pl'),
('makaron', 'A2', 'pl'),
('zupa', 'A2', 'pl'),
('cukier', 'A2', 'pl'),
('sól', 'A2', 'pl'),
('pieprz', 'A2', 'pl'),
('olej', 'A2', 'pl'),
('zakupy', 'A2', 'pl'),
('odzież', 'A2', 'pl'),
('koszula', 'A2', 'pl'),
('spodnie', 'A2', 'pl'),
('sukienka', 'A2', 'pl'),
('buty', 'A2', 'pl'),
('kapelusz', 'A2', 'pl'),
('kurtka', 'A2', 'pl'),
('płaszcz', 'A2', 'pl'),
('pogoda', 'A2', 'pl'),
('śnieg', 'A2', 'pl'),
('wiatr', 'A2', 'pl'),
('burza', 'A2', 'pl'),
('hotele', 'A2', 'pl'),
('gość', 'A2', 'pl'),
('praca', 'A2', 'pl'),
('przyjęcie', 'A2', 'pl'),
('klawisz', 'A2', 'pl'),
('rezerwacja', 'A2', 'pl'),
('plaża', 'A2', 'pl'),
('morze', 'A2', 'pl'),
('pływacki', 'A2', 'pl'),
('basen', 'A2', 'pl'),
('góra', 'A2', 'pl'),
('wieś', 'A2', 'pl'),
('kraj', 'A2', 'pl'),
('język', 'A2', 'pl'),
('zagraniczny', 'A2', 'pl'),
('egzamin', 'A2', 'pl'),
('test', 'A2', 'pl'),
('praca domowa', 'A2', 'pl'),
('klasa', 'A2', 'pl'),
('temat', 'A2', 'pl'),
('matematyka', 'A2', 'pl'),
('historia', 'A2', 'pl'),
('nauka', 'A2', 'pl'),
('biblioteka', 'A2', 'pl'),
('księgarnia', 'A2', 'pl'),
('komputer', 'A2', 'pl'),
('Internet', 'A2', 'pl'),
('e-mail', 'A2', 'pl'),
('wiadomość', 'A2', 'pl'),
('list', 'A2', 'pl'),
('post', 'A2', 'pl'),
('bank', 'A2', 'pl'),
('pieniądze', 'A2', 'pl'),
('karta kredytowa', 'A2', 'pl'),
('cena', 'A2', 'pl'),
('tani', 'A2', 'pl'),
('drogi', 'A2', 'pl'),
('pytanie', 'A2', 'pl'),
('odpowiedź', 'A2', 'pl'),
('wyjaśnić', 'A2', 'pl'),
('pomoc', 'A2', 'pl'),
('problem', 'A2', 'pl'),
('rozwiązanie', 'A2', 'pl'),
('zdrowie', 'A2', 'pl'),
('medycyna', 'A2', 'pl'),
('lekarz', 'A2', 'pl'),
('pielęgniarka', 'A2', 'pl'),
('pacjent', 'A2', 'pl'),
('spotkanie', 'A2', 'pl'),
('gorączka', 'A2', 'pl'),
('kaszel', 'A2', 'pl'),
('doświadczenie', 'B1', 'pl'),
('przygoda', 'B1', 'pl'),
('opinia', 'B1', 'pl'),
('dyskusja', 'B1', 'pl'),
('argument', 'B1', 'pl'),
('decyzja', 'B1', 'pl'),
('powód', 'B1', 'pl'),
('możliwość', 'B1', 'pl'),
('wyzwanie', 'B1', 'pl'),
('sukces', 'B1', 'pl'),
('awaria', 'B1', 'pl'),
('bramka', 'B1', 'pl'),
('plan', 'B1', 'pl'),
('projekt', 'B1', 'pl'),
('wiedza', 'B1', 'pl'),
('umiejętność', 'B1', 'pl'),
('umiejętność', 'B1', 'pl'),
('poprawa', 'B1', 'pl'),
('szkolenie', 'B1', 'pl'),
('rozmowa kwalifikacyjna', 'B1', 'pl'),
('aplikacja', 'B1', 'pl'),
('kariera', 'B1', 'pl'),
('menedżer', 'B1', 'pl'),
('kolega z pracy', 'B1', 'pl'),
('spotkanie', 'B1', 'pl'),
('zadanie', 'B1', 'pl'),
('odpowiedzialność', 'B1', 'pl'),
('Wakacyjna wycieczka', 'B1', 'pl'),
('kultura', 'B1', 'pl'),
('tradycja', 'B1', 'pl'),
('zwyczaj', 'B1', 'pl'),
('festiwal', 'B1', 'pl'),
('uroczystość', 'B1', 'pl'),
('wydajność', 'B1', 'pl'),
('koncert', 'B1', 'pl'),
('teatr', 'B1', 'pl'),
('wystawa', 'B1', 'pl'),
('malarstwo', 'B1', 'pl'),
('rzeźba', 'B1', 'pl'),
('muzeum', 'B1', 'pl'),
('książka historyczna', 'B1', 'pl'),
('fikcja', 'B1', 'pl'),
('wiersz', 'B1', 'pl'),
('powieść', 'B1', 'pl'),
('charakter', 'B1', 'pl'),
('działka', 'B1', 'pl'),
('historia', 'B1', 'pl'),
('gazeta', 'B1', 'pl'),
('magazyn', 'B1', 'pl'),
('artykuł', 'B1', 'pl'),
('raport', 'B1', 'pl'),
('prezentacja', 'B1', 'pl'),
('wykład', 'B1', 'pl'),
('edukacja', 'B1', 'pl'),
('uniwersytet', 'B1', 'pl'),
('stopień', 'B1', 'pl'),
('dyplom', 'B1', 'pl'),
('certyfikat', 'B1', 'pl'),
('środowisko', 'B1', 'pl'),
('natura', 'B1', 'pl'),
('recykling', 'B1', 'pl'),
('zanieczyszczenie', 'B1', 'pl'),
('zmiana klimatu', 'B1', 'pl'),
('Globalne ocieplenie', 'B1', 'pl'),
('energia', 'B1', 'pl'),
('technologia', 'B1', 'pl'),
('innowacja', 'B1', 'pl'),
('wynalazek', 'B1', 'pl'),
('urządzenie', 'B1', 'pl'),
('maszyna', 'B1', 'pl'),
('program komputerowy', 'B1', 'pl'),
('strona internetowa', 'B1', 'pl'),
('aplikacja', 'B1', 'pl'),
('Media społecznościowe', 'B1', 'pl'),
('komunikacja', 'B1', 'pl'),
('rozmowa', 'B1', 'pl'),
('wzajemne oddziaływanie', 'B1', 'pl'),
('relacja', 'B1', 'pl'),
('przyjaźń', 'B1', 'pl'),
('małżeństwo', 'B1', 'pl'),
('życie rodzinne', 'B1', 'pl'),
('szczęście', 'B1', 'pl'),
('gniew', 'B1', 'pl'),
('strach', 'B1', 'pl'),
('mieć nadzieję', 'B1', 'pl'),
('marzenie', 'B1', 'pl'),
('ambicja', 'B1', 'pl'),
('motywacja', 'B1', 'pl'),
('zaufanie', 'B1', 'pl'),
('ciekawość', 'B1', 'pl'),
('cierpliwość', 'B1', 'pl'),
('innowacja', 'B2', 'pl'),
('rozwój', 'B2', 'pl'),
('badania', 'B2', 'pl'),
('analiza', 'B2', 'pl'),
('interpretacja', 'B2', 'pl'),
('argumentacja', 'B2', 'pl'),
('porównanie', 'B2', 'pl'),
('hipoteza', 'B2', 'pl'),
('teoria', 'B2', 'pl'),
('eksperyment', 'B2', 'pl'),
('dowód', 'B2', 'pl'),
('metoda', 'B2', 'pl'),
('wniosek', 'B2', 'pl'),
('obserwacja', 'B2', 'pl'),
('perspektywiczny', 'B2', 'pl'),
('założenie', 'B2', 'pl'),
('kontekst', 'B2', 'pl'),
('kryteria', 'B2', 'pl'),
('zasada', 'B2', 'pl'),
('priorytet', 'B2', 'pl'),
('złożoność', 'B2', 'pl'),
('efektywność', 'B2', 'pl'),
('wydajność', 'B2', 'pl'),
('inwestycja', 'B2', 'pl'),
('gospodarka', 'B2', 'pl'),
('finanse', 'B2', 'pl'),
('negocjacja', 'B2', 'pl'),
('porozumienie', 'B2', 'pl'),
('umowa', 'B2', 'pl'),
('polityka', 'B2', 'pl'),
('rząd', 'B2', 'pl'),
('polityka', 'B2', 'pl'),
('wybór', 'B2', 'pl'),
('demokracja', 'B2', 'pl'),
('wolność', 'B2', 'pl'),
('sprawiedliwość', 'B2', 'pl'),
('równość', 'B2', 'pl'),
('prawo', 'B2', 'pl'),
('przestępczość', 'B2', 'pl'),
('kara', 'B2', 'pl'),
('kara', 'B2', 'pl'),
('bezpieczeństwo', 'B2', 'pl'),
('konflikt', 'B2', 'pl'),
('wojna', 'B2', 'pl'),
('pokój', 'B2', 'pl'),
('przemoc', 'B2', 'pl'),
('terroryzm', 'B2', 'pl'),
('globalizacja', 'B2', 'pl'),
('integracja', 'B2', 'pl'),
('różnorodność', 'B2', 'pl'),
('tożsamość', 'B2', 'pl'),
('emigracja', 'B2', 'pl'),
('uchodźca', 'B2', 'pl'),
('wspólnota', 'B2', 'pl'),
('sieć', 'B2', 'pl'),
('organizacja', 'B2', 'pl'),
('instytucja', 'B2', 'pl'),
('przywództwo', 'B2', 'pl'),
('kierownictwo', 'B2', 'pl'),
('planowanie', 'B2', 'pl'),
('strategia', 'B2', 'pl'),
('inicjatywa', 'B2', 'pl'),
('kreatywność', 'B2', 'pl'),
('współpraca', 'B2', 'pl'),
('praca zespołowa', 'B2', 'pl'),
('odpowiedzialność', 'B2', 'pl'),
('odpowiedzialność', 'B2', 'pl'),
('zrównoważony rozwój', 'B2', 'pl'),
('Ochrona środowiska', 'B2', 'pl'),
('energia odnawialna', 'B2', 'pl'),
('proces innowacji', 'B2', 'pl'),
('Krytyczne myślenie', 'B2', 'pl'),
('Rozwiązywanie problemów', 'B2', 'pl'),
('podejmowanie decyzji', 'B2', 'pl'),
('Zarządzanie czasem', 'B2', 'pl'),
('Samodyscyplina', 'B2', 'pl'),
('dostosowanie', 'B2', 'pl'),
('odporność', 'B2', 'pl'),
('niezależność', 'B2', 'pl'),
('współpraca', 'B2', 'pl'),
('zaufanie', 'B2', 'pl'),
('szacunek', 'B2', 'pl'),
('empatia', 'B2', 'pl'),
('lojalność', 'B2', 'pl'),
('uczciwość', 'B2', 'pl'),
('etyka', 'B2', 'pl'),
('moralność', 'B2', 'pl'),
('filozofia', 'B2', 'pl'),
('psychologia', 'B2', 'pl'),
('socjologia', 'B2', 'pl'),
('biologia', 'B2', 'pl'),
('chemia', 'B2', 'pl'),
('fizyka', 'B2', 'pl'),
('Analiza krytyczna', 'C1', 'pl'),
('logiczne rozumowanie', 'C1', 'pl'),
('interpretacja', 'C1', 'pl'),
('Głębokie porównanie', 'C1', 'pl'),
('Wniosek naukowy', 'C1', 'pl'),
('złożona hipoteza', 'C1', 'pl'),
('Zaawansowana teoria', 'C1', 'pl'),
('Dogłębny eksperyment', 'C1', 'pl'),
('Kompleksowa ocena', 'C1', 'pl'),
('Dyskusja filozoficzna', 'C1', 'pl'),
('Mocny argument', 'C1', 'pl'),
('namacalne dowody', 'C1', 'pl'),
('sprzeczne dowody', 'C1', 'pl'),
('Koncepcja abstrakcyjna', 'C1', 'pl'),
('pozycja etyczna', 'C1', 'pl'),
('Najwyższa wartość', 'C1', 'pl'),
('główna zasada', 'C1', 'pl'),
('Najwyższy priorytet', 'C1', 'pl'),
('główna odpowiedzialność', 'C1', 'pl'),
('kluczowa decyzja', 'C1', 'pl'),
('Złożone zarządzanie', 'C1', 'pl'),
('Planowanie strategiczne', 'C1', 'pl'),
('Zrównoważony rozwój', 'C1', 'pl'),
('Nowoczesna innowacja', 'C1', 'pl'),
('Zaawansowana kreatywność', 'C1', 'pl'),
('nowe odkrycie', 'C1', 'pl'),
('innowacyjny wynalazek', 'C1', 'pl'),
('Analiza ekonomiczna', 'C1', 'pl'),
('Raport finansowy', 'C1', 'pl'),
('Projekt na dużą skalę', 'C1', 'pl'),
('Negocjacje międzynarodowe', 'C1', 'pl'),
('formalna umowa', 'C1', 'pl'),
('skuteczna strategia', 'C1', 'pl'),
('Globalna instytucja', 'C1', 'pl'),
('Centrum badawcze', 'C1', 'pl'),
('Zaawansowane badanie naukowe', 'C1', 'pl'),
('Recenzja krytyczna', 'C1', 'pl'),
('Interpretacja filozoficzna', 'C1', 'pl'),
('systematyczne podejście', 'C1', 'pl'),
('współczesna teoria', 'C1', 'pl'),
('Badania stosowane', 'C1', 'pl'),
('Praktyczny eksperyment', 'C1', 'pl'),
('Ocena obiektywna', 'C1', 'pl'),
('szczegółowe wyniki', 'C1', 'pl'),
('Zaawansowana debata', 'C1', 'pl'),
('Badanie porównawcze', 'C1', 'pl'),
('Badania terenowe', 'C1', 'pl'),
('praktyczne zalecenie', 'C1', 'pl'),
('Zaawansowane umiejętności', 'C1', 'pl'),
('Ramy koncepcyjne', 'C1', 'pl'),
('precyzyjne planowanie', 'C1', 'pl'),
('Strategia długoterminowa', 'C1', 'pl'),
('Ocena ryzyka', 'C1', 'pl'),
('Recenzja akademicka', 'C1', 'pl'),
('Projekt badawczy', 'C1', 'pl'),
('Innowacja naukowa', 'C1', 'pl'),
('Rozwój technologiczny', 'C1', 'pl'),
('Analiza literacka', 'C1', 'pl'),
('ustalenia naukowe', 'C1', 'pl'),
('Zaawansowana interpretacja', 'C1', 'pl'),
('Holistyczny widok', 'C1', 'pl'),
('Plan wdrożenia', 'C1', 'pl'),
('Decyzja strategiczna', 'C1', 'pl'),
('Zarządzanie zasobami', 'C1', 'pl'),
('złożone wyzwania', 'C1', 'pl'),
('Innowacyjne rozwiązania', 'C1', 'pl'),
('Kompleksowe podejście', 'C1', 'pl'),
('Analiza danych', 'C1', 'pl'),
('Testowanie hipotez', 'C1', 'pl'),
('Studium przypadku', 'C1', 'pl'),
('Zaawansowane prace terenowe', 'C1', 'pl'),
('Recenzja filozoficzna', 'C1', 'pl'),
('Applied Research Project', 'C1', 'pl'),
('Dyskusja akademicka', 'C1', 'pl'),
('Ocena strategiczna', 'C1', 'pl'),
('praktyczne zalecenia', 'C1', 'pl'),
('Plan pracy', 'C1', 'pl'),
('Zarządzanie projektem', 'C1', 'pl'),
('Publikacja akademicka', 'C1', 'pl'),
('odkrycie naukowe', 'C1', 'pl'),
('Zastosowana innowacja', 'C1', 'pl'),
('ciągły rozwój', 'C1', 'pl'),
('Dogłębna analiza danych', 'C1', 'pl'),
('Doświadczenie badawcze', 'C1', 'pl'),
('interpretacja naukowa', 'C1', 'pl'),
('Krytyczna perspektywa', 'C1', 'pl');
