INSERT INTO words (word, level, language_code) VALUES
('rumah', 'A1', 'id'),
('pintu', 'A1', 'id'),
('jendela', 'A1', 'id'),
('meja', 'A1', 'id'),
('kursi', 'A1', 'id'),
('buku', 'A1', 'id'),
('pena', 'A1', 'id'),
('sekolah', 'A1', 'id'),
('guru', 'A1', 'id'),
('murid', 'A1', 'id'),
('apel', 'A1', 'id'),
('air', 'A1', 'id'),
('makanan', 'A1', 'id'),
('mobil', 'A1', 'id'),
('bis', 'A1', 'id'),
('jalan', 'A1', 'id'),
('teman', 'A1', 'id'),
('keluarga', 'A1', 'id'),
('ibu', 'A1', 'id'),
('ayah', 'A1', 'id'),
('saudari', 'A1', 'id'),
('saudara laki-laki', 'A1', 'id'),
('hari', 'A1', 'id'),
('malam', 'A1', 'id'),
('Pagi', 'A1', 'id'),
('malam', 'A1', 'id'),
('Halo', 'A1', 'id'),
('selamat tinggal', 'A1', 'id'),
('Tolong', 'A1', 'id'),
('Terima kasih', 'A1', 'id'),
('Ya', 'A1', 'id'),
('TIDAK', 'A1', 'id'),
('merah', 'A1', 'id'),
('biru', 'A1', 'id'),
('hijau', 'A1', 'id'),
('putih', 'A1', 'id'),
('hitam', 'A1', 'id'),
('kecil', 'A1', 'id'),
('besar', 'A1', 'id'),
('Bagus', 'A1', 'id'),
('buruk', 'A1', 'id'),
('panas', 'A1', 'id'),
('dingin', 'A1', 'id'),
('kopi', 'A1', 'id'),
('teh', 'A1', 'id'),
('uang', 'A1', 'id'),
('bekerja', 'A1', 'id'),
('rumah', 'A1', 'id'),
('toko', 'A1', 'id'),
('pasar', 'A1', 'id'),
('makanan', 'A1', 'id'),
('minum', 'A1', 'id'),
('kota', 'A1', 'id'),
('taman', 'A1', 'id'),
('jalan', 'A1', 'id'),
('halte bus', 'A1', 'id'),
('kereta', 'A1', 'id'),
('stasiun', 'A1', 'id'),
('hotel', 'A1', 'id'),
('ruang', 'A1', 'id'),
('tempat tidur', 'A1', 'id'),
('dokter', 'A1', 'id'),
('RSUD', 'A1', 'id'),
('sekolah', 'A1', 'id'),
('universitas', 'A1', 'id'),
('komputer', 'A1', 'id'),
('telepon', 'A1', 'id'),
('televisi', 'A1', 'id'),
('musik', 'A1', 'id'),
('lagu', 'A1', 'id'),
('film', 'A1', 'id'),
('permainan', 'A1', 'id'),
('sepak bola', 'A1', 'id'),
('bola', 'A1', 'id'),
('air', 'A1', 'id'),
('hujan', 'A1', 'id'),
('matahari', 'A1', 'id'),
('langit', 'A1', 'id'),
('pohon', 'A1', 'id'),
('bunga', 'A1', 'id'),
('hewan', 'A1', 'id'),
('kucing', 'A1', 'id'),
('anjing', 'A1', 'id'),
('burung', 'A1', 'id'),
('ikan', 'A1', 'id'),
('pria', 'A1', 'id'),
('wanita', 'A1', 'id'),
('anak', 'A1', 'id'),
('rakyat', 'A1', 'id'),
('jalan', 'A1', 'id'),
('tempat', 'A1', 'id'),
('waktu', 'A1', 'id'),
('tahun', 'A1', 'id'),
('bulan', 'A1', 'id'),
('pekan', 'A1', 'id'),
('Hari ini', 'A1', 'id'),
('besok', 'A1', 'id'),
('Kemarin', 'A1', 'id'),
('nama', 'A1', 'id'),
('alamat', 'A1', 'id'),
('nomor', 'A1', 'id'),
('bandara', 'A2', 'id'),
('penerbangan', 'A2', 'id'),
('tiket', 'A2', 'id'),
('paspor', 'A2', 'id'),
('bepergian', 'A2', 'id'),
('hari libur', 'A2', 'id'),
('perjalanan', 'A2', 'id'),
('bagasi', 'A2', 'id'),
('stasiun', 'A2', 'id'),
('platform', 'A2', 'id'),
('restoran', 'A2', 'id'),
('kafe', 'A2', 'id'),
('sarapan', 'A2', 'id'),
('makan siang', 'A2', 'id'),
('makan malam', 'A2', 'id'),
('sayuran', 'A2', 'id'),
('buah', 'A2', 'id'),
('daging', 'A2', 'id'),
('ayam', 'A2', 'id'),
('daging sapi', 'A2', 'id'),
('ikan', 'A2', 'id'),
('roti', 'A2', 'id'),
('beras', 'A2', 'id'),
('pasta', 'A2', 'id'),
('sup', 'A2', 'id'),
('gula', 'A2', 'id'),
('garam', 'A2', 'id'),
('merica', 'A2', 'id'),
('minyak', 'A2', 'id'),
('belanja', 'A2', 'id'),
('pakaian', 'A2', 'id'),
('kemeja', 'A2', 'id'),
('celana panjang', 'A2', 'id'),
('gaun', 'A2', 'id'),
('sepatu', 'A2', 'id'),
('topi', 'A2', 'id'),
('jaket', 'A2', 'id'),
('mantel', 'A2', 'id'),
('cuaca', 'A2', 'id'),
('salju', 'A2', 'id'),
('angin', 'A2', 'id'),
('badai', 'A2', 'id'),
('hotel', 'A2', 'id'),
('tamu', 'A2', 'id'),
('melayani', 'A2', 'id'),
('penerimaan', 'A2', 'id'),
('kunci', 'A2', 'id'),
('reservasi', 'A2', 'id'),
('pantai', 'A2', 'id'),
('laut', 'A2', 'id'),
('renang', 'A2', 'id'),
('kolam', 'A2', 'id'),
('gunung', 'A2', 'id'),
('desa', 'A2', 'id'),
('negara', 'A2', 'id'),
('bahasa', 'A2', 'id'),
('luar negeri', 'A2', 'id'),
('ujian', 'A2', 'id'),
('tes', 'A2', 'id'),
('pekerjaan rumah', 'A2', 'id'),
('kelas', 'A2', 'id'),
('subjek', 'A2', 'id'),
('Matematika', 'A2', 'id'),
('sejarah', 'A2', 'id'),
('sains', 'A2', 'id'),
('perpustakaan', 'A2', 'id'),
('toko buku', 'A2', 'id'),
('komputer', 'A2', 'id'),
('Internet', 'A2', 'id'),
('e-mail', 'A2', 'id'),
('pesan', 'A2', 'id'),
('surat', 'A2', 'id'),
('pos', 'A2', 'id'),
('bank', 'A2', 'id'),
('uang', 'A2', 'id'),
('kartu kredit', 'A2', 'id'),
('harga', 'A2', 'id'),
('murah', 'A2', 'id'),
('mahal', 'A2', 'id'),
('pertanyaan', 'A2', 'id'),
('menjawab', 'A2', 'id'),
('menjelaskan', 'A2', 'id'),
('membantu', 'A2', 'id'),
('masalah', 'A2', 'id'),
('larutan', 'A2', 'id'),
('kesehatan', 'A2', 'id'),
('obat', 'A2', 'id'),
('dokter', 'A2', 'id'),
('perawat', 'A2', 'id'),
('sabar', 'A2', 'id'),
('janji temu', 'A2', 'id'),
('demam', 'A2', 'id'),
('batuk', 'A2', 'id'),
('pengalaman', 'B1', 'id'),
('petualangan', 'B1', 'id'),
('pendapat', 'B1', 'id'),
('diskusi', 'B1', 'id'),
('argumen', 'B1', 'id'),
('keputusan', 'B1', 'id'),
('alasan', 'B1', 'id'),
('peluang', 'B1', 'id'),
('tantangan', 'B1', 'id'),
('kesuksesan', 'B1', 'id'),
('kegagalan', 'B1', 'id'),
('sasaran', 'B1', 'id'),
('rencana', 'B1', 'id'),
('proyek', 'B1', 'id'),
('pengetahuan', 'B1', 'id'),
('keahlian', 'B1', 'id'),
('kemampuan', 'B1', 'id'),
('peningkatan', 'B1', 'id'),
('pelatihan', 'B1', 'id'),
('wawancara kerja', 'B1', 'id'),
('aplikasi', 'B1', 'id'),
('karier', 'B1', 'id'),
('manajer', 'B1', 'id'),
('kolega', 'B1', 'id'),
('pertemuan', 'B1', 'id'),
('tugas', 'B1', 'id'),
('tanggung jawab', 'B1', 'id'),
('perjalanan liburan', 'B1', 'id'),
('budaya', 'B1', 'id'),
('tradisi', 'B1', 'id'),
('kebiasaan', 'B1', 'id'),
('festival', 'B1', 'id'),
('perayaan', 'B1', 'id'),
('pertunjukan', 'B1', 'id'),
('konser', 'B1', 'id'),
('teater', 'B1', 'id'),
('pameran', 'B1', 'id'),
('lukisan', 'B1', 'id'),
('patung', 'B1', 'id'),
('museum', 'B1', 'id'),
('Buku Sejarah', 'B1', 'id'),
('fiksi', 'B1', 'id'),
('puisi', 'B1', 'id'),
('novel', 'B1', 'id'),
('karakter', 'B1', 'id'),
('merencanakan', 'B1', 'id'),
('cerita', 'B1', 'id'),
('koran', 'B1', 'id'),
('majalah', 'B1', 'id'),
('artikel', 'B1', 'id'),
('laporan', 'B1', 'id'),
('presentasi', 'B1', 'id'),
('kuliah', 'B1', 'id'),
('pendidikan', 'B1', 'id'),
('universitas', 'B1', 'id'),
('derajat', 'B1', 'id'),
('diploma', 'B1', 'id'),
('sertifikat', 'B1', 'id'),
('lingkungan', 'B1', 'id'),
('alam', 'B1', 'id'),
('daur ulang', 'B1', 'id'),
('polusi', 'B1', 'id'),
('Perubahan Iklim', 'B1', 'id'),
('Pemanasan global', 'B1', 'id'),
('energi', 'B1', 'id'),
('teknologi', 'B1', 'id'),
('inovasi', 'B1', 'id'),
('penemuan', 'B1', 'id'),
('perangkat', 'B1', 'id'),
('mesin', 'B1', 'id'),
('program komputer', 'B1', 'id'),
('situs web', 'B1', 'id'),
('aplikasi', 'B1', 'id'),
('media sosial', 'B1', 'id'),
('komunikasi', 'B1', 'id'),
('percakapan', 'B1', 'id'),
('interaksi', 'B1', 'id'),
('hubungan', 'B1', 'id'),
('persahabatan', 'B1', 'id'),
('pernikahan', 'B1', 'id'),
('kehidupan keluarga', 'B1', 'id'),
('kebahagiaan', 'B1', 'id'),
('amarah', 'B1', 'id'),
('takut', 'B1', 'id'),
('harapan', 'B1', 'id'),
('mimpi', 'B1', 'id'),
('ambisi', 'B1', 'id'),
('motivasi', 'B1', 'id'),
('kepercayaan diri', 'B1', 'id'),
('Keingintahuan', 'B1', 'id'),
('kesabaran', 'B1', 'id'),
('inovasi', 'B2', 'id'),
('perkembangan', 'B2', 'id'),
('riset', 'B2', 'id'),
('analisa', 'B2', 'id'),
('interpretasi', 'B2', 'id'),
('argumentasi', 'B2', 'id'),
('perbandingan', 'B2', 'id'),
('hipotesa', 'B2', 'id'),
('teori', 'B2', 'id'),
('percobaan', 'B2', 'id'),
('bukti', 'B2', 'id'),
('metode', 'B2', 'id'),
('kesimpulan', 'B2', 'id'),
('pengamatan', 'B2', 'id'),
('perspektif', 'B2', 'id'),
('anggapan', 'B2', 'id'),
('konteks', 'B2', 'id'),
('kriteria', 'B2', 'id'),
('prinsip', 'B2', 'id'),
('prioritas', 'B2', 'id'),
('kompleksitas', 'B2', 'id'),
('efisiensi', 'B2', 'id'),
('produktivitas', 'B2', 'id'),
('investasi', 'B2', 'id'),
('ekonomi', 'B2', 'id'),
('keuangan', 'B2', 'id'),
('perundingan', 'B2', 'id'),
('perjanjian', 'B2', 'id'),
('kontrak', 'B2', 'id'),
('kebijakan', 'B2', 'id'),
('pemerintah', 'B2', 'id'),
('politik', 'B2', 'id'),
('pemilihan', 'B2', 'id'),
('demokrasi', 'B2', 'id'),
('kebebasan', 'B2', 'id'),
('keadilan', 'B2', 'id'),
('persamaan', 'B2', 'id'),
('hukum', 'B2', 'id'),
('kejahatan', 'B2', 'id'),
('penalti', 'B2', 'id'),
('hukuman', 'B2', 'id'),
('keamanan', 'B2', 'id'),
('konflik', 'B2', 'id'),
('perang', 'B2', 'id'),
('perdamaian', 'B2', 'id'),
('kekerasan', 'B2', 'id'),
('terorisme', 'B2', 'id'),
('Globalisasi', 'B2', 'id'),
('integrasi', 'B2', 'id'),
('keberagaman', 'B2', 'id'),
('identitas', 'B2', 'id'),
('migrasi', 'B2', 'id'),
('pengungsi', 'B2', 'id'),
('masyarakat', 'B2', 'id'),
('jaringan', 'B2', 'id'),
('organisasi', 'B2', 'id'),
('lembaga', 'B2', 'id'),
('kepemimpinan', 'B2', 'id'),
('pengelolaan', 'B2', 'id'),
('perencanaan', 'B2', 'id'),
('strategi', 'B2', 'id'),
('prakarsa', 'B2', 'id'),
('kreativitas', 'B2', 'id'),
('kolaborasi', 'B2', 'id'),
('kerja sama', 'B2', 'id'),
('tanggung jawab', 'B2', 'id'),
('akuntabilitas', 'B2', 'id'),
('Keberlanjutan', 'B2', 'id'),
('Perlindungan Lingkungan', 'B2', 'id'),
('energi terbarukan', 'B2', 'id'),
('proses inovasi', 'B2', 'id'),
('pemikiran kritis', 'B2', 'id'),
('pemecahan masalah', 'B2', 'id'),
('pengambilan keputusan', 'B2', 'id'),
('manajemen waktu', 'B2', 'id'),
('disiplin diri', 'B2', 'id'),
('adaptasi', 'B2', 'id'),
('ketangguhan', 'B2', 'id'),
('kemerdekaan', 'B2', 'id'),
('kerja sama', 'B2', 'id'),
('memercayai', 'B2', 'id'),
('menghormati', 'B2', 'id'),
('Empati', 'B2', 'id'),
('loyalitas', 'B2', 'id'),
('integritas', 'B2', 'id'),
('etika', 'B2', 'id'),
('moralitas', 'B2', 'id'),
('filsafat', 'B2', 'id'),
('psikologi', 'B2', 'id'),
('sosiologi', 'B2', 'id'),
('biologi', 'B2', 'id'),
('kimia', 'B2', 'id'),
('fisika', 'B2', 'id'),
('analisis kritis', 'C1', 'id'),
('penalaran logis', 'C1', 'id'),
('interpretasi', 'C1', 'id'),
('perbandingan yang mendalam', 'C1', 'id'),
('kesimpulan ilmiah', 'C1', 'id'),
('hipotesis kompleks', 'C1', 'id'),
('teori lanjutan', 'C1', 'id'),
('Eksperimen mendalam', 'C1', 'id'),
('Evaluasi Komprehensif', 'C1', 'id'),
('Diskusi Filsafat', 'C1', 'id'),
('argumen yang kuat', 'C1', 'id'),
('bukti nyata', 'C1', 'id'),
('bukti kontradiktif', 'C1', 'id'),
('Konsep abstrak', 'C1', 'id'),
('posisi etis', 'C1', 'id'),
('nilai tertinggi', 'C1', 'id'),
('Prinsip dasar', 'C1', 'id'),
('prioritas utama', 'C1', 'id'),
('tanggung jawab utama', 'C1', 'id'),
('keputusan penting', 'C1', 'id'),
('manajemen yang kompleks', 'C1', 'id'),
('perencanaan strategis', 'C1', 'id'),
('Pembangunan Berkelanjutan', 'C1', 'id'),
('Inovasi modern', 'C1', 'id'),
('kreativitas canggih', 'C1', 'id'),
('penemuan baru', 'C1', 'id'),
('penemuan inovatif', 'C1', 'id'),
('Analisis Ekonomi', 'C1', 'id'),
('Laporan Keuangan', 'C1', 'id'),
('proyek skala besar', 'C1', 'id'),
('negosiasi internasional', 'C1', 'id'),
('perjanjian formal', 'C1', 'id'),
('strategi yang efektif', 'C1', 'id'),
('Lembaga Global', 'C1', 'id'),
('Pusat Penelitian', 'C1', 'id'),
('Studi Ilmiah Lanjutan', 'C1', 'id'),
('Ulasan Kritis', 'C1', 'id'),
('interpretasi filosofis', 'C1', 'id'),
('pendekatan sistematis', 'C1', 'id'),
('teori modern', 'C1', 'id'),
('Penelitian Terapan', 'C1', 'id'),
('Eksperimen Praktis', 'C1', 'id'),
('Evaluasi obyektif', 'C1', 'id'),
('Hasil terperinci', 'C1', 'id'),
('debat lanjutan', 'C1', 'id'),
('studi perbandingan', 'C1', 'id'),
('Penelitian Lapangan', 'C1', 'id'),
('Rekomendasi Praktis', 'C1', 'id'),
('keterampilan lanjutan', 'C1', 'id'),
('kerangka kerja konseptual', 'C1', 'id'),
('perencanaan yang tepat', 'C1', 'id'),
('strategi jangka panjang', 'C1', 'id'),
('penilaian risiko', 'C1', 'id'),
('Ulasan Akademik', 'C1', 'id'),
('proyek penelitian', 'C1', 'id'),
('Inovasi ilmiah', 'C1', 'id'),
('Perkembangan Teknologi', 'C1', 'id'),
('analisis sastra', 'C1', 'id'),
('temuan ilmiah', 'C1', 'id'),
('interpretasi lanjutan', 'C1', 'id'),
('pandangan holistik', 'C1', 'id'),
('Rencana Implementasi', 'C1', 'id'),
('keputusan strategis', 'C1', 'id'),
('Manajemen Sumber Daya', 'C1', 'id'),
('tantangan yang kompleks', 'C1', 'id'),
('solusi inovatif', 'C1', 'id'),
('pendekatan komprehensif', 'C1', 'id'),
('Analisis Data', 'C1', 'id'),
('Pengujian Hipotesis', 'C1', 'id'),
('studi kasus', 'C1', 'id'),
('Kerja lapangan tingkat lanjut', 'C1', 'id'),
('Ulasan filosofis', 'C1', 'id'),
('Proyek Penelitian Terapan', 'C1', 'id'),
('Diskusi Akademik', 'C1', 'id'),
('Evaluasi Strategis', 'C1', 'id'),
('Rekomendasi Praktis', 'C1', 'id'),
('rencana kerja', 'C1', 'id'),
('Manajemen Proyek', 'C1', 'id'),
('publikasi akademik', 'C1', 'id'),
('penemuan ilmiah', 'C1', 'id'),
('Inovasi Terapan', 'C1', 'id'),
('Perkembangan Berkelanjutan', 'C1', 'id'),
('Analisis data mendalam', 'C1', 'id'),
('pengalaman penelitian', 'C1', 'id'),
('interpretasi ilmiah', 'C1', 'id'),
('perspektif kritis', 'C1', 'id');
