INSERT INTO words (word, level, language_code) VALUES
('kuća', 'A1', 'hr'),
('vrata', 'A1', 'hr'),
('prozor', 'A1', 'hr'),
('stol', 'A1', 'hr'),
('stolica', 'A1', 'hr'),
('rezervirati', 'A1', 'hr'),
('olovka', 'A1', 'hr'),
('škola', 'A1', 'hr'),
('učitelj', 'A1', 'hr'),
('student', 'A1', 'hr'),
('jabuka', 'A1', 'hr'),
('voda', 'A1', 'hr'),
('hrana', 'A1', 'hr'),
('automobil', 'A1', 'hr'),
('autobus', 'A1', 'hr'),
('ulica', 'A1', 'hr'),
('prijatelj', 'A1', 'hr'),
('obitelj', 'A1', 'hr'),
('majka', 'A1', 'hr'),
('otac', 'A1', 'hr'),
('sestra', 'A1', 'hr'),
('brat', 'A1', 'hr'),
('dan', 'A1', 'hr'),
('noć', 'A1', 'hr'),
('jutro', 'A1', 'hr'),
('večer', 'A1', 'hr'),
('Zdravo', 'A1', 'hr'),
('Zbogom', 'A1', 'hr'),
('Molim', 'A1', 'hr'),
('Hvala', 'A1', 'hr'),
('Da', 'A1', 'hr'),
('Ne', 'A1', 'hr'),
('crveni', 'A1', 'hr'),
('plavi', 'A1', 'hr'),
('zelena', 'A1', 'hr'),
('bijela', 'A1', 'hr'),
('crni', 'A1', 'hr'),
('mali', 'A1', 'hr'),
('velik', 'A1', 'hr'),
('dobro', 'A1', 'hr'),
('loš', 'A1', 'hr'),
('vrući', 'A1', 'hr'),
('hladnoća', 'A1', 'hr'),
('kava', 'A1', 'hr'),
('čaj', 'A1', 'hr'),
('novac', 'A1', 'hr'),
('raditi', 'A1', 'hr'),
('dom', 'A1', 'hr'),
('dućan', 'A1', 'hr'),
('tržište', 'A1', 'hr'),
('hrana', 'A1', 'hr'),
('piće', 'A1', 'hr'),
('grad', 'A1', 'hr'),
('park', 'A1', 'hr'),
('ulica', 'A1', 'hr'),
('autobusna stanica', 'A1', 'hr'),
('vlak', 'A1', 'hr'),
('stanica', 'A1', 'hr'),
('hotel', 'A1', 'hr'),
('soba', 'A1', 'hr'),
('krevet', 'A1', 'hr'),
('liječnik', 'A1', 'hr'),
('bolnica', 'A1', 'hr'),
('škola', 'A1', 'hr'),
('sveučilište', 'A1', 'hr'),
('računalo', 'A1', 'hr'),
('telefon', 'A1', 'hr'),
('televizija', 'A1', 'hr'),
('glazba', 'A1', 'hr'),
('pjesma', 'A1', 'hr'),
('film', 'A1', 'hr'),
('igra', 'A1', 'hr'),
('nogomet', 'A1', 'hr'),
('lopta', 'A1', 'hr'),
('voda', 'A1', 'hr'),
('kiša', 'A1', 'hr'),
('sunce', 'A1', 'hr'),
('nebo', 'A1', 'hr'),
('stablo', 'A1', 'hr'),
('cvijet', 'A1', 'hr'),
('životinja', 'A1', 'hr'),
('mačka', 'A1', 'hr'),
('pas', 'A1', 'hr'),
('ptica', 'A1', 'hr'),
('riba', 'A1', 'hr'),
('čovjek', 'A1', 'hr'),
('žena', 'A1', 'hr'),
('dijete', 'A1', 'hr'),
('ljudi', 'A1', 'hr'),
('ulica', 'A1', 'hr'),
('mjesto', 'A1', 'hr'),
('vrijeme', 'A1', 'hr'),
('godina', 'A1', 'hr'),
('mjesec', 'A1', 'hr'),
('tjedan', 'A1', 'hr'),
('danas', 'A1', 'hr'),
('sutra', 'A1', 'hr'),
('jučer', 'A1', 'hr'),
('ime', 'A1', 'hr'),
('adresa', 'A1', 'hr'),
('broj', 'A1', 'hr'),
('zračna luka', 'A2', 'hr'),
('let', 'A2', 'hr'),
('ulaznica', 'A2', 'hr'),
('putovnica', 'A2', 'hr'),
('putovati', 'A2', 'hr'),
('odmor', 'A2', 'hr'),
('putovanje', 'A2', 'hr'),
('prtljaga', 'A2', 'hr'),
('stanica', 'A2', 'hr'),
('platforma', 'A2', 'hr'),
('restoran', 'A2', 'hr'),
('kafić', 'A2', 'hr'),
('doručak', 'A2', 'hr'),
('ručak', 'A2', 'hr'),
('večera', 'A2', 'hr'),
('povrće', 'A2', 'hr'),
('voće', 'A2', 'hr'),
('meso', 'A2', 'hr'),
('piletina', 'A2', 'hr'),
('govedina', 'A2', 'hr'),
('riba', 'A2', 'hr'),
('kruh', 'A2', 'hr'),
('riža', 'A2', 'hr'),
('tjestenina', 'A2', 'hr'),
('juha', 'A2', 'hr'),
('šećer', 'A2', 'hr'),
('sol', 'A2', 'hr'),
('papar', 'A2', 'hr'),
('ulje', 'A2', 'hr'),
('kupovina', 'A2', 'hr'),
('odjeća', 'A2', 'hr'),
('košulja', 'A2', 'hr'),
('hlače', 'A2', 'hr'),
('haljina', 'A2', 'hr'),
('cipele', 'A2', 'hr'),
('šešir', 'A2', 'hr'),
('jakna', 'A2', 'hr'),
('kaput', 'A2', 'hr'),
('vrijeme', 'A2', 'hr'),
('snijeg', 'A2', 'hr'),
('vjetar', 'A2', 'hr'),
('oluja', 'A2', 'hr'),
('hoteli', 'A2', 'hr'),
('gost', 'A2', 'hr'),
('servis', 'A2', 'hr'),
('recepcija', 'A2', 'hr'),
('ključ', 'A2', 'hr'),
('rezervacija', 'A2', 'hr'),
('plaža', 'A2', 'hr'),
('more', 'A2', 'hr'),
('plivanje', 'A2', 'hr'),
('bazen', 'A2', 'hr'),
('planina', 'A2', 'hr'),
('selo', 'A2', 'hr'),
('zemlja', 'A2', 'hr'),
('jezik', 'A2', 'hr'),
('inozemni', 'A2', 'hr'),
('ispit', 'A2', 'hr'),
('test', 'A2', 'hr'),
('domaća zadaća', 'A2', 'hr'),
('učionica', 'A2', 'hr'),
('subjekt', 'A2', 'hr'),
('matematika', 'A2', 'hr'),
('povijest', 'A2', 'hr'),
('znanost', 'A2', 'hr'),
('knjižnica', 'A2', 'hr'),
('knjižara', 'A2', 'hr'),
('računalo', 'A2', 'hr'),
('Internet', 'A2', 'hr'),
('e -mail', 'A2', 'hr'),
('poruka', 'A2', 'hr'),
('pismo', 'A2', 'hr'),
('objaviti', 'A2', 'hr'),
('banka', 'A2', 'hr'),
('novac', 'A2', 'hr'),
('kreditna kartica', 'A2', 'hr'),
('cijena', 'A2', 'hr'),
('jeftin', 'A2', 'hr'),
('skup', 'A2', 'hr'),
('pitanje', 'A2', 'hr'),
('odgovor', 'A2', 'hr'),
('objasniti', 'A2', 'hr'),
('pomoć', 'A2', 'hr'),
('problem', 'A2', 'hr'),
('otopina', 'A2', 'hr'),
('zdravlje', 'A2', 'hr'),
('lijek', 'A2', 'hr'),
('liječnik', 'A2', 'hr'),
('sestra', 'A2', 'hr'),
('pacijent', 'A2', 'hr'),
('imenovanje', 'A2', 'hr'),
('vrućica', 'A2', 'hr'),
('kašalj', 'A2', 'hr'),
('iskustvo', 'B1', 'hr'),
('avantura', 'B1', 'hr'),
('mišljenje', 'B1', 'hr'),
('rasprava', 'B1', 'hr'),
('argument', 'B1', 'hr'),
('odluka', 'B1', 'hr'),
('razlog', 'B1', 'hr'),
('prilika', 'B1', 'hr'),
('izazov', 'B1', 'hr'),
('uspjeh', 'B1', 'hr'),
('neuspjeh', 'B1', 'hr'),
('cilj', 'B1', 'hr'),
('plan', 'B1', 'hr'),
('projekt', 'B1', 'hr'),
('znanje', 'B1', 'hr'),
('vještina', 'B1', 'hr'),
('sposobnost', 'B1', 'hr'),
('poboljšanje', 'B1', 'hr'),
('trening', 'B1', 'hr'),
('razgovor za posao', 'B1', 'hr'),
('prijava', 'B1', 'hr'),
('karijera', 'B1', 'hr'),
('menadžer', 'B1', 'hr'),
('kolega', 'B1', 'hr'),
('sastanak', 'B1', 'hr'),
('zadatak', 'B1', 'hr'),
('odgovornost', 'B1', 'hr'),
('putovanje', 'B1', 'hr'),
('kultura', 'B1', 'hr'),
('tradicija', 'B1', 'hr'),
('običaj', 'B1', 'hr'),
('festival', 'B1', 'hr'),
('proslava', 'B1', 'hr'),
('performanse', 'B1', 'hr'),
('koncert', 'B1', 'hr'),
('kazalište', 'B1', 'hr'),
('izložba', 'B1', 'hr'),
('slika', 'B1', 'hr'),
('skulptura', 'B1', 'hr'),
('muzej', 'B1', 'hr'),
('povijesna knjiga', 'B1', 'hr'),
('fikcija', 'B1', 'hr'),
('pjesma', 'B1', 'hr'),
('roman', 'B1', 'hr'),
('lik', 'B1', 'hr'),
('zemljište', 'B1', 'hr'),
('priča', 'B1', 'hr'),
('novine', 'B1', 'hr'),
('časopis', 'B1', 'hr'),
('članak', 'B1', 'hr'),
('izvješće', 'B1', 'hr'),
('prezentacija', 'B1', 'hr'),
('predavanje', 'B1', 'hr'),
('obrazovanje', 'B1', 'hr'),
('sveučilište', 'B1', 'hr'),
('stupanj', 'B1', 'hr'),
('diploma', 'B1', 'hr'),
('potvrda', 'B1', 'hr'),
('okoliš', 'B1', 'hr'),
('priroda', 'B1', 'hr'),
('recikliranje', 'B1', 'hr'),
('zagađenje', 'B1', 'hr'),
('klimatska promjena', 'B1', 'hr'),
('globalno zagrijavanje', 'B1', 'hr'),
('energija', 'B1', 'hr'),
('tehnologija', 'B1', 'hr'),
('inovacija', 'B1', 'hr'),
('izum', 'B1', 'hr'),
('uređaj', 'B1', 'hr'),
('mašina', 'B1', 'hr'),
('računalni program', 'B1', 'hr'),
('web stranica', 'B1', 'hr'),
('prijava', 'B1', 'hr'),
('Društveni mediji', 'B1', 'hr'),
('komunikacija', 'B1', 'hr'),
('razgovor', 'B1', 'hr'),
('interakcija', 'B1', 'hr'),
('odnos', 'B1', 'hr'),
('prijateljstvo', 'B1', 'hr'),
('brak', 'B1', 'hr'),
('obiteljski život', 'B1', 'hr'),
('sreća', 'B1', 'hr'),
('bijes', 'B1', 'hr'),
('strah', 'B1', 'hr'),
('nada', 'B1', 'hr'),
('san', 'B1', 'hr'),
('ambicija', 'B1', 'hr'),
('motivacija', 'B1', 'hr'),
('povjerenje', 'B1', 'hr'),
('znatiželja', 'B1', 'hr'),
('strpljenje', 'B1', 'hr'),
('inovacija', 'B2', 'hr'),
('razvoj', 'B2', 'hr'),
('istraživanje', 'B2', 'hr'),
('analiza', 'B2', 'hr'),
('tumačenje', 'B2', 'hr'),
('argumentacija', 'B2', 'hr'),
('usporedba', 'B2', 'hr'),
('hipoteza', 'B2', 'hr'),
('teorija', 'B2', 'hr'),
('eksperiment', 'B2', 'hr'),
('dokaz', 'B2', 'hr'),
('metoda', 'B2', 'hr'),
('zaključak', 'B2', 'hr'),
('opažanje', 'B2', 'hr'),
('perspektiva', 'B2', 'hr'),
('pretpostavka', 'B2', 'hr'),
('kontekst', 'B2', 'hr'),
('kriterij', 'B2', 'hr'),
('načelo', 'B2', 'hr'),
('prioritet', 'B2', 'hr'),
('složenost', 'B2', 'hr'),
('učinkovitost', 'B2', 'hr'),
('produktivnost', 'B2', 'hr'),
('ulaganje', 'B2', 'hr'),
('gospodarstvo', 'B2', 'hr'),
('financiranje', 'B2', 'hr'),
('pregovaranje', 'B2', 'hr'),
('sporazum', 'B2', 'hr'),
('ugovor', 'B2', 'hr'),
('politika', 'B2', 'hr'),
('vlada', 'B2', 'hr'),
('politika', 'B2', 'hr'),
('izborni', 'B2', 'hr'),
('demokracija', 'B2', 'hr'),
('sloboda', 'B2', 'hr'),
('pravda', 'B2', 'hr'),
('jednakost', 'B2', 'hr'),
('zakon', 'B2', 'hr'),
('zločin', 'B2', 'hr'),
('kazna', 'B2', 'hr'),
('kazna', 'B2', 'hr'),
('sigurnost', 'B2', 'hr'),
('sukob', 'B2', 'hr'),
('rat', 'B2', 'hr'),
('mir', 'B2', 'hr'),
('nasilje', 'B2', 'hr'),
('terorizam', 'B2', 'hr'),
('globalizacija', 'B2', 'hr'),
('integracija', 'B2', 'hr'),
('raznolikost', 'B2', 'hr'),
('identitet', 'B2', 'hr'),
('migracija', 'B2', 'hr'),
('izbjeglica', 'B2', 'hr'),
('zajednica', 'B2', 'hr'),
('mreža', 'B2', 'hr'),
('organizacija', 'B2', 'hr'),
('institucija', 'B2', 'hr'),
('rukovodstvo', 'B2', 'hr'),
('upravljanje', 'B2', 'hr'),
('planiranje', 'B2', 'hr'),
('strategija', 'B2', 'hr'),
('inicijativa', 'B2', 'hr'),
('kreativnost', 'B2', 'hr'),
('suradnja', 'B2', 'hr'),
('timski rad', 'B2', 'hr'),
('odgovornost', 'B2', 'hr'),
('odgovornost', 'B2', 'hr'),
('održivost', 'B2', 'hr'),
('zaštita okoliša', 'B2', 'hr'),
('obnovljiva energija', 'B2', 'hr'),
('inovacijski postupak', 'B2', 'hr'),
('kritičko razmišljanje', 'B2', 'hr'),
('rješavanje problema', 'B2', 'hr'),
('donošenje odluka', 'B2', 'hr'),
('upravljanje vremenom', 'B2', 'hr'),
('samodisciplina', 'B2', 'hr'),
('adaptacija', 'B2', 'hr'),
('elastičnost', 'B2', 'hr'),
('neovisnost', 'B2', 'hr'),
('suradnju', 'B2', 'hr'),
('povjerenje', 'B2', 'hr'),
('poštovanje', 'B2', 'hr'),
('empatija', 'B2', 'hr'),
('lojalnost', 'B2', 'hr'),
('integritet', 'B2', 'hr'),
('etika', 'B2', 'hr'),
('moralnost', 'B2', 'hr'),
('filozofija', 'B2', 'hr'),
('psihologija', 'B2', 'hr'),
('sociologija', 'B2', 'hr'),
('biologija', 'B2', 'hr'),
('kemija', 'B2', 'hr'),
('fizika', 'B2', 'hr'),
('kritička analiza', 'C1', 'hr'),
('logično obrazloženje', 'C1', 'hr'),
('tumačenje', 'C1', 'hr'),
('duboka usporedba', 'C1', 'hr'),
('znanstveni zaključak', 'C1', 'hr'),
('složena hipoteza', 'C1', 'hr'),
('Napredna teorija', 'C1', 'hr'),
('detaljni eksperiment', 'C1', 'hr'),
('sveobuhvatna procjena', 'C1', 'hr'),
('filozofska rasprava', 'C1', 'hr'),
('snažna argument', 'C1', 'hr'),
('opipljivi dokazi', 'C1', 'hr'),
('kontradiktorni dokazi', 'C1', 'hr'),
('apstraktni koncept', 'C1', 'hr'),
('etički položaj', 'C1', 'hr'),
('vrhovna vrijednost', 'C1', 'hr'),
('temeljni princip', 'C1', 'hr'),
('glavni prioritet', 'C1', 'hr'),
('glavna odgovornost', 'C1', 'hr'),
('ključna odluka', 'C1', 'hr'),
('složeno upravljanje', 'C1', 'hr'),
('Strateško planiranje', 'C1', 'hr'),
('održivi razvoj', 'C1', 'hr'),
('Moderna inovacija', 'C1', 'hr'),
('Napredna kreativnost', 'C1', 'hr'),
('Novo otkriće', 'C1', 'hr'),
('inovativni izum', 'C1', 'hr'),
('ekonomska analiza', 'C1', 'hr'),
('financijski izvještaj', 'C1', 'hr'),
('Projekt velikog razmjera', 'C1', 'hr'),
('međunarodni pregovori', 'C1', 'hr'),
('formalni dogovor', 'C1', 'hr'),
('učinkovita strategija', 'C1', 'hr'),
('globalna ustanova', 'C1', 'hr'),
('istraživački centar', 'C1', 'hr'),
('Napredna znanstvena studija', 'C1', 'hr'),
('kritički pregled', 'C1', 'hr'),
('filozofsko tumačenje', 'C1', 'hr'),
('sustavni pristup', 'C1', 'hr'),
('Moderna teorija', 'C1', 'hr'),
('primijenjeno istraživanje', 'C1', 'hr'),
('praktični eksperiment', 'C1', 'hr'),
('Objektivna procjena', 'C1', 'hr'),
('Detaljni rezultati', 'C1', 'hr'),
('Napredna rasprava', 'C1', 'hr'),
('komparativna studija', 'C1', 'hr'),
('terensko istraživanje', 'C1', 'hr'),
('praktična preporuka', 'C1', 'hr'),
('Napredna vještina', 'C1', 'hr'),
('konceptualni okvir', 'C1', 'hr'),
('Precizno planiranje', 'C1', 'hr'),
('dugoročna strategija', 'C1', 'hr'),
('procjena rizika', 'C1', 'hr'),
('akademski pregled', 'C1', 'hr'),
('istraživački projekt', 'C1', 'hr'),
('znanstvena inovacija', 'C1', 'hr'),
('tehnološki razvoj', 'C1', 'hr'),
('književna analiza', 'C1', 'hr'),
('Znanstvena nalaza', 'C1', 'hr'),
('Napredno tumačenje', 'C1', 'hr'),
('holistički pogled', 'C1', 'hr'),
('plan provedbe', 'C1', 'hr'),
('strateška odluka', 'C1', 'hr'),
('upravljanje resursima', 'C1', 'hr'),
('Složeni izazovi', 'C1', 'hr'),
('Inovativna rješenja', 'C1', 'hr'),
('sveobuhvatan pristup', 'C1', 'hr'),
('analiza podataka', 'C1', 'hr'),
('testiranje hipoteza', 'C1', 'hr'),
('studija slučaja', 'C1', 'hr'),
('Napredni terenski rad', 'C1', 'hr'),
('filozofski pregled', 'C1', 'hr'),
('Primijenjeni istraživački projekt', 'C1', 'hr'),
('akademska rasprava', 'C1', 'hr'),
('Strateška procjena', 'C1', 'hr'),
('praktične preporuke', 'C1', 'hr'),
('plan rada', 'C1', 'hr'),
('upravljanje projektima', 'C1', 'hr'),
('akademska publikacija', 'C1', 'hr'),
('znanstveno otkriće', 'C1', 'hr'),
('primijenjena inovacija', 'C1', 'hr'),
('kontinuirani razvoj', 'C1', 'hr'),
('detaljna analiza podataka', 'C1', 'hr'),
('Iskustvo istraživanja', 'C1', 'hr'),
('znanstveno tumačenje', 'C1', 'hr'),
('kritička perspektiva', 'C1', 'hr');
