INSERT INTO words (word, level, language_code) VALUES
('hiša', 'A1', 'sl'),
('vrata', 'A1', 'sl'),
('okno', 'A1', 'sl'),
('miza', 'A1', 'sl'),
('stol', 'A1', 'sl'),
('Knjiga', 'A1', 'sl'),
('pero', 'A1', 'sl'),
('šola', 'A1', 'sl'),
('učitelj', 'A1', 'sl'),
('študent', 'A1', 'sl'),
('Apple', 'A1', 'sl'),
('voda', 'A1', 'sl'),
('hrana', 'A1', 'sl'),
('avto', 'A1', 'sl'),
('avtobus', 'A1', 'sl'),
('ulica', 'A1', 'sl'),
('prijatelj', 'A1', 'sl'),
('družina', 'A1', 'sl'),
('mama', 'A1', 'sl'),
('oče', 'A1', 'sl'),
('sestra', 'A1', 'sl'),
('brat', 'A1', 'sl'),
('dan', 'A1', 'sl'),
('noč', 'A1', 'sl'),
('jutro', 'A1', 'sl'),
('zvečer', 'A1', 'sl'),
('Pozdravljeni', 'A1', 'sl'),
('Zbogom', 'A1', 'sl'),
('prosim', 'A1', 'sl'),
('Hvala', 'A1', 'sl'),
('DA', 'A1', 'sl'),
('ne', 'A1', 'sl'),
('rdeča', 'A1', 'sl'),
('modro', 'A1', 'sl'),
('Zeleno', 'A1', 'sl'),
('bela', 'A1', 'sl'),
('črn', 'A1', 'sl'),
('majhno', 'A1', 'sl'),
('velik', 'A1', 'sl'),
('dobro', 'A1', 'sl'),
('slabo', 'A1', 'sl'),
('vroče', 'A1', 'sl'),
('hladno', 'A1', 'sl'),
('kava', 'A1', 'sl'),
('čaj', 'A1', 'sl'),
('denar', 'A1', 'sl'),
('delo', 'A1', 'sl'),
('doma', 'A1', 'sl'),
('Trgovina', 'A1', 'sl'),
('trg', 'A1', 'sl'),
('hrana', 'A1', 'sl'),
('piti', 'A1', 'sl'),
('mesto', 'A1', 'sl'),
('parkiranje', 'A1', 'sl'),
('ulica', 'A1', 'sl'),
('avtobusno postajališče', 'A1', 'sl'),
('vlak', 'A1', 'sl'),
('postaja', 'A1', 'sl'),
('hotel', 'A1', 'sl'),
('soba', 'A1', 'sl'),
('postelja', 'A1', 'sl'),
('zdravnik', 'A1', 'sl'),
('Bolnišnica', 'A1', 'sl'),
('šola', 'A1', 'sl'),
('Univerza', 'A1', 'sl'),
('računalnik', 'A1', 'sl'),
('telefon', 'A1', 'sl'),
('televizija', 'A1', 'sl'),
('glasba', 'A1', 'sl'),
('pesem', 'A1', 'sl'),
('film', 'A1', 'sl'),
('igra', 'A1', 'sl'),
('nogomet', 'A1', 'sl'),
('žoga', 'A1', 'sl'),
('voda', 'A1', 'sl'),
('dež', 'A1', 'sl'),
('sonce', 'A1', 'sl'),
('nebo', 'A1', 'sl'),
('drevo', 'A1', 'sl'),
('cvet', 'A1', 'sl'),
('žival', 'A1', 'sl'),
('mačka', 'A1', 'sl'),
('pes', 'A1', 'sl'),
('ptica', 'A1', 'sl'),
('ribe', 'A1', 'sl'),
('človek', 'A1', 'sl'),
('ženska', 'A1', 'sl'),
('otrok', 'A1', 'sl'),
('ljudje', 'A1', 'sl'),
('ulica', 'A1', 'sl'),
('mesto', 'A1', 'sl'),
('čas', 'A1', 'sl'),
('leto', 'A1', 'sl'),
('mesec', 'A1', 'sl'),
('teden', 'A1', 'sl'),
('danes', 'A1', 'sl'),
('jutri', 'A1', 'sl'),
('včeraj', 'A1', 'sl'),
('ime', 'A1', 'sl'),
('nagovor', 'A1', 'sl'),
('številka', 'A1', 'sl'),
('Letališče', 'A2', 'sl'),
('let', 'A2', 'sl'),
('Vstopnica', 'A2', 'sl'),
('potni list', 'A2', 'sl'),
('potovati', 'A2', 'sl'),
('praznik', 'A2', 'sl'),
('potovanje', 'A2', 'sl'),
('prtljaga', 'A2', 'sl'),
('postaja', 'A2', 'sl'),
('obnosipa', 'A2', 'sl'),
('restavracija', 'A2', 'sl'),
('kavarna', 'A2', 'sl'),
('zajtrk', 'A2', 'sl'),
('kosilo', 'A2', 'sl'),
('večerja', 'A2', 'sl'),
('zelenjava', 'A2', 'sl'),
('sadje', 'A2', 'sl'),
('meso', 'A2', 'sl'),
('piščanec', 'A2', 'sl'),
('govedina', 'A2', 'sl'),
('ribe', 'A2', 'sl'),
('kruh', 'A2', 'sl'),
('riž', 'A2', 'sl'),
('testenine', 'A2', 'sl'),
('juha', 'A2', 'sl'),
('sladkor', 'A2', 'sl'),
('sol', 'A2', 'sl'),
('poper', 'A2', 'sl'),
('olje', 'A2', 'sl'),
('nakupovanje', 'A2', 'sl'),
('oblačila', 'A2', 'sl'),
('srajca', 'A2', 'sl'),
('hlače', 'A2', 'sl'),
('Obleka', 'A2', 'sl'),
('čevlji', 'A2', 'sl'),
('klobuk', 'A2', 'sl'),
('jakna', 'A2', 'sl'),
('plašč', 'A2', 'sl'),
('vreme', 'A2', 'sl'),
('sneg', 'A2', 'sl'),
('veter', 'A2', 'sl'),
('nevihta', 'A2', 'sl'),
('hoteli', 'A2', 'sl'),
('gost', 'A2', 'sl'),
('postrežba', 'A2', 'sl'),
('sprejem', 'A2', 'sl'),
('ključ', 'A2', 'sl'),
('rezervacija', 'A2', 'sl'),
('plaža', 'A2', 'sl'),
('morje', 'A2', 'sl'),
('plavanje', 'A2', 'sl'),
('bazen', 'A2', 'sl'),
('gora', 'A2', 'sl'),
('vasi', 'A2', 'sl'),
('država', 'A2', 'sl'),
('jezik', 'A2', 'sl'),
('tujca', 'A2', 'sl'),
('izpit', 'A2', 'sl'),
('test', 'A2', 'sl'),
('domača naloga', 'A2', 'sl'),
('učilnica', 'A2', 'sl'),
('tema', 'A2', 'sl'),
('matematika', 'A2', 'sl'),
('Zgodovina', 'A2', 'sl'),
('znanost', 'A2', 'sl'),
('Knjižnica', 'A2', 'sl'),
('knjigarna', 'A2', 'sl'),
('računalnik', 'A2', 'sl'),
('internet', 'A2', 'sl'),
('e -pošta', 'A2', 'sl'),
('sporočilo', 'A2', 'sl'),
('pismo', 'A2', 'sl'),
('objavo', 'A2', 'sl'),
('banka', 'A2', 'sl'),
('denar', 'A2', 'sl'),
('kreditna kartica', 'A2', 'sl'),
('cena', 'A2', 'sl'),
('poceni', 'A2', 'sl'),
('drago', 'A2', 'sl'),
('vprašanje', 'A2', 'sl'),
('odgovor', 'A2', 'sl'),
('razložiti', 'A2', 'sl'),
('pomoč', 'A2', 'sl'),
('problem', 'A2', 'sl'),
('rešitev', 'A2', 'sl'),
('zdravje', 'A2', 'sl'),
('zdravilo', 'A2', 'sl'),
('zdravnik', 'A2', 'sl'),
('medicinska sestra', 'A2', 'sl'),
('pacient', 'A2', 'sl'),
('sestanek', 'A2', 'sl'),
('vročina', 'A2', 'sl'),
('kašelj', 'A2', 'sl'),
('izkušnje', 'B1', 'sl'),
('pustolovščina', 'B1', 'sl'),
('mnenje', 'B1', 'sl'),
('razprava', 'B1', 'sl'),
('argument', 'B1', 'sl'),
('odločitev', 'B1', 'sl'),
('razlog', 'B1', 'sl'),
('priložnost', 'B1', 'sl'),
('izziv', 'B1', 'sl'),
('uspeh', 'B1', 'sl'),
('neuspeh', 'B1', 'sl'),
('cilj', 'B1', 'sl'),
('načrt', 'B1', 'sl'),
('projekt', 'B1', 'sl'),
('znanje', 'B1', 'sl'),
('spretnost', 'B1', 'sl'),
('sposobnost', 'B1', 'sl'),
('izboljšanje', 'B1', 'sl'),
('usposabljanje', 'B1', 'sl'),
('razgovor za službo', 'B1', 'sl'),
('aplikacija', 'B1', 'sl'),
('kariera', 'B1', 'sl'),
('Upravitelj', 'B1', 'sl'),
('kolega', 'B1', 'sl'),
('srečanje', 'B1', 'sl'),
('naloga', 'B1', 'sl'),
('odgovornost', 'B1', 'sl'),
('počitniško potovanje', 'B1', 'sl'),
('Kultura', 'B1', 'sl'),
('tradicija', 'B1', 'sl'),
('navada', 'B1', 'sl'),
('festival', 'B1', 'sl'),
('praznovanje', 'B1', 'sl'),
('uspešnost', 'B1', 'sl'),
('koncert', 'B1', 'sl'),
('gledališče', 'B1', 'sl'),
('razstava', 'B1', 'sl'),
('slika', 'B1', 'sl'),
('Skulptura', 'B1', 'sl'),
('Muzej', 'B1', 'sl'),
('Zgodovinska knjiga', 'B1', 'sl'),
('leposlovje', 'B1', 'sl'),
('pesem', 'B1', 'sl'),
('roman', 'B1', 'sl'),
('lik', 'B1', 'sl'),
('zaplet', 'B1', 'sl'),
('zgodba', 'B1', 'sl'),
('časopis', 'B1', 'sl'),
('revija', 'B1', 'sl'),
('članek', 'B1', 'sl'),
('poročilo', 'B1', 'sl'),
('predstavitev', 'B1', 'sl'),
('predavanje', 'B1', 'sl'),
('izobrazba', 'B1', 'sl'),
('Univerza', 'B1', 'sl'),
('stopinja', 'B1', 'sl'),
('diploma', 'B1', 'sl'),
('spričevalo', 'B1', 'sl'),
('okolje', 'B1', 'sl'),
('narava', 'B1', 'sl'),
('recikliranje', 'B1', 'sl'),
('onesnaževanje', 'B1', 'sl'),
('podnebne spremembe', 'B1', 'sl'),
('globalno segrevanje', 'B1', 'sl'),
('energija', 'B1', 'sl'),
('tehnologija', 'B1', 'sl'),
('inovacije', 'B1', 'sl'),
('izum', 'B1', 'sl'),
('naprava', 'B1', 'sl'),
('stroj', 'B1', 'sl'),
('računalniški program', 'B1', 'sl'),
('spletno mesto', 'B1', 'sl'),
('aplikacija', 'B1', 'sl'),
('socialni mediji', 'B1', 'sl'),
('komunikacija', 'B1', 'sl'),
('pogovor', 'B1', 'sl'),
('interakcija', 'B1', 'sl'),
('zveza', 'B1', 'sl'),
('prijateljstvo', 'B1', 'sl'),
('poroka', 'B1', 'sl'),
('družinsko življenje', 'B1', 'sl'),
('sreča', 'B1', 'sl'),
('jeza', 'B1', 'sl'),
('strah', 'B1', 'sl'),
('upanje', 'B1', 'sl'),
('sanje', 'B1', 'sl'),
('ambicija', 'B1', 'sl'),
('motivacija', 'B1', 'sl'),
('zaupanje', 'B1', 'sl'),
('Radovednost', 'B1', 'sl'),
('potrpljenje', 'B1', 'sl'),
('inovacije', 'B2', 'sl'),
('razvoj', 'B2', 'sl'),
('raziskave', 'B2', 'sl'),
('analiza', 'B2', 'sl'),
('interpretacija', 'B2', 'sl'),
('argumentacija', 'B2', 'sl'),
('primerjava', 'B2', 'sl'),
('hipoteza', 'B2', 'sl'),
('teorija', 'B2', 'sl'),
('poskus', 'B2', 'sl'),
('dokaze', 'B2', 'sl'),
('metoda', 'B2', 'sl'),
('zaključek', 'B2', 'sl'),
('opazovanje', 'B2', 'sl'),
('perspektiva', 'B2', 'sl'),
('predpostavka', 'B2', 'sl'),
('kontekst', 'B2', 'sl'),
('merila', 'B2', 'sl'),
('načelo', 'B2', 'sl'),
('prednostna naloga', 'B2', 'sl'),
('Kompleksnost', 'B2', 'sl'),
('učinkovitost', 'B2', 'sl'),
('produktivnost', 'B2', 'sl'),
('naložba', 'B2', 'sl'),
('ekonomija', 'B2', 'sl'),
('financiranje', 'B2', 'sl'),
('pogajanje', 'B2', 'sl'),
('sporazum', 'B2', 'sl'),
('pogodba', 'B2', 'sl'),
('politika', 'B2', 'sl'),
('vlada', 'B2', 'sl'),
('politika', 'B2', 'sl'),
('volitve', 'B2', 'sl'),
('demokracija', 'B2', 'sl'),
('svoboda', 'B2', 'sl'),
('pravičnost', 'B2', 'sl'),
('enakost', 'B2', 'sl'),
('zakon', 'B2', 'sl'),
('zločin', 'B2', 'sl'),
('kazen', 'B2', 'sl'),
('kazen', 'B2', 'sl'),
('varnost', 'B2', 'sl'),
('konflikt', 'B2', 'sl'),
('vojna', 'B2', 'sl'),
('mir', 'B2', 'sl'),
('nasilje', 'B2', 'sl'),
('terorizem', 'B2', 'sl'),
('globalizacija', 'B2', 'sl'),
('integracija', 'B2', 'sl'),
('raznolikost', 'B2', 'sl'),
('identiteta', 'B2', 'sl'),
('migracije', 'B2', 'sl'),
('begunec', 'B2', 'sl'),
('skupnost', 'B2', 'sl'),
('omrežje', 'B2', 'sl'),
('organizacija', 'B2', 'sl'),
('institucija', 'B2', 'sl'),
('vodstvo', 'B2', 'sl'),
('upravljanje', 'B2', 'sl'),
('načrtovanje', 'B2', 'sl'),
('strategija', 'B2', 'sl'),
('pobuda', 'B2', 'sl'),
('ustvarjalnost', 'B2', 'sl'),
('sodelovanje', 'B2', 'sl'),
('timsko delo', 'B2', 'sl'),
('odgovornost', 'B2', 'sl'),
('Odgovornost', 'B2', 'sl'),
('trajnost', 'B2', 'sl'),
('varstvo okolja', 'B2', 'sl'),
('obnovljiva energija', 'B2', 'sl'),
('inovacijski proces', 'B2', 'sl'),
('kritično razmišljanje', 'B2', 'sl'),
('reševanje problemov', 'B2', 'sl'),
('odločanje', 'B2', 'sl'),
('Upravljanje časa', 'B2', 'sl'),
('samodisciplina', 'B2', 'sl'),
('Prilagoditev', 'B2', 'sl'),
('odpornost', 'B2', 'sl'),
('neodvisnost', 'B2', 'sl'),
('sodelovanje', 'B2', 'sl'),
('zaupanje', 'B2', 'sl'),
('spoštovanje', 'B2', 'sl'),
('Empatija', 'B2', 'sl'),
('zvestoba', 'B2', 'sl'),
('integriteta', 'B2', 'sl'),
('etika', 'B2', 'sl'),
('morala', 'B2', 'sl'),
('filozofija', 'B2', 'sl'),
('Psihologija', 'B2', 'sl'),
('sociologija', 'B2', 'sl'),
('biologija', 'B2', 'sl'),
('Kemija', 'B2', 'sl'),
('fizika', 'B2', 'sl'),
('Kritična analiza', 'C1', 'sl'),
('logično sklepanje', 'C1', 'sl'),
('interpretacija', 'C1', 'sl'),
('Globoka primerjava', 'C1', 'sl'),
('Znanstveni zaključek', 'C1', 'sl'),
('zapletena hipoteza', 'C1', 'sl'),
('Napredna teorija', 'C1', 'sl'),
('Poglobljen eksperiment', 'C1', 'sl'),
('celovita ocena', 'C1', 'sl'),
('Filozofska razprava', 'C1', 'sl'),
('močan argument', 'C1', 'sl'),
('oprijemljivi dokazi', 'C1', 'sl'),
('nasprotujoči si dokazi', 'C1', 'sl'),
('abstraktni koncept', 'C1', 'sl'),
('etični položaj', 'C1', 'sl'),
('Vrhovna vrednost', 'C1', 'sl'),
('Temeljno načelo', 'C1', 'sl'),
('Najboljša prioriteta', 'C1', 'sl'),
('glavna odgovornost', 'C1', 'sl'),
('Ključna odločitev', 'C1', 'sl'),
('zapleteno upravljanje', 'C1', 'sl'),
('Strateško načrtovanje', 'C1', 'sl'),
('trajnostni razvoj', 'C1', 'sl'),
('sodobna inovacija', 'C1', 'sl'),
('Napredna ustvarjalnost', 'C1', 'sl'),
('novo odkritje', 'C1', 'sl'),
('inovativen izum', 'C1', 'sl'),
('ekonomska analiza', 'C1', 'sl'),
('finančno poročilo', 'C1', 'sl'),
('obsežen projekt', 'C1', 'sl'),
('Mednarodna pogajanja', 'C1', 'sl'),
('formalni dogovor', 'C1', 'sl'),
('učinkovita strategija', 'C1', 'sl'),
('globalna institucija', 'C1', 'sl'),
('Raziskovalni center', 'C1', 'sl'),
('Napredna znanstvena študija', 'C1', 'sl'),
('kritični pregled', 'C1', 'sl'),
('Filozofska interpretacija', 'C1', 'sl'),
('sistematični pristop', 'C1', 'sl'),
('sodobna teorija', 'C1', 'sl'),
('uporabne raziskave', 'C1', 'sl'),
('praktični eksperiment', 'C1', 'sl'),
('objektivna ocena', 'C1', 'sl'),
('podrobni rezultati', 'C1', 'sl'),
('Napredna razprava', 'C1', 'sl'),
('Primerjalna študija', 'C1', 'sl'),
('terenske raziskave', 'C1', 'sl'),
('Praktično priporočilo', 'C1', 'sl'),
('Napredna spretnost', 'C1', 'sl'),
('Konceptualni okvir', 'C1', 'sl'),
('natančno načrtovanje', 'C1', 'sl'),
('dolgoročna strategija', 'C1', 'sl'),
('Ocena tveganja', 'C1', 'sl'),
('Akademski pregled', 'C1', 'sl'),
('raziskovalni projekt', 'C1', 'sl'),
('Znanstvena inovacija', 'C1', 'sl'),
('tehnološki razvoj', 'C1', 'sl'),
('literarna analiza', 'C1', 'sl'),
('Znanstvene ugotovitve', 'C1', 'sl'),
('Napredna razlaga', 'C1', 'sl'),
('celostni pogled', 'C1', 'sl'),
('Načrt izvajanja', 'C1', 'sl'),
('strateška odločitev', 'C1', 'sl'),
('Upravljanje virov', 'C1', 'sl'),
('zapleteni izzivi', 'C1', 'sl'),
('inovativne rešitve', 'C1', 'sl'),
('celovit pristop', 'C1', 'sl'),
('analiza podatkov', 'C1', 'sl'),
('testiranje hipotez', 'C1', 'sl'),
('Študija primera', 'C1', 'sl'),
('Napredno terensko delo', 'C1', 'sl'),
('Filozofski pregled', 'C1', 'sl'),
('Aplikativni raziskovalni projekt', 'C1', 'sl'),
('akademska razprava', 'C1', 'sl'),
('Strateško vrednotenje', 'C1', 'sl'),
('praktična priporočila', 'C1', 'sl'),
('Delovni načrt', 'C1', 'sl'),
('Upravljanje projektov', 'C1', 'sl'),
('akademska publikacija', 'C1', 'sl'),
('Znanstveno odkritje', 'C1', 'sl'),
('uporabna inovacija', 'C1', 'sl'),
('neprekinjen razvoj', 'C1', 'sl'),
('Poglobljena analiza podatkov', 'C1', 'sl'),
('raziskovalne izkušnje', 'C1', 'sl'),
('znanstvena razlaga', 'C1', 'sl'),
('kritična perspektiva', 'C1', 'sl');
