INSERT INTO words (word, level, language_code) VALUES
('căn nhà', 'A1', 'vi'),
('Cửa', 'A1', 'vi'),
('cửa sổ', 'A1', 'vi'),
('bàn', 'A1', 'vi'),
('Chủ tịch', 'A1', 'vi'),
('sách', 'A1', 'vi'),
('cái bút', 'A1', 'vi'),
('trường học', 'A1', 'vi'),
('giáo viên', 'A1', 'vi'),
('học sinh', 'A1', 'vi'),
('quả táo', 'A1', 'vi'),
('Nước', 'A1', 'vi'),
('đồ ăn', 'A1', 'vi'),
('xe hơi', 'A1', 'vi'),
('Xe buýt', 'A1', 'vi'),
('đường phố', 'A1', 'vi'),
('bạn', 'A1', 'vi'),
('gia đình', 'A1', 'vi'),
('mẹ', 'A1', 'vi'),
('bố', 'A1', 'vi'),
('em gái', 'A1', 'vi'),
('anh trai', 'A1', 'vi'),
('ngày', 'A1', 'vi'),
('đêm', 'A1', 'vi'),
('buổi sáng', 'A1', 'vi'),
('buổi tối', 'A1', 'vi'),
('Xin chào', 'A1', 'vi'),
('tạm biệt', 'A1', 'vi'),
('Xin vui lòng', 'A1', 'vi'),
('Cảm ơn', 'A1', 'vi'),
('Đúng', 'A1', 'vi'),
('KHÔNG', 'A1', 'vi'),
('màu đỏ', 'A1', 'vi'),
('màu xanh da trời', 'A1', 'vi'),
('màu xanh lá', 'A1', 'vi'),
('trắng', 'A1', 'vi'),
('đen', 'A1', 'vi'),
('bé nhỏ', 'A1', 'vi'),
('to lớn', 'A1', 'vi'),
('Tốt', 'A1', 'vi'),
('xấu', 'A1', 'vi'),
('nóng', 'A1', 'vi'),
('lạnh lẽo', 'A1', 'vi'),
('cà phê', 'A1', 'vi'),
('trà', 'A1', 'vi'),
('tiền bạc', 'A1', 'vi'),
('công việc', 'A1', 'vi'),
('trang chủ', 'A1', 'vi'),
('cửa hàng', 'A1', 'vi'),
('chợ', 'A1', 'vi'),
('đồ ăn', 'A1', 'vi'),
('uống', 'A1', 'vi'),
('thành phố', 'A1', 'vi'),
('công viên', 'A1', 'vi'),
('đường phố', 'A1', 'vi'),
('trạm dừng xe buýt', 'A1', 'vi'),
('xe lửa', 'A1', 'vi'),
('ga tàu', 'A1', 'vi'),
('khách sạn', 'A1', 'vi'),
('phòng', 'A1', 'vi'),
('giường', 'A1', 'vi'),
('bác sĩ', 'A1', 'vi'),
('bệnh viện', 'A1', 'vi'),
('trường học', 'A1', 'vi'),
('trường đại học', 'A1', 'vi'),
('máy tính', 'A1', 'vi'),
('điện thoại', 'A1', 'vi'),
('tivi', 'A1', 'vi'),
('âm nhạc', 'A1', 'vi'),
('Bài hát', 'A1', 'vi'),
('phim ảnh', 'A1', 'vi'),
('trò chơi', 'A1', 'vi'),
('bóng đá', 'A1', 'vi'),
('quả bóng', 'A1', 'vi'),
('Nước', 'A1', 'vi'),
('cơn mưa', 'A1', 'vi'),
('mặt trời', 'A1', 'vi'),
('bầu trời', 'A1', 'vi'),
('cây', 'A1', 'vi'),
('hoa', 'A1', 'vi'),
('động vật', 'A1', 'vi'),
('con mèo', 'A1', 'vi'),
('chó', 'A1', 'vi'),
('chim', 'A1', 'vi'),
('cá', 'A1', 'vi'),
('người đàn ông', 'A1', 'vi'),
('đàn bà', 'A1', 'vi'),
('đứa trẻ', 'A1', 'vi'),
('mọi người', 'A1', 'vi'),
('đường phố', 'A1', 'vi'),
('địa điểm', 'A1', 'vi'),
('thời gian', 'A1', 'vi'),
('năm', 'A1', 'vi'),
('tháng', 'A1', 'vi'),
('tuần', 'A1', 'vi'),
('Hôm nay', 'A1', 'vi'),
('Ngày mai', 'A1', 'vi'),
('Hôm qua', 'A1', 'vi'),
('tên', 'A1', 'vi'),
('Địa chỉ', 'A1', 'vi'),
('con số', 'A1', 'vi'),
('sân bay', 'A2', 'vi'),
('chuyến bay', 'A2', 'vi'),
('vé', 'A2', 'vi'),
('Hộ chiếu', 'A2', 'vi'),
('du lịch', 'A2', 'vi'),
('ngày lễ', 'A2', 'vi'),
('hành trình', 'A2', 'vi'),
('hành lý', 'A2', 'vi'),
('ga tàu', 'A2', 'vi'),
('nền tảng', 'A2', 'vi'),
('nhà hàng', 'A2', 'vi'),
('Quán cà phê', 'A2', 'vi'),
('bữa sáng', 'A2', 'vi'),
('bữa trưa', 'A2', 'vi'),
('bữa tối', 'A2', 'vi'),
('rau', 'A2', 'vi'),
('hoa quả', 'A2', 'vi'),
('thịt', 'A2', 'vi'),
('thịt gà', 'A2', 'vi'),
('thịt bò', 'A2', 'vi'),
('cá', 'A2', 'vi'),
('bánh mỳ', 'A2', 'vi'),
('cơm', 'A2', 'vi'),
('mì ống', 'A2', 'vi'),
('canh', 'A2', 'vi'),
('đường', 'A2', 'vi'),
('muối', 'A2', 'vi'),
('hạt tiêu', 'A2', 'vi'),
('dầu', 'A2', 'vi'),
('mua sắm', 'A2', 'vi'),
('quần áo', 'A2', 'vi'),
('áo sơ mi', 'A2', 'vi'),
('quần dài', 'A2', 'vi'),
('đầm', 'A2', 'vi'),
('đôi giày', 'A2', 'vi'),
('Mũ', 'A2', 'vi'),
('áo khoác', 'A2', 'vi'),
('áo choàng', 'A2', 'vi'),
('thời tiết', 'A2', 'vi'),
('tuyết', 'A2', 'vi'),
('gió', 'A2', 'vi'),
('bão', 'A2', 'vi'),
('khách sạn', 'A2', 'vi'),
('khách mời', 'A2', 'vi'),
('dịch vụ', 'A2', 'vi'),
('thu nhận', 'A2', 'vi'),
('chìa khóa', 'A2', 'vi'),
('sự đặt chỗ', 'A2', 'vi'),
('bãi biển', 'A2', 'vi'),
('biển', 'A2', 'vi'),
('bơi lội', 'A2', 'vi'),
('hồ bơi', 'A2', 'vi'),
('núi', 'A2', 'vi'),
('làng bản', 'A2', 'vi'),
('quốc gia', 'A2', 'vi'),
('ngôn ngữ', 'A2', 'vi'),
('nước ngoài', 'A2', 'vi'),
('bài thi', 'A2', 'vi'),
('Bài kiểm tra', 'A2', 'vi'),
('bài tập về nhà', 'A2', 'vi'),
('Lớp học', 'A2', 'vi'),
('chủ thể', 'A2', 'vi'),
('toán học', 'A2', 'vi'),
('lịch sử', 'A2', 'vi'),
('khoa học', 'A2', 'vi'),
('thư viện', 'A2', 'vi'),
('hiệu sách', 'A2', 'vi'),
('máy tính', 'A2', 'vi'),
('internet', 'A2', 'vi'),
('e-mail', 'A2', 'vi'),
('tin nhắn', 'A2', 'vi'),
('thư', 'A2', 'vi'),
('bưu kiện', 'A2', 'vi'),
('ngân hàng', 'A2', 'vi'),
('tiền bạc', 'A2', 'vi'),
('Thẻ tín dụng', 'A2', 'vi'),
('giá', 'A2', 'vi'),
('rẻ', 'A2', 'vi'),
('đắt', 'A2', 'vi'),
('câu hỏi', 'A2', 'vi'),
('trả lời', 'A2', 'vi'),
('giải thích', 'A2', 'vi'),
('giúp đỡ', 'A2', 'vi'),
('vấn đề', 'A2', 'vi'),
('giải pháp', 'A2', 'vi'),
('sức khỏe', 'A2', 'vi'),
('thuốc', 'A2', 'vi'),
('bác sĩ', 'A2', 'vi'),
('y tá', 'A2', 'vi'),
('kiên nhẫn', 'A2', 'vi'),
('cuộc hẹn', 'A2', 'vi'),
('sốt', 'A2', 'vi'),
('ho', 'A2', 'vi'),
('kinh nghiệm', 'B1', 'vi'),
('cuộc phiêu lưu', 'B1', 'vi'),
('ý kiến', 'B1', 'vi'),
('cuộc thảo luận', 'B1', 'vi'),
('lý lẽ', 'B1', 'vi'),
('phán quyết', 'B1', 'vi'),
('lý do', 'B1', 'vi'),
('cơ hội', 'B1', 'vi'),
('thử thách', 'B1', 'vi'),
('thành công', 'B1', 'vi'),
('sự thất bại', 'B1', 'vi'),
('mục tiêu', 'B1', 'vi'),
('kế hoạch', 'B1', 'vi'),
('dự án', 'B1', 'vi'),
('kiến thức', 'B1', 'vi'),
('kỹ năng', 'B1', 'vi'),
('khả năng', 'B1', 'vi'),
('sự cải tiến', 'B1', 'vi'),
('đào tạo', 'B1', 'vi'),
('Phỏng vấn xin việc', 'B1', 'vi'),
('ứng dụng', 'B1', 'vi'),
('sự nghiệp', 'B1', 'vi'),
('giám đốc', 'B1', 'vi'),
('đồng nghiệp', 'B1', 'vi'),
('cuộc họp', 'B1', 'vi'),
('nhiệm vụ', 'B1', 'vi'),
('trách nhiệm', 'B1', 'vi'),
('Chuyến đi nghỉ mát', 'B1', 'vi'),
('văn hoá', 'B1', 'vi'),
('truyền thống', 'B1', 'vi'),
('phong tục', 'B1', 'vi'),
('lễ hội', 'B1', 'vi'),
('lễ ăn mừng', 'B1', 'vi'),
('hiệu suất', 'B1', 'vi'),
('buổi hòa nhạc', 'B1', 'vi'),
('nhà hát', 'B1', 'vi'),
('triển lãm', 'B1', 'vi'),
('bức vẽ', 'B1', 'vi'),
('điêu khắc', 'B1', 'vi'),
('bảo tàng', 'B1', 'vi'),
('Sách lịch sử', 'B1', 'vi'),
('viễn tưởng', 'B1', 'vi'),
('Bài thơ', 'B1', 'vi'),
('cuốn tiểu thuyết', 'B1', 'vi'),
('tính cách', 'B1', 'vi'),
('kịch bản', 'B1', 'vi'),
('câu chuyện', 'B1', 'vi'),
('báo', 'B1', 'vi'),
('tạp chí', 'B1', 'vi'),
('bài báo', 'B1', 'vi'),
('báo cáo', 'B1', 'vi'),
('bài thuyết trình', 'B1', 'vi'),
('Bài giảng', 'B1', 'vi'),
('giáo dục', 'B1', 'vi'),
('trường đại học', 'B1', 'vi'),
('bằng cấp', 'B1', 'vi'),
('bằng cấp', 'B1', 'vi'),
('giấy chứng nhận', 'B1', 'vi'),
('môi trường', 'B1', 'vi'),
('thiên nhiên', 'B1', 'vi'),
('tái chế', 'B1', 'vi'),
('sự ô nhiễm', 'B1', 'vi'),
('biến đổi khí hậu', 'B1', 'vi'),
('Sự nóng lên toàn cầu', 'B1', 'vi'),
('năng lượng', 'B1', 'vi'),
('công nghệ', 'B1', 'vi'),
('sự đổi mới', 'B1', 'vi'),
('sự phát minh', 'B1', 'vi'),
('thiết bị', 'B1', 'vi'),
('máy móc', 'B1', 'vi'),
('chương trình máy tính', 'B1', 'vi'),
('trang web', 'B1', 'vi'),
('ứng dụng', 'B1', 'vi'),
('Phương tiện truyền thông xã hội', 'B1', 'vi'),
('giao tiếp', 'B1', 'vi'),
('cuộc hội thoại', 'B1', 'vi'),
('sự tương tác', 'B1', 'vi'),
('mối quan hệ', 'B1', 'vi'),
('tình bạn', 'B1', 'vi'),
('kết hôn', 'B1', 'vi'),
('cuộc sống gia đình', 'B1', 'vi'),
('niềm hạnh phúc', 'B1', 'vi'),
('sự tức giận', 'B1', 'vi'),
('nỗi sợ', 'B1', 'vi'),
('mong', 'B1', 'vi'),
('mơ', 'B1', 'vi'),
('tham vọng', 'B1', 'vi'),
('động lực', 'B1', 'vi'),
('sự tự tin', 'B1', 'vi'),
('sự tò mò', 'B1', 'vi'),
('tính kiên nhẫn', 'B1', 'vi'),
('sự đổi mới', 'B2', 'vi'),
('phát triển', 'B2', 'vi'),
('nghiên cứu', 'B2', 'vi'),
('Phân tích', 'B2', 'vi'),
('Giải thích', 'B2', 'vi'),
('lập luận', 'B2', 'vi'),
('so sánh', 'B2', 'vi'),
('Giả thuyết', 'B2', 'vi'),
('lý thuyết', 'B2', 'vi'),
('cuộc thí nghiệm', 'B2', 'vi'),
('chứng cớ', 'B2', 'vi'),
('phương pháp', 'B2', 'vi'),
('Phần kết luận', 'B2', 'vi'),
('quan sát', 'B2', 'vi'),
('luật xa gần', 'B2', 'vi'),
('giả định', 'B2', 'vi'),
('bối cảnh', 'B2', 'vi'),
('tiêu chuẩn', 'B2', 'vi'),
('nguyên tắc', 'B2', 'vi'),
('sự ưu tiên', 'B2', 'vi'),
('sự phức tạp', 'B2', 'vi'),
('hiệu quả', 'B2', 'vi'),
('năng suất', 'B2', 'vi'),
('sự đầu tư', 'B2', 'vi'),
('kinh tế', 'B2', 'vi'),
('tài chính', 'B2', 'vi'),
('Đàm phán', 'B2', 'vi'),
('hiệp định', 'B2', 'vi'),
('hợp đồng', 'B2', 'vi'),
('chính sách', 'B2', 'vi'),
('chính phủ', 'B2', 'vi'),
('chính trị', 'B2', 'vi'),
('bầu cử', 'B2', 'vi'),
('nền dân chủ', 'B2', 'vi'),
('tự do', 'B2', 'vi'),
('công lý', 'B2', 'vi'),
('sự bình đẳng', 'B2', 'vi'),
('pháp luật', 'B2', 'vi'),
('tội phạm', 'B2', 'vi'),
('hình phạt', 'B2', 'vi'),
('hình phạt', 'B2', 'vi'),
('bảo vệ', 'B2', 'vi'),
('xung đột', 'B2', 'vi'),
('chiến tranh', 'B2', 'vi'),
('hòa bình', 'B2', 'vi'),
('bạo lực', 'B2', 'vi'),
('khủng bố', 'B2', 'vi'),
('Toàn cầu hóa', 'B2', 'vi'),
('Tích hợp', 'B2', 'vi'),
('đa dạng', 'B2', 'vi'),
('danh tính', 'B2', 'vi'),
('di cư', 'B2', 'vi'),
('Người tị nạn', 'B2', 'vi'),
('cộng đồng', 'B2', 'vi'),
('mạng', 'B2', 'vi'),
('tổ chức', 'B2', 'vi'),
('tổ chức', 'B2', 'vi'),
('Khả năng lãnh đạo', 'B2', 'vi'),
('sự quản lý', 'B2', 'vi'),
('lập kế hoạch', 'B2', 'vi'),
('chiến lược', 'B2', 'vi'),
('sáng kiến', 'B2', 'vi'),
('sáng tạo', 'B2', 'vi'),
('sự hợp tác', 'B2', 'vi'),
('Làm việc nhóm', 'B2', 'vi'),
('trách nhiệm', 'B2', 'vi'),
('trách nhiệm', 'B2', 'vi'),
('bền vững', 'B2', 'vi'),
('Bảo vệ môi trường', 'B2', 'vi'),
('năng lượng tái tạo', 'B2', 'vi'),
('quá trình đổi mới', 'B2', 'vi'),
('tư duy phê phán', 'B2', 'vi'),
('giải quyết vấn đề', 'B2', 'vi'),
('ra quyết định', 'B2', 'vi'),
('Quản lý thời gian', 'B2', 'vi'),
('Kỷ luật tự giác', 'B2', 'vi'),
('thích ứng', 'B2', 'vi'),
('khả năng phục hồi', 'B2', 'vi'),
('sự độc lập', 'B2', 'vi'),
('sự hợp tác', 'B2', 'vi'),
('lòng tin', 'B2', 'vi'),
('sự tôn trọng', 'B2', 'vi'),
('sự đồng cảm', 'B2', 'vi'),
('lòng trung thành', 'B2', 'vi'),
('chính trực', 'B2', 'vi'),
('Đạo đức', 'B2', 'vi'),
('đạo đức', 'B2', 'vi'),
('triết lý', 'B2', 'vi'),
('tâm lý', 'B2', 'vi'),
('Xã hội học', 'B2', 'vi'),
('sinh vật học', 'B2', 'vi'),
('hoá học', 'B2', 'vi'),
('Vật lý', 'B2', 'vi'),
('Phân tích quan trọng', 'C1', 'vi'),
('Lý luận hợp lý', 'C1', 'vi'),
('Giải thích', 'C1', 'vi'),
('So sánh sâu', 'C1', 'vi'),
('Kết luận khoa học', 'C1', 'vi'),
('Giả thuyết phức tạp', 'C1', 'vi'),
('Lý thuyết nâng cao', 'C1', 'vi'),
('Thí nghiệm chuyên sâu', 'C1', 'vi'),
('Đánh giá toàn diện', 'C1', 'vi'),
('Thảo luận triết học', 'C1', 'vi'),
('lập luận mạnh mẽ', 'C1', 'vi'),
('Bằng chứng hữu hình', 'C1', 'vi'),
('Bằng chứng mâu thuẫn', 'C1', 'vi'),
('Khái niệm trừu tượng', 'C1', 'vi'),
('vị trí đạo đức', 'C1', 'vi'),
('Giá trị tối cao', 'C1', 'vi'),
('nguyên tắc cơ bản', 'C1', 'vi'),
('Ưu tiên hàng đầu', 'C1', 'vi'),
('trách nhiệm chính', 'C1', 'vi'),
('Quyết định quan trọng', 'C1', 'vi'),
('Quản lý phức tạp', 'C1', 'vi'),
('Lập kế hoạch chiến lược', 'C1', 'vi'),
('Phát triển bền vững', 'C1', 'vi'),
('Đổi mới hiện đại', 'C1', 'vi'),
('sáng tạo nâng cao', 'C1', 'vi'),
('Khám phá mới', 'C1', 'vi'),
('Phát minh sáng tạo', 'C1', 'vi'),
('Phân tích kinh tế', 'C1', 'vi'),
('Báo cáo tài chính', 'C1', 'vi'),
('Dự án quy mô lớn', 'C1', 'vi'),
('Đàm phán quốc tế', 'C1', 'vi'),
('Thỏa thuận chính thức', 'C1', 'vi'),
('chiến lược hiệu quả', 'C1', 'vi'),
('tổ chức toàn cầu', 'C1', 'vi'),
('Trung tâm nghiên cứu', 'C1', 'vi'),
('Nghiên cứu khoa học nâng cao', 'C1', 'vi'),
('Đánh giá quan trọng', 'C1', 'vi'),
('Giải thích triết học', 'C1', 'vi'),
('cách tiếp cận có hệ thống', 'C1', 'vi'),
('Lý thuyết hiện đại', 'C1', 'vi'),
('nghiên cứu ứng dụng', 'C1', 'vi'),
('thí nghiệm thực tế', 'C1', 'vi'),
('Đánh giá khách quan', 'C1', 'vi'),
('Kết quả chi tiết', 'C1', 'vi'),
('Cuộc tranh luận nâng cao', 'C1', 'vi'),
('Nghiên cứu so sánh', 'C1', 'vi'),
('Nghiên cứu thực địa', 'C1', 'vi'),
('Khuyến nghị thực tế', 'C1', 'vi'),
('kỹ năng nâng cao', 'C1', 'vi'),
('Khung khái niệm', 'C1', 'vi'),
('Kế hoạch chính xác', 'C1', 'vi'),
('Chiến lược dài hạn', 'C1', 'vi'),
('Đánh giá rủi ro', 'C1', 'vi'),
('Đánh giá học tập', 'C1', 'vi'),
('Dự án nghiên cứu', 'C1', 'vi'),
('đổi mới khoa học', 'C1', 'vi'),
('Phát triển công nghệ', 'C1', 'vi'),
('Phân tích văn học', 'C1', 'vi'),
('Kết quả khoa học', 'C1', 'vi'),
('Giải thích nâng cao', 'C1', 'vi'),
('quan điểm toàn diện', 'C1', 'vi'),
('kế hoạch thực hiện', 'C1', 'vi'),
('Quyết định chiến lược', 'C1', 'vi'),
('Quản lý tài nguyên', 'C1', 'vi'),
('những thách thức phức tạp', 'C1', 'vi'),
('Giải pháp sáng tạo', 'C1', 'vi'),
('cách tiếp cận toàn diện', 'C1', 'vi'),
('Phân tích dữ liệu', 'C1', 'vi'),
('Kiểm tra giả thuyết', 'C1', 'vi'),
('trường hợp nghiên cứu', 'C1', 'vi'),
('Công việc thực địa nâng cao', 'C1', 'vi'),
('Đánh giá triết học', 'C1', 'vi'),
('Dự án nghiên cứu ứng dụng', 'C1', 'vi'),
('Thảo luận học thuật', 'C1', 'vi'),
('Đánh giá chiến lược', 'C1', 'vi'),
('khuyến nghị thực tế', 'C1', 'vi'),
('kế hoạch làm việc', 'C1', 'vi'),
('Quản lý dự án', 'C1', 'vi'),
('Ấn phẩm học thuật', 'C1', 'vi'),
('Khám phá khoa học', 'C1', 'vi'),
('Đổi mới ứng dụng', 'C1', 'vi'),
('Phát triển liên tục', 'C1', 'vi'),
('Phân tích dữ liệu chuyên sâu', 'C1', 'vi'),
('Kinh nghiệm nghiên cứu', 'C1', 'vi'),
('Giải thích khoa học', 'C1', 'vi'),
('quan điểm phê phán', 'C1', 'vi');
