INSERT INTO words (word, level, language_code) VALUES
('dům', 'A1', 'cs'),
('dveře', 'A1', 'cs'),
('okno', 'A1', 'cs'),
('tabulka', 'A1', 'cs'),
('židle', 'A1', 'cs'),
('rezervovat', 'A1', 'cs'),
('pero', 'A1', 'cs'),
('škola', 'A1', 'cs'),
('učitel', 'A1', 'cs'),
('student', 'A1', 'cs'),
('jablko', 'A1', 'cs'),
('voda', 'A1', 'cs'),
('jídlo', 'A1', 'cs'),
('auto', 'A1', 'cs'),
('autobus', 'A1', 'cs'),
('ulice', 'A1', 'cs'),
('příteli', 'A1', 'cs'),
('rodina', 'A1', 'cs'),
('matka', 'A1', 'cs'),
('otec', 'A1', 'cs'),
('sestra', 'A1', 'cs'),
('bratr', 'A1', 'cs'),
('den', 'A1', 'cs'),
('noc', 'A1', 'cs'),
('ráno', 'A1', 'cs'),
('večer', 'A1', 'cs'),
('Ahoj', 'A1', 'cs'),
('Sbohem', 'A1', 'cs'),
('Prosím', 'A1', 'cs'),
('Děkuju', 'A1', 'cs'),
('Ano', 'A1', 'cs'),
('žádný', 'A1', 'cs'),
('červený', 'A1', 'cs'),
('modrý', 'A1', 'cs'),
('zelený', 'A1', 'cs'),
('bílý', 'A1', 'cs'),
('černý', 'A1', 'cs'),
('malý', 'A1', 'cs'),
('velký', 'A1', 'cs'),
('dobrý', 'A1', 'cs'),
('špatný', 'A1', 'cs'),
('horký', 'A1', 'cs'),
('studený', 'A1', 'cs'),
('káva', 'A1', 'cs'),
('čaj', 'A1', 'cs'),
('peníze', 'A1', 'cs'),
('práce', 'A1', 'cs'),
('domov', 'A1', 'cs'),
('nakupovat', 'A1', 'cs'),
('trh', 'A1', 'cs'),
('jídlo', 'A1', 'cs'),
('pití', 'A1', 'cs'),
('město', 'A1', 'cs'),
('park', 'A1', 'cs'),
('ulice', 'A1', 'cs'),
('ZASTÁVKA', 'A1', 'cs'),
('vlak', 'A1', 'cs'),
('stanice', 'A1', 'cs'),
('hotel', 'A1', 'cs'),
('pokoj', 'A1', 'cs'),
('postel', 'A1', 'cs'),
('lékař', 'A1', 'cs'),
('NEMOCNICE', 'A1', 'cs'),
('škola', 'A1', 'cs'),
('univerzita', 'A1', 'cs'),
('počítač', 'A1', 'cs'),
('telefon', 'A1', 'cs'),
('televize', 'A1', 'cs'),
('hudba', 'A1', 'cs'),
('píseň', 'A1', 'cs'),
('film', 'A1', 'cs'),
('hra', 'A1', 'cs'),
('fotbal', 'A1', 'cs'),
('míč', 'A1', 'cs'),
('voda', 'A1', 'cs'),
('déšť', 'A1', 'cs'),
('slunce', 'A1', 'cs'),
('nebe', 'A1', 'cs'),
('strom', 'A1', 'cs'),
('květ', 'A1', 'cs'),
('zvíře', 'A1', 'cs'),
('kočka', 'A1', 'cs'),
('pes', 'A1', 'cs'),
('pták', 'A1', 'cs'),
('ryba', 'A1', 'cs'),
('muž', 'A1', 'cs'),
('žena', 'A1', 'cs'),
('dítě', 'A1', 'cs'),
('lidé', 'A1', 'cs'),
('ulice', 'A1', 'cs'),
('místo', 'A1', 'cs'),
('čas', 'A1', 'cs'),
('rok', 'A1', 'cs'),
('měsíc', 'A1', 'cs'),
('týden', 'A1', 'cs'),
('dnes', 'A1', 'cs'),
('zítra', 'A1', 'cs'),
('včera', 'A1', 'cs'),
('jméno', 'A1', 'cs'),
('adresa', 'A1', 'cs'),
('číslo', 'A1', 'cs'),
('LETIŠTĚ', 'A2', 'cs'),
('let', 'A2', 'cs'),
('lístek', 'A2', 'cs'),
('pas', 'A2', 'cs'),
('cestovat', 'A2', 'cs'),
('dovolená', 'A2', 'cs'),
('cesta', 'A2', 'cs'),
('zavazadla', 'A2', 'cs'),
('stanice', 'A2', 'cs'),
('platforma', 'A2', 'cs'),
('restaurace', 'A2', 'cs'),
('kavárna', 'A2', 'cs'),
('snídaně', 'A2', 'cs'),
('oběd', 'A2', 'cs'),
('večeře', 'A2', 'cs'),
('zelenina', 'A2', 'cs'),
('ovoce', 'A2', 'cs'),
('maso', 'A2', 'cs'),
('kuře', 'A2', 'cs'),
('hovězí', 'A2', 'cs'),
('ryba', 'A2', 'cs'),
('chléb', 'A2', 'cs'),
('rýže', 'A2', 'cs'),
('těstoviny', 'A2', 'cs'),
('polévka', 'A2', 'cs'),
('cukr', 'A2', 'cs'),
('sůl', 'A2', 'cs'),
('pepř', 'A2', 'cs'),
('olej', 'A2', 'cs'),
('nakupování', 'A2', 'cs'),
('oblečení', 'A2', 'cs'),
('košile', 'A2', 'cs'),
('kalhoty', 'A2', 'cs'),
('šaty', 'A2', 'cs'),
('obuv', 'A2', 'cs'),
('čepice', 'A2', 'cs'),
('bunda', 'A2', 'cs'),
('kabát', 'A2', 'cs'),
('počasí', 'A2', 'cs'),
('sněžení', 'A2', 'cs'),
('vítr', 'A2', 'cs'),
('bouře', 'A2', 'cs'),
('hotely', 'A2', 'cs'),
('host', 'A2', 'cs'),
('servis', 'A2', 'cs'),
('recepce', 'A2', 'cs'),
('klíč', 'A2', 'cs'),
('rezervace', 'A2', 'cs'),
('pláž', 'A2', 'cs'),
('moře', 'A2', 'cs'),
('plavání', 'A2', 'cs'),
('bazén', 'A2', 'cs'),
('hora', 'A2', 'cs'),
('obec', 'A2', 'cs'),
('země', 'A2', 'cs'),
('jazyk', 'A2', 'cs'),
('zahraniční', 'A2', 'cs'),
('zkouška', 'A2', 'cs'),
('test', 'A2', 'cs'),
('domácí úkol', 'A2', 'cs'),
('třída', 'A2', 'cs'),
('podrobit', 'A2', 'cs'),
('matematika', 'A2', 'cs'),
('dějiny', 'A2', 'cs'),
('věda', 'A2', 'cs'),
('knihovna', 'A2', 'cs'),
('knihkupectví', 'A2', 'cs'),
('počítač', 'A2', 'cs'),
('Internet', 'A2', 'cs'),
('e-mail', 'A2', 'cs'),
('zpráva', 'A2', 'cs'),
('dopis', 'A2', 'cs'),
('zveřejnit', 'A2', 'cs'),
('banka', 'A2', 'cs'),
('peníze', 'A2', 'cs'),
('kreditní karta', 'A2', 'cs'),
('cena', 'A2', 'cs'),
('levný', 'A2', 'cs'),
('drahý', 'A2', 'cs'),
('otázka', 'A2', 'cs'),
('odpověď', 'A2', 'cs'),
('vysvětlit', 'A2', 'cs'),
('pomoc', 'A2', 'cs'),
('problém', 'A2', 'cs'),
('řešení', 'A2', 'cs'),
('zdraví', 'A2', 'cs'),
('lék', 'A2', 'cs'),
('lékař', 'A2', 'cs'),
('zdravotní sestra', 'A2', 'cs'),
('pacient', 'A2', 'cs'),
('jmenování', 'A2', 'cs'),
('horečka', 'A2', 'cs'),
('kašel', 'A2', 'cs'),
('zažít', 'B1', 'cs'),
('dobrodružství', 'B1', 'cs'),
('názor', 'B1', 'cs'),
('diskuse', 'B1', 'cs'),
('argument', 'B1', 'cs'),
('rozhodnutí', 'B1', 'cs'),
('důvod', 'B1', 'cs'),
('příležitost', 'B1', 'cs'),
('výzva', 'B1', 'cs'),
('úspěch', 'B1', 'cs'),
('selhání', 'B1', 'cs'),
('gól', 'B1', 'cs'),
('plán', 'B1', 'cs'),
('projekt', 'B1', 'cs'),
('znalost', 'B1', 'cs'),
('dovednost', 'B1', 'cs'),
('schopnost', 'B1', 'cs'),
('zlepšení', 'B1', 'cs'),
('výcvik', 'B1', 'cs'),
('pracovní pohovor', 'B1', 'cs'),
('aplikace', 'B1', 'cs'),
('kariéra', 'B1', 'cs'),
('manažer', 'B1', 'cs'),
('kolega', 'B1', 'cs'),
('zasedání', 'B1', 'cs'),
('úkol', 'B1', 'cs'),
('odpovědnost', 'B1', 'cs'),
('Prázdninový výlet', 'B1', 'cs'),
('kultura', 'B1', 'cs'),
('tradice', 'B1', 'cs'),
('zvyk', 'B1', 'cs'),
('festival', 'B1', 'cs'),
('oslava', 'B1', 'cs'),
('výkon', 'B1', 'cs'),
('koncert', 'B1', 'cs'),
('divadlo', 'B1', 'cs'),
('výstava', 'B1', 'cs'),
('malování', 'B1', 'cs'),
('sochařství', 'B1', 'cs'),
('muzeum', 'B1', 'cs'),
('historická kniha', 'B1', 'cs'),
('beletrie', 'B1', 'cs'),
('báseň', 'B1', 'cs'),
('román', 'B1', 'cs'),
('charakter', 'B1', 'cs'),
('spiknutí', 'B1', 'cs'),
('příběh', 'B1', 'cs'),
('noviny', 'B1', 'cs'),
('časopis', 'B1', 'cs'),
('článek', 'B1', 'cs'),
('zpráva', 'B1', 'cs'),
('prezentace', 'B1', 'cs'),
('přednáška', 'B1', 'cs'),
('školství', 'B1', 'cs'),
('univerzita', 'B1', 'cs'),
('stupeň', 'B1', 'cs'),
('diplom', 'B1', 'cs'),
('osvědčení', 'B1', 'cs'),
('prostředí', 'B1', 'cs'),
('příroda', 'B1', 'cs'),
('recyklace', 'B1', 'cs'),
('znečištění', 'B1', 'cs'),
('změna klimatu', 'B1', 'cs'),
('Globální oteplování', 'B1', 'cs'),
('energie', 'B1', 'cs'),
('technologie', 'B1', 'cs'),
('inovace', 'B1', 'cs'),
('vynález', 'B1', 'cs'),
('zařízení', 'B1', 'cs'),
('stroj', 'B1', 'cs'),
('Počítačový program', 'B1', 'cs'),
('Web', 'B1', 'cs'),
('aplikace', 'B1', 'cs'),
('sociální média', 'B1', 'cs'),
('sdělení', 'B1', 'cs'),
('konverzace', 'B1', 'cs'),
('interakce', 'B1', 'cs'),
('vztah', 'B1', 'cs'),
('přátelství', 'B1', 'cs'),
('manželství', 'B1', 'cs'),
('rodinný život', 'B1', 'cs'),
('štěstí', 'B1', 'cs'),
('hněv', 'B1', 'cs'),
('strach', 'B1', 'cs'),
('naděje', 'B1', 'cs'),
('sen', 'B1', 'cs'),
('ctižádost', 'B1', 'cs'),
('motivace', 'B1', 'cs'),
('důvěra', 'B1', 'cs'),
('zvědavost', 'B1', 'cs'),
('trpělivost', 'B1', 'cs'),
('inovace', 'B2', 'cs'),
('rozvoj', 'B2', 'cs'),
('výzkum', 'B2', 'cs'),
('analýza', 'B2', 'cs'),
('výklad', 'B2', 'cs'),
('argumentace', 'B2', 'cs'),
('srovnání', 'B2', 'cs'),
('hypotéza', 'B2', 'cs'),
('teorie', 'B2', 'cs'),
('experimentovat', 'B2', 'cs'),
('důkaz', 'B2', 'cs'),
('metoda', 'B2', 'cs'),
('závěr', 'B2', 'cs'),
('pozorování', 'B2', 'cs'),
('perspektivní', 'B2', 'cs'),
('předpoklad', 'B2', 'cs'),
('kontext', 'B2', 'cs'),
('kritéria', 'B2', 'cs'),
('princip', 'B2', 'cs'),
('přednost', 'B2', 'cs'),
('složitost', 'B2', 'cs'),
('účinnost', 'B2', 'cs'),
('produktivita', 'B2', 'cs'),
('investice', 'B2', 'cs'),
('ekonomika', 'B2', 'cs'),
('finance', 'B2', 'cs'),
('jednání', 'B2', 'cs'),
('dohoda', 'B2', 'cs'),
('smlouva', 'B2', 'cs'),
('politika', 'B2', 'cs'),
('vláda', 'B2', 'cs'),
('politika', 'B2', 'cs'),
('volby', 'B2', 'cs'),
('demokracie', 'B2', 'cs'),
('svoboda', 'B2', 'cs'),
('spravedlnost', 'B2', 'cs'),
('rovnost', 'B2', 'cs'),
('zákon', 'B2', 'cs'),
('zločin', 'B2', 'cs'),
('trest', 'B2', 'cs'),
('trest', 'B2', 'cs'),
('zabezpečení', 'B2', 'cs'),
('konflikt', 'B2', 'cs'),
('válka', 'B2', 'cs'),
('mír', 'B2', 'cs'),
('násilí', 'B2', 'cs'),
('terorismus', 'B2', 'cs'),
('Globalizace', 'B2', 'cs'),
('integrace', 'B2', 'cs'),
('rozmanitost', 'B2', 'cs'),
('identita', 'B2', 'cs'),
('migrace', 'B2', 'cs'),
('uprchlík', 'B2', 'cs'),
('společenství', 'B2', 'cs'),
('síť', 'B2', 'cs'),
('organizace', 'B2', 'cs'),
('instituce', 'B2', 'cs'),
('vedení', 'B2', 'cs'),
('řízení', 'B2', 'cs'),
('plánování', 'B2', 'cs'),
('strategie', 'B2', 'cs'),
('iniciativa', 'B2', 'cs'),
('tvořivost', 'B2', 'cs'),
('spolupráce', 'B2', 'cs'),
('týmová práce', 'B2', 'cs'),
('odpovědnost', 'B2', 'cs'),
('odpovědnost', 'B2', 'cs'),
('udržitelnost', 'B2', 'cs'),
('ochrana životního prostředí', 'B2', 'cs'),
('obnovitelná energie', 'B2', 'cs'),
('Inovační proces', 'B2', 'cs'),
('kritické myšlení', 'B2', 'cs'),
('Řešení problémů', 'B2', 'cs'),
('rozhodování', 'B2', 'cs'),
('Řízení času', 'B2', 'cs'),
('sebekázeň', 'B2', 'cs'),
('přizpůsobování', 'B2', 'cs'),
('odolnost', 'B2', 'cs'),
('nezávislost', 'B2', 'cs'),
('spolupráce', 'B2', 'cs'),
('důvěra', 'B2', 'cs'),
('respektovat', 'B2', 'cs'),
('empatie', 'B2', 'cs'),
('věrnost', 'B2', 'cs'),
('integrita', 'B2', 'cs'),
('etika', 'B2', 'cs'),
('morálka', 'B2', 'cs'),
('filozofie', 'B2', 'cs'),
('psychologie', 'B2', 'cs'),
('sociologie', 'B2', 'cs'),
('biologie', 'B2', 'cs'),
('chemie', 'B2', 'cs'),
('fyzika', 'B2', 'cs'),
('Kritická analýza', 'C1', 'cs'),
('logické uvažování', 'C1', 'cs'),
('výklad', 'C1', 'cs'),
('hluboké srovnání', 'C1', 'cs'),
('Vědecký závěr', 'C1', 'cs'),
('Složitá hypotéza', 'C1', 'cs'),
('Pokročilá teorie', 'C1', 'cs'),
('Hloubkový experiment', 'C1', 'cs'),
('Komplexní hodnocení', 'C1', 'cs'),
('Filozofická diskuse', 'C1', 'cs'),
('silný argument', 'C1', 'cs'),
('hmatatelné důkazy', 'C1', 'cs'),
('protichůdné důkazy', 'C1', 'cs'),
('Abstraktní koncept', 'C1', 'cs'),
('etické postavení', 'C1', 'cs'),
('Nejvyšší hodnota', 'C1', 'cs'),
('Základní princip', 'C1', 'cs'),
('nejvyšší priorita', 'C1', 'cs'),
('hlavní odpovědnost', 'C1', 'cs'),
('zásadní rozhodnutí', 'C1', 'cs'),
('Komplexní řízení', 'C1', 'cs'),
('strategické plánování', 'C1', 'cs'),
('Udržitelný rozvoj', 'C1', 'cs'),
('Moderní inovace', 'C1', 'cs'),
('Pokročilá kreativita', 'C1', 'cs'),
('nový objev', 'C1', 'cs'),
('Inovativní vynález', 'C1', 'cs'),
('ekonomická analýza', 'C1', 'cs'),
('finanční zpráva', 'C1', 'cs'),
('rozsáhlý projekt', 'C1', 'cs'),
('mezinárodní jednání', 'C1', 'cs'),
('formální dohoda', 'C1', 'cs'),
('Efektivní strategie', 'C1', 'cs'),
('Globální instituce', 'C1', 'cs'),
('Výzkumné centrum', 'C1', 'cs'),
('Pokročilé vědecké studium', 'C1', 'cs'),
('Kritická recenze', 'C1', 'cs'),
('Filozofická interpretace', 'C1', 'cs'),
('systematický přístup', 'C1', 'cs'),
('moderní teorie', 'C1', 'cs'),
('Aplikovaný výzkum', 'C1', 'cs'),
('praktický experiment', 'C1', 'cs'),
('Hodnocení objektivu', 'C1', 'cs'),
('Podrobné výsledky', 'C1', 'cs'),
('Pokročilá debata', 'C1', 'cs'),
('Srovnávací studie', 'C1', 'cs'),
('terénní výzkum', 'C1', 'cs'),
('praktické doporučení', 'C1', 'cs'),
('Pokročilé dovednosti', 'C1', 'cs'),
('Koncepční rámec', 'C1', 'cs'),
('Přesné plánování', 'C1', 'cs'),
('dlouhodobá strategie', 'C1', 'cs'),
('Posouzení rizik', 'C1', 'cs'),
('Akademická recenze', 'C1', 'cs'),
('Výzkumný projekt', 'C1', 'cs'),
('Vědecká inovace', 'C1', 'cs'),
('Technologický vývoj', 'C1', 'cs'),
('Literární analýza', 'C1', 'cs'),
('Vědecké zjištění', 'C1', 'cs'),
('Pokročilá interpretace', 'C1', 'cs'),
('Holistický pohled', 'C1', 'cs'),
('Plán implementace', 'C1', 'cs'),
('strategické rozhodnutí', 'C1', 'cs'),
('Správa zdrojů', 'C1', 'cs'),
('Složité výzvy', 'C1', 'cs'),
('Inovativní řešení', 'C1', 'cs'),
('Komplexní přístup', 'C1', 'cs'),
('Analýza dat', 'C1', 'cs'),
('Testování hypotéz', 'C1', 'cs'),
('Případová studie', 'C1', 'cs'),
('Pokročilá práce v terénu', 'C1', 'cs'),
('Filozofický přehled', 'C1', 'cs'),
('Aplikovaný výzkumný projekt', 'C1', 'cs'),
('Akademická diskuse', 'C1', 'cs'),
('strategické hodnocení', 'C1', 'cs'),
('praktická doporučení', 'C1', 'cs'),
('pracovní plán', 'C1', 'cs'),
('Projektový management', 'C1', 'cs'),
('Akademická publikace', 'C1', 'cs'),
('vědecký objev', 'C1', 'cs'),
('Aplikovaná inovace', 'C1', 'cs'),
('nepřetržitý vývoj', 'C1', 'cs'),
('Hloubková analýza dat', 'C1', 'cs'),
('Výzkumné zkušenosti', 'C1', 'cs'),
('Vědecká interpretace', 'C1', 'cs'),
('kritická perspektiva', 'C1', 'cs');
