INSERT INTO words (word, level, language_code) VALUES
('ház', 'A1', 'hu'),
('ajtó', 'A1', 'hu'),
('ablak', 'A1', 'hu'),
('táblázat', 'A1', 'hu'),
('szék', 'A1', 'hu'),
('könyv', 'A1', 'hu'),
('toll', 'A1', 'hu'),
('iskola', 'A1', 'hu'),
('tanár', 'A1', 'hu'),
('diák', 'A1', 'hu'),
('alma', 'A1', 'hu'),
('víz', 'A1', 'hu'),
('élelmiszer', 'A1', 'hu'),
('autó', 'A1', 'hu'),
('busz', 'A1', 'hu'),
('utca', 'A1', 'hu'),
('barát', 'A1', 'hu'),
('család', 'A1', 'hu'),
('anya', 'A1', 'hu'),
('apa', 'A1', 'hu'),
('nővér', 'A1', 'hu'),
('testvér', 'A1', 'hu'),
('nap', 'A1', 'hu'),
('éjszaka', 'A1', 'hu'),
('reggel', 'A1', 'hu'),
('este', 'A1', 'hu'),
('Helló', 'A1', 'hu'),
('búcsú', 'A1', 'hu'),
('Kérem', 'A1', 'hu'),
('Köszönöm', 'A1', 'hu'),
('igen', 'A1', 'hu'),
('nem', 'A1', 'hu'),
('piros', 'A1', 'hu'),
('kék', 'A1', 'hu'),
('zöld', 'A1', 'hu'),
('fehér', 'A1', 'hu'),
('fekete', 'A1', 'hu'),
('kicsi', 'A1', 'hu'),
('nagy', 'A1', 'hu'),
('jó', 'A1', 'hu'),
('rossz', 'A1', 'hu'),
('forró', 'A1', 'hu'),
('hideg', 'A1', 'hu'),
('kávé', 'A1', 'hu'),
('tea', 'A1', 'hu'),
('pénz', 'A1', 'hu'),
('munka', 'A1', 'hu'),
('otthon', 'A1', 'hu'),
('üzlet', 'A1', 'hu'),
('piac', 'A1', 'hu'),
('élelmiszer', 'A1', 'hu'),
('ital', 'A1', 'hu'),
('város', 'A1', 'hu'),
('park', 'A1', 'hu'),
('utca', 'A1', 'hu'),
('buszmegálló', 'A1', 'hu'),
('vonat', 'A1', 'hu'),
('állomás', 'A1', 'hu'),
('szálloda', 'A1', 'hu'),
('szoba', 'A1', 'hu'),
('ágy', 'A1', 'hu'),
('orvos', 'A1', 'hu'),
('kórház', 'A1', 'hu'),
('iskola', 'A1', 'hu'),
('egyetemi', 'A1', 'hu'),
('számítógép', 'A1', 'hu'),
('telefon', 'A1', 'hu'),
('televízió', 'A1', 'hu'),
('zene', 'A1', 'hu'),
('dal', 'A1', 'hu'),
('film', 'A1', 'hu'),
('játék', 'A1', 'hu'),
('futball', 'A1', 'hu'),
('labda', 'A1', 'hu'),
('víz', 'A1', 'hu'),
('eső', 'A1', 'hu'),
('nap', 'A1', 'hu'),
('ég', 'A1', 'hu'),
('fa', 'A1', 'hu'),
('virág', 'A1', 'hu'),
('állati', 'A1', 'hu'),
('macska', 'A1', 'hu'),
('kutya', 'A1', 'hu'),
('madár', 'A1', 'hu'),
('hal', 'A1', 'hu'),
('férfi', 'A1', 'hu'),
('nő', 'A1', 'hu'),
('gyermek', 'A1', 'hu'),
('emberek', 'A1', 'hu'),
('utca', 'A1', 'hu'),
('hely', 'A1', 'hu'),
('idő', 'A1', 'hu'),
('év', 'A1', 'hu'),
('hónap', 'A1', 'hu'),
('hét', 'A1', 'hu'),
('ma', 'A1', 'hu'),
('holnap', 'A1', 'hu'),
('tegnap', 'A1', 'hu'),
('név', 'A1', 'hu'),
('cím', 'A1', 'hu'),
('szám', 'A1', 'hu'),
('repülőtér', 'A2', 'hu'),
('repülési', 'A2', 'hu'),
('jegy', 'A2', 'hu'),
('útlevél', 'A2', 'hu'),
('utazási', 'A2', 'hu'),
('ünnep', 'A2', 'hu'),
('utazás', 'A2', 'hu'),
('poggyász', 'A2', 'hu'),
('állomás', 'A2', 'hu'),
('platform', 'A2', 'hu'),
('étterem', 'A2', 'hu'),
('kávéház', 'A2', 'hu'),
('reggeli', 'A2', 'hu'),
('ebéd', 'A2', 'hu'),
('vacsora', 'A2', 'hu'),
('zöldségek', 'A2', 'hu'),
('gyümölcs', 'A2', 'hu'),
('hús', 'A2', 'hu'),
('csirke', 'A2', 'hu'),
('marhahús', 'A2', 'hu'),
('hal', 'A2', 'hu'),
('kenyér', 'A2', 'hu'),
('rizs', 'A2', 'hu'),
('tészta', 'A2', 'hu'),
('leves', 'A2', 'hu'),
('cukor', 'A2', 'hu'),
('só', 'A2', 'hu'),
('bors', 'A2', 'hu'),
('olaj', 'A2', 'hu'),
('bevásárlás', 'A2', 'hu'),
('ruházat', 'A2', 'hu'),
('ing', 'A2', 'hu'),
('nadrág', 'A2', 'hu'),
('ruha', 'A2', 'hu'),
('cipő', 'A2', 'hu'),
('kalap', 'A2', 'hu'),
('kabát', 'A2', 'hu'),
('kabát', 'A2', 'hu'),
('időjárás', 'A2', 'hu'),
('hó', 'A2', 'hu'),
('szél', 'A2', 'hu'),
('vihar', 'A2', 'hu'),
('szállodák', 'A2', 'hu'),
('vendég', 'A2', 'hu'),
('szolgáltatás', 'A2', 'hu'),
('recepció', 'A2', 'hu'),
('kulcsfontosságú', 'A2', 'hu'),
('foglalás', 'A2', 'hu'),
('strand', 'A2', 'hu'),
('tenger', 'A2', 'hu'),
('úszás', 'A2', 'hu'),
('medence', 'A2', 'hu'),
('hegy', 'A2', 'hu'),
('falu', 'A2', 'hu'),
('ország', 'A2', 'hu'),
('nyelv', 'A2', 'hu'),
('külföldi', 'A2', 'hu'),
('vizsgálat', 'A2', 'hu'),
('teszt', 'A2', 'hu'),
('házi feladat', 'A2', 'hu'),
('tanterem', 'A2', 'hu'),
('téma', 'A2', 'hu'),
('matematika', 'A2', 'hu'),
('történelem', 'A2', 'hu'),
('tudomány', 'A2', 'hu'),
('könyvtár', 'A2', 'hu'),
('könyvkereskedés', 'A2', 'hu'),
('számítógép', 'A2', 'hu'),
('Internet', 'A2', 'hu'),
('email', 'A2', 'hu'),
('üzenet', 'A2', 'hu'),
('levél', 'A2', 'hu'),
('oszlop', 'A2', 'hu'),
('bank', 'A2', 'hu'),
('pénz', 'A2', 'hu'),
('hitelkártya', 'A2', 'hu'),
('ár', 'A2', 'hu'),
('olcsó', 'A2', 'hu'),
('drága', 'A2', 'hu'),
('kérdés', 'A2', 'hu'),
('válasz', 'A2', 'hu'),
('elmagyaráz', 'A2', 'hu'),
('Segítség', 'A2', 'hu'),
('probléma', 'A2', 'hu'),
('megoldás', 'A2', 'hu'),
('egészség', 'A2', 'hu'),
('gyógyszer', 'A2', 'hu'),
('orvos', 'A2', 'hu'),
('nővér', 'A2', 'hu'),
('beteg', 'A2', 'hu'),
('kinevezés', 'A2', 'hu'),
('láz', 'A2', 'hu'),
('köhögés', 'A2', 'hu'),
('tapasztalat', 'B1', 'hu'),
('kaland', 'B1', 'hu'),
('vélemény', 'B1', 'hu'),
('vita', 'B1', 'hu'),
('érv', 'B1', 'hu'),
('döntés', 'B1', 'hu'),
('ok', 'B1', 'hu'),
('lehetőség', 'B1', 'hu'),
('kihívás', 'B1', 'hu'),
('siker', 'B1', 'hu'),
('hiba', 'B1', 'hu'),
('cél', 'B1', 'hu'),
('terv', 'B1', 'hu'),
('projekt', 'B1', 'hu'),
('tudás', 'B1', 'hu'),
('készség', 'B1', 'hu'),
('képesség', 'B1', 'hu'),
('javulás', 'B1', 'hu'),
('edzés', 'B1', 'hu'),
('állásinterjú', 'B1', 'hu'),
('alkalmazás', 'B1', 'hu'),
('karrier', 'B1', 'hu'),
('menedzser', 'B1', 'hu'),
('kolléga', 'B1', 'hu'),
('találkozó', 'B1', 'hu'),
('feladat', 'B1', 'hu'),
('felelősség', 'B1', 'hu'),
('ünnepi utazás', 'B1', 'hu'),
('kultúra', 'B1', 'hu'),
('hagyomány', 'B1', 'hu'),
('szokás', 'B1', 'hu'),
('fesztivál', 'B1', 'hu'),
('ünneplés', 'B1', 'hu'),
('teljesítmény', 'B1', 'hu'),
('koncert', 'B1', 'hu'),
('színház', 'B1', 'hu'),
('kiállítás', 'B1', 'hu'),
('festés', 'B1', 'hu'),
('szobor', 'B1', 'hu'),
('múzeum', 'B1', 'hu'),
('történelemkönyv', 'B1', 'hu'),
('fikció', 'B1', 'hu'),
('vers', 'B1', 'hu'),
('regény', 'B1', 'hu'),
('jellegzetesség', 'B1', 'hu'),
('telek', 'B1', 'hu'),
('történet', 'B1', 'hu'),
('újság', 'B1', 'hu'),
('magazin', 'B1', 'hu'),
('cikk', 'B1', 'hu'),
('jelentés', 'B1', 'hu'),
('előadás', 'B1', 'hu'),
('előadás', 'B1', 'hu'),
('oktatás', 'B1', 'hu'),
('egyetemi', 'B1', 'hu'),
('fokozat', 'B1', 'hu'),
('oklevél', 'B1', 'hu'),
('bizonyítvány', 'B1', 'hu'),
('környezet', 'B1', 'hu'),
('természet', 'B1', 'hu'),
('újrafeldolgozás', 'B1', 'hu'),
('környezetszennyezés', 'B1', 'hu'),
('éghajlatváltozás', 'B1', 'hu'),
('globális felmelegedés', 'B1', 'hu'),
('energia', 'B1', 'hu'),
('technológia', 'B1', 'hu'),
('innováció', 'B1', 'hu'),
('találmány', 'B1', 'hu'),
('eszköz', 'B1', 'hu'),
('gép', 'B1', 'hu'),
('számítógépes program', 'B1', 'hu'),
('weboldal', 'B1', 'hu'),
('alkalmazás', 'B1', 'hu'),
('közösségi média', 'B1', 'hu'),
('kommunikáció', 'B1', 'hu'),
('beszélgetés', 'B1', 'hu'),
('kölcsönhatás', 'B1', 'hu'),
('kapcsolat', 'B1', 'hu'),
('barátság', 'B1', 'hu'),
('házasság', 'B1', 'hu'),
('családi élet', 'B1', 'hu'),
('boldogság', 'B1', 'hu'),
('harag', 'B1', 'hu'),
('félelem', 'B1', 'hu'),
('remény', 'B1', 'hu'),
('álom', 'B1', 'hu'),
('törekvés', 'B1', 'hu'),
('motiváció', 'B1', 'hu'),
('bizalom', 'B1', 'hu'),
('kíváncsiság', 'B1', 'hu'),
('türelem', 'B1', 'hu'),
('innováció', 'B2', 'hu'),
('fejlesztés', 'B2', 'hu'),
('kutatás', 'B2', 'hu'),
('elemzés', 'B2', 'hu'),
('értelmezés', 'B2', 'hu'),
('érvelés', 'B2', 'hu'),
('összehasonlítás', 'B2', 'hu'),
('hipotézis', 'B2', 'hu'),
('elmélet', 'B2', 'hu'),
('kísérlet', 'B2', 'hu'),
('bizonyíték', 'B2', 'hu'),
('módszer', 'B2', 'hu'),
('következtetés', 'B2', 'hu'),
('megfigyelés', 'B2', 'hu'),
('perspektíva', 'B2', 'hu'),
('feltevés', 'B2', 'hu'),
('kontextus', 'B2', 'hu'),
('kritériumok', 'B2', 'hu'),
('alapelv', 'B2', 'hu'),
('prioritás', 'B2', 'hu'),
('bonyolultság', 'B2', 'hu'),
('hatékonyság', 'B2', 'hu'),
('termelékenység', 'B2', 'hu'),
('beruházás', 'B2', 'hu'),
('gazdaság', 'B2', 'hu'),
('pénzügy', 'B2', 'hu'),
('tárgyalás', 'B2', 'hu'),
('megállapodás', 'B2', 'hu'),
('szerződés', 'B2', 'hu'),
('politika', 'B2', 'hu'),
('kormány', 'B2', 'hu'),
('politika', 'B2', 'hu'),
('választás', 'B2', 'hu'),
('demokrácia', 'B2', 'hu'),
('szabadság', 'B2', 'hu'),
('igazságszolgáltatás', 'B2', 'hu'),
('egyenlőség', 'B2', 'hu'),
('törvény', 'B2', 'hu'),
('bűncselekmény', 'B2', 'hu'),
('büntetés', 'B2', 'hu'),
('büntetés', 'B2', 'hu'),
('biztonság', 'B2', 'hu'),
('konfliktus', 'B2', 'hu'),
('háború', 'B2', 'hu'),
('béke', 'B2', 'hu'),
('erőszak', 'B2', 'hu'),
('terrorizmus', 'B2', 'hu'),
('globalizáció', 'B2', 'hu'),
('integráció', 'B2', 'hu'),
('sokféleség', 'B2', 'hu'),
('identitás', 'B2', 'hu'),
('vándorlás', 'B2', 'hu'),
('menekült', 'B2', 'hu'),
('közösség', 'B2', 'hu'),
('hálózat', 'B2', 'hu'),
('szervezet', 'B2', 'hu'),
('intézmény', 'B2', 'hu'),
('vezetés', 'B2', 'hu'),
('vezetés', 'B2', 'hu'),
('tervezés', 'B2', 'hu'),
('stratégia', 'B2', 'hu'),
('kezdeményezés', 'B2', 'hu'),
('kreativitás', 'B2', 'hu'),
('együttműködés', 'B2', 'hu'),
('csapatmunka', 'B2', 'hu'),
('felelősség', 'B2', 'hu'),
('elszámoltathatóság', 'B2', 'hu'),
('fenntarthatóság', 'B2', 'hu'),
('környezetvédelem', 'B2', 'hu'),
('megújuló energia', 'B2', 'hu'),
('innovációs folyamat', 'B2', 'hu'),
('kritikus gondolkodás', 'B2', 'hu'),
('problémamegoldás', 'B2', 'hu'),
('döntéshozatal', 'B2', 'hu'),
('időgazdálkodás', 'B2', 'hu'),
('önfegyelem', 'B2', 'hu'),
('alkalmazkodás', 'B2', 'hu'),
('rugalmasság', 'B2', 'hu'),
('függetlenség', 'B2', 'hu'),
('együttműködés', 'B2', 'hu'),
('bizalom', 'B2', 'hu'),
('tisztelet', 'B2', 'hu'),
('empátia', 'B2', 'hu'),
('hűség', 'B2', 'hu'),
('integritás', 'B2', 'hu'),
('etika', 'B2', 'hu'),
('erkölcs', 'B2', 'hu'),
('filozófia', 'B2', 'hu'),
('pszichológia', 'B2', 'hu'),
('szociológia', 'B2', 'hu'),
('biológia', 'B2', 'hu'),
('kémia', 'B2', 'hu'),
('fizika', 'B2', 'hu'),
('kritikus elemzés', 'C1', 'hu'),
('logikus érvelés', 'C1', 'hu'),
('értelmezés', 'C1', 'hu'),
('mély összehasonlítás', 'C1', 'hu'),
('tudományos következtetés', 'C1', 'hu'),
('összetett hipotézis', 'C1', 'hu'),
('fejlett elmélet', 'C1', 'hu'),
('mélyreható kísérlet', 'C1', 'hu'),
('átfogó értékelés', 'C1', 'hu'),
('filozófiai vita', 'C1', 'hu'),
('erős érv', 'C1', 'hu'),
('kézzelfogható bizonyítékok', 'C1', 'hu'),
('ellentmondásos bizonyítékok', 'C1', 'hu'),
('absztrakt fogalom', 'C1', 'hu'),
('etikai helyzet', 'C1', 'hu'),
('legfelsőbb érték', 'C1', 'hu'),
('alapelv', 'C1', 'hu'),
('kiemelt prioritás', 'C1', 'hu'),
('nagy felelősség', 'C1', 'hu'),
('döntő döntés', 'C1', 'hu'),
('összetett menedzsment', 'C1', 'hu'),
('stratégiai tervezés', 'C1', 'hu'),
('fenntartható fejlődés', 'C1', 'hu'),
('modern innováció', 'C1', 'hu'),
('fejlett kreativitás', 'C1', 'hu'),
('új felfedezés', 'C1', 'hu'),
('innovatív találmány', 'C1', 'hu'),
('gazdasági elemzés', 'C1', 'hu'),
('pénzügyi jelentés', 'C1', 'hu'),
('nagyszabású projekt', 'C1', 'hu'),
('nemzetközi tárgyalások', 'C1', 'hu'),
('hivatalos megállapodás', 'C1', 'hu'),
('hatékony stratégia', 'C1', 'hu'),
('globális intézmény', 'C1', 'hu'),
('kutatóközpont', 'C1', 'hu'),
('fejlett tudományos tanulmány', 'C1', 'hu'),
('kritikus áttekintés', 'C1', 'hu'),
('filozófiai értelmezés', 'C1', 'hu'),
('szisztematikus megközelítés', 'C1', 'hu'),
('modern elmélet', 'C1', 'hu'),
('alkalmazott kutatás', 'C1', 'hu'),
('gyakorlati kísérlet', 'C1', 'hu'),
('objektív értékelés', 'C1', 'hu'),
('Részletes eredmények', 'C1', 'hu'),
('fejlett vita', 'C1', 'hu'),
('összehasonlító tanulmány', 'C1', 'hu'),
('helyszíni kutatás', 'C1', 'hu'),
('gyakorlati ajánlás', 'C1', 'hu'),
('haladó készség', 'C1', 'hu'),
('fogalmi keret', 'C1', 'hu'),
('pontos tervezés', 'C1', 'hu'),
('hosszú távú stratégia', 'C1', 'hu'),
('kockázatértékelés', 'C1', 'hu'),
('tudományos áttekintés', 'C1', 'hu'),
('kutatási projekt', 'C1', 'hu'),
('tudományos innováció', 'C1', 'hu'),
('technológiai fejlődés', 'C1', 'hu'),
('irodalmi elemzés', 'C1', 'hu'),
('tudományos eredmények', 'C1', 'hu'),
('fejlett értelmezés', 'C1', 'hu'),
('holisztikus nézet', 'C1', 'hu'),
('végrehajtási terv', 'C1', 'hu'),
('hadászati ​​döntés', 'C1', 'hu'),
('erőforrás -kezelés', 'C1', 'hu'),
('összetett kihívások', 'C1', 'hu'),
('innovatív megoldások', 'C1', 'hu'),
('átfogó megközelítés', 'C1', 'hu'),
('adatelemzés', 'C1', 'hu'),
('hipotézis tesztelés', 'C1', 'hu'),
('esettanulmány', 'C1', 'hu'),
('fejlett terepmunka', 'C1', 'hu'),
('filozófiai áttekintés', 'C1', 'hu'),
('alkalmazott kutatási projekt', 'C1', 'hu'),
('tudományos vita', 'C1', 'hu'),
('stratégiai értékelés', 'C1', 'hu'),
('gyakorlati ajánlások', 'C1', 'hu'),
('munkaterv', 'C1', 'hu'),
('projektmenedzsment', 'C1', 'hu'),
('tudományos publikáció', 'C1', 'hu'),
('tudományos felfedezés', 'C1', 'hu'),
('alkalmazott innováció', 'C1', 'hu'),
('folyamatos fejlesztés', 'C1', 'hu'),
('mélyreható adatelemzés', 'C1', 'hu'),
('kutatási tapasztalat', 'C1', 'hu'),
('tudományos értelmezés', 'C1', 'hu'),
('kritikus perspektíva', 'C1', 'hu');
