INSERT INTO words (word, level, language_code) VALUES
('huis', 'A1', 'nl'),
('deur', 'A1', 'nl'),
('raam', 'A1', 'nl'),
('tafel', 'A1', 'nl'),
('stoel', 'A1', 'nl'),
('boek', 'A1', 'nl'),
('pen', 'A1', 'nl'),
('school', 'A1', 'nl'),
('docent', 'A1', 'nl'),
('student', 'A1', 'nl'),
('appel', 'A1', 'nl'),
('water', 'A1', 'nl'),
('voedsel', 'A1', 'nl'),
('auto', 'A1', 'nl'),
('bus', 'A1', 'nl'),
('straat', 'A1', 'nl'),
('vriend', 'A1', 'nl'),
('familie', 'A1', 'nl'),
('moeder', 'A1', 'nl'),
('vader', 'A1', 'nl'),
('zus', 'A1', 'nl'),
('broer', 'A1', 'nl'),
('dag', 'A1', 'nl'),
('nacht', 'A1', 'nl'),
('ochtend', 'A1', 'nl'),
('avond', 'A1', 'nl'),
('Hallo', 'A1', 'nl'),
('tot ziens', 'A1', 'nl'),
('Alsjeblieft', 'A1', 'nl'),
('Bedankt', 'A1', 'nl'),
('Ja', 'A1', 'nl'),
('Nee', 'A1', 'nl'),
('rood', 'A1', 'nl'),
('blauw', 'A1', 'nl'),
('groente', 'A1', 'nl'),
('wit', 'A1', 'nl'),
('zwart', 'A1', 'nl'),
('klein', 'A1', 'nl'),
('groot', 'A1', 'nl'),
('Goed', 'A1', 'nl'),
('slecht', 'A1', 'nl'),
('heet', 'A1', 'nl'),
('koud', 'A1', 'nl'),
('koffie', 'A1', 'nl'),
('thee', 'A1', 'nl'),
('geld', 'A1', 'nl'),
('werk', 'A1', 'nl'),
('thuis', 'A1', 'nl'),
('winkel', 'A1', 'nl'),
('markt', 'A1', 'nl'),
('voedsel', 'A1', 'nl'),
('drankje', 'A1', 'nl'),
('stad', 'A1', 'nl'),
('park', 'A1', 'nl'),
('straat', 'A1', 'nl'),
('Bushalte', 'A1', 'nl'),
('trein', 'A1', 'nl'),
('station', 'A1', 'nl'),
('hotel', 'A1', 'nl'),
('kamer', 'A1', 'nl'),
('bed', 'A1', 'nl'),
('arts', 'A1', 'nl'),
('ziekenhuis', 'A1', 'nl'),
('school', 'A1', 'nl'),
('universiteit', 'A1', 'nl'),
('computer', 'A1', 'nl'),
('telefoon', 'A1', 'nl'),
('televisie', 'A1', 'nl'),
('muziek', 'A1', 'nl'),
('liedje', 'A1', 'nl'),
('film', 'A1', 'nl'),
('spel', 'A1', 'nl'),
('voetbal', 'A1', 'nl'),
('bal', 'A1', 'nl'),
('water', 'A1', 'nl'),
('regen', 'A1', 'nl'),
('zon', 'A1', 'nl'),
('lucht', 'A1', 'nl'),
('boom', 'A1', 'nl'),
('bloem', 'A1', 'nl'),
('dier', 'A1', 'nl'),
('kat', 'A1', 'nl'),
('hond', 'A1', 'nl'),
('vogel', 'A1', 'nl'),
('vis', 'A1', 'nl'),
('man', 'A1', 'nl'),
('vrouw', 'A1', 'nl'),
('kind', 'A1', 'nl'),
('mensen', 'A1', 'nl'),
('straat', 'A1', 'nl'),
('plaats', 'A1', 'nl'),
('tijd', 'A1', 'nl'),
('jaar', 'A1', 'nl'),
('maand', 'A1', 'nl'),
('week', 'A1', 'nl'),
('Vandaag', 'A1', 'nl'),
('morgen', 'A1', 'nl'),
('gisteren', 'A1', 'nl'),
('naam', 'A1', 'nl'),
('adres', 'A1', 'nl'),
('nummer', 'A1', 'nl'),
('luchthaven', 'A2', 'nl'),
('vlucht', 'A2', 'nl'),
('ticket', 'A2', 'nl'),
('paspoort', 'A2', 'nl'),
('reis', 'A2', 'nl'),
('vakantie', 'A2', 'nl'),
('reis', 'A2', 'nl'),
('bagage', 'A2', 'nl'),
('station', 'A2', 'nl'),
('platform', 'A2', 'nl'),
('restaurant', 'A2', 'nl'),
('café', 'A2', 'nl'),
('ontbijt', 'A2', 'nl'),
('lunch', 'A2', 'nl'),
('diner', 'A2', 'nl'),
('groenten', 'A2', 'nl'),
('fruit', 'A2', 'nl'),
('vlees', 'A2', 'nl'),
('kip', 'A2', 'nl'),
('rundvlees', 'A2', 'nl'),
('vis', 'A2', 'nl'),
('brood', 'A2', 'nl'),
('rijst', 'A2', 'nl'),
('pasta', 'A2', 'nl'),
('soep', 'A2', 'nl'),
('suiker', 'A2', 'nl'),
('zout', 'A2', 'nl'),
('peper', 'A2', 'nl'),
('olie', 'A2', 'nl'),
('winkelen', 'A2', 'nl'),
('kleren', 'A2', 'nl'),
('shirt', 'A2', 'nl'),
('broek', 'A2', 'nl'),
('jurk', 'A2', 'nl'),
('schoenen', 'A2', 'nl'),
('hoed', 'A2', 'nl'),
('jasje', 'A2', 'nl'),
('jas', 'A2', 'nl'),
('weer', 'A2', 'nl'),
('sneeuw', 'A2', 'nl'),
('wind', 'A2', 'nl'),
('storm', 'A2', 'nl'),
('hotels', 'A2', 'nl'),
('gast', 'A2', 'nl'),
('dienst', 'A2', 'nl'),
('receptie', 'A2', 'nl'),
('sleutel', 'A2', 'nl'),
('reservering', 'A2', 'nl'),
('strand', 'A2', 'nl'),
('zee', 'A2', 'nl'),
('zwemmen', 'A2', 'nl'),
('pool', 'A2', 'nl'),
('berg', 'A2', 'nl'),
('dorp', 'A2', 'nl'),
('land', 'A2', 'nl'),
('taal', 'A2', 'nl'),
('buitenlands', 'A2', 'nl'),
('examen', 'A2', 'nl'),
('test', 'A2', 'nl'),
('huiswerk', 'A2', 'nl'),
('klas', 'A2', 'nl'),
('onderwerp', 'A2', 'nl'),
('wiskunde', 'A2', 'nl'),
('geschiedenis', 'A2', 'nl'),
('wetenschap', 'A2', 'nl'),
('bibliotheek', 'A2', 'nl'),
('boekhandel', 'A2', 'nl'),
('computer', 'A2', 'nl'),
('internet', 'A2', 'nl'),
('e -mail', 'A2', 'nl'),
('bericht', 'A2', 'nl'),
('brief', 'A2', 'nl'),
('na', 'A2', 'nl'),
('bank', 'A2', 'nl'),
('geld', 'A2', 'nl'),
('creditcard', 'A2', 'nl'),
('prijs', 'A2', 'nl'),
('goedkoop', 'A2', 'nl'),
('duur', 'A2', 'nl'),
('vraag', 'A2', 'nl'),
('antwoord', 'A2', 'nl'),
('uitleggen', 'A2', 'nl'),
('hulp', 'A2', 'nl'),
('probleem', 'A2', 'nl'),
('oplossing', 'A2', 'nl'),
('gezondheid', 'A2', 'nl'),
('geneesmiddel', 'A2', 'nl'),
('arts', 'A2', 'nl'),
('verpleegkundige', 'A2', 'nl'),
('geduldig', 'A2', 'nl'),
('afspraak', 'A2', 'nl'),
('koorts', 'A2', 'nl'),
('hoest', 'A2', 'nl'),
('ervaring', 'B1', 'nl'),
('avontuur', 'B1', 'nl'),
('mening', 'B1', 'nl'),
('discussie', 'B1', 'nl'),
('argument', 'B1', 'nl'),
('beslissing', 'B1', 'nl'),
('reden', 'B1', 'nl'),
('mogelijkheid', 'B1', 'nl'),
('uitdaging', 'B1', 'nl'),
('succes', 'B1', 'nl'),
('mislukking', 'B1', 'nl'),
('doel', 'B1', 'nl'),
('plan', 'B1', 'nl'),
('project', 'B1', 'nl'),
('kennis', 'B1', 'nl'),
('vaardigheid', 'B1', 'nl'),
('vaardigheid', 'B1', 'nl'),
('verbetering', 'B1', 'nl'),
('opleiding', 'B1', 'nl'),
('sollicitatiegesprek', 'B1', 'nl'),
('sollicitatie', 'B1', 'nl'),
('carrière', 'B1', 'nl'),
('manager', 'B1', 'nl'),
('collega', 'B1', 'nl'),
('ontmoeting', 'B1', 'nl'),
('taak', 'B1', 'nl'),
('verantwoordelijkheid', 'B1', 'nl'),
('vakantiereis', 'B1', 'nl'),
('cultuur', 'B1', 'nl'),
('traditie', 'B1', 'nl'),
('aangepast', 'B1', 'nl'),
('festival', 'B1', 'nl'),
('viering', 'B1', 'nl'),
('prestatie', 'B1', 'nl'),
('concert', 'B1', 'nl'),
('theater', 'B1', 'nl'),
('tentoonstelling', 'B1', 'nl'),
('schilderen', 'B1', 'nl'),
('beeldhouwwerk', 'B1', 'nl'),
('museum', 'B1', 'nl'),
('geschiedenisboek', 'B1', 'nl'),
('fictie', 'B1', 'nl'),
('gedicht', 'B1', 'nl'),
('roman', 'B1', 'nl'),
('karakter', 'B1', 'nl'),
('verhaallijn', 'B1', 'nl'),
('verhaal', 'B1', 'nl'),
('krant', 'B1', 'nl'),
('tijdschrift', 'B1', 'nl'),
('artikel', 'B1', 'nl'),
('rapport', 'B1', 'nl'),
('presentatie', 'B1', 'nl'),
('lezing', 'B1', 'nl'),
('onderwijs', 'B1', 'nl'),
('universiteit', 'B1', 'nl'),
('rang', 'B1', 'nl'),
('diploma', 'B1', 'nl'),
('certificaat', 'B1', 'nl'),
('omgeving', 'B1', 'nl'),
('natuur', 'B1', 'nl'),
('recycling', 'B1', 'nl'),
('vervuiling', 'B1', 'nl'),
('klimaatverandering', 'B1', 'nl'),
('opwarming van de aarde', 'B1', 'nl'),
('energie', 'B1', 'nl'),
('technologie', 'B1', 'nl'),
('innovatie', 'B1', 'nl'),
('uitvinding', 'B1', 'nl'),
('apparaat', 'B1', 'nl'),
('machine', 'B1', 'nl'),
('computerprogramma', 'B1', 'nl'),
('website', 'B1', 'nl'),
('sollicitatie', 'B1', 'nl'),
('sociale media', 'B1', 'nl'),
('mededeling', 'B1', 'nl'),
('gesprek', 'B1', 'nl'),
('interactie', 'B1', 'nl'),
('relatie', 'B1', 'nl'),
('vriendschap', 'B1', 'nl'),
('huwelijk', 'B1', 'nl'),
('gezinsleven', 'B1', 'nl'),
('geluk', 'B1', 'nl'),
('woede', 'B1', 'nl'),
('angst', 'B1', 'nl'),
('hoop', 'B1', 'nl'),
('droom', 'B1', 'nl'),
('ambitie', 'B1', 'nl'),
('motivatie', 'B1', 'nl'),
('vertrouwen', 'B1', 'nl'),
('nieuwsgierigheid', 'B1', 'nl'),
('geduld', 'B1', 'nl'),
('innovatie', 'B2', 'nl'),
('ontwikkeling', 'B2', 'nl'),
('onderzoek', 'B2', 'nl'),
('analyse', 'B2', 'nl'),
('interpretatie', 'B2', 'nl'),
('argumentatie', 'B2', 'nl'),
('vergelijking', 'B2', 'nl'),
('hypothese', 'B2', 'nl'),
('theorie', 'B2', 'nl'),
('experiment', 'B2', 'nl'),
('bewijs', 'B2', 'nl'),
('methode', 'B2', 'nl'),
('conclusie', 'B2', 'nl'),
('observatie', 'B2', 'nl'),
('perspectief', 'B2', 'nl'),
('aanname', 'B2', 'nl'),
('context', 'B2', 'nl'),
('criteria', 'B2', 'nl'),
('beginsel', 'B2', 'nl'),
('prioriteit', 'B2', 'nl'),
('complexiteit', 'B2', 'nl'),
('efficiëntie', 'B2', 'nl'),
('productiviteit', 'B2', 'nl'),
('investering', 'B2', 'nl'),
('economie', 'B2', 'nl'),
('financiën', 'B2', 'nl'),
('onderhandeling', 'B2', 'nl'),
('overeenkomst', 'B2', 'nl'),
('contract', 'B2', 'nl'),
('beleid', 'B2', 'nl'),
('regering', 'B2', 'nl'),
('politiek', 'B2', 'nl'),
('verkiezing', 'B2', 'nl'),
('democratie', 'B2', 'nl'),
('vrijheid', 'B2', 'nl'),
('gerechtigheid', 'B2', 'nl'),
('gelijkwaardigheid', 'B2', 'nl'),
('wet', 'B2', 'nl'),
('misdaad', 'B2', 'nl'),
('boete', 'B2', 'nl'),
('straf', 'B2', 'nl'),
('beveiliging', 'B2', 'nl'),
('conflict', 'B2', 'nl'),
('oorlog', 'B2', 'nl'),
('vrede', 'B2', 'nl'),
('geweld', 'B2', 'nl'),
('terrorisme', 'B2', 'nl'),
('globalisering', 'B2', 'nl'),
('integratie', 'B2', 'nl'),
('diversiteit', 'B2', 'nl'),
('identiteit', 'B2', 'nl'),
('migratie', 'B2', 'nl'),
('vluchteling', 'B2', 'nl'),
('gemeenschap', 'B2', 'nl'),
('netwerk', 'B2', 'nl'),
('organisatie', 'B2', 'nl'),
('instelling', 'B2', 'nl'),
('leiderschap', 'B2', 'nl'),
('beheer', 'B2', 'nl'),
('planning', 'B2', 'nl'),
('strategie', 'B2', 'nl'),
('initiatief', 'B2', 'nl'),
('creativiteit', 'B2', 'nl'),
('samenwerking', 'B2', 'nl'),
('teamwerk', 'B2', 'nl'),
('verantwoordelijkheid', 'B2', 'nl'),
('verantwoordelijkheid', 'B2', 'nl'),
('duurzaamheid', 'B2', 'nl'),
('milieubescherming', 'B2', 'nl'),
('hernieuwbare energie', 'B2', 'nl'),
('innovatieproces', 'B2', 'nl'),
('kritisch denken', 'B2', 'nl'),
('Probleemoplossing', 'B2', 'nl'),
('besluitvorming', 'B2', 'nl'),
('Tijdbeheer', 'B2', 'nl'),
('zelfdiscipline', 'B2', 'nl'),
('aanpassing', 'B2', 'nl'),
('weerstand', 'B2', 'nl'),
('onafhankelijkheid', 'B2', 'nl'),
('samenwerking', 'B2', 'nl'),
('vertrouwen', 'B2', 'nl'),
('respect', 'B2', 'nl'),
('empathie', 'B2', 'nl'),
('loyaliteit', 'B2', 'nl'),
('integriteit', 'B2', 'nl'),
('ethiek', 'B2', 'nl'),
('moraliteit', 'B2', 'nl'),
('filosofie', 'B2', 'nl'),
('psychologie', 'B2', 'nl'),
('sociologie', 'B2', 'nl'),
('biologie', 'B2', 'nl'),
('scheikunde', 'B2', 'nl'),
('natuurkunde', 'B2', 'nl'),
('Kritische analyse', 'C1', 'nl'),
('logisch redeneren', 'C1', 'nl'),
('interpretatie', 'C1', 'nl'),
('Diepe vergelijking', 'C1', 'nl'),
('Wetenschappelijke conclusie', 'C1', 'nl'),
('Complexe hypothese', 'C1', 'nl'),
('Geavanceerde theorie', 'C1', 'nl'),
('diepgaand experiment', 'C1', 'nl'),
('uitgebreide evaluatie', 'C1', 'nl'),
('filosofische discussie', 'C1', 'nl'),
('sterk argument', 'C1', 'nl'),
('tastbaar bewijs', 'C1', 'nl'),
('tegenstrijdig bewijs', 'C1', 'nl'),
('Abstract concept', 'C1', 'nl'),
('ethische positie', 'C1', 'nl'),
('Supreme waarde', 'C1', 'nl'),
('Fundamentele principe', 'C1', 'nl'),
('topprioriteit', 'C1', 'nl'),
('Grote verantwoordelijkheid', 'C1', 'nl'),
('cruciale beslissing', 'C1', 'nl'),
('complex beheer', 'C1', 'nl'),
('strategische planning', 'C1', 'nl'),
('Duurzame ontwikkeling', 'C1', 'nl'),
('Moderne innovatie', 'C1', 'nl'),
('Geavanceerde creativiteit', 'C1', 'nl'),
('Nieuwe ontdekking', 'C1', 'nl'),
('innovatieve uitvinding', 'C1', 'nl'),
('economische analyse', 'C1', 'nl'),
('financieel rapport', 'C1', 'nl'),
('grootschalig project', 'C1', 'nl'),
('Internationale onderhandelingen', 'C1', 'nl'),
('formele overeenkomst', 'C1', 'nl'),
('Effectieve strategie', 'C1', 'nl'),
('wereldwijde instelling', 'C1', 'nl'),
('onderzoekscentrum', 'C1', 'nl'),
('Geavanceerde wetenschappelijke studie', 'C1', 'nl'),
('Kritische beoordeling', 'C1', 'nl'),
('filosofische interpretatie', 'C1', 'nl'),
('systematische benadering', 'C1', 'nl'),
('moderne theorie', 'C1', 'nl'),
('Toegepast onderzoek', 'C1', 'nl'),
('praktisch experiment', 'C1', 'nl'),
('objectieve evaluatie', 'C1', 'nl'),
('Gedetailleerde resultaten', 'C1', 'nl'),
('Geavanceerd debat', 'C1', 'nl'),
('Vergelijkende studie', 'C1', 'nl'),
('veldonderzoek', 'C1', 'nl'),
('praktische aanbeveling', 'C1', 'nl'),
('Geavanceerde vaardigheid', 'C1', 'nl'),
('conceptueel raamwerk', 'C1', 'nl'),
('Nauwkeurige planning', 'C1', 'nl'),
('langetermijnstrategie', 'C1', 'nl'),
('risicobeoordeling', 'C1', 'nl'),
('academische beoordeling', 'C1', 'nl'),
('onderzoeksproject', 'C1', 'nl'),
('Wetenschappelijke innovatie', 'C1', 'nl'),
('technologische ontwikkeling', 'C1', 'nl'),
('literaire analyse', 'C1', 'nl'),
('Wetenschappelijke bevindingen', 'C1', 'nl'),
('Geavanceerde interpretatie', 'C1', 'nl'),
('holistische uitzicht', 'C1', 'nl'),
('implementatieplan', 'C1', 'nl'),
('strategische beslissing', 'C1', 'nl'),
('resource management', 'C1', 'nl'),
('Complexe uitdagingen', 'C1', 'nl'),
('innovatieve oplossingen', 'C1', 'nl'),
('uitgebreide aanpak', 'C1', 'nl'),
('gegevensanalyse', 'C1', 'nl'),
('Hypothesetesten', 'C1', 'nl'),
('case study', 'C1', 'nl'),
('Geavanceerd veldwerk', 'C1', 'nl'),
('filosofische recensie', 'C1', 'nl'),
('Toegepast onderzoeksproject', 'C1', 'nl'),
('academische discussie', 'C1', 'nl'),
('strategische evaluatie', 'C1', 'nl'),
('praktische aanbevelingen', 'C1', 'nl'),
('werkplan', 'C1', 'nl'),
('projectmanagement', 'C1', 'nl'),
('academische publicatie', 'C1', 'nl'),
('Wetenschappelijke ontdekking', 'C1', 'nl'),
('Toegepaste innovatie', 'C1', 'nl'),
('continue ontwikkeling', 'C1', 'nl'),
('Diepgaande gegevensanalyse', 'C1', 'nl'),
('onderzoekservaring', 'C1', 'nl'),
('Wetenschappelijke interpretatie', 'C1', 'nl'),
('kritisch perspectief', 'C1', 'nl');
