INSERT INTO words (word, level, language_code) VALUES
('maja', 'A1', 'et'),
('uks', 'A1', 'et'),
('aken', 'A1', 'et'),
('laud', 'A1', 'et'),
('juhataja', 'A1', 'et'),
('raamat', 'A1', 'et'),
('pliiats', 'A1', 'et'),
('kool', 'A1', 'et'),
('õpetaja', 'A1', 'et'),
('tudeng', 'A1', 'et'),
('õun', 'A1', 'et'),
('vesi', 'A1', 'et'),
('toit', 'A1', 'et'),
('auto', 'A1', 'et'),
('buss', 'A1', 'et'),
('tänav', 'A1', 'et'),
('sõber', 'A1', 'et'),
('perekond', 'A1', 'et'),
('ema', 'A1', 'et'),
('isa', 'A1', 'et'),
('õde', 'A1', 'et'),
('vend', 'A1', 'et'),
('päev', 'A1', 'et'),
('öö', 'A1', 'et'),
('hommikune', 'A1', 'et'),
('õhtu', 'A1', 'et'),
('tere', 'A1', 'et'),
('hüvastijätmine', 'A1', 'et'),
('palun', 'A1', 'et'),
('Aitäh', 'A1', 'et'),
('jah', 'A1', 'et'),
('mitte', 'A1', 'et'),
('punane', 'A1', 'et'),
('sinine', 'A1', 'et'),
('roheline', 'A1', 'et'),
('valge', 'A1', 'et'),
('must', 'A1', 'et'),
('väike', 'A1', 'et'),
('suur', 'A1', 'et'),
('hea', 'A1', 'et'),
('kahjulik', 'A1', 'et'),
('kuum', 'A1', 'et'),
('külm', 'A1', 'et'),
('kohv', 'A1', 'et'),
('tee', 'A1', 'et'),
('raha', 'A1', 'et'),
('töö', 'A1', 'et'),
('kodu', 'A1', 'et'),
('kauplus', 'A1', 'et'),
('turg', 'A1', 'et'),
('toit', 'A1', 'et'),
('jook', 'A1', 'et'),
('linn', 'A1', 'et'),
('park', 'A1', 'et'),
('tänav', 'A1', 'et'),
('bussipeatus', 'A1', 'et'),
('rong', 'A1', 'et'),
('jaam', 'A1', 'et'),
('hotell', 'A1', 'et'),
('ruum', 'A1', 'et'),
('voodi', 'A1', 'et'),
('arst', 'A1', 'et'),
('haigla', 'A1', 'et'),
('kool', 'A1', 'et'),
('ülikool', 'A1', 'et'),
('arvuti', 'A1', 'et'),
('telefon', 'A1', 'et'),
('televisioon', 'A1', 'et'),
('muusika', 'A1', 'et'),
('laul', 'A1', 'et'),
('film', 'A1', 'et'),
('mängumäng', 'A1', 'et'),
('jalgpall', 'A1', 'et'),
('kuuli', 'A1', 'et'),
('vesi', 'A1', 'et'),
('vihm', 'A1', 'et'),
('päike', 'A1', 'et'),
('taevas', 'A1', 'et'),
('puu', 'A1', 'et'),
('lill', 'A1', 'et'),
('loom', 'A1', 'et'),
('kass', 'A1', 'et'),
('koer', 'A1', 'et'),
('lind', 'A1', 'et'),
('kalastama', 'A1', 'et'),
('mees', 'A1', 'et'),
('naine', 'A1', 'et'),
('laps', 'A1', 'et'),
('inimesed', 'A1', 'et'),
('tänav', 'A1', 'et'),
('koht', 'A1', 'et'),
('aeg', 'A1', 'et'),
('aasta', 'A1', 'et'),
('kuu', 'A1', 'et'),
('nädal', 'A1', 'et'),
('täna', 'A1', 'et'),
('homme', 'A1', 'et'),
('eile', 'A1', 'et'),
('nimetus', 'A1', 'et'),
('aadress', 'A1', 'et'),
('arv', 'A1', 'et'),
('lennujaam', 'A2', 'et'),
('lend', 'A2', 'et'),
('pilet', 'A2', 'et'),
('pass', 'A2', 'et'),
('reis', 'A2', 'et'),
('puhkus', 'A2', 'et'),
('teekond', 'A2', 'et'),
('pagas', 'A2', 'et'),
('jaam', 'A2', 'et'),
('platvorm', 'A2', 'et'),
('restoran', 'A2', 'et'),
('kohvik', 'A2', 'et'),
('hommikusöök', 'A2', 'et'),
('lõuna', 'A2', 'et'),
('õhtusöök', 'A2', 'et'),
('köögiviljad', 'A2', 'et'),
('puuvili', 'A2', 'et'),
('liha', 'A2', 'et'),
('kana', 'A2', 'et'),
('veiseliha', 'A2', 'et'),
('kalastama', 'A2', 'et'),
('leib', 'A2', 'et'),
('riis', 'A2', 'et'),
('pasta', 'A2', 'et'),
('supp', 'A2', 'et'),
('suhkur', 'A2', 'et'),
('soola', 'A2', 'et'),
('pipar', 'A2', 'et'),
('õli', 'A2', 'et'),
('ostmine', 'A2', 'et'),
('riided', 'A2', 'et'),
('särk', 'A2', 'et'),
('püksid', 'A2', 'et'),
('riietus', 'A2', 'et'),
('kingad', 'A2', 'et'),
('müts', 'A2', 'et'),
('jope', 'A2', 'et'),
('mantel', 'A2', 'et'),
('ilm', 'A2', 'et'),
('lund', 'A2', 'et'),
('tuul', 'A2', 'et'),
('torm', 'A2', 'et'),
('hotellid', 'A2', 'et'),
('külaline', 'A2', 'et'),
('teenistus', 'A2', 'et'),
('vastuvõtt', 'A2', 'et'),
('võti', 'A2', 'et'),
('reserveerimine', 'A2', 'et'),
('rand', 'A2', 'et'),
('meri', 'A2', 'et'),
('ujumine', 'A2', 'et'),
('bassein', 'A2', 'et'),
('mägi', 'A2', 'et'),
('küla', 'A2', 'et'),
('riik', 'A2', 'et'),
('keel', 'A2', 'et'),
('võõras', 'A2', 'et'),
('eksam', 'A2', 'et'),
('test', 'A2', 'et'),
('kodutöö', 'A2', 'et'),
('klassiruum', 'A2', 'et'),
('subjekt', 'A2', 'et'),
('matemaatika', 'A2', 'et'),
('ajalugu', 'A2', 'et'),
('teadus', 'A2', 'et'),
('raamatukogu', 'A2', 'et'),
('raamatupood', 'A2', 'et'),
('arvuti', 'A2', 'et'),
('internet', 'A2', 'et'),
('e -kiri', 'A2', 'et'),
('teade', 'A2', 'et'),
('kiri', 'A2', 'et'),
('postitus', 'A2', 'et'),
('pank', 'A2', 'et'),
('raha', 'A2', 'et'),
('krediitkaart', 'A2', 'et'),
('hind', 'A2', 'et'),
('odav', 'A2', 'et'),
('kallis', 'A2', 'et'),
('küsitlus', 'A2', 'et'),
('vastus', 'A2', 'et'),
('selgitama', 'A2', 'et'),
('abi', 'A2', 'et'),
('probleem', 'A2', 'et'),
('lahendus', 'A2', 'et'),
('tervis', 'A2', 'et'),
('ravim', 'A2', 'et'),
('arst', 'A2', 'et'),
('õde', 'A2', 'et'),
('patsient', 'A2', 'et'),
('ametisse nimetamine', 'A2', 'et'),
('palavik', 'A2', 'et'),
('köha', 'A2', 'et'),
('kogemus', 'B1', 'et'),
('seiklus', 'B1', 'et'),
('arvamus', 'B1', 'et'),
('arutelu', 'B1', 'et'),
('argument', 'B1', 'et'),
('otsus', 'B1', 'et'),
('mõistus', 'B1', 'et'),
('võimalus', 'B1', 'et'),
('väljakutse', 'B1', 'et'),
('edu', 'B1', 'et'),
('läbikukkumine', 'B1', 'et'),
('eesmärk', 'B1', 'et'),
('plaan', 'B1', 'et'),
('projekt', 'B1', 'et'),
('teadmised', 'B1', 'et'),
('oskused', 'B1', 'et'),
('võime', 'B1', 'et'),
('parandamine', 'B1', 'et'),
('koolitus', 'B1', 'et'),
('tööintervjuu', 'B1', 'et'),
('rakendus', 'B1', 'et'),
('karjäär', 'B1', 'et'),
('juhataja', 'B1', 'et'),
('kolleeg', 'B1', 'et'),
('koosolek', 'B1', 'et'),
('ülesanne', 'B1', 'et'),
('vastutus', 'B1', 'et'),
('puhkusereis', 'B1', 'et'),
('kultuur', 'B1', 'et'),
('traditsioon', 'B1', 'et'),
('kohandatud', 'B1', 'et'),
('festival', 'B1', 'et'),
('pidustus', 'B1', 'et'),
('esinemine', 'B1', 'et'),
('kontsert', 'B1', 'et'),
('teater', 'B1', 'et'),
('näitus', 'B1', 'et'),
('maalimine', 'B1', 'et'),
('skulptuur', 'B1', 'et'),
('muuseum', 'B1', 'et'),
('ajalooraamat', 'B1', 'et'),
('väljamõeldis', 'B1', 'et'),
('luuletus', 'B1', 'et'),
('uudne', 'B1', 'et'),
('omadus', 'B1', 'et'),
('süžee', 'B1', 'et'),
('lugu', 'B1', 'et'),
('ajaleht', 'B1', 'et'),
('ajakiri', 'B1', 'et'),
('artikkel', 'B1', 'et'),
('aruanne', 'B1', 'et'),
('esitlus', 'B1', 'et'),
('loeng', 'B1', 'et'),
('haridus', 'B1', 'et'),
('ülikool', 'B1', 'et'),
('kraad', 'B1', 'et'),
('diplom', 'B1', 'et'),
('sertifikaat', 'B1', 'et'),
('keskkond', 'B1', 'et'),
('olemus', 'B1', 'et'),
('ringlussevõtt', 'B1', 'et'),
('reostus', 'B1', 'et'),
('kliimamuutused', 'B1', 'et'),
('globaalne soojenemine', 'B1', 'et'),
('energia', 'B1', 'et'),
('tehnoloogia', 'B1', 'et'),
('innovatsioon', 'B1', 'et'),
('leiutis', 'B1', 'et'),
('seade', 'B1', 'et'),
('masin', 'B1', 'et'),
('arvutiprogramm', 'B1', 'et'),
('veebisait', 'B1', 'et'),
('rakendus', 'B1', 'et'),
('sotsiaalmeedia', 'B1', 'et'),
('suhtlus', 'B1', 'et'),
('vestlus', 'B1', 'et'),
('koostoime', 'B1', 'et'),
('suhe', 'B1', 'et'),
('sõprus', 'B1', 'et'),
('abielu', 'B1', 'et'),
('pereelu', 'B1', 'et'),
('õnn', 'B1', 'et'),
('viha', 'B1', 'et'),
('hirm', 'B1', 'et'),
('lootus', 'B1', 'et'),
('unistus', 'B1', 'et'),
('ambitsioon', 'B1', 'et'),
('motivatsioon', 'B1', 'et'),
('usaldus', 'B1', 'et'),
('uudishimu', 'B1', 'et'),
('kannatlikkus', 'B1', 'et'),
('innovatsioon', 'B2', 'et'),
('arendamine', 'B2', 'et'),
('uurimine', 'B2', 'et'),
('analüüs', 'B2', 'et'),
('tõlgendamine', 'B2', 'et'),
('argumentatsioon', 'B2', 'et'),
('võrdlus', 'B2', 'et'),
('hüpotees', 'B2', 'et'),
('teooria', 'B2', 'et'),
('eksperimenteerima', 'B2', 'et'),
('tõend', 'B2', 'et'),
('meetod', 'B2', 'et'),
('järeldus', 'B2', 'et'),
('vaatlus', 'B2', 'et'),
('perspektiiv', 'B2', 'et'),
('eeldus', 'B2', 'et'),
('kontekst', 'B2', 'et'),
('kriteerium', 'B2', 'et'),
('põhimõte', 'B2', 'et'),
('prioriteet', 'B2', 'et'),
('keerukus', 'B2', 'et'),
('efektiivsus', 'B2', 'et'),
('tootlikkus', 'B2', 'et'),
('investeering', 'B2', 'et'),
('majandus', 'B2', 'et'),
('rahandus', 'B2', 'et'),
('läbirääkimised', 'B2', 'et'),
('kokkulepe', 'B2', 'et'),
('leping', 'B2', 'et'),
('poliitika', 'B2', 'et'),
('valitsus', 'B2', 'et'),
('poliitika', 'B2', 'et'),
('valimised', 'B2', 'et'),
('demokraatia', 'B2', 'et'),
('vabadus', 'B2', 'et'),
('õiglus', 'B2', 'et'),
('võrdsus', 'B2', 'et'),
('seadus', 'B2', 'et'),
('kuritegevus', 'B2', 'et'),
('karistus', 'B2', 'et'),
('karistus', 'B2', 'et'),
('turvalisus', 'B2', 'et'),
('konflikt', 'B2', 'et'),
('sõda', 'B2', 'et'),
('rahu', 'B2', 'et'),
('vägivald', 'B2', 'et'),
('terrorism', 'B2', 'et'),
('globaliseerumine', 'B2', 'et'),
('integreerimine', 'B2', 'et'),
('mitmekesisus', 'B2', 'et'),
('identiteet', 'B2', 'et'),
('ränne', 'B2', 'et'),
('pagulane', 'B2', 'et'),
('kogukond', 'B2', 'et'),
('võrgustik', 'B2', 'et'),
('korraldus', 'B2', 'et'),
('asutus', 'B2', 'et'),
('juhtimine', 'B2', 'et'),
('juhtimine', 'B2', 'et'),
('kavandamine', 'B2', 'et'),
('strateegia', 'B2', 'et'),
('algatus', 'B2', 'et'),
('loovus', 'B2', 'et'),
('koostöö', 'B2', 'et'),
('meeskonnatöö', 'B2', 'et'),
('vastutus', 'B2', 'et'),
('vastutus', 'B2', 'et'),
('jätkusuutlikkus', 'B2', 'et'),
('keskkonnakaitse', 'B2', 'et'),
('taastuvenergia', 'B2', 'et'),
('innovatsiooniprotsess', 'B2', 'et'),
('kriitiline mõtlemine', 'B2', 'et'),
('probleemide lahendamine', 'B2', 'et'),
('otsuste tegemine', 'B2', 'et'),
('ajahaldus', 'B2', 'et'),
('enesedistsipliin', 'B2', 'et'),
('kohanemine', 'B2', 'et'),
('vastupidasus', 'B2', 'et'),
('iseseisvus', 'B2', 'et'),
('koostöö', 'B2', 'et'),
('usaldus', 'B2', 'et'),
('austus', 'B2', 'et'),
('empaatiavõime', 'B2', 'et'),
('lojaalsus', 'B2', 'et'),
('terviklikkus', 'B2', 'et'),
('eetika', 'B2', 'et'),
('moraalsus', 'B2', 'et'),
('filosoofia', 'B2', 'et'),
('psühholoogia', 'B2', 'et'),
('sotsioloogia', 'B2', 'et'),
('bioloogia', 'B2', 'et'),
('keemia', 'B2', 'et'),
('füüsika', 'B2', 'et'),
('kriitiline analüüs', 'C1', 'et'),
('loogiline arutluskäik', 'C1', 'et'),
('tõlgendamine', 'C1', 'et'),
('sügav võrdlus', 'C1', 'et'),
('teaduslik järeldus', 'C1', 'et'),
('keeruline hüpotees', 'C1', 'et'),
('arenenud teooria', 'C1', 'et'),
('põhjalik katse', 'C1', 'et'),
('põhjalik hindamine', 'C1', 'et'),
('filosoofiline arutelu', 'C1', 'et'),
('tugev argument', 'C1', 'et'),
('käegakatsutavad tõendid', 'C1', 'et'),
('vastuolulised tõendid', 'C1', 'et'),
('abstraktne kontseptsioon', 'C1', 'et'),
('eetiline positsioon', 'C1', 'et'),
('kõrgeim väärtus', 'C1', 'et'),
('aluspõhimõte', 'C1', 'et'),
('prioriteet', 'C1', 'et'),
('peamine vastutus', 'C1', 'et'),
('ülioluline otsus', 'C1', 'et'),
('keeruline juhtimine', 'C1', 'et'),
('strateegiline planeerimine', 'C1', 'et'),
('jätkusuutlik areng', 'C1', 'et'),
('kaasaegne uuendus', 'C1', 'et'),
('arenenud loovus', 'C1', 'et'),
('uus avastus', 'C1', 'et'),
('uuenduslik leiutis', 'C1', 'et'),
('majandusanalüüs', 'C1', 'et'),
('finantsaruanne', 'C1', 'et'),
('suuremahuline projekt', 'C1', 'et'),
('rahvusvahelised läbirääkimised', 'C1', 'et'),
('ametlik leping', 'C1', 'et'),
('tõhus strateegia', 'C1', 'et'),
('ülemaailmne asutus', 'C1', 'et'),
('uurimiskeskus', 'C1', 'et'),
('arenenud teaduslik uuring', 'C1', 'et'),
('kriitiline ülevaade', 'C1', 'et'),
('filosoofiline tõlgendus', 'C1', 'et'),
('süstemaatiline lähenemisviis', 'C1', 'et'),
('kaasaegne teooria', 'C1', 'et'),
('rakendusuuringud', 'C1', 'et'),
('praktiline katse', 'C1', 'et'),
('objektiivne hindamine', 'C1', 'et'),
('üksikasjalikud tulemused', 'C1', 'et'),
('arenenud arutelu', 'C1', 'et'),
('võrdlev uuring', 'C1', 'et'),
('välitingimused', 'C1', 'et'),
('praktiline soovitus', 'C1', 'et'),
('arenenud oskused', 'C1', 'et'),
('kontseptuaalne raamistik', 'C1', 'et'),
('täpne planeerimine', 'C1', 'et'),
('pikaajaline strateegia', 'C1', 'et'),
('riskihindamine', 'C1', 'et'),
('akadeemiline ülevaade', 'C1', 'et'),
('uurimisprojekt', 'C1', 'et'),
('teaduslik uuendus', 'C1', 'et'),
('tehnoloogiline areng', 'C1', 'et'),
('kirjandusanalüüs', 'C1', 'et'),
('teaduslikud leiud', 'C1', 'et'),
('täiustatud tõlgendus', 'C1', 'et'),
('terviklik vaade', 'C1', 'et'),
('rakendusplaan', 'C1', 'et'),
('strateegiline otsus', 'C1', 'et'),
('ressursside haldamine', 'C1', 'et'),
('keerulised väljakutsed', 'C1', 'et'),
('uuenduslikud lahendused', 'C1', 'et'),
('põhjalik lähenemisviis', 'C1', 'et'),
('andmeanalüüs', 'C1', 'et'),
('hüpoteesi testimine', 'C1', 'et'),
('juhtumianalüüs', 'C1', 'et'),
('arenenud välitöö', 'C1', 'et'),
('filosoofiline ülevaade', 'C1', 'et'),
('rakendusprojekt', 'C1', 'et'),
('akadeemiline arutelu', 'C1', 'et'),
('strateegiline hindamine', 'C1', 'et'),
('praktilised soovitused', 'C1', 'et'),
('tööplaan', 'C1', 'et'),
('projektijuhtimine', 'C1', 'et'),
('akadeemiline väljaanne', 'C1', 'et'),
('teaduslik avastus', 'C1', 'et'),
('rakendusinnovatsioon', 'C1', 'et'),
('pidev areng', 'C1', 'et'),
('põhjalik andmete analüüs', 'C1', 'et'),
('uurimiskogemus', 'C1', 'et'),
('teaduslik tõlgendus', 'C1', 'et'),
('kriitiline perspektiiv', 'C1', 'et');
