INSERT INTO words (word, level, language_code) VALUES
('hus', 'A1', 'da'),
('dør', 'A1', 'da'),
('vindue', 'A1', 'da'),
('tabel', 'A1', 'da'),
('stol', 'A1', 'da'),
('bog', 'A1', 'da'),
('pen', 'A1', 'da'),
('skole', 'A1', 'da'),
('lærer', 'A1', 'da'),
('studerende', 'A1', 'da'),
('æble', 'A1', 'da'),
('vand', 'A1', 'da'),
('mad', 'A1', 'da'),
('bil', 'A1', 'da'),
('bus', 'A1', 'da'),
('gade', 'A1', 'da'),
('ven', 'A1', 'da'),
('familie', 'A1', 'da'),
('mor', 'A1', 'da'),
('far', 'A1', 'da'),
('søster', 'A1', 'da'),
('bror', 'A1', 'da'),
('dag', 'A1', 'da'),
('nat', 'A1', 'da'),
('morgen', 'A1', 'da'),
('aften', 'A1', 'da'),
('hej', 'A1', 'da'),
('farvel', 'A1', 'da'),
('behage', 'A1', 'da'),
('Tak', 'A1', 'da'),
('ja', 'A1', 'da'),
('ingen', 'A1', 'da'),
('rød', 'A1', 'da'),
('blå', 'A1', 'da'),
('grøn', 'A1', 'da'),
('hvid', 'A1', 'da'),
('sort', 'A1', 'da'),
('lille', 'A1', 'da'),
('stor', 'A1', 'da'),
('god', 'A1', 'da'),
('Dårligt', 'A1', 'da'),
('varm', 'A1', 'da'),
('kold', 'A1', 'da'),
('kaffe', 'A1', 'da'),
('te', 'A1', 'da'),
('penge', 'A1', 'da'),
('arbejde', 'A1', 'da'),
('hjem', 'A1', 'da'),
('butik', 'A1', 'da'),
('marked', 'A1', 'da'),
('mad', 'A1', 'da'),
('drikke', 'A1', 'da'),
('by', 'A1', 'da'),
('parkere', 'A1', 'da'),
('gade', 'A1', 'da'),
('busstoppested', 'A1', 'da'),
('tog', 'A1', 'da'),
('station', 'A1', 'da'),
('hotel', 'A1', 'da'),
('værelse', 'A1', 'da'),
('seng', 'A1', 'da'),
('læge', 'A1', 'da'),
('hospital', 'A1', 'da'),
('skole', 'A1', 'da'),
('universitet', 'A1', 'da'),
('computer', 'A1', 'da'),
('telefon', 'A1', 'da'),
('television', 'A1', 'da'),
('musik', 'A1', 'da'),
('sang', 'A1', 'da'),
('film', 'A1', 'da'),
('spil', 'A1', 'da'),
('Fodbold', 'A1', 'da'),
('bold', 'A1', 'da'),
('vand', 'A1', 'da'),
('regn', 'A1', 'da'),
('sol', 'A1', 'da'),
('himmel', 'A1', 'da'),
('træ', 'A1', 'da'),
('blomst', 'A1', 'da'),
('dyr', 'A1', 'da'),
('kat', 'A1', 'da'),
('hund', 'A1', 'da'),
('fugl', 'A1', 'da'),
('fisk', 'A1', 'da'),
('mand', 'A1', 'da'),
('kvinde', 'A1', 'da'),
('barn', 'A1', 'da'),
('mennesker', 'A1', 'da'),
('gade', 'A1', 'da'),
('placere', 'A1', 'da'),
('tid', 'A1', 'da'),
('år', 'A1', 'da'),
('måned', 'A1', 'da'),
('uge', 'A1', 'da'),
('i dag', 'A1', 'da'),
('i morgen', 'A1', 'da'),
('i går', 'A1', 'da'),
('navn', 'A1', 'da'),
('adresse', 'A1', 'da'),
('antal', 'A1', 'da'),
('lufthavn', 'A2', 'da'),
('flyvningen', 'A2', 'da'),
('billet', 'A2', 'da'),
('pas', 'A2', 'da'),
('rejse', 'A2', 'da'),
('ferie', 'A2', 'da'),
('rejse', 'A2', 'da'),
('bagage', 'A2', 'da'),
('station', 'A2', 'da'),
('platform', 'A2', 'da'),
('restaurant', 'A2', 'da'),
('cafe', 'A2', 'da'),
('morgenmad', 'A2', 'da'),
('frokost', 'A2', 'da'),
('middag', 'A2', 'da'),
('grøntsager', 'A2', 'da'),
('frugt', 'A2', 'da'),
('kød', 'A2', 'da'),
('kylling', 'A2', 'da'),
('oksekød', 'A2', 'da'),
('fisk', 'A2', 'da'),
('brød', 'A2', 'da'),
('ris', 'A2', 'da'),
('pasta', 'A2', 'da'),
('suppe', 'A2', 'da'),
('sukker', 'A2', 'da'),
('salt', 'A2', 'da'),
('peber', 'A2', 'da'),
('olie', 'A2', 'da'),
('shopping', 'A2', 'da'),
('tøj', 'A2', 'da'),
('skjorte', 'A2', 'da'),
('bukser', 'A2', 'da'),
('kjole', 'A2', 'da'),
('Sko', 'A2', 'da'),
('hat', 'A2', 'da'),
('jakke', 'A2', 'da'),
('frakke', 'A2', 'da'),
('vejr', 'A2', 'da'),
('sne', 'A2', 'da'),
('vind', 'A2', 'da'),
('storm', 'A2', 'da'),
('hoteller', 'A2', 'da'),
('gæst', 'A2', 'da'),
('service', 'A2', 'da'),
('reception', 'A2', 'da'),
('nøgle', 'A2', 'da'),
('Reservation', 'A2', 'da'),
('strand', 'A2', 'da'),
('hav', 'A2', 'da'),
('svømning', 'A2', 'da'),
('pool', 'A2', 'da'),
('bjerg', 'A2', 'da'),
('landsby', 'A2', 'da'),
('land', 'A2', 'da'),
('sprog', 'A2', 'da'),
('udenlandsk', 'A2', 'da'),
('eksamen', 'A2', 'da'),
('prøve', 'A2', 'da'),
('lektier', 'A2', 'da'),
('Klasselokale', 'A2', 'da'),
('emne', 'A2', 'da'),
('matematik', 'A2', 'da'),
('historie', 'A2', 'da'),
('videnskab', 'A2', 'da'),
('bibliotek', 'A2', 'da'),
('boghandel', 'A2', 'da'),
('computer', 'A2', 'da'),
('Internet', 'A2', 'da'),
('e -mail', 'A2', 'da'),
('besked', 'A2', 'da'),
('bogstav', 'A2', 'da'),
('stolpe', 'A2', 'da'),
('bank', 'A2', 'da'),
('penge', 'A2', 'da'),
('Kreditkort', 'A2', 'da'),
('pris', 'A2', 'da'),
('billig', 'A2', 'da'),
('dyr', 'A2', 'da'),
('spørgsmål', 'A2', 'da'),
('svar', 'A2', 'da'),
('forklare', 'A2', 'da'),
('hjælp', 'A2', 'da'),
('problem', 'A2', 'da'),
('løsning', 'A2', 'da'),
('sundhed', 'A2', 'da'),
('medicin', 'A2', 'da'),
('læge', 'A2', 'da'),
('amme', 'A2', 'da'),
('patient', 'A2', 'da'),
('udnævnelse', 'A2', 'da'),
('feber', 'A2', 'da'),
('hoste', 'A2', 'da'),
('erfaring', 'B1', 'da'),
('eventyr', 'B1', 'da'),
('udtalelse', 'B1', 'da'),
('diskussion', 'B1', 'da'),
('argument', 'B1', 'da'),
('afgørelse', 'B1', 'da'),
('årsag', 'B1', 'da'),
('lejlighed', 'B1', 'da'),
('udfordring', 'B1', 'da'),
('succes', 'B1', 'da'),
('fiasko', 'B1', 'da'),
('mål', 'B1', 'da'),
('plan', 'B1', 'da'),
('projekt', 'B1', 'da'),
('viden', 'B1', 'da'),
('dygtighed', 'B1', 'da'),
('evne', 'B1', 'da'),
('forbedring', 'B1', 'da'),
('uddannelse', 'B1', 'da'),
('Jobinterview', 'B1', 'da'),
('anvendelse', 'B1', 'da'),
('karriere', 'B1', 'da'),
('manager', 'B1', 'da'),
('kollega', 'B1', 'da'),
('møde', 'B1', 'da'),
('opgave', 'B1', 'da'),
('ansvar', 'B1', 'da'),
('Holiday Trip', 'B1', 'da'),
('kultur', 'B1', 'da'),
('tradition', 'B1', 'da'),
('skik', 'B1', 'da'),
('festival', 'B1', 'da'),
('fest', 'B1', 'da'),
('præstation', 'B1', 'da'),
('koncert', 'B1', 'da'),
('teater', 'B1', 'da'),
('udstilling', 'B1', 'da'),
('maleri', 'B1', 'da'),
('skulptur', 'B1', 'da'),
('museum', 'B1', 'da'),
('Historiebog', 'B1', 'da'),
('fiktion', 'B1', 'da'),
('digt', 'B1', 'da'),
('roman', 'B1', 'da'),
('karakter', 'B1', 'da'),
('grund', 'B1', 'da'),
('historie', 'B1', 'da'),
('avis', 'B1', 'da'),
('magasin', 'B1', 'da'),
('Artikel', 'B1', 'da'),
('rapport', 'B1', 'da'),
('præsentation', 'B1', 'da'),
('foredrag', 'B1', 'da'),
('undervisning', 'B1', 'da'),
('universitet', 'B1', 'da'),
('grad', 'B1', 'da'),
('eksamensbevis', 'B1', 'da'),
('certifikat', 'B1', 'da'),
('miljø', 'B1', 'da'),
('natur', 'B1', 'da'),
('genanvendelse', 'B1', 'da'),
('forurening', 'B1', 'da'),
('Klimaændringer', 'B1', 'da'),
('Global opvarmning', 'B1', 'da'),
('energi', 'B1', 'da'),
('teknologi', 'B1', 'da'),
('innovation', 'B1', 'da'),
('opfindelse', 'B1', 'da'),
('enhed', 'B1', 'da'),
('maskine', 'B1', 'da'),
('Computerprogram', 'B1', 'da'),
('Hjemmeside', 'B1', 'da'),
('anvendelse', 'B1', 'da'),
('Sociale medier', 'B1', 'da'),
('meddelelse', 'B1', 'da'),
('samtale', 'B1', 'da'),
('vekselvirkning', 'B1', 'da'),
('forhold', 'B1', 'da'),
('venskab', 'B1', 'da'),
('ægteskab', 'B1', 'da'),
('Familieliv', 'B1', 'da'),
('lykke', 'B1', 'da'),
('vrede', 'B1', 'da'),
('frygt', 'B1', 'da'),
('håb', 'B1', 'da'),
('drøm', 'B1', 'da'),
('ambition', 'B1', 'da'),
('motivering', 'B1', 'da'),
('tillid', 'B1', 'da'),
('nysgerrighed', 'B1', 'da'),
('tålmodighed', 'B1', 'da'),
('innovation', 'B2', 'da'),
('udvikling', 'B2', 'da'),
('forskning', 'B2', 'da'),
('analyse', 'B2', 'da'),
('Fortolkning', 'B2', 'da'),
('Argumentation', 'B2', 'da'),
('sammenligning', 'B2', 'da'),
('Hypotese', 'B2', 'da'),
('teori', 'B2', 'da'),
('eksperiment', 'B2', 'da'),
('bevis', 'B2', 'da'),
('metode', 'B2', 'da'),
('konklusion', 'B2', 'da'),
('observation', 'B2', 'da'),
('perspektiv', 'B2', 'da'),
('antagelse', 'B2', 'da'),
('sammenhæng', 'B2', 'da'),
('kriterier', 'B2', 'da'),
('princip', 'B2', 'da'),
('prioritet', 'B2', 'da'),
('Kompleksitet', 'B2', 'da'),
('effektivitet', 'B2', 'da'),
('produktivitet', 'B2', 'da'),
('investering', 'B2', 'da'),
('økonomi', 'B2', 'da'),
('finansiere', 'B2', 'da'),
('forhandling', 'B2', 'da'),
('aftale', 'B2', 'da'),
('kontrakt', 'B2', 'da'),
('politik', 'B2', 'da'),
('regering', 'B2', 'da'),
('politik', 'B2', 'da'),
('valg', 'B2', 'da'),
('demokrati', 'B2', 'da'),
('frihed', 'B2', 'da'),
('retfærdighed', 'B2', 'da'),
('lighed', 'B2', 'da'),
('lov', 'B2', 'da'),
('forbrydelse', 'B2', 'da'),
('straf', 'B2', 'da'),
('straf', 'B2', 'da'),
('sikkerhed', 'B2', 'da'),
('konflikt', 'B2', 'da'),
('krig', 'B2', 'da'),
('fred', 'B2', 'da'),
('vold', 'B2', 'da'),
('terrorisme', 'B2', 'da'),
('Globalisering', 'B2', 'da'),
('integration', 'B2', 'da'),
('Mangfoldighed', 'B2', 'da'),
('identitet', 'B2', 'da'),
('migration', 'B2', 'da'),
('flygtning', 'B2', 'da'),
('fællesskab', 'B2', 'da'),
('netværk', 'B2', 'da'),
('organisation', 'B2', 'da'),
('institution', 'B2', 'da'),
('ledelse', 'B2', 'da'),
('ledelse', 'B2', 'da'),
('planlægning', 'B2', 'da'),
('strategi', 'B2', 'da'),
('initiativ', 'B2', 'da'),
('kreativitet', 'B2', 'da'),
('samarbejde', 'B2', 'da'),
('samarbejde', 'B2', 'da'),
('ansvar', 'B2', 'da'),
('Ansvarlighed', 'B2', 'da'),
('bæredygtighed', 'B2', 'da'),
('Miljøbeskyttelse', 'B2', 'da'),
('vedvarende energi', 'B2', 'da'),
('Innovationsproces', 'B2', 'da'),
('Kritisk tænkning', 'B2', 'da'),
('problemløsning', 'B2', 'da'),
('beslutningstagning', 'B2', 'da'),
('Tidsstyring', 'B2', 'da'),
('Selvdisciplin', 'B2', 'da'),
('Tilpasning', 'B2', 'da'),
('Resilience', 'B2', 'da'),
('uafhængighed', 'B2', 'da'),
('samarbejde', 'B2', 'da'),
('tillid', 'B2', 'da'),
('respekt', 'B2', 'da'),
('empati', 'B2', 'da'),
('loyalitet', 'B2', 'da'),
('integritet', 'B2', 'da'),
('etik', 'B2', 'da'),
('moral', 'B2', 'da'),
('filosofi', 'B2', 'da'),
('Psykologi', 'B2', 'da'),
('Sociologi', 'B2', 'da'),
('biologi', 'B2', 'da'),
('kemi', 'B2', 'da'),
('Fysik', 'B2', 'da'),
('Kritisk analyse', 'C1', 'da'),
('Logisk ræsonnement', 'C1', 'da'),
('Fortolkning', 'C1', 'da'),
('dyb sammenligning', 'C1', 'da'),
('videnskabelig konklusion', 'C1', 'da'),
('Kompleks hypotese', 'C1', 'da'),
('Avanceret teori', 'C1', 'da'),
('et dybtgående eksperiment', 'C1', 'da'),
('omfattende evaluering', 'C1', 'da'),
('filosofisk diskussion', 'C1', 'da'),
('stærkt argument', 'C1', 'da'),
('Motgribelig bevis', 'C1', 'da'),
('modstridende bevis', 'C1', 'da'),
('Abstrakt koncept', 'C1', 'da'),
('etisk position', 'C1', 'da'),
('højeste værdi', 'C1', 'da'),
('grundlæggende princip', 'C1', 'da'),
('højeste prioritet', 'C1', 'da'),
('hovedansvar', 'C1', 'da'),
('afgørende beslutning', 'C1', 'da'),
('Kompleks ledelse', 'C1', 'da'),
('Strategisk planlægning', 'C1', 'da'),
('bæredygtig udvikling', 'C1', 'da'),
('Moderne innovation', 'C1', 'da'),
('Avanceret kreativitet', 'C1', 'da'),
('Ny opdagelse', 'C1', 'da'),
('Innovativ opfindelse', 'C1', 'da'),
('Økonomisk analyse', 'C1', 'da'),
('Finansiel rapport', 'C1', 'da'),
('Storskala projekt', 'C1', 'da'),
('Internationale forhandlinger', 'C1', 'da'),
('formel aftale', 'C1', 'da'),
('Effektiv strategi', 'C1', 'da'),
('Global institution', 'C1', 'da'),
('Forskningscenter', 'C1', 'da'),
('Avanceret videnskabelig undersøgelse', 'C1', 'da'),
('Kritisk gennemgang', 'C1', 'da'),
('filosofisk fortolkning', 'C1', 'da'),
('Systematisk tilgang', 'C1', 'da'),
('Moderne teori', 'C1', 'da'),
('Anvendt forskning', 'C1', 'da'),
('Praktisk eksperiment', 'C1', 'da'),
('objektiv evaluering', 'C1', 'da'),
('detaljerede resultater', 'C1', 'da'),
('Avanceret debat', 'C1', 'da'),
('Sammenlignende undersøgelse', 'C1', 'da'),
('Feltundersøgelser', 'C1', 'da'),
('Praktisk anbefaling', 'C1', 'da'),
('Avanceret dygtighed', 'C1', 'da'),
('Konceptuelle rammer', 'C1', 'da'),
('Præcis planlægning', 'C1', 'da'),
('Langsigtet strategi', 'C1', 'da'),
('risikovurdering', 'C1', 'da'),
('Akademisk gennemgang', 'C1', 'da'),
('Forskningsprojekt', 'C1', 'da'),
('Videnskabelig innovation', 'C1', 'da'),
('teknologisk udvikling', 'C1', 'da'),
('litterær analyse', 'C1', 'da'),
('videnskabelige fund', 'C1', 'da'),
('Avanceret fortolkning', 'C1', 'da'),
('Holistisk udsigt', 'C1', 'da'),
('Implementeringsplan', 'C1', 'da'),
('Strategisk beslutning', 'C1', 'da'),
('Ressourcestyring', 'C1', 'da'),
('komplekse udfordringer', 'C1', 'da'),
('innovative løsninger', 'C1', 'da'),
('omfattende tilgang', 'C1', 'da'),
('Dataanalyse', 'C1', 'da'),
('Hypotesetest', 'C1', 'da'),
('Casestudie', 'C1', 'da'),
('Avanceret feltarbejde', 'C1', 'da'),
('filosofisk gennemgang', 'C1', 'da'),
('Anvendt forskningsprojekt', 'C1', 'da'),
('Akademisk diskussion', 'C1', 'da'),
('Strategisk evaluering', 'C1', 'da'),
('Praktiske anbefalinger', 'C1', 'da'),
('Arbejdsplan', 'C1', 'da'),
('Projektstyring', 'C1', 'da'),
('Akademisk publikation', 'C1', 'da'),
('Videnskabelig opdagelse', 'C1', 'da'),
('Anvendt innovation', 'C1', 'da'),
('Kontinuerlig udvikling', 'C1', 'da'),
('dybdegående dataanalyse', 'C1', 'da'),
('Forskningsoplevelse', 'C1', 'da'),
('Videnskabelig fortolkning', 'C1', 'da'),
('Kritisk perspektiv', 'C1', 'da');
