INSERT INTO words (word, level, language_code) VALUES
('hus', 'A1', 'sv'),
('dörr', 'A1', 'sv'),
('fönster', 'A1', 'sv'),
('tabell', 'A1', 'sv'),
('stol', 'A1', 'sv'),
('boka', 'A1', 'sv'),
('penna', 'A1', 'sv'),
('skola', 'A1', 'sv'),
('lärare', 'A1', 'sv'),
('student', 'A1', 'sv'),
('äpple', 'A1', 'sv'),
('vatten', 'A1', 'sv'),
('mat', 'A1', 'sv'),
('bil', 'A1', 'sv'),
('buss', 'A1', 'sv'),
('gata', 'A1', 'sv'),
('vän', 'A1', 'sv'),
('familj', 'A1', 'sv'),
('mor', 'A1', 'sv'),
('far', 'A1', 'sv'),
('syster', 'A1', 'sv'),
('bror', 'A1', 'sv'),
('dag', 'A1', 'sv'),
('natt', 'A1', 'sv'),
('morgon', 'A1', 'sv'),
('kväll', 'A1', 'sv'),
('Hej', 'A1', 'sv'),
('adjö', 'A1', 'sv'),
('behaga', 'A1', 'sv'),
('tack', 'A1', 'sv'),
('ja', 'A1', 'sv'),
('inga', 'A1', 'sv'),
('röd', 'A1', 'sv'),
('blå', 'A1', 'sv'),
('grön', 'A1', 'sv'),
('vit', 'A1', 'sv'),
('svart', 'A1', 'sv'),
('små', 'A1', 'sv'),
('stor', 'A1', 'sv'),
('bra', 'A1', 'sv'),
('dålig', 'A1', 'sv'),
('varm', 'A1', 'sv'),
('kall', 'A1', 'sv'),
('kaffe', 'A1', 'sv'),
('te', 'A1', 'sv'),
('pengar', 'A1', 'sv'),
('arbete', 'A1', 'sv'),
('hem', 'A1', 'sv'),
('handla', 'A1', 'sv'),
('marknadsföra', 'A1', 'sv'),
('mat', 'A1', 'sv'),
('dryck', 'A1', 'sv'),
('stad', 'A1', 'sv'),
('parkera', 'A1', 'sv'),
('gata', 'A1', 'sv'),
('busshållplats', 'A1', 'sv'),
('tåg', 'A1', 'sv'),
('station', 'A1', 'sv'),
('hotell', 'A1', 'sv'),
('rum', 'A1', 'sv'),
('säng', 'A1', 'sv'),
('läkare', 'A1', 'sv'),
('sjukhus', 'A1', 'sv'),
('skola', 'A1', 'sv'),
('universitet', 'A1', 'sv'),
('dator', 'A1', 'sv'),
('telefon', 'A1', 'sv'),
('tv', 'A1', 'sv'),
('musik', 'A1', 'sv'),
('låt', 'A1', 'sv'),
('filma', 'A1', 'sv'),
('spel', 'A1', 'sv'),
('fotboll', 'A1', 'sv'),
('boll', 'A1', 'sv'),
('vatten', 'A1', 'sv'),
('regn', 'A1', 'sv'),
('sola', 'A1', 'sv'),
('sky', 'A1', 'sv'),
('träd', 'A1', 'sv'),
('blomma', 'A1', 'sv'),
('djur', 'A1', 'sv'),
('katt', 'A1', 'sv'),
('hund', 'A1', 'sv'),
('fågel', 'A1', 'sv'),
('fisk', 'A1', 'sv'),
('man', 'A1', 'sv'),
('kvinna', 'A1', 'sv'),
('barn', 'A1', 'sv'),
('personer', 'A1', 'sv'),
('gata', 'A1', 'sv'),
('plats', 'A1', 'sv'),
('tid', 'A1', 'sv'),
('år', 'A1', 'sv'),
('månad', 'A1', 'sv'),
('vecka', 'A1', 'sv'),
('i dag', 'A1', 'sv'),
('i morgon', 'A1', 'sv'),
('i går', 'A1', 'sv'),
('namn', 'A1', 'sv'),
('adress', 'A1', 'sv'),
('antal', 'A1', 'sv'),
('flygplats', 'A2', 'sv'),
('flyg', 'A2', 'sv'),
('biljett', 'A2', 'sv'),
('pass', 'A2', 'sv'),
('resa', 'A2', 'sv'),
('semester', 'A2', 'sv'),
('resa', 'A2', 'sv'),
('bagage', 'A2', 'sv'),
('station', 'A2', 'sv'),
('plattform', 'A2', 'sv'),
('restaurang', 'A2', 'sv'),
('kafé', 'A2', 'sv'),
('frukost', 'A2', 'sv'),
('lunch', 'A2', 'sv'),
('middag', 'A2', 'sv'),
('grönsaker', 'A2', 'sv'),
('frukt', 'A2', 'sv'),
('kött', 'A2', 'sv'),
('kyckling', 'A2', 'sv'),
('nötkött', 'A2', 'sv'),
('fisk', 'A2', 'sv'),
('bröd', 'A2', 'sv'),
('ris', 'A2', 'sv'),
('pasta', 'A2', 'sv'),
('soppa', 'A2', 'sv'),
('socker', 'A2', 'sv'),
('salt', 'A2', 'sv'),
('peppar', 'A2', 'sv'),
('olja', 'A2', 'sv'),
('shopping', 'A2', 'sv'),
('kläder', 'A2', 'sv'),
('skjorta', 'A2', 'sv'),
('byxor', 'A2', 'sv'),
('klä', 'A2', 'sv'),
('skor', 'A2', 'sv'),
('hatt', 'A2', 'sv'),
('jacka', 'A2', 'sv'),
('täcka', 'A2', 'sv'),
('väder', 'A2', 'sv'),
('snö', 'A2', 'sv'),
('vind', 'A2', 'sv'),
('storm', 'A2', 'sv'),
('hotell', 'A2', 'sv'),
('gäst', 'A2', 'sv'),
('service', 'A2', 'sv'),
('reception', 'A2', 'sv'),
('nyckel', 'A2', 'sv'),
('bokning', 'A2', 'sv'),
('strand', 'A2', 'sv'),
('hav', 'A2', 'sv'),
('simning', 'A2', 'sv'),
('slå samman', 'A2', 'sv'),
('fjäll', 'A2', 'sv'),
('by', 'A2', 'sv'),
('land', 'A2', 'sv'),
('språk', 'A2', 'sv'),
('utländsk', 'A2', 'sv'),
('examen', 'A2', 'sv'),
('testa', 'A2', 'sv'),
('läxa', 'A2', 'sv'),
('klassrum', 'A2', 'sv'),
('ämne', 'A2', 'sv'),
('matematik', 'A2', 'sv'),
('historia', 'A2', 'sv'),
('vetenskap', 'A2', 'sv'),
('bibliotek', 'A2', 'sv'),
('bokhandel', 'A2', 'sv'),
('dator', 'A2', 'sv'),
('internet', 'A2', 'sv'),
('e-post', 'A2', 'sv'),
('meddelande', 'A2', 'sv'),
('brev', 'A2', 'sv'),
('posta', 'A2', 'sv'),
('bank', 'A2', 'sv'),
('pengar', 'A2', 'sv'),
('kreditkort', 'A2', 'sv'),
('pris', 'A2', 'sv'),
('billig', 'A2', 'sv'),
('dyr', 'A2', 'sv'),
('fråga', 'A2', 'sv'),
('svar', 'A2', 'sv'),
('förklara', 'A2', 'sv'),
('hjälp', 'A2', 'sv'),
('problem', 'A2', 'sv'),
('lösning', 'A2', 'sv'),
('hälsa', 'A2', 'sv'),
('medicin', 'A2', 'sv'),
('läkare', 'A2', 'sv'),
('sjuksköterska', 'A2', 'sv'),
('patient', 'A2', 'sv'),
('utnämning', 'A2', 'sv'),
('feber', 'A2', 'sv'),
('hosta', 'A2', 'sv'),
('uppleva', 'B1', 'sv'),
('äventyr', 'B1', 'sv'),
('omdöme', 'B1', 'sv'),
('diskussion', 'B1', 'sv'),
('argument', 'B1', 'sv'),
('beslut', 'B1', 'sv'),
('resonera', 'B1', 'sv'),
('möjlighet', 'B1', 'sv'),
('utmaning', 'B1', 'sv'),
('framgång', 'B1', 'sv'),
('fel', 'B1', 'sv'),
('mål', 'B1', 'sv'),
('planera', 'B1', 'sv'),
('projekt', 'B1', 'sv'),
('kunskap', 'B1', 'sv'),
('skicklighet', 'B1', 'sv'),
('förmåga', 'B1', 'sv'),
('förbättring', 'B1', 'sv'),
('utbildning', 'B1', 'sv'),
('arbetsintervju', 'B1', 'sv'),
('ansökan', 'B1', 'sv'),
('karriär', 'B1', 'sv'),
('chef', 'B1', 'sv'),
('kollega', 'B1', 'sv'),
('möte', 'B1', 'sv'),
('uppgift', 'B1', 'sv'),
('ansvar', 'B1', 'sv'),
('semesterresa', 'B1', 'sv'),
('kultur', 'B1', 'sv'),
('tradition', 'B1', 'sv'),
('beställnings-', 'B1', 'sv'),
('festival', 'B1', 'sv'),
('firande', 'B1', 'sv'),
('prestanda', 'B1', 'sv'),
('konsert', 'B1', 'sv'),
('teater', 'B1', 'sv'),
('utställning', 'B1', 'sv'),
('målning', 'B1', 'sv'),
('skulptur', 'B1', 'sv'),
('museum', 'B1', 'sv'),
('historiebok', 'B1', 'sv'),
('fiktion', 'B1', 'sv'),
('dikt', 'B1', 'sv'),
('roman', 'B1', 'sv'),
('karaktär', 'B1', 'sv'),
('tomt', 'B1', 'sv'),
('berättelse', 'B1', 'sv'),
('tidning', 'B1', 'sv'),
('tidskrift', 'B1', 'sv'),
('artikel', 'B1', 'sv'),
('rapportera', 'B1', 'sv'),
('presentation', 'B1', 'sv'),
('föreläsning', 'B1', 'sv'),
('utbildning', 'B1', 'sv'),
('universitet', 'B1', 'sv'),
('grad', 'B1', 'sv'),
('diplom', 'B1', 'sv'),
('certifikat', 'B1', 'sv'),
('miljö', 'B1', 'sv'),
('natur', 'B1', 'sv'),
('återvinning', 'B1', 'sv'),
('föroreningar', 'B1', 'sv'),
('klimatförändring', 'B1', 'sv'),
('global uppvärmning', 'B1', 'sv'),
('energi', 'B1', 'sv'),
('teknologi', 'B1', 'sv'),
('innovation', 'B1', 'sv'),
('uppfinning', 'B1', 'sv'),
('anordning', 'B1', 'sv'),
('maskin', 'B1', 'sv'),
('datorprogram', 'B1', 'sv'),
('webbplats', 'B1', 'sv'),
('ansökan', 'B1', 'sv'),
('sociala medier', 'B1', 'sv'),
('kommunikation', 'B1', 'sv'),
('konversation', 'B1', 'sv'),
('interaktion', 'B1', 'sv'),
('relation', 'B1', 'sv'),
('vänskap', 'B1', 'sv'),
('äktenskap', 'B1', 'sv'),
('familjeliv', 'B1', 'sv'),
('lycka', 'B1', 'sv'),
('ilska', 'B1', 'sv'),
('rädsla', 'B1', 'sv'),
('hoppas', 'B1', 'sv'),
('dröm', 'B1', 'sv'),
('ambition', 'B1', 'sv'),
('motivering', 'B1', 'sv'),
('förtroende', 'B1', 'sv'),
('nyfikenhet', 'B1', 'sv'),
('tålamod', 'B1', 'sv'),
('innovation', 'B2', 'sv'),
('utveckling', 'B2', 'sv'),
('forskning', 'B2', 'sv'),
('analys', 'B2', 'sv'),
('tolkning', 'B2', 'sv'),
('argumentation', 'B2', 'sv'),
('jämförelse', 'B2', 'sv'),
('hypotes', 'B2', 'sv'),
('teori', 'B2', 'sv'),
('experimentera', 'B2', 'sv'),
('bevis', 'B2', 'sv'),
('metod', 'B2', 'sv'),
('slutsats', 'B2', 'sv'),
('observation', 'B2', 'sv'),
('perspektiv', 'B2', 'sv'),
('antagande', 'B2', 'sv'),
('sammanhang', 'B2', 'sv'),
('kriterier', 'B2', 'sv'),
('princip', 'B2', 'sv'),
('prioritet', 'B2', 'sv'),
('komplexitet', 'B2', 'sv'),
('effektivitet', 'B2', 'sv'),
('produktivitet', 'B2', 'sv'),
('investering', 'B2', 'sv'),
('ekonomi', 'B2', 'sv'),
('finansiera', 'B2', 'sv'),
('förhandling', 'B2', 'sv'),
('avtal', 'B2', 'sv'),
('kontrakt', 'B2', 'sv'),
('politik', 'B2', 'sv'),
('regering', 'B2', 'sv'),
('politik', 'B2', 'sv'),
('val', 'B2', 'sv'),
('demokrati', 'B2', 'sv'),
('frihet', 'B2', 'sv'),
('rättvisa', 'B2', 'sv'),
('jämställdhet', 'B2', 'sv'),
('lag', 'B2', 'sv'),
('brottslighet', 'B2', 'sv'),
('straff', 'B2', 'sv'),
('bestraffning', 'B2', 'sv'),
('säkerhet', 'B2', 'sv'),
('konflikt', 'B2', 'sv'),
('krig', 'B2', 'sv'),
('fred', 'B2', 'sv'),
('våld', 'B2', 'sv'),
('terrorism', 'B2', 'sv'),
('globalisering', 'B2', 'sv'),
('integration', 'B2', 'sv'),
('mångfald', 'B2', 'sv'),
('identitet', 'B2', 'sv'),
('migrering', 'B2', 'sv'),
('flykting', 'B2', 'sv'),
('gemenskap', 'B2', 'sv'),
('nätverk', 'B2', 'sv'),
('organisation', 'B2', 'sv'),
('institution', 'B2', 'sv'),
('ledarskap', 'B2', 'sv'),
('förvaltning', 'B2', 'sv'),
('planering', 'B2', 'sv'),
('strategi', 'B2', 'sv'),
('initiativ', 'B2', 'sv'),
('kreativitet', 'B2', 'sv'),
('samarbete', 'B2', 'sv'),
('grupparbete', 'B2', 'sv'),
('ansvar', 'B2', 'sv'),
('ansvarighet', 'B2', 'sv'),
('hållbarhet', 'B2', 'sv'),
('miljöskydd', 'B2', 'sv'),
('förnybar energi', 'B2', 'sv'),
('innovationsprocess', 'B2', 'sv'),
('kritiskt tänkande', 'B2', 'sv'),
('problemlösning', 'B2', 'sv'),
('beslutsfattande', 'B2', 'sv'),
('tidshantering', 'B2', 'sv'),
('självdisciplin', 'B2', 'sv'),
('anpassning', 'B2', 'sv'),
('elasticitet', 'B2', 'sv'),
('oberoende', 'B2', 'sv'),
('samarbete', 'B2', 'sv'),
('förtroende', 'B2', 'sv'),
('respektera', 'B2', 'sv'),
('empati', 'B2', 'sv'),
('lojalitet', 'B2', 'sv'),
('integritet', 'B2', 'sv'),
('etik', 'B2', 'sv'),
('moral', 'B2', 'sv'),
('filosofi', 'B2', 'sv'),
('psykologi', 'B2', 'sv'),
('sociologi', 'B2', 'sv'),
('biologi', 'B2', 'sv'),
('kemi', 'B2', 'sv'),
('fysik', 'B2', 'sv'),
('kritisk analys', 'C1', 'sv'),
('logiskt resonemang', 'C1', 'sv'),
('tolkning', 'C1', 'sv'),
('djup jämförelse', 'C1', 'sv'),
('vetenskaplig slutsats', 'C1', 'sv'),
('komplex hypotes', 'C1', 'sv'),
('avancerad teori', 'C1', 'sv'),
('djupgående experiment', 'C1', 'sv'),
('omfattande utvärdering', 'C1', 'sv'),
('filosofisk diskussion', 'C1', 'sv'),
('starkt argument', 'C1', 'sv'),
('materiella bevis', 'C1', 'sv'),
('motstridande bevis', 'C1', 'sv'),
('abstrakt begrepp', 'C1', 'sv'),
('etisk position', 'C1', 'sv'),
('högsta värde', 'C1', 'sv'),
('grundprincip', 'C1', 'sv'),
('högsta prioritet', 'C1', 'sv'),
('huvudansvar', 'C1', 'sv'),
('avgörande beslut', 'C1', 'sv'),
('komplexhantering', 'C1', 'sv'),
('strategisk planering', 'C1', 'sv'),
('hållbar utveckling', 'C1', 'sv'),
('modern innovation', 'C1', 'sv'),
('Avancerad kreativitet', 'C1', 'sv'),
('ny upptäckt', 'C1', 'sv'),
('innovativ uppfinning', 'C1', 'sv'),
('ekonomisk analys', 'C1', 'sv'),
('finansiell rapport', 'C1', 'sv'),
('storskaligt projekt', 'C1', 'sv'),
('internationella förhandlingar', 'C1', 'sv'),
('formellt avtal', 'C1', 'sv'),
('Effektiv strategi', 'C1', 'sv'),
('global institution', 'C1', 'sv'),
('forskningscentrum', 'C1', 'sv'),
('Avancerad vetenskaplig studie', 'C1', 'sv'),
('kritisk översyn', 'C1', 'sv'),
('filosofisk tolkning', 'C1', 'sv'),
('systematisk strategi', 'C1', 'sv'),
('modern teori', 'C1', 'sv'),
('tillämpad forskning', 'C1', 'sv'),
('praktiskt experiment', 'C1', 'sv'),
('objektiv utvärdering', 'C1', 'sv'),
('Detaljerade resultat', 'C1', 'sv'),
('avancerad debatt', 'C1', 'sv'),
('jämförande studie', 'C1', 'sv'),
('fältforskning', 'C1', 'sv'),
('praktisk rekommendation', 'C1', 'sv'),
('avancerad skicklighet', 'C1', 'sv'),
('konceptuell ram', 'C1', 'sv'),
('exakt planering', 'C1', 'sv'),
('långsiktig strategi', 'C1', 'sv'),
('riskbedömning', 'C1', 'sv'),
('akademisk översyn', 'C1', 'sv'),
('forskningsprojekt', 'C1', 'sv'),
('vetenskaplig innovation', 'C1', 'sv'),
('teknologisk utveckling', 'C1', 'sv'),
('litterär analys', 'C1', 'sv'),
('vetenskapliga resultat', 'C1', 'sv'),
('avancerad tolkning', 'C1', 'sv'),
('holistisk vy', 'C1', 'sv'),
('genomförandeplan', 'C1', 'sv'),
('strategiskt beslut', 'C1', 'sv'),
('resurshantering', 'C1', 'sv'),
('komplexa utmaningar', 'C1', 'sv'),
('innovativa lösningar', 'C1', 'sv'),
('omfattande strategi', 'C1', 'sv'),
('dataanalys', 'C1', 'sv'),
('hypotesstestning', 'C1', 'sv'),
('fallstudie', 'C1', 'sv'),
('avancerat fältarbete', 'C1', 'sv'),
('filosofisk översyn', 'C1', 'sv'),
('tillämpat forskningsprojekt', 'C1', 'sv'),
('akademisk diskussion', 'C1', 'sv'),
('strategisk utvärdering', 'C1', 'sv'),
('Praktiska rekommendationer', 'C1', 'sv'),
('arbetsplan', 'C1', 'sv'),
('projektledning', 'C1', 'sv'),
('akademisk publikation', 'C1', 'sv'),
('vetenskaplig upptäckt', 'C1', 'sv'),
('tillämpad innovation', 'C1', 'sv'),
('kontinuerlig utveckling', 'C1', 'sv'),
('djupgående dataanalys', 'C1', 'sv'),
('forskningsupplevelse', 'C1', 'sv'),
('vetenskaplig tolkning', 'C1', 'sv'),
('kritiskt perspektiv', 'C1', 'sv');
