INSERT INTO words (word, level, language_code) VALUES
('Haus', 'A1', 'de'),
('Tür', 'A1', 'de'),
('Fenster', 'A1', 'de'),
('Tisch', 'A1', 'de'),
('Stuhl', 'A1', 'de'),
('Buch', 'A1', 'de'),
('Stift', 'A1', 'de'),
('Schule', 'A1', 'de'),
('Lehrer', 'A1', 'de'),
('Student', 'A1', 'de'),
('Apfel', 'A1', 'de'),
('Wasser', 'A1', 'de'),
('Essen', 'A1', 'de'),
('Auto', 'A1', 'de'),
('Bus', 'A1', 'de'),
('Straße', 'A1', 'de'),
('Freund', 'A1', 'de'),
('Familie', 'A1', 'de'),
('Mutter', 'A1', 'de'),
('Vater', 'A1', 'de'),
('Schwester', 'A1', 'de'),
('Bruder', 'A1', 'de'),
('Tag', 'A1', 'de'),
('Nacht', 'A1', 'de'),
('Morgen', 'A1', 'de'),
('Abend', 'A1', 'de'),
('Hallo', 'A1', 'de'),
('Verabschiedung', 'A1', 'de'),
('Bitte', 'A1', 'de'),
('Danke', 'A1', 'de'),
('Ja', 'A1', 'de'),
('NEIN', 'A1', 'de'),
('Rot', 'A1', 'de'),
('Blau', 'A1', 'de'),
('Grün', 'A1', 'de'),
('Weiß', 'A1', 'de'),
('Schwarz', 'A1', 'de'),
('klein', 'A1', 'de'),
('groß', 'A1', 'de'),
('Gut', 'A1', 'de'),
('schlecht', 'A1', 'de'),
('heiß', 'A1', 'de'),
('kalt', 'A1', 'de'),
('Kaffee', 'A1', 'de'),
('Tee', 'A1', 'de'),
('Geld', 'A1', 'de'),
('arbeiten', 'A1', 'de'),
('heim', 'A1', 'de'),
('Geschäft', 'A1', 'de'),
('Markt', 'A1', 'de'),
('Essen', 'A1', 'de'),
('trinken', 'A1', 'de'),
('Stadt', 'A1', 'de'),
('Park', 'A1', 'de'),
('Straße', 'A1', 'de'),
('Bushaltestelle', 'A1', 'de'),
('Zug', 'A1', 'de'),
('Station', 'A1', 'de'),
('Hotel', 'A1', 'de'),
('Zimmer', 'A1', 'de'),
('Bett', 'A1', 'de'),
('Arzt', 'A1', 'de'),
('Krankenhaus', 'A1', 'de'),
('Schule', 'A1', 'de'),
('Universität', 'A1', 'de'),
('Computer', 'A1', 'de'),
('Telefon', 'A1', 'de'),
('Fernsehen', 'A1', 'de'),
('Musik', 'A1', 'de'),
('Lied', 'A1', 'de'),
('Film', 'A1', 'de'),
('Spiel', 'A1', 'de'),
('Fußball', 'A1', 'de'),
('Ball', 'A1', 'de'),
('Wasser', 'A1', 'de'),
('Regen', 'A1', 'de'),
('Sonne', 'A1', 'de'),
('Himmel', 'A1', 'de'),
('Baum', 'A1', 'de'),
('Blume', 'A1', 'de'),
('Tier', 'A1', 'de'),
('Katze', 'A1', 'de'),
('Hund', 'A1', 'de'),
('Vogel', 'A1', 'de'),
('Fisch', 'A1', 'de'),
('Mann', 'A1', 'de'),
('Frau', 'A1', 'de'),
('Kind', 'A1', 'de'),
('Menschen', 'A1', 'de'),
('Straße', 'A1', 'de'),
('Ort', 'A1', 'de'),
('Zeit', 'A1', 'de'),
('Jahr', 'A1', 'de'),
('Monat', 'A1', 'de'),
('Woche', 'A1', 'de'),
('Heute', 'A1', 'de'),
('morgen', 'A1', 'de'),
('gestern', 'A1', 'de'),
('Name', 'A1', 'de'),
('Adresse', 'A1', 'de'),
('Nummer', 'A1', 'de'),
('Flughafen', 'A2', 'de'),
('Flug', 'A2', 'de'),
('Ticket', 'A2', 'de'),
('Reisepass', 'A2', 'de'),
('reisen', 'A2', 'de'),
('Urlaub', 'A2', 'de'),
('Reise', 'A2', 'de'),
('Gepäck', 'A2', 'de'),
('Station', 'A2', 'de'),
('Plattform', 'A2', 'de'),
('Restaurant', 'A2', 'de'),
('Cafe', 'A2', 'de'),
('Frühstück', 'A2', 'de'),
('Mittagessen', 'A2', 'de'),
('Abendessen', 'A2', 'de'),
('Gemüse', 'A2', 'de'),
('Obst', 'A2', 'de'),
('Fleisch', 'A2', 'de'),
('Huhn', 'A2', 'de'),
('Rindfleisch', 'A2', 'de'),
('Fisch', 'A2', 'de'),
('brot', 'A2', 'de'),
('Reis', 'A2', 'de'),
('Pasta', 'A2', 'de'),
('Suppe', 'A2', 'de'),
('Zucker', 'A2', 'de'),
('Salz', 'A2', 'de'),
('Pfeffer', 'A2', 'de'),
('Öl', 'A2', 'de'),
('Einkaufen', 'A2', 'de'),
('Kleidung', 'A2', 'de'),
('Hemd', 'A2', 'de'),
('Hose', 'A2', 'de'),
('Kleid', 'A2', 'de'),
('Schuhe', 'A2', 'de'),
('Hut', 'A2', 'de'),
('Jacke', 'A2', 'de'),
('Mantel', 'A2', 'de'),
('Wetter', 'A2', 'de'),
('Schnee', 'A2', 'de'),
('Wind', 'A2', 'de'),
('Sturm', 'A2', 'de'),
('Hotels', 'A2', 'de'),
('Gast', 'A2', 'de'),
('Service', 'A2', 'de'),
('Rezeption', 'A2', 'de'),
('Schlüssel', 'A2', 'de'),
('Reservierung', 'A2', 'de'),
('Strand', 'A2', 'de'),
('Meer', 'A2', 'de'),
('Baden', 'A2', 'de'),
('Pool', 'A2', 'de'),
('Berg', 'A2', 'de'),
('Dorf', 'A2', 'de'),
('Land', 'A2', 'de'),
('Sprache', 'A2', 'de'),
('ausländisch', 'A2', 'de'),
('Prüfung', 'A2', 'de'),
('prüfen', 'A2', 'de'),
('Hausaufgaben', 'A2', 'de'),
('Klassenzimmer', 'A2', 'de'),
('Thema', 'A2', 'de'),
('Mathe', 'A2', 'de'),
('Geschichte', 'A2', 'de'),
('Wissenschaft', 'A2', 'de'),
('Bibliothek', 'A2', 'de'),
('Buchhandlung', 'A2', 'de'),
('Computer', 'A2', 'de'),
('Internet', 'A2', 'de'),
('E-Mail', 'A2', 'de'),
('Nachricht', 'A2', 'de'),
('Brief', 'A2', 'de'),
('Post', 'A2', 'de'),
('Bank', 'A2', 'de'),
('Geld', 'A2', 'de'),
('Kreditkarte', 'A2', 'de'),
('Preis', 'A2', 'de'),
('billig', 'A2', 'de'),
('teuer', 'A2', 'de'),
('Frage', 'A2', 'de'),
('Antwort', 'A2', 'de'),
('erklären', 'A2', 'de'),
('helfen', 'A2', 'de'),
('Problem', 'A2', 'de'),
('Lösung', 'A2', 'de'),
('Gesundheit', 'A2', 'de'),
('Medizin', 'A2', 'de'),
('Arzt', 'A2', 'de'),
('Krankenschwester', 'A2', 'de'),
('geduldig', 'A2', 'de'),
('Termin', 'A2', 'de'),
('Fieber', 'A2', 'de'),
('Husten', 'A2', 'de'),
('Erfahrung', 'B1', 'de'),
('Abenteuer', 'B1', 'de'),
('Meinung', 'B1', 'de'),
('Diskussion', 'B1', 'de'),
('Argument', 'B1', 'de'),
('Entscheidung', 'B1', 'de'),
('Grund', 'B1', 'de'),
('Gelegenheit', 'B1', 'de'),
('Herausforderung', 'B1', 'de'),
('Erfolg', 'B1', 'de'),
('Versagen', 'B1', 'de'),
('Ziel', 'B1', 'de'),
('planen', 'B1', 'de'),
('Projekt', 'B1', 'de'),
('Wissen', 'B1', 'de'),
('Fähigkeit', 'B1', 'de'),
('Fähigkeit', 'B1', 'de'),
('Verbesserung', 'B1', 'de'),
('Ausbildung', 'B1', 'de'),
('Vorstellungsgespräch', 'B1', 'de'),
('Anwendung', 'B1', 'de'),
('Karriere', 'B1', 'de'),
('Manager', 'B1', 'de'),
('Kollege', 'B1', 'de'),
('treffen', 'B1', 'de'),
('Aufgabe', 'B1', 'de'),
('Verantwortung', 'B1', 'de'),
('Urlaubsreise', 'B1', 'de'),
('Kultur', 'B1', 'de'),
('Tradition', 'B1', 'de'),
('Brauch', 'B1', 'de'),
('Festival', 'B1', 'de'),
('Feier', 'B1', 'de'),
('Leistung', 'B1', 'de'),
('Konzert', 'B1', 'de'),
('Theater', 'B1', 'de'),
('Ausstellung', 'B1', 'de'),
('Malerei', 'B1', 'de'),
('Skulptur', 'B1', 'de'),
('Museum', 'B1', 'de'),
('Geschichtsbuch', 'B1', 'de'),
('Fiktion', 'B1', 'de'),
('Gedicht', 'B1', 'de'),
('Roman', 'B1', 'de'),
('Charakter', 'B1', 'de'),
('Handlung', 'B1', 'de'),
('Geschichte', 'B1', 'de'),
('Zeitung', 'B1', 'de'),
('Magazin', 'B1', 'de'),
('Artikel', 'B1', 'de'),
('Bericht', 'B1', 'de'),
('Präsentation', 'B1', 'de'),
('Vortrag', 'B1', 'de'),
('Ausbildung', 'B1', 'de'),
('Universität', 'B1', 'de'),
('Grad', 'B1', 'de'),
('Diplom', 'B1', 'de'),
('Zertifikat', 'B1', 'de'),
('Umfeld', 'B1', 'de'),
('Natur', 'B1', 'de'),
('Recycling', 'B1', 'de'),
('Verschmutzung', 'B1', 'de'),
('Klimawandel', 'B1', 'de'),
('globale Erwärmung', 'B1', 'de'),
('Energie', 'B1', 'de'),
('Technologie', 'B1', 'de'),
('Innovation', 'B1', 'de'),
('Erfindung', 'B1', 'de'),
('Gerät', 'B1', 'de'),
('Maschine', 'B1', 'de'),
('Computerprogramm', 'B1', 'de'),
('Webseite', 'B1', 'de'),
('Anwendung', 'B1', 'de'),
('Social Media', 'B1', 'de'),
('Kommunikation', 'B1', 'de'),
('Gespräch', 'B1', 'de'),
('Interaktion', 'B1', 'de'),
('Beziehung', 'B1', 'de'),
('Freundschaft', 'B1', 'de'),
('Hochzeit', 'B1', 'de'),
('Familienleben', 'B1', 'de'),
('Glück', 'B1', 'de'),
('Wut', 'B1', 'de'),
('Furcht', 'B1', 'de'),
('Hoffnung', 'B1', 'de'),
('Traum', 'B1', 'de'),
('Ehrgeiz', 'B1', 'de'),
('Motivation', 'B1', 'de'),
('Vertrauen', 'B1', 'de'),
('Neugier', 'B1', 'de'),
('Geduld', 'B1', 'de'),
('Innovation', 'B2', 'de'),
('Entwicklung', 'B2', 'de'),
('Forschung', 'B2', 'de'),
('Analyse', 'B2', 'de'),
('Interpretation', 'B2', 'de'),
('Argumentation', 'B2', 'de'),
('Vergleich', 'B2', 'de'),
('Hypothese', 'B2', 'de'),
('Theorie', 'B2', 'de'),
('Experiment', 'B2', 'de'),
('Beweis', 'B2', 'de'),
('Verfahren', 'B2', 'de'),
('Abschluss', 'B2', 'de'),
('Beobachtung', 'B2', 'de'),
('Perspektive', 'B2', 'de'),
('Annahme', 'B2', 'de'),
('Kontext', 'B2', 'de'),
('Kriterien', 'B2', 'de'),
('Prinzip', 'B2', 'de'),
('Priorität', 'B2', 'de'),
('Komplexität', 'B2', 'de'),
('Effizienz', 'B2', 'de'),
('Produktivität', 'B2', 'de'),
('Investition', 'B2', 'de'),
('Wirtschaft', 'B2', 'de'),
('Finanzen', 'B2', 'de'),
('Verhandlung', 'B2', 'de'),
('Vereinbarung', 'B2', 'de'),
('Vertrag', 'B2', 'de'),
('Politik', 'B2', 'de'),
('Regierung', 'B2', 'de'),
('Politik', 'B2', 'de'),
('Wahl', 'B2', 'de'),
('Demokratie', 'B2', 'de'),
('Freiheit', 'B2', 'de'),
('Gerechtigkeit', 'B2', 'de'),
('Gleichwertigkeit', 'B2', 'de'),
('Gesetz', 'B2', 'de'),
('Verbrechen', 'B2', 'de'),
('Strafe', 'B2', 'de'),
('Bestrafung', 'B2', 'de'),
('Sicherheit', 'B2', 'de'),
('Konflikt', 'B2', 'de'),
('Krieg', 'B2', 'de'),
('Frieden', 'B2', 'de'),
('Gewalt', 'B2', 'de'),
('Terrorismus', 'B2', 'de'),
('Globalisierung', 'B2', 'de'),
('Integration', 'B2', 'de'),
('Diversität', 'B2', 'de'),
('Identität', 'B2', 'de'),
('Migration', 'B2', 'de'),
('Flüchtling', 'B2', 'de'),
('Gemeinschaft', 'B2', 'de'),
('Netzwerk', 'B2', 'de'),
('Organisation', 'B2', 'de'),
('Institution', 'B2', 'de'),
('Führung', 'B2', 'de'),
('Management', 'B2', 'de'),
('Planung', 'B2', 'de'),
('Strategie', 'B2', 'de'),
('Initiative', 'B2', 'de'),
('Kreativität', 'B2', 'de'),
('Zusammenarbeit', 'B2', 'de'),
('Teamarbeit', 'B2', 'de'),
('Verantwortung', 'B2', 'de'),
('Rechenschaftspflicht', 'B2', 'de'),
('Nachhaltigkeit', 'B2', 'de'),
('Umweltschutz', 'B2', 'de'),
('erneuerbare Energie', 'B2', 'de'),
('Innovationsprozess', 'B2', 'de'),
('kritisches Denken', 'B2', 'de'),
('Problemlösung', 'B2', 'de'),
('Entscheidungsfindung', 'B2', 'de'),
('Zeitmanagement', 'B2', 'de'),
('Selbstdisziplin', 'B2', 'de'),
('Anpassung', 'B2', 'de'),
('Widerstandsfähigkeit', 'B2', 'de'),
('Unabhängigkeit', 'B2', 'de'),
('Zusammenarbeit', 'B2', 'de'),
('Vertrauen', 'B2', 'de'),
('respektieren', 'B2', 'de'),
('Empathie', 'B2', 'de'),
('Loyalität', 'B2', 'de'),
('Integrität', 'B2', 'de'),
('Ethik', 'B2', 'de'),
('Moral', 'B2', 'de'),
('Philosophie', 'B2', 'de'),
('Psychologie', 'B2', 'de'),
('Soziologie', 'B2', 'de'),
('Biologie', 'B2', 'de'),
('Chemie', 'B2', 'de'),
('Physik', 'B2', 'de'),
('Kritische Analyse', 'C1', 'de'),
('logische Argumentation', 'C1', 'de'),
('Interpretation', 'C1', 'de'),
('Tiefer Vergleich', 'C1', 'de'),
('Wissenschaftliche Schlussfolgerung', 'C1', 'de'),
('Komplexe Hypothese', 'C1', 'de'),
('Fortgeschrittene Theorie', 'C1', 'de'),
('eingehendes Experiment', 'C1', 'de'),
('umfassende Bewertung', 'C1', 'de'),
('Philosophische Diskussion', 'C1', 'de'),
('starkes Argument', 'C1', 'de'),
('Greifbare Beweise', 'C1', 'de'),
('widersprüchliche Beweise', 'C1', 'de'),
('Zusammenfassung Konzept', 'C1', 'de'),
('Ethische Position', 'C1', 'de'),
('höchster Wert', 'C1', 'de'),
('Grundprinzip', 'C1', 'de'),
('oberste Priorität', 'C1', 'de'),
('Hauptverantwortung', 'C1', 'de'),
('entscheidende Entscheidung', 'C1', 'de'),
('Komplexes Management', 'C1', 'de'),
('Strategische Planung', 'C1', 'de'),
('nachhaltige Entwicklung', 'C1', 'de'),
('Moderne Innovation', 'C1', 'de'),
('Erweiterte Kreativität', 'C1', 'de'),
('Neue Entdeckung', 'C1', 'de'),
('innovative Erfindung', 'C1', 'de'),
('Wirtschaftsanalyse', 'C1', 'de'),
('Finanzbericht', 'C1', 'de'),
('Großes Projekt', 'C1', 'de'),
('internationale Verhandlungen', 'C1', 'de'),
('formelle Vereinbarung', 'C1', 'de'),
('Effektive Strategie', 'C1', 'de'),
('Globale Institution', 'C1', 'de'),
('Forschungszentrum', 'C1', 'de'),
('Fortgeschrittene wissenschaftliche Studie', 'C1', 'de'),
('Kritische Überprüfung', 'C1', 'de'),
('Philosophische Interpretation', 'C1', 'de'),
('systematischer Ansatz', 'C1', 'de'),
('Moderne Theorie', 'C1', 'de'),
('Angewandte Forschung', 'C1', 'de'),
('Praktisches Experiment', 'C1', 'de'),
('objektive Bewertung', 'C1', 'de'),
('detaillierte Ergebnisse', 'C1', 'de'),
('Erweiterte Debatte', 'C1', 'de'),
('Vergleichende Studie', 'C1', 'de'),
('Feldforschung', 'C1', 'de'),
('Praktische Empfehlung', 'C1', 'de'),
('Fortgeschrittene Fähigkeiten', 'C1', 'de'),
('konzeptioneller Rahmen', 'C1', 'de'),
('präzise Planung', 'C1', 'de'),
('langfristige Strategie', 'C1', 'de'),
('Risikobewertung', 'C1', 'de'),
('Akademische Überprüfung', 'C1', 'de'),
('Forschungsprojekt', 'C1', 'de'),
('Wissenschaftliche Innovation', 'C1', 'de'),
('technologische Entwicklung', 'C1', 'de'),
('Literaturanalyse', 'C1', 'de'),
('Wissenschaftliche Erkenntnisse', 'C1', 'de'),
('Erweiterte Interpretation', 'C1', 'de'),
('Ganzheitliche Sichtweise', 'C1', 'de'),
('Implementierungsplan', 'C1', 'de'),
('Strategische Entscheidung', 'C1', 'de'),
('Ressourcenmanagement', 'C1', 'de'),
('Komplexe Herausforderungen', 'C1', 'de'),
('innovative Lösungen', 'C1', 'de'),
('Umfassender Ansatz', 'C1', 'de'),
('Datenanalyse', 'C1', 'de'),
('Hypothesentest', 'C1', 'de'),
('Fallstudie', 'C1', 'de'),
('Erweiterte Feldarbeit', 'C1', 'de'),
('Philosophische Bewertung', 'C1', 'de'),
('Angewandter Forschungsprojekt', 'C1', 'de'),
('akademische Diskussion', 'C1', 'de'),
('Strategische Bewertung', 'C1', 'de'),
('Praktische Empfehlungen', 'C1', 'de'),
('Arbeitsplan', 'C1', 'de'),
('Projektmanagement', 'C1', 'de'),
('Akademische Veröffentlichung', 'C1', 'de'),
('Wissenschaftliche Entdeckung', 'C1', 'de'),
('Angewandte Innovation', 'C1', 'de'),
('kontinuierliche Entwicklung', 'C1', 'de'),
('Eingehende Datenanalyse', 'C1', 'de'),
('Forschungserfahrung', 'C1', 'de'),
('wissenschaftliche Interpretation', 'C1', 'de'),
('kritische Perspektive', 'C1', 'de');
