INSERT INTO words (word, level, language_code) VALUES
('maison', 'A1', 'fr'),
('porte', 'A1', 'fr'),
('fenêtre', 'A1', 'fr'),
('tableau', 'A1', 'fr'),
('chaise', 'A1', 'fr'),
('livre', 'A1', 'fr'),
('stylo', 'A1', 'fr'),
('école', 'A1', 'fr'),
('professeur', 'A1', 'fr'),
('étudiant', 'A1', 'fr'),
('pomme', 'A1', 'fr'),
('eau', 'A1', 'fr'),
('nourriture', 'A1', 'fr'),
('voiture', 'A1', 'fr'),
('bus', 'A1', 'fr'),
('rue', 'A1', 'fr'),
('ami', 'A1', 'fr'),
('famille', 'A1', 'fr'),
('mère', 'A1', 'fr'),
('père', 'A1', 'fr'),
('sœur', 'A1', 'fr'),
('frère', 'A1', 'fr'),
('jour', 'A1', 'fr'),
('nuit', 'A1', 'fr'),
('matin', 'A1', 'fr'),
('soirée', 'A1', 'fr'),
('Bonjour', 'A1', 'fr'),
('au revoir', 'A1', 'fr'),
('s''il te plaît', 'A1', 'fr'),
('merci', 'A1', 'fr'),
('Oui', 'A1', 'fr'),
('Non', 'A1', 'fr'),
('rouge', 'A1', 'fr'),
('bleu', 'A1', 'fr'),
('vert', 'A1', 'fr'),
('blanc', 'A1', 'fr'),
('noir', 'A1', 'fr'),
('petit', 'A1', 'fr'),
('grand', 'A1', 'fr'),
('bien', 'A1', 'fr'),
('mauvais', 'A1', 'fr'),
('chaud', 'A1', 'fr'),
('froid', 'A1', 'fr'),
('café', 'A1', 'fr'),
('thé', 'A1', 'fr'),
('argent', 'A1', 'fr'),
('travail', 'A1', 'fr'),
('maison', 'A1', 'fr'),
('boutique', 'A1', 'fr'),
('marché', 'A1', 'fr'),
('nourriture', 'A1', 'fr'),
('boire', 'A1', 'fr'),
('ville', 'A1', 'fr'),
('parc', 'A1', 'fr'),
('rue', 'A1', 'fr'),
('arrêt de bus', 'A1', 'fr'),
('former', 'A1', 'fr'),
('gare', 'A1', 'fr'),
('hôtel', 'A1', 'fr'),
('chambre', 'A1', 'fr'),
('lit', 'A1', 'fr'),
('médecin', 'A1', 'fr'),
('hôpital', 'A1', 'fr'),
('école', 'A1', 'fr'),
('université', 'A1', 'fr'),
('ordinateur', 'A1', 'fr'),
('téléphone', 'A1', 'fr'),
('télévision', 'A1', 'fr'),
('musique', 'A1', 'fr'),
('chanson', 'A1', 'fr'),
('film', 'A1', 'fr'),
('jeu', 'A1', 'fr'),
('football', 'A1', 'fr'),
('balle', 'A1', 'fr'),
('eau', 'A1', 'fr'),
('pluie', 'A1', 'fr'),
('soleil', 'A1', 'fr'),
('ciel', 'A1', 'fr'),
('arbre', 'A1', 'fr'),
('fleur', 'A1', 'fr'),
('animal', 'A1', 'fr'),
('chat', 'A1', 'fr'),
('chien', 'A1', 'fr'),
('oiseau', 'A1', 'fr'),
('poisson', 'A1', 'fr'),
('homme', 'A1', 'fr'),
('femme', 'A1', 'fr'),
('enfant', 'A1', 'fr'),
('personnes', 'A1', 'fr'),
('rue', 'A1', 'fr'),
('lieu', 'A1', 'fr'),
('temps', 'A1', 'fr'),
('année', 'A1', 'fr'),
('mois', 'A1', 'fr'),
('semaine', 'A1', 'fr'),
('aujourd''hui', 'A1', 'fr'),
('demain', 'A1', 'fr'),
('hier', 'A1', 'fr'),
('nom', 'A1', 'fr'),
('adresse', 'A1', 'fr'),
('nombre', 'A1', 'fr'),
('aéroport', 'A2', 'fr'),
('vol', 'A2', 'fr'),
('billet', 'A2', 'fr'),
('passeport', 'A2', 'fr'),
('voyage', 'A2', 'fr'),
('vacances', 'A2', 'fr'),
('voyage', 'A2', 'fr'),
('bagage', 'A2', 'fr'),
('gare', 'A2', 'fr'),
('plate-forme', 'A2', 'fr'),
('restaurant', 'A2', 'fr'),
('café', 'A2', 'fr'),
('petit-déjeuner', 'A2', 'fr'),
('déjeuner', 'A2', 'fr'),
('dîner', 'A2', 'fr'),
('légumes', 'A2', 'fr'),
('fruit', 'A2', 'fr'),
('viande', 'A2', 'fr'),
('poulet', 'A2', 'fr'),
('bœuf', 'A2', 'fr'),
('poisson', 'A2', 'fr'),
('pain', 'A2', 'fr'),
('riz', 'A2', 'fr'),
('pâtes', 'A2', 'fr'),
('soupe', 'A2', 'fr'),
('sucre', 'A2', 'fr'),
('sel', 'A2', 'fr'),
('poivre', 'A2', 'fr'),
('huile', 'A2', 'fr'),
('achats', 'A2', 'fr'),
('vêtements', 'A2', 'fr'),
('chemise', 'A2', 'fr'),
('pantalon', 'A2', 'fr'),
('robe', 'A2', 'fr'),
('chaussures', 'A2', 'fr'),
('chapeau', 'A2', 'fr'),
('veste', 'A2', 'fr'),
('manteau', 'A2', 'fr'),
('météo', 'A2', 'fr'),
('neige', 'A2', 'fr'),
('vent', 'A2', 'fr'),
('tempête', 'A2', 'fr'),
('hôtels', 'A2', 'fr'),
('invité', 'A2', 'fr'),
('service', 'A2', 'fr'),
('réception', 'A2', 'fr'),
('clé', 'A2', 'fr'),
('réservation', 'A2', 'fr'),
('plage', 'A2', 'fr'),
('mer', 'A2', 'fr'),
('natation', 'A2', 'fr'),
('piscine', 'A2', 'fr'),
('montagne', 'A2', 'fr'),
('village', 'A2', 'fr'),
('pays', 'A2', 'fr'),
('langue', 'A2', 'fr'),
('étranger', 'A2', 'fr'),
('examen', 'A2', 'fr'),
('test', 'A2', 'fr'),
('devoirs', 'A2', 'fr'),
('classe', 'A2', 'fr'),
('sujet', 'A2', 'fr'),
('mathématiques', 'A2', 'fr'),
('histoire', 'A2', 'fr'),
('science', 'A2', 'fr'),
('bibliothèque', 'A2', 'fr'),
('librairie', 'A2', 'fr'),
('ordinateur', 'A2', 'fr'),
('Internet', 'A2', 'fr'),
('e-mail', 'A2', 'fr'),
('message', 'A2', 'fr'),
('lettre', 'A2', 'fr'),
('poste', 'A2', 'fr'),
('banque', 'A2', 'fr'),
('argent', 'A2', 'fr'),
('carte de crédit', 'A2', 'fr'),
('prix', 'A2', 'fr'),
('bon marché', 'A2', 'fr'),
('cher', 'A2', 'fr'),
('question', 'A2', 'fr'),
('répondre', 'A2', 'fr'),
('expliquer', 'A2', 'fr'),
('aide', 'A2', 'fr'),
('problème', 'A2', 'fr'),
('solution', 'A2', 'fr'),
('santé', 'A2', 'fr'),
('médecine', 'A2', 'fr'),
('médecin', 'A2', 'fr'),
('infirmière', 'A2', 'fr'),
('patient', 'A2', 'fr'),
('rendez-vous', 'A2', 'fr'),
('fièvre', 'A2', 'fr'),
('toux', 'A2', 'fr'),
('expérience', 'B1', 'fr'),
('aventure', 'B1', 'fr'),
('avis', 'B1', 'fr'),
('discussion', 'B1', 'fr'),
('argument', 'B1', 'fr'),
('décision', 'B1', 'fr'),
('raison', 'B1', 'fr'),
('opportunité', 'B1', 'fr'),
('défi', 'B1', 'fr'),
('succès', 'B1', 'fr'),
('échec', 'B1', 'fr'),
('but', 'B1', 'fr'),
('plan', 'B1', 'fr'),
('projet', 'B1', 'fr'),
('connaissance', 'B1', 'fr'),
('compétence', 'B1', 'fr'),
('capacité', 'B1', 'fr'),
('amélioration', 'B1', 'fr'),
('entraînement', 'B1', 'fr'),
('entretien d''embauche', 'B1', 'fr'),
('application', 'B1', 'fr'),
('carrière', 'B1', 'fr'),
('directeur', 'B1', 'fr'),
('collègue', 'B1', 'fr'),
('réunion', 'B1', 'fr'),
('tâche', 'B1', 'fr'),
('responsabilité', 'B1', 'fr'),
('voyage de vacances', 'B1', 'fr'),
('culture', 'B1', 'fr'),
('tradition', 'B1', 'fr'),
('coutume', 'B1', 'fr'),
('festival', 'B1', 'fr'),
('célébration', 'B1', 'fr'),
('performance', 'B1', 'fr'),
('concert', 'B1', 'fr'),
('théâtre', 'B1', 'fr'),
('exposition', 'B1', 'fr'),
('peinture', 'B1', 'fr'),
('sculpture', 'B1', 'fr'),
('musée', 'B1', 'fr'),
('livre d''histoire', 'B1', 'fr'),
('fiction', 'B1', 'fr'),
('poème', 'B1', 'fr'),
('roman', 'B1', 'fr'),
('personnage', 'B1', 'fr'),
('parcelle', 'B1', 'fr'),
('histoire', 'B1', 'fr'),
('journal', 'B1', 'fr'),
('revue', 'B1', 'fr'),
('article', 'B1', 'fr'),
('rapport', 'B1', 'fr'),
('présentation', 'B1', 'fr'),
('conférence', 'B1', 'fr'),
('éducation', 'B1', 'fr'),
('université', 'B1', 'fr'),
('degré', 'B1', 'fr'),
('diplôme', 'B1', 'fr'),
('certificat', 'B1', 'fr'),
('environnement', 'B1', 'fr'),
('nature', 'B1', 'fr'),
('recyclage', 'B1', 'fr'),
('pollution', 'B1', 'fr'),
('changement climatique', 'B1', 'fr'),
('réchauffement climatique', 'B1', 'fr'),
('énergie', 'B1', 'fr'),
('technologie', 'B1', 'fr'),
('innovation', 'B1', 'fr'),
('invention', 'B1', 'fr'),
('appareil', 'B1', 'fr'),
('machine', 'B1', 'fr'),
('programme informatique', 'B1', 'fr'),
('site web', 'B1', 'fr'),
('application', 'B1', 'fr'),
('réseaux sociaux', 'B1', 'fr'),
('communication', 'B1', 'fr'),
('conversation', 'B1', 'fr'),
('interaction', 'B1', 'fr'),
('relation', 'B1', 'fr'),
('amitié', 'B1', 'fr'),
('mariage', 'B1', 'fr'),
('vie de famille', 'B1', 'fr'),
('bonheur', 'B1', 'fr'),
('colère', 'B1', 'fr'),
('peur', 'B1', 'fr'),
('espoir', 'B1', 'fr'),
('rêve', 'B1', 'fr'),
('ambition', 'B1', 'fr'),
('motivation', 'B1', 'fr'),
('confiance', 'B1', 'fr'),
('curiosité', 'B1', 'fr'),
('patience', 'B1', 'fr'),
('innovation', 'B2', 'fr'),
('développement', 'B2', 'fr'),
('recherche', 'B2', 'fr'),
('analyse', 'B2', 'fr'),
('interprétation', 'B2', 'fr'),
('argumentation', 'B2', 'fr'),
('comparaison', 'B2', 'fr'),
('hypothèse', 'B2', 'fr'),
('théorie', 'B2', 'fr'),
('expérience', 'B2', 'fr'),
('preuve', 'B2', 'fr'),
('méthode', 'B2', 'fr'),
('conclusion', 'B2', 'fr'),
('observation', 'B2', 'fr'),
('perspective', 'B2', 'fr'),
('hypothèse', 'B2', 'fr'),
('contexte', 'B2', 'fr'),
('critères', 'B2', 'fr'),
('principe', 'B2', 'fr'),
('priorité', 'B2', 'fr'),
('complexité', 'B2', 'fr'),
('efficacité', 'B2', 'fr'),
('productivité', 'B2', 'fr'),
('investissement', 'B2', 'fr'),
('économie', 'B2', 'fr'),
('finance', 'B2', 'fr'),
('négociation', 'B2', 'fr'),
('accord', 'B2', 'fr'),
('contracter', 'B2', 'fr'),
('politique', 'B2', 'fr'),
('gouvernement', 'B2', 'fr'),
('politique', 'B2', 'fr'),
('élection', 'B2', 'fr'),
('démocratie', 'B2', 'fr'),
('liberté', 'B2', 'fr'),
('justice', 'B2', 'fr'),
('égalité', 'B2', 'fr'),
('loi', 'B2', 'fr'),
('crime', 'B2', 'fr'),
('peine', 'B2', 'fr'),
('punition', 'B2', 'fr'),
('sécurité', 'B2', 'fr'),
('conflit', 'B2', 'fr'),
('guerre', 'B2', 'fr'),
('paix', 'B2', 'fr'),
('violence', 'B2', 'fr'),
('terrorisme', 'B2', 'fr'),
('mondialisation', 'B2', 'fr'),
('intégration', 'B2', 'fr'),
('diversité', 'B2', 'fr'),
('identité', 'B2', 'fr'),
('migration', 'B2', 'fr'),
('réfugié', 'B2', 'fr'),
('communauté', 'B2', 'fr'),
('réseau', 'B2', 'fr'),
('organisation', 'B2', 'fr'),
('institution', 'B2', 'fr'),
('direction', 'B2', 'fr'),
('gestion', 'B2', 'fr'),
('planification', 'B2', 'fr'),
('stratégie', 'B2', 'fr'),
('initiative', 'B2', 'fr'),
('créativité', 'B2', 'fr'),
('collaboration', 'B2', 'fr'),
('travail d''équipe', 'B2', 'fr'),
('responsabilité', 'B2', 'fr'),
('responsabilité', 'B2', 'fr'),
('durabilité', 'B2', 'fr'),
('protection de l''environnement', 'B2', 'fr'),
('énergie renouvelable', 'B2', 'fr'),
('processus d''innovation', 'B2', 'fr'),
('pensée critique', 'B2', 'fr'),
('résolution de problèmes', 'B2', 'fr'),
('prise de décision', 'B2', 'fr'),
('gestion du temps', 'B2', 'fr'),
('autodiscipline', 'B2', 'fr'),
('adaptation', 'B2', 'fr'),
('résilience', 'B2', 'fr'),
('indépendance', 'B2', 'fr'),
('coopération', 'B2', 'fr'),
('confiance', 'B2', 'fr'),
('respect', 'B2', 'fr'),
('empathie', 'B2', 'fr'),
('loyauté', 'B2', 'fr'),
('intégrité', 'B2', 'fr'),
('éthique', 'B2', 'fr'),
('moralité', 'B2', 'fr'),
('philosophie', 'B2', 'fr'),
('psychologie', 'B2', 'fr'),
('sociologie', 'B2', 'fr'),
('biologie', 'B2', 'fr'),
('chimie', 'B2', 'fr'),
('physique', 'B2', 'fr'),
('analyse critique', 'C1', 'fr'),
('raisonnement logique', 'C1', 'fr'),
('interprétation', 'C1', 'fr'),
('comparaison profonde', 'C1', 'fr'),
('conclusion scientifique', 'C1', 'fr'),
('hypothèse complexe', 'C1', 'fr'),
('théorie avancée', 'C1', 'fr'),
('expérience approfondie', 'C1', 'fr'),
('évaluation complète', 'C1', 'fr'),
('discussion philosophique', 'C1', 'fr'),
('argument fort', 'C1', 'fr'),
('preuves tangibles', 'C1', 'fr'),
('preuve contradictoire', 'C1', 'fr'),
('concept abstrait', 'C1', 'fr'),
('position éthique', 'C1', 'fr'),
('valeur suprême', 'C1', 'fr'),
('principe fondamental', 'C1', 'fr'),
('priorité absolue', 'C1', 'fr'),
('responsabilité majeure', 'C1', 'fr'),
('décision cruciale', 'C1', 'fr'),
('gestion complexe', 'C1', 'fr'),
('planification stratégique', 'C1', 'fr'),
('développement durable', 'C1', 'fr'),
('innovation moderne', 'C1', 'fr'),
('créativité avancée', 'C1', 'fr'),
('nouvelle découverte', 'C1', 'fr'),
('invention innovante', 'C1', 'fr'),
('analyse économique', 'C1', 'fr'),
('rapport financier', 'C1', 'fr'),
('projet à grande échelle', 'C1', 'fr'),
('négociations internationales', 'C1', 'fr'),
('accord officiel', 'C1', 'fr'),
('stratégie efficace', 'C1', 'fr'),
('institution mondiale', 'C1', 'fr'),
('centre de recherche', 'C1', 'fr'),
('étude scientifique avancée', 'C1', 'fr'),
('revue critique', 'C1', 'fr'),
('interprétation philosophique', 'C1', 'fr'),
('approche systématique', 'C1', 'fr'),
('théorie moderne', 'C1', 'fr'),
('recherche appliquée', 'C1', 'fr'),
('expérience pratique', 'C1', 'fr'),
('évaluation objective', 'C1', 'fr'),
('Résultats détaillés', 'C1', 'fr'),
('débat avancé', 'C1', 'fr'),
('étude comparative', 'C1', 'fr'),
('recherche sur le terrain', 'C1', 'fr'),
('recommandation pratique', 'C1', 'fr'),
('compétence avancée', 'C1', 'fr'),
('cadre conceptuel', 'C1', 'fr'),
('planification précise', 'C1', 'fr'),
('stratégie à long terme', 'C1', 'fr'),
('l''évaluation des risques', 'C1', 'fr'),
('revue académique', 'C1', 'fr'),
('projet de recherche', 'C1', 'fr'),
('innovation scientifique', 'C1', 'fr'),
('développement technologique', 'C1', 'fr'),
('analyse littéraire', 'C1', 'fr'),
('résultats scientifiques', 'C1', 'fr'),
('interprétation avancée', 'C1', 'fr'),
('vue holistique', 'C1', 'fr'),
('plan de mise en œuvre', 'C1', 'fr'),
('décision stratégique', 'C1', 'fr'),
('gestion des ressources', 'C1', 'fr'),
('Défis complexes', 'C1', 'fr'),
('solutions innovantes', 'C1', 'fr'),
('approche complète', 'C1', 'fr'),
('analyse des données', 'C1', 'fr'),
('test d''hypothèse', 'C1', 'fr'),
('étude de cas', 'C1', 'fr'),
('Travail de terrain avancé', 'C1', 'fr'),
('revue philosophique', 'C1', 'fr'),
('Projet de recherche appliqué', 'C1', 'fr'),
('discussion académique', 'C1', 'fr'),
('évaluation stratégique', 'C1', 'fr'),
('recommandations pratiques', 'C1', 'fr'),
('plan de travail', 'C1', 'fr'),
('gestion de projet', 'C1', 'fr'),
('publication académique', 'C1', 'fr'),
('découverte scientifique', 'C1', 'fr'),
('innovation appliquée', 'C1', 'fr'),
('développement continu', 'C1', 'fr'),
('Analyse approfondie des données', 'C1', 'fr'),
('expérience de recherche', 'C1', 'fr'),
('interprétation scientifique', 'C1', 'fr'),
('perspective critique', 'C1', 'fr');
