INSERT INTO words (word, level, language_code) VALUES
('talo', 'A1', 'fi'),
('ovi', 'A1', 'fi'),
('ikkuna', 'A1', 'fi'),
('taulukko', 'A1', 'fi'),
('tuoli', 'A1', 'fi'),
('kirja', 'A1', 'fi'),
('kynä', 'A1', 'fi'),
('koulutus', 'A1', 'fi'),
('opettaja', 'A1', 'fi'),
('opiskelija', 'A1', 'fi'),
('omena', 'A1', 'fi'),
('vettä', 'A1', 'fi'),
('ruoka', 'A1', 'fi'),
('auto', 'A1', 'fi'),
('linja -auto', 'A1', 'fi'),
('katu', 'A1', 'fi'),
('ystävä', 'A1', 'fi'),
('perhe', 'A1', 'fi'),
('äiti', 'A1', 'fi'),
('isä', 'A1', 'fi'),
('sisko', 'A1', 'fi'),
('veli', 'A1', 'fi'),
('päivä', 'A1', 'fi'),
('yö', 'A1', 'fi'),
('aamu', 'A1', 'fi'),
('ilta', 'A1', 'fi'),
('Hei', 'A1', 'fi'),
('Hyvästi', 'A1', 'fi'),
('Ole hyvä', 'A1', 'fi'),
('Kiitos', 'A1', 'fi'),
('kyllä', 'A1', 'fi'),
('ei', 'A1', 'fi'),
('punainen', 'A1', 'fi'),
('sininen', 'A1', 'fi'),
('vihreä', 'A1', 'fi'),
('valkoinen', 'A1', 'fi'),
('musta', 'A1', 'fi'),
('pieni', 'A1', 'fi'),
('iso', 'A1', 'fi'),
('hyvä', 'A1', 'fi'),
('huono', 'A1', 'fi'),
('kuuma', 'A1', 'fi'),
('kylmä', 'A1', 'fi'),
('kahvi', 'A1', 'fi'),
('teetä', 'A1', 'fi'),
('raha', 'A1', 'fi'),
('työ', 'A1', 'fi'),
('kotiin', 'A1', 'fi'),
('kauppa', 'A1', 'fi'),
('markkinoida', 'A1', 'fi'),
('ruoka', 'A1', 'fi'),
('juoda', 'A1', 'fi'),
('kaupunki', 'A1', 'fi'),
('pysäköidä', 'A1', 'fi'),
('katu', 'A1', 'fi'),
('bussipysäkki', 'A1', 'fi'),
('kouluttaa', 'A1', 'fi'),
('asema', 'A1', 'fi'),
('hotelli', 'A1', 'fi'),
('huone', 'A1', 'fi'),
('vuode', 'A1', 'fi'),
('lääkäri', 'A1', 'fi'),
('sairaala', 'A1', 'fi'),
('koulutus', 'A1', 'fi'),
('yliopisto', 'A1', 'fi'),
('tietokone', 'A1', 'fi'),
('puhelin', 'A1', 'fi'),
('televisio', 'A1', 'fi'),
('musiikki', 'A1', 'fi'),
('laulu', 'A1', 'fi'),
('elokuva', 'A1', 'fi'),
('peli', 'A1', 'fi'),
('jalkapallo', 'A1', 'fi'),
('pallo', 'A1', 'fi'),
('vettä', 'A1', 'fi'),
('sade', 'A1', 'fi'),
('aurinko', 'A1', 'fi'),
('taivas', 'A1', 'fi'),
('puu', 'A1', 'fi'),
('kukka', 'A1', 'fi'),
('eläin', 'A1', 'fi'),
('kissa', 'A1', 'fi'),
('koira', 'A1', 'fi'),
('lintu', 'A1', 'fi'),
('kalastaa', 'A1', 'fi'),
('mies', 'A1', 'fi'),
('nainen', 'A1', 'fi'),
('lapsi', 'A1', 'fi'),
('ihmiset', 'A1', 'fi'),
('katu', 'A1', 'fi'),
('paikka', 'A1', 'fi'),
('aika', 'A1', 'fi'),
('vuosi', 'A1', 'fi'),
('kuukausi', 'A1', 'fi'),
('viikko', 'A1', 'fi'),
('tänään', 'A1', 'fi'),
('huomenna', 'A1', 'fi'),
('eilen', 'A1', 'fi'),
('nimi', 'A1', 'fi'),
('osoite', 'A1', 'fi'),
('määrä', 'A1', 'fi'),
('lentokenttä', 'A2', 'fi'),
('lento', 'A2', 'fi'),
('lippu', 'A2', 'fi'),
('passi', 'A2', 'fi'),
('matkustaa', 'A2', 'fi'),
('loma', 'A2', 'fi'),
('matka', 'A2', 'fi'),
('matkatavarat', 'A2', 'fi'),
('asema', 'A2', 'fi'),
('alusta', 'A2', 'fi'),
('ravintola', 'A2', 'fi'),
('kahvila', 'A2', 'fi'),
('aamiainen', 'A2', 'fi'),
('lounas', 'A2', 'fi'),
('päivällinen', 'A2', 'fi'),
('vihannekset', 'A2', 'fi'),
('hedelmä', 'A2', 'fi'),
('liha', 'A2', 'fi'),
('kana', 'A2', 'fi'),
('naudanliha', 'A2', 'fi'),
('kalastaa', 'A2', 'fi'),
('leipä', 'A2', 'fi'),
('riisi', 'A2', 'fi'),
('pasta', 'A2', 'fi'),
('keitto', 'A2', 'fi'),
('sokeri', 'A2', 'fi'),
('suolaa', 'A2', 'fi'),
('pippuri', 'A2', 'fi'),
('öljy', 'A2', 'fi'),
('ostoksia', 'A2', 'fi'),
('vaatteet', 'A2', 'fi'),
('paita', 'A2', 'fi'),
('housut', 'A2', 'fi'),
('pukeutua', 'A2', 'fi'),
('kengät', 'A2', 'fi'),
('hattu', 'A2', 'fi'),
('takki', 'A2', 'fi'),
('takki', 'A2', 'fi'),
('sää', 'A2', 'fi'),
('lumi', 'A2', 'fi'),
('tuuli', 'A2', 'fi'),
('myrsky', 'A2', 'fi'),
('hotellit', 'A2', 'fi'),
('vieras', 'A2', 'fi'),
('huolto', 'A2', 'fi'),
('vastaanotto', 'A2', 'fi'),
('avain', 'A2', 'fi'),
('varaus', 'A2', 'fi'),
('ranta', 'A2', 'fi'),
('meri', 'A2', 'fi'),
('uima-', 'A2', 'fi'),
('yhdysvalta', 'A2', 'fi'),
('vuori', 'A2', 'fi'),
('kylä', 'A2', 'fi'),
('maa', 'A2', 'fi'),
('kieli', 'A2', 'fi'),
('ulkomainen', 'A2', 'fi'),
('tentti', 'A2', 'fi'),
('testata', 'A2', 'fi'),
('kotitehtävä', 'A2', 'fi'),
('luokkahuone', 'A2', 'fi'),
('kohde', 'A2', 'fi'),
('matematiikka', 'A2', 'fi'),
('historia', 'A2', 'fi'),
('tiede', 'A2', 'fi'),
('kirjasto', 'A2', 'fi'),
('kirjakauppa', 'A2', 'fi'),
('tietokone', 'A2', 'fi'),
('Internet', 'A2', 'fi'),
('sähköposti', 'A2', 'fi'),
('viesti', 'A2', 'fi'),
('kirje', 'A2', 'fi'),
('lähettää', 'A2', 'fi'),
('pankki', 'A2', 'fi'),
('raha', 'A2', 'fi'),
('luottokortti', 'A2', 'fi'),
('hinta', 'A2', 'fi'),
('halpa', 'A2', 'fi'),
('kallis', 'A2', 'fi'),
('kyseenalaistaa', 'A2', 'fi'),
('vastaus', 'A2', 'fi'),
('selittää', 'A2', 'fi'),
('auttaa', 'A2', 'fi'),
('ongelma', 'A2', 'fi'),
('ratkaisu', 'A2', 'fi'),
('terveys', 'A2', 'fi'),
('lääke', 'A2', 'fi'),
('lääkäri', 'A2', 'fi'),
('sairaanhoitaja', 'A2', 'fi'),
('potilas', 'A2', 'fi'),
('nimittäminen', 'A2', 'fi'),
('kuume', 'A2', 'fi'),
('yskä', 'A2', 'fi'),
('kokea', 'B1', 'fi'),
('seikkailu', 'B1', 'fi'),
('lausunto', 'B1', 'fi'),
('keskustelu', 'B1', 'fi'),
('väite', 'B1', 'fi'),
('päätös', 'B1', 'fi'),
('syy', 'B1', 'fi'),
('mahdollisuus', 'B1', 'fi'),
('haaste', 'B1', 'fi'),
('menestys', 'B1', 'fi'),
('epäonnistuminen', 'B1', 'fi'),
('tavoite', 'B1', 'fi'),
('suunnitelma', 'B1', 'fi'),
('projekti', 'B1', 'fi'),
('tieto', 'B1', 'fi'),
('taito', 'B1', 'fi'),
('kyky', 'B1', 'fi'),
('parannus', 'B1', 'fi'),
('koulutus', 'B1', 'fi'),
('työhaastattelu', 'B1', 'fi'),
('soveltaminen', 'B1', 'fi'),
('ura', 'B1', 'fi'),
('johtaja', 'B1', 'fi'),
('kollega', 'B1', 'fi'),
('tapaaminen', 'B1', 'fi'),
('tehtävä', 'B1', 'fi'),
('vastuu', 'B1', 'fi'),
('lomamatka', 'B1', 'fi'),
('kulttuuri', 'B1', 'fi'),
('perinne', 'B1', 'fi'),
('räätälöity', 'B1', 'fi'),
('festivaali', 'B1', 'fi'),
('juhla', 'B1', 'fi'),
('suorituskyky', 'B1', 'fi'),
('konsertti', 'B1', 'fi'),
('teatteri', 'B1', 'fi'),
('näyttely', 'B1', 'fi'),
('maalaus', 'B1', 'fi'),
('veistos', 'B1', 'fi'),
('museo', 'B1', 'fi'),
('historiakirja', 'B1', 'fi'),
('fiktio', 'B1', 'fi'),
('runo', 'B1', 'fi'),
('uusi', 'B1', 'fi'),
('merkki', 'B1', 'fi'),
('juonia', 'B1', 'fi'),
('tarina', 'B1', 'fi'),
('sanomalehti', 'B1', 'fi'),
('lehti', 'B1', 'fi'),
('artikla', 'B1', 'fi'),
('raportti', 'B1', 'fi'),
('esitys', 'B1', 'fi'),
('luento', 'B1', 'fi'),
('koulutus', 'B1', 'fi'),
('yliopisto', 'B1', 'fi'),
('aste', 'B1', 'fi'),
('tutkintotodistus', 'B1', 'fi'),
('todistus', 'B1', 'fi'),
('ympäristö', 'B1', 'fi'),
('luonto', 'B1', 'fi'),
('kierrätys', 'B1', 'fi'),
('pilaantuminen', 'B1', 'fi'),
('ilmastonmuutos', 'B1', 'fi'),
('ilmaston lämpeneminen', 'B1', 'fi'),
('energia', 'B1', 'fi'),
('tekniikka', 'B1', 'fi'),
('innovaatio', 'B1', 'fi'),
('keksintö', 'B1', 'fi'),
('laite', 'B1', 'fi'),
('kone', 'B1', 'fi'),
('tietokoneohjelma', 'B1', 'fi'),
('verkkosivusto', 'B1', 'fi'),
('soveltaminen', 'B1', 'fi'),
('sosiaalinen media', 'B1', 'fi'),
('viestintä', 'B1', 'fi'),
('keskustelu', 'B1', 'fi'),
('vuorovaikutus', 'B1', 'fi'),
('suhteet', 'B1', 'fi'),
('ystävyys', 'B1', 'fi'),
('avioliitto', 'B1', 'fi'),
('perhe -elämä', 'B1', 'fi'),
('onnea', 'B1', 'fi'),
('suututtaa', 'B1', 'fi'),
('pelko', 'B1', 'fi'),
('toivoa', 'B1', 'fi'),
('unelma', 'B1', 'fi'),
('kunnianhimo', 'B1', 'fi'),
('motivaatio', 'B1', 'fi'),
('luottamus', 'B1', 'fi'),
('uteliaisuus', 'B1', 'fi'),
('kärsivällisyys', 'B1', 'fi'),
('innovaatio', 'B2', 'fi'),
('kehitys', 'B2', 'fi'),
('tutkimus', 'B2', 'fi'),
('analyysi', 'B2', 'fi'),
('tulkinta', 'B2', 'fi'),
('väitteet', 'B2', 'fi'),
('vertailu', 'B2', 'fi'),
('hypoteesi', 'B2', 'fi'),
('teoria', 'B2', 'fi'),
('kokeilu', 'B2', 'fi'),
('todiste', 'B2', 'fi'),
('menetelmä', 'B2', 'fi'),
('johtopäätös', 'B2', 'fi'),
('havainto', 'B2', 'fi'),
('näkökulma', 'B2', 'fi'),
('oletus', 'B2', 'fi'),
('konteksti', 'B2', 'fi'),
('kriteerit', 'B2', 'fi'),
('periaate', 'B2', 'fi'),
('prioriteetti', 'B2', 'fi'),
('monimutkaisuus', 'B2', 'fi'),
('tehokkuus', 'B2', 'fi'),
('tuottavuus', 'B2', 'fi'),
('investointi', 'B2', 'fi'),
('talous', 'B2', 'fi'),
('rahoitus', 'B2', 'fi'),
('neuvottelut', 'B2', 'fi'),
('sopimus', 'B2', 'fi'),
('sopimus', 'B2', 'fi'),
('politiikka', 'B2', 'fi'),
('hallitus', 'B2', 'fi'),
('politiikka', 'B2', 'fi'),
('vaaleja', 'B2', 'fi'),
('demokratia', 'B2', 'fi'),
('vapaus', 'B2', 'fi'),
('oikeudenmukaisuus', 'B2', 'fi'),
('tasa -arvo', 'B2', 'fi'),
('laki', 'B2', 'fi'),
('rikos', 'B2', 'fi'),
('rangaistus', 'B2', 'fi'),
('rangaistus', 'B2', 'fi'),
('turvallisuus', 'B2', 'fi'),
('konflikti', 'B2', 'fi'),
('sota', 'B2', 'fi'),
('rauha', 'B2', 'fi'),
('väkivalta', 'B2', 'fi'),
('terrorismi', 'B2', 'fi'),
('globalisaatio', 'B2', 'fi'),
('integrointi', 'B2', 'fi'),
('monimuotoisuus', 'B2', 'fi'),
('identiteetti', 'B2', 'fi'),
('muuttoliike', 'B2', 'fi'),
('pakolainen', 'B2', 'fi'),
('yhteisö', 'B2', 'fi'),
('verkko', 'B2', 'fi'),
('organisaatio', 'B2', 'fi'),
('laitos', 'B2', 'fi'),
('johtajuus', 'B2', 'fi'),
('hallinta', 'B2', 'fi'),
('suunnittelu', 'B2', 'fi'),
('strategia', 'B2', 'fi'),
('aloite', 'B2', 'fi'),
('luovuus', 'B2', 'fi'),
('yhteistyö', 'B2', 'fi'),
('ryhmätyö', 'B2', 'fi'),
('vastuu', 'B2', 'fi'),
('vastuu', 'B2', 'fi'),
('kestävyys', 'B2', 'fi'),
('ympäristönsuojelu', 'B2', 'fi'),
('uusiutuva energia', 'B2', 'fi'),
('innovaatioprosessi', 'B2', 'fi'),
('kriittinen ajattelu', 'B2', 'fi'),
('ongelmanratkaisu', 'B2', 'fi'),
('päätöksenteko', 'B2', 'fi'),
('ajanhallinta', 'B2', 'fi'),
('itsekuri', 'B2', 'fi'),
('sopeutuminen', 'B2', 'fi'),
('kestävyys', 'B2', 'fi'),
('itsenäisyys', 'B2', 'fi'),
('yhteistyö', 'B2', 'fi'),
('luottamus', 'B2', 'fi'),
('kunnioittaminen', 'B2', 'fi'),
('empatia', 'B2', 'fi'),
('uskollisuus', 'B2', 'fi'),
('eheys', 'B2', 'fi'),
('etiikka', 'B2', 'fi'),
('moraali', 'B2', 'fi'),
('filosofia', 'B2', 'fi'),
('psykologia', 'B2', 'fi'),
('sosiologia', 'B2', 'fi'),
('biologia', 'B2', 'fi'),
('kemia', 'B2', 'fi'),
('fysiikka', 'B2', 'fi'),
('kriittinen analyysi', 'C1', 'fi'),
('looginen päättely', 'C1', 'fi'),
('tulkinta', 'C1', 'fi'),
('syvä vertailu', 'C1', 'fi'),
('tieteellinen johtopäätös', 'C1', 'fi'),
('monimutkainen hypoteesi', 'C1', 'fi'),
('edistynyt teoria', 'C1', 'fi'),
('perusteellinen koe', 'C1', 'fi'),
('kattava arviointi', 'C1', 'fi'),
('filosofinen keskustelu', 'C1', 'fi'),
('vahva väite', 'C1', 'fi'),
('konkreettiset todisteet', 'C1', 'fi'),
('ristiriitaiset todisteet', 'C1', 'fi'),
('abstrakti käsite', 'C1', 'fi'),
('eettinen asema', 'C1', 'fi'),
('ylin arvo', 'C1', 'fi'),
('perusperiaate', 'C1', 'fi'),
('ensisijainen tavoite', 'C1', 'fi'),
('suuri vastuu', 'C1', 'fi'),
('ratkaiseva päätös', 'C1', 'fi'),
('monimutkainen hallinta', 'C1', 'fi'),
('strateginen suunnittelu', 'C1', 'fi'),
('kestävä kehitys', 'C1', 'fi'),
('moderni innovaatio', 'C1', 'fi'),
('edistynyt luovuus', 'C1', 'fi'),
('uusi löytö', 'C1', 'fi'),
('innovatiivinen keksintö', 'C1', 'fi'),
('taloudellinen analyysi', 'C1', 'fi'),
('taloudellinen raportti', 'C1', 'fi'),
('laajamittainen projekti', 'C1', 'fi'),
('kansainväliset neuvottelut', 'C1', 'fi'),
('virallinen sopimus', 'C1', 'fi'),
('tehokas strategia', 'C1', 'fi'),
('globaali laitos', 'C1', 'fi'),
('tutkimuskeskus', 'C1', 'fi'),
('Kehittynyt tieteellinen tutkimus', 'C1', 'fi'),
('kriittinen arvostelu', 'C1', 'fi'),
('filosofinen tulkinta', 'C1', 'fi'),
('systemaattinen lähestymistapa', 'C1', 'fi'),
('moderni teoria', 'C1', 'fi'),
('sovellettu tutkimus', 'C1', 'fi'),
('käytännöllinen kokeilu', 'C1', 'fi'),
('objektiivien arviointi', 'C1', 'fi'),
('Yksityiskohtaiset tulokset', 'C1', 'fi'),
('edistynyt keskustelu', 'C1', 'fi'),
('vertaileva tutkimus', 'C1', 'fi'),
('kenttätutkimus', 'C1', 'fi'),
('käytännön suositus', 'C1', 'fi'),
('edistynyt taito', 'C1', 'fi'),
('käsitteellinen kehys', 'C1', 'fi'),
('tarkka suunnittelu', 'C1', 'fi'),
('pitkäaikainen strategia', 'C1', 'fi'),
('riskinarviointi', 'C1', 'fi'),
('akateeminen katsaus', 'C1', 'fi'),
('tutkimushanke', 'C1', 'fi'),
('tieteellinen innovaatio', 'C1', 'fi'),
('tekninen kehitys', 'C1', 'fi'),
('kirjallinen analyysi', 'C1', 'fi'),
('tieteelliset havainnot', 'C1', 'fi'),
('edistynyt tulkinta', 'C1', 'fi'),
('kokonaisvaltainen näkymä', 'C1', 'fi'),
('täytäntöönpanosuunnitelma', 'C1', 'fi'),
('strateginen päätös', 'C1', 'fi'),
('resurssien hallinta', 'C1', 'fi'),
('monimutkaiset haasteet', 'C1', 'fi'),
('innovatiiviset ratkaisut', 'C1', 'fi'),
('kattava lähestymistapa', 'C1', 'fi'),
('tietojen analysointi', 'C1', 'fi'),
('hypoteesitestaus', 'C1', 'fi'),
('tapaustutkimus', 'C1', 'fi'),
('edistynyt kenttätyö', 'C1', 'fi'),
('filosofinen arvostelu', 'C1', 'fi'),
('sovellettu tutkimushanke', 'C1', 'fi'),
('akateeminen keskustelu', 'C1', 'fi'),
('strateginen arviointi', 'C1', 'fi'),
('käytännön suositukset', 'C1', 'fi'),
('työsuunnitelma', 'C1', 'fi'),
('projektinhallinta', 'C1', 'fi'),
('akateeminen julkaisu', 'C1', 'fi'),
('tieteellinen löytö', 'C1', 'fi'),
('sovellettu innovaatio', 'C1', 'fi'),
('jatkuva kehitys', 'C1', 'fi'),
('syvällinen tietoanalyysi', 'C1', 'fi'),
('tutkimuskokemus', 'C1', 'fi'),
('tieteellinen tulkinta', 'C1', 'fi'),
('kriittinen näkökulma', 'C1', 'fi');
