INSERT INTO words (word, level, language_code) VALUES
('nyumba', 'A1', 'sw'),
('mlango', 'A1', 'sw'),
('Dirisha', 'A1', 'sw'),
('meza', 'A1', 'sw'),
('mwenyekiti', 'A1', 'sw'),
('kitabu', 'A1', 'sw'),
('kalamu', 'A1', 'sw'),
('shule', 'A1', 'sw'),
('mwalimu', 'A1', 'sw'),
('mwanafunzi', 'A1', 'sw'),
('apple', 'A1', 'sw'),
('maji', 'A1', 'sw'),
('chakula', 'A1', 'sw'),
('gari', 'A1', 'sw'),
('basi', 'A1', 'sw'),
('barabara', 'A1', 'sw'),
('rafiki', 'A1', 'sw'),
('familia', 'A1', 'sw'),
('mama', 'A1', 'sw'),
('baba', 'A1', 'sw'),
('dada', 'A1', 'sw'),
('kaka', 'A1', 'sw'),
('siku', 'A1', 'sw'),
('usiku', 'A1', 'sw'),
('Asubuhi', 'A1', 'sw'),
('jioni', 'A1', 'sw'),
('hello', 'A1', 'sw'),
('Kwaheri', 'A1', 'sw'),
('Tafadhali', 'A1', 'sw'),
('Asante', 'A1', 'sw'),
('Ndio', 'A1', 'sw'),
('hapana', 'A1', 'sw'),
('nyekundu', 'A1', 'sw'),
('Bluu', 'A1', 'sw'),
('kijani', 'A1', 'sw'),
('Nyeupe', 'A1', 'sw'),
('nyeusi', 'A1', 'sw'),
('ndogo', 'A1', 'sw'),
('kubwa', 'A1', 'sw'),
('Nzuri', 'A1', 'sw'),
('mbaya', 'A1', 'sw'),
('moto', 'A1', 'sw'),
('baridi', 'A1', 'sw'),
('kahawa', 'A1', 'sw'),
('chai', 'A1', 'sw'),
('Pesa', 'A1', 'sw'),
('kazi', 'A1', 'sw'),
('nyumbani', 'A1', 'sw'),
('duka', 'A1', 'sw'),
('soko', 'A1', 'sw'),
('chakula', 'A1', 'sw'),
('kunywa', 'A1', 'sw'),
('mji', 'A1', 'sw'),
('Hifadhi', 'A1', 'sw'),
('barabara', 'A1', 'sw'),
('kituo cha basi', 'A1', 'sw'),
('Treni', 'A1', 'sw'),
('kituo', 'A1', 'sw'),
('Hoteli', 'A1', 'sw'),
('chumba', 'A1', 'sw'),
('kitanda', 'A1', 'sw'),
('Daktari', 'A1', 'sw'),
('Hospitali', 'A1', 'sw'),
('shule', 'A1', 'sw'),
('chuo kikuu', 'A1', 'sw'),
('kompyuta', 'A1', 'sw'),
('simu', 'A1', 'sw'),
('Televisheni', 'A1', 'sw'),
('muziki', 'A1', 'sw'),
('wimbo', 'A1', 'sw'),
('Filamu', 'A1', 'sw'),
('mchezo', 'A1', 'sw'),
('mpira wa miguu', 'A1', 'sw'),
('Mpira', 'A1', 'sw'),
('maji', 'A1', 'sw'),
('mvua', 'A1', 'sw'),
('Jua', 'A1', 'sw'),
('Anga', 'A1', 'sw'),
('mti', 'A1', 'sw'),
('ua', 'A1', 'sw'),
('mnyama', 'A1', 'sw'),
('paka', 'A1', 'sw'),
('mbwa', 'A1', 'sw'),
('ndege', 'A1', 'sw'),
('samaki', 'A1', 'sw'),
('mtu', 'A1', 'sw'),
('mwanamke', 'A1', 'sw'),
('mtoto', 'A1', 'sw'),
('watu', 'A1', 'sw'),
('barabara', 'A1', 'sw'),
('mahali', 'A1', 'sw'),
('wakati', 'A1', 'sw'),
('mwaka', 'A1', 'sw'),
('mwezi', 'A1', 'sw'),
('wiki', 'A1', 'sw'),
('leo', 'A1', 'sw'),
('kesho', 'A1', 'sw'),
('jana', 'A1', 'sw'),
('Jina', 'A1', 'sw'),
('Anwani', 'A1', 'sw'),
('nambari', 'A1', 'sw'),
('uwanja wa ndege', 'A2', 'sw'),
('ndege', 'A2', 'sw'),
('tikiti', 'A2', 'sw'),
('pasipoti', 'A2', 'sw'),
('kusafiri', 'A2', 'sw'),
('Likizo', 'A2', 'sw'),
('safari', 'A2', 'sw'),
('mzigo', 'A2', 'sw'),
('kituo', 'A2', 'sw'),
('Jukwaa', 'A2', 'sw'),
('mgahawa', 'A2', 'sw'),
('cafe', 'A2', 'sw'),
('kifungua kinywa', 'A2', 'sw'),
('Chakula cha mchana', 'A2', 'sw'),
('Chakula cha jioni', 'A2', 'sw'),
('mboga', 'A2', 'sw'),
('matunda', 'A2', 'sw'),
('nyama', 'A2', 'sw'),
('Kuku', 'A2', 'sw'),
('nyama ya ng''ombe', 'A2', 'sw'),
('samaki', 'A2', 'sw'),
('mkate', 'A2', 'sw'),
('mpunga', 'A2', 'sw'),
('pasta', 'A2', 'sw'),
('supu', 'A2', 'sw'),
('sukari', 'A2', 'sw'),
('chumvi', 'A2', 'sw'),
('pilipili', 'A2', 'sw'),
('mafuta', 'A2', 'sw'),
('ununuzi', 'A2', 'sw'),
('Nguo', 'A2', 'sw'),
('shati', 'A2', 'sw'),
('suruali', 'A2', 'sw'),
('Mavazi', 'A2', 'sw'),
('Viatu', 'A2', 'sw'),
('kofia', 'A2', 'sw'),
('koti', 'A2', 'sw'),
('kanzu', 'A2', 'sw'),
('hali ya hewa', 'A2', 'sw'),
('Theluji', 'A2', 'sw'),
('upepo', 'A2', 'sw'),
('Dhoruba', 'A2', 'sw'),
('Hoteli', 'A2', 'sw'),
('mgeni', 'A2', 'sw'),
('huduma', 'A2', 'sw'),
('mapokezi', 'A2', 'sw'),
('ufunguo', 'A2', 'sw'),
('Uhifadhi', 'A2', 'sw'),
('pwani', 'A2', 'sw'),
('bahari', 'A2', 'sw'),
('kuogelea', 'A2', 'sw'),
('dimbwi', 'A2', 'sw'),
('Mlima', 'A2', 'sw'),
('kijiji', 'A2', 'sw'),
('nchi', 'A2', 'sw'),
('lugha', 'A2', 'sw'),
('kigeni', 'A2', 'sw'),
('mtihani', 'A2', 'sw'),
('mtihani', 'A2', 'sw'),
('kazi ya nyumbani', 'A2', 'sw'),
('darasa', 'A2', 'sw'),
('somo', 'A2', 'sw'),
('Math', 'A2', 'sw'),
('Historia', 'A2', 'sw'),
('Sayansi', 'A2', 'sw'),
('Maktaba', 'A2', 'sw'),
('Duka', 'A2', 'sw'),
('kompyuta', 'A2', 'sw'),
('mtandao', 'A2', 'sw'),
('Barua pepe', 'A2', 'sw'),
('Ujumbe', 'A2', 'sw'),
('barua', 'A2', 'sw'),
('post', 'A2', 'sw'),
('benki', 'A2', 'sw'),
('Pesa', 'A2', 'sw'),
('kadi ya mkopo', 'A2', 'sw'),
('bei', 'A2', 'sw'),
('nafuu', 'A2', 'sw'),
('ghali', 'A2', 'sw'),
('swali', 'A2', 'sw'),
('jibu', 'A2', 'sw'),
('Fafanua', 'A2', 'sw'),
('Msaada', 'A2', 'sw'),
('Tatizo', 'A2', 'sw'),
('Suluhisho', 'A2', 'sw'),
('afya', 'A2', 'sw'),
('dawa', 'A2', 'sw'),
('Daktari', 'A2', 'sw'),
('muuguzi', 'A2', 'sw'),
('mgonjwa', 'A2', 'sw'),
('miadi', 'A2', 'sw'),
('homa', 'A2', 'sw'),
('kikohozi', 'A2', 'sw'),
('uzoefu', 'B1', 'sw'),
('Matangazo', 'B1', 'sw'),
('maoni', 'B1', 'sw'),
('majadiliano', 'B1', 'sw'),
('hoja', 'B1', 'sw'),
('uamuzi', 'B1', 'sw'),
('Sababu', 'B1', 'sw'),
('fursa', 'B1', 'sw'),
('Changamoto', 'B1', 'sw'),
('mafanikio', 'B1', 'sw'),
('Kushindwa', 'B1', 'sw'),
('lengo', 'B1', 'sw'),
('mpango', 'B1', 'sw'),
('Mradi', 'B1', 'sw'),
('maarifa', 'B1', 'sw'),
('Ujuzi', 'B1', 'sw'),
('Uwezo', 'B1', 'sw'),
('Uboreshaji', 'B1', 'sw'),
('Mafunzo', 'B1', 'sw'),
('Mahojiano ya kazi', 'B1', 'sw'),
('maombi', 'B1', 'sw'),
('kazi', 'B1', 'sw'),
('meneja', 'B1', 'sw'),
('mwenzake', 'B1', 'sw'),
('mkutano', 'B1', 'sw'),
('kazi', 'B1', 'sw'),
('uwajibikaji', 'B1', 'sw'),
('safari ya likizo', 'B1', 'sw'),
('utamaduni', 'B1', 'sw'),
('mila', 'B1', 'sw'),
('desturi', 'B1', 'sw'),
('Tamasha', 'B1', 'sw'),
('Sherehe', 'B1', 'sw'),
('Utendaji', 'B1', 'sw'),
('Tamasha', 'B1', 'sw'),
('ukumbi wa michezo', 'B1', 'sw'),
('Maonyesho', 'B1', 'sw'),
('Uchoraji', 'B1', 'sw'),
('sanamu', 'B1', 'sw'),
('makumbusho', 'B1', 'sw'),
('Kitabu cha Historia', 'B1', 'sw'),
('hadithi', 'B1', 'sw'),
('shairi', 'B1', 'sw'),
('riwaya', 'B1', 'sw'),
('tabia', 'B1', 'sw'),
('njama', 'B1', 'sw'),
('hadithi', 'B1', 'sw'),
('gazeti', 'B1', 'sw'),
('Jarida', 'B1', 'sw'),
('Kifungu', 'B1', 'sw'),
('ripoti', 'B1', 'sw'),
('uwasilishaji', 'B1', 'sw'),
('Hotuba', 'B1', 'sw'),
('elimu', 'B1', 'sw'),
('chuo kikuu', 'B1', 'sw'),
('digrii', 'B1', 'sw'),
('diploma', 'B1', 'sw'),
('Cheti', 'B1', 'sw'),
('mazingira', 'B1', 'sw'),
('asili', 'B1', 'sw'),
('kuchakata tena', 'B1', 'sw'),
('uchafuzi', 'B1', 'sw'),
('Mabadiliko ya hali ya hewa', 'B1', 'sw'),
('ongezeko la joto duniani', 'B1', 'sw'),
('nishati', 'B1', 'sw'),
('Teknolojia', 'B1', 'sw'),
('uvumbuzi', 'B1', 'sw'),
('uvumbuzi', 'B1', 'sw'),
('kifaa', 'B1', 'sw'),
('mashine', 'B1', 'sw'),
('Programu ya kompyuta', 'B1', 'sw'),
('Tovuti', 'B1', 'sw'),
('maombi', 'B1', 'sw'),
('Vyombo vya habari vya kijamii', 'B1', 'sw'),
('Mawasiliano', 'B1', 'sw'),
('mazungumzo', 'B1', 'sw'),
('mwingiliano', 'B1', 'sw'),
('uhusiano', 'B1', 'sw'),
('urafiki', 'B1', 'sw'),
('Ndoa', 'B1', 'sw'),
('Maisha ya Familia', 'B1', 'sw'),
('Furaha', 'B1', 'sw'),
('hasira', 'B1', 'sw'),
('Hofu', 'B1', 'sw'),
('Matumaini', 'B1', 'sw'),
('Ndoto', 'B1', 'sw'),
('Tamaa', 'B1', 'sw'),
('motisha', 'B1', 'sw'),
('ujasiri', 'B1', 'sw'),
('udadisi', 'B1', 'sw'),
('uvumilivu', 'B1', 'sw'),
('uvumbuzi', 'B2', 'sw'),
('Maendeleo', 'B2', 'sw'),
('Utafiti', 'B2', 'sw'),
('uchambuzi', 'B2', 'sw'),
('Ufasiri', 'B2', 'sw'),
('hoja', 'B2', 'sw'),
('kulinganisha', 'B2', 'sw'),
('nadharia', 'B2', 'sw'),
('nadharia', 'B2', 'sw'),
('Jaribio', 'B2', 'sw'),
('ushahidi', 'B2', 'sw'),
('Mbinu', 'B2', 'sw'),
('Hitimisho', 'B2', 'sw'),
('uchunguzi', 'B2', 'sw'),
('Mtazamo', 'B2', 'sw'),
('dhana', 'B2', 'sw'),
('muktadha', 'B2', 'sw'),
('vigezo', 'B2', 'sw'),
('kanuni', 'B2', 'sw'),
('kipaumbele', 'B2', 'sw'),
('ugumu', 'B2', 'sw'),
('ufanisi', 'B2', 'sw'),
('Uzalishaji', 'B2', 'sw'),
('Uwekezaji', 'B2', 'sw'),
('Uchumi', 'B2', 'sw'),
('fedha', 'B2', 'sw'),
('mazungumzo', 'B2', 'sw'),
('makubaliano', 'B2', 'sw'),
('mkataba', 'B2', 'sw'),
('sera', 'B2', 'sw'),
('serikali', 'B2', 'sw'),
('siasa', 'B2', 'sw'),
('Uchaguzi', 'B2', 'sw'),
('demokrasia', 'B2', 'sw'),
('Uhuru', 'B2', 'sw'),
('Haki', 'B2', 'sw'),
('Usawa', 'B2', 'sw'),
('sheria', 'B2', 'sw'),
('uhalifu', 'B2', 'sw'),
('adhabu', 'B2', 'sw'),
('adhabu', 'B2', 'sw'),
('usalama', 'B2', 'sw'),
('mizozo', 'B2', 'sw'),
('vita', 'B2', 'sw'),
('Amani', 'B2', 'sw'),
('vurugu', 'B2', 'sw'),
('ugaidi', 'B2', 'sw'),
('utandawazi', 'B2', 'sw'),
('ujumuishaji', 'B2', 'sw'),
('utofauti', 'B2', 'sw'),
('kitambulisho', 'B2', 'sw'),
('uhamiaji', 'B2', 'sw'),
('Wakimbizi', 'B2', 'sw'),
('jamii', 'B2', 'sw'),
('mtandao', 'B2', 'sw'),
('shirika', 'B2', 'sw'),
('taasisi', 'B2', 'sw'),
('Uongozi', 'B2', 'sw'),
('Usimamizi', 'B2', 'sw'),
('Upangaji', 'B2', 'sw'),
('Mkakati', 'B2', 'sw'),
('mpango', 'B2', 'sw'),
('ubunifu', 'B2', 'sw'),
('Ushirikiano', 'B2', 'sw'),
('kazi ya pamoja', 'B2', 'sw'),
('uwajibikaji', 'B2', 'sw'),
('uwajibikaji', 'B2', 'sw'),
('uendelevu', 'B2', 'sw'),
('Ulinzi wa Mazingira', 'B2', 'sw'),
('nishati mbadala', 'B2', 'sw'),
('Mchakato wa uvumbuzi', 'B2', 'sw'),
('Kufikiria muhimu', 'B2', 'sw'),
('kutatua shida', 'B2', 'sw'),
('kufanya maamuzi', 'B2', 'sw'),
('Usimamizi wa wakati', 'B2', 'sw'),
('nidhamu ya kibinafsi', 'B2', 'sw'),
('Marekebisho', 'B2', 'sw'),
('Ustahimilivu', 'B2', 'sw'),
('uhuru', 'B2', 'sw'),
('ushirikiano', 'B2', 'sw'),
('Imani', 'B2', 'sw'),
('heshima', 'B2', 'sw'),
('huruma', 'B2', 'sw'),
('Uaminifu', 'B2', 'sw'),
('Uadilifu', 'B2', 'sw'),
('Maadili', 'B2', 'sw'),
('maadili', 'B2', 'sw'),
('falsafa', 'B2', 'sw'),
('Saikolojia', 'B2', 'sw'),
('Sosholojia', 'B2', 'sw'),
('Baiolojia', 'B2', 'sw'),
('Kemia', 'B2', 'sw'),
('Fizikia', 'B2', 'sw'),
('Uchambuzi muhimu', 'C1', 'sw'),
('Hoja ya kimantiki', 'C1', 'sw'),
('Ufasiri', 'C1', 'sw'),
('Ulinganisho wa kina', 'C1', 'sw'),
('Hitimisho la kisayansi', 'C1', 'sw'),
('nadharia ngumu', 'C1', 'sw'),
('nadharia ya hali ya juu', 'C1', 'sw'),
('Jaribio la kina', 'C1', 'sw'),
('Tathmini kamili', 'C1', 'sw'),
('Majadiliano ya kifalsafa', 'C1', 'sw'),
('hoja kali', 'C1', 'sw'),
('ushahidi unaoonekana', 'C1', 'sw'),
('ushahidi unaopingana', 'C1', 'sw'),
('Dhana ya Abstract', 'C1', 'sw'),
('msimamo wa maadili', 'C1', 'sw'),
('Thamani Kuu', 'C1', 'sw'),
('kanuni ya msingi', 'C1', 'sw'),
('kipaumbele cha juu', 'C1', 'sw'),
('jukumu kubwa', 'C1', 'sw'),
('uamuzi muhimu', 'C1', 'sw'),
('Usimamizi tata', 'C1', 'sw'),
('Upangaji wa kimkakati', 'C1', 'sw'),
('Maendeleo Endelevu', 'C1', 'sw'),
('uvumbuzi wa kisasa', 'C1', 'sw'),
('Ubunifu wa hali ya juu', 'C1', 'sw'),
('Ugunduzi mpya', 'C1', 'sw'),
('uvumbuzi wa ubunifu', 'C1', 'sw'),
('Uchambuzi wa Uchumi', 'C1', 'sw'),
('Ripoti ya kifedha', 'C1', 'sw'),
('Mradi wa kiwango kikubwa', 'C1', 'sw'),
('Mazungumzo ya Kimataifa', 'C1', 'sw'),
('makubaliano rasmi', 'C1', 'sw'),
('Mkakati mzuri', 'C1', 'sw'),
('Taasisi ya Ulimwenguni', 'C1', 'sw'),
('Kituo cha utafiti', 'C1', 'sw'),
('Utafiti wa kisayansi wa hali ya juu', 'C1', 'sw'),
('Mapitio muhimu', 'C1', 'sw'),
('Tafsiri ya kifalsafa', 'C1', 'sw'),
('Njia ya kimfumo', 'C1', 'sw'),
('Nadharia ya kisasa', 'C1', 'sw'),
('Utafiti uliotumika', 'C1', 'sw'),
('Jaribio la vitendo', 'C1', 'sw'),
('Tathmini ya lengo', 'C1', 'sw'),
('Matokeo ya kina', 'C1', 'sw'),
('Mjadala wa hali ya juu', 'C1', 'sw'),
('Utafiti wa kulinganisha', 'C1', 'sw'),
('Utafiti wa shamba', 'C1', 'sw'),
('Mapendekezo ya vitendo', 'C1', 'sw'),
('Ujuzi wa hali ya juu', 'C1', 'sw'),
('Mfumo wa dhana', 'C1', 'sw'),
('Upangaji sahihi', 'C1', 'sw'),
('Mkakati wa muda mrefu', 'C1', 'sw'),
('Tathmini ya hatari', 'C1', 'sw'),
('Mapitio ya kitaaluma', 'C1', 'sw'),
('Mradi wa utafiti', 'C1', 'sw'),
('uvumbuzi wa kisayansi', 'C1', 'sw'),
('Maendeleo ya Teknolojia', 'C1', 'sw'),
('Uchambuzi wa fasihi', 'C1', 'sw'),
('Matokeo ya kisayansi', 'C1', 'sw'),
('tafsiri ya hali ya juu', 'C1', 'sw'),
('Mtazamo wa jumla', 'C1', 'sw'),
('mpango wa utekelezaji', 'C1', 'sw'),
('Uamuzi wa kimkakati', 'C1', 'sw'),
('Usimamizi wa rasilimali', 'C1', 'sw'),
('Changamoto ngumu', 'C1', 'sw'),
('suluhisho za ubunifu', 'C1', 'sw'),
('Njia kamili', 'C1', 'sw'),
('Uchambuzi wa data', 'C1', 'sw'),
('Upimaji wa Hypothesis', 'C1', 'sw'),
('Uchunguzi wa kesi', 'C1', 'sw'),
('kazi ya uwanja wa juu', 'C1', 'sw'),
('Mapitio ya Falsafa', 'C1', 'sw'),
('Mradi wa Utafiti uliotumika', 'C1', 'sw'),
('majadiliano ya kitaaluma', 'C1', 'sw'),
('Tathmini ya kimkakati', 'C1', 'sw'),
('Mapendekezo ya vitendo', 'C1', 'sw'),
('mpango wa kazi', 'C1', 'sw'),
('Usimamizi wa Mradi', 'C1', 'sw'),
('Mchapishaji wa kitaaluma', 'C1', 'sw'),
('Ugunduzi wa kisayansi', 'C1', 'sw'),
('Ubunifu uliotumika', 'C1', 'sw'),
('maendeleo endelevu', 'C1', 'sw'),
('Uchambuzi wa kina wa data', 'C1', 'sw'),
('Uzoefu wa utafiti', 'C1', 'sw'),
('tafsiri ya kisayansi', 'C1', 'sw'),
('Mtazamo muhimu', 'C1', 'sw');
