INSERT INTO words (word, level, language_code) VALUES
('hus', 'A1', 'no'),
('dør', 'A1', 'no'),
('vindu', 'A1', 'no'),
('bord', 'A1', 'no'),
('stol', 'A1', 'no'),
('bok', 'A1', 'no'),
('penn', 'A1', 'no'),
('skole', 'A1', 'no'),
('lærer', 'A1', 'no'),
('student', 'A1', 'no'),
('eple', 'A1', 'no'),
('vann', 'A1', 'no'),
('mat', 'A1', 'no'),
('bil', 'A1', 'no'),
('buss', 'A1', 'no'),
('gate', 'A1', 'no'),
('venn', 'A1', 'no'),
('familie', 'A1', 'no'),
('mor', 'A1', 'no'),
('far', 'A1', 'no'),
('søster', 'A1', 'no'),
('bror', 'A1', 'no'),
('dag', 'A1', 'no'),
('natt', 'A1', 'no'),
('morgen', 'A1', 'no'),
('kveld', 'A1', 'no'),
('hallo', 'A1', 'no'),
('adjø', 'A1', 'no'),
('vennligst', 'A1', 'no'),
('Takk', 'A1', 'no'),
('ja', 'A1', 'no'),
('ingen', 'A1', 'no'),
('rød', 'A1', 'no'),
('blå', 'A1', 'no'),
('grønn', 'A1', 'no'),
('hvit', 'A1', 'no'),
('svart', 'A1', 'no'),
('liten', 'A1', 'no'),
('stor', 'A1', 'no'),
('god', 'A1', 'no'),
('dårlig', 'A1', 'no'),
('varm', 'A1', 'no'),
('kald', 'A1', 'no'),
('kaffe', 'A1', 'no'),
('te', 'A1', 'no'),
('penger', 'A1', 'no'),
('arbeid', 'A1', 'no'),
('hjem', 'A1', 'no'),
('butikk', 'A1', 'no'),
('marked', 'A1', 'no'),
('mat', 'A1', 'no'),
('drikke', 'A1', 'no'),
('by', 'A1', 'no'),
('parkere', 'A1', 'no'),
('gate', 'A1', 'no'),
('bussholdeplass', 'A1', 'no'),
('tog', 'A1', 'no'),
('stasjon', 'A1', 'no'),
('hotell', 'A1', 'no'),
('rom', 'A1', 'no'),
('seng', 'A1', 'no'),
('doktor', 'A1', 'no'),
('sykehus', 'A1', 'no'),
('skole', 'A1', 'no'),
('universitet', 'A1', 'no'),
('computer', 'A1', 'no'),
('Telefon', 'A1', 'no'),
('fjernsyn', 'A1', 'no'),
('musikk', 'A1', 'no'),
('sang', 'A1', 'no'),
('film', 'A1', 'no'),
('spill', 'A1', 'no'),
('Fotball', 'A1', 'no'),
('ball', 'A1', 'no'),
('vann', 'A1', 'no'),
('regn', 'A1', 'no'),
('sol', 'A1', 'no'),
('himmel', 'A1', 'no'),
('tre', 'A1', 'no'),
('blomst', 'A1', 'no'),
('dyr', 'A1', 'no'),
('katt', 'A1', 'no'),
('hund', 'A1', 'no'),
('fugl', 'A1', 'no'),
('fisk', 'A1', 'no'),
('mann', 'A1', 'no'),
('kvinne', 'A1', 'no'),
('barn', 'A1', 'no'),
('mennesker', 'A1', 'no'),
('gate', 'A1', 'no'),
('sted', 'A1', 'no'),
('tid', 'A1', 'no'),
('år', 'A1', 'no'),
('måned', 'A1', 'no'),
('uke', 'A1', 'no'),
('i dag', 'A1', 'no'),
('i morgen', 'A1', 'no'),
('i går', 'A1', 'no'),
('navn', 'A1', 'no'),
('adresse', 'A1', 'no'),
('tall', 'A1', 'no'),
('flyplass', 'A2', 'no'),
('flyvning', 'A2', 'no'),
('billett', 'A2', 'no'),
('pass', 'A2', 'no'),
('reise', 'A2', 'no'),
('ferie', 'A2', 'no'),
('reise', 'A2', 'no'),
('bagasje', 'A2', 'no'),
('stasjon', 'A2', 'no'),
('plattform', 'A2', 'no'),
('restaurant', 'A2', 'no'),
('kafe', 'A2', 'no'),
('frokost', 'A2', 'no'),
('lunsj', 'A2', 'no'),
('middag', 'A2', 'no'),
('grønnsaker', 'A2', 'no'),
('frukt', 'A2', 'no'),
('kjøtt', 'A2', 'no'),
('kylling', 'A2', 'no'),
('biff', 'A2', 'no'),
('fisk', 'A2', 'no'),
('brød', 'A2', 'no'),
('ris', 'A2', 'no'),
('Pasta', 'A2', 'no'),
('suppe', 'A2', 'no'),
('sukker', 'A2', 'no'),
('salt', 'A2', 'no'),
('pepper', 'A2', 'no'),
('olje', 'A2', 'no'),
('shopping', 'A2', 'no'),
('Klær', 'A2', 'no'),
('skjorte', 'A2', 'no'),
('bukse', 'A2', 'no'),
('kle', 'A2', 'no'),
('Sko', 'A2', 'no'),
('hatt', 'A2', 'no'),
('jakke', 'A2', 'no'),
('frakk', 'A2', 'no'),
('vær', 'A2', 'no'),
('snø', 'A2', 'no'),
('vind', 'A2', 'no'),
('storm', 'A2', 'no'),
('hotell', 'A2', 'no'),
('gjest', 'A2', 'no'),
('service', 'A2', 'no'),
('resepsjon', 'A2', 'no'),
('nøkkel', 'A2', 'no'),
('reservasjon', 'A2', 'no'),
('strand', 'A2', 'no'),
('sjø', 'A2', 'no'),
('svømming', 'A2', 'no'),
('basseng', 'A2', 'no'),
('fjell', 'A2', 'no'),
('landsby', 'A2', 'no'),
('land', 'A2', 'no'),
('språk', 'A2', 'no'),
('fremmed', 'A2', 'no'),
('eksamen', 'A2', 'no'),
('test', 'A2', 'no'),
('lekser', 'A2', 'no'),
('Klasserom', 'A2', 'no'),
('tema', 'A2', 'no'),
('matematikk', 'A2', 'no'),
('historie', 'A2', 'no'),
('vitenskap', 'A2', 'no'),
('bibliotek', 'A2', 'no'),
('bokhandel', 'A2', 'no'),
('computer', 'A2', 'no'),
('Internett', 'A2', 'no'),
('e -post', 'A2', 'no'),
('beskjed', 'A2', 'no'),
('brev', 'A2', 'no'),
('stolpe', 'A2', 'no'),
('bank', 'A2', 'no'),
('penger', 'A2', 'no'),
('kredittkort', 'A2', 'no'),
('pris', 'A2', 'no'),
('billig', 'A2', 'no'),
('dyr', 'A2', 'no'),
('spørsmål', 'A2', 'no'),
('svare', 'A2', 'no'),
('forklare', 'A2', 'no'),
('hjelp', 'A2', 'no'),
('problem', 'A2', 'no'),
('løsning', 'A2', 'no'),
('helse', 'A2', 'no'),
('medisin', 'A2', 'no'),
('doktor', 'A2', 'no'),
('sykepleier', 'A2', 'no'),
('pasient', 'A2', 'no'),
('ansettelse', 'A2', 'no'),
('feber', 'A2', 'no'),
('hoste', 'A2', 'no'),
('erfaring', 'B1', 'no'),
('eventyr', 'B1', 'no'),
('mening', 'B1', 'no'),
('diskusjon', 'B1', 'no'),
('argument', 'B1', 'no'),
('avgjørelse', 'B1', 'no'),
('grunn', 'B1', 'no'),
('anledning', 'B1', 'no'),
('utfordring', 'B1', 'no'),
('suksess', 'B1', 'no'),
('feil', 'B1', 'no'),
('mål', 'B1', 'no'),
('plan', 'B1', 'no'),
('prosjekt', 'B1', 'no'),
('kunnskap', 'B1', 'no'),
('ferdighet', 'B1', 'no'),
('evne', 'B1', 'no'),
('forbedring', 'B1', 'no'),
('opplæring', 'B1', 'no'),
('Jobbintervju', 'B1', 'no'),
('søknad', 'B1', 'no'),
('karriere', 'B1', 'no'),
('leder', 'B1', 'no'),
('kollega', 'B1', 'no'),
('møte', 'B1', 'no'),
('oppgave', 'B1', 'no'),
('ansvar', 'B1', 'no'),
('Ferietur', 'B1', 'no'),
('kultur', 'B1', 'no'),
('tradisjon', 'B1', 'no'),
('skikk', 'B1', 'no'),
('festival', 'B1', 'no'),
('feiring', 'B1', 'no'),
('ytelse', 'B1', 'no'),
('konsert', 'B1', 'no'),
('teater', 'B1', 'no'),
('utstilling', 'B1', 'no'),
('maleri', 'B1', 'no'),
('skulptur', 'B1', 'no'),
('museum', 'B1', 'no'),
('Historiebok', 'B1', 'no'),
('fiksjon', 'B1', 'no'),
('dikt', 'B1', 'no'),
('roman', 'B1', 'no'),
('karakter', 'B1', 'no'),
('tomt', 'B1', 'no'),
('historie', 'B1', 'no'),
('avis', 'B1', 'no'),
('magasin', 'B1', 'no'),
('artikkel', 'B1', 'no'),
('rapportere', 'B1', 'no'),
('presentasjon', 'B1', 'no'),
('foredrag', 'B1', 'no'),
('utdannelse', 'B1', 'no'),
('universitet', 'B1', 'no'),
('grad', 'B1', 'no'),
('Diplom', 'B1', 'no'),
('sertifikat', 'B1', 'no'),
('miljø', 'B1', 'no'),
('natur', 'B1', 'no'),
('gjenvinning', 'B1', 'no'),
('forurensing', 'B1', 'no'),
('Klimaendringer', 'B1', 'no'),
('Global oppvarming', 'B1', 'no'),
('energi', 'B1', 'no'),
('teknologi', 'B1', 'no'),
('innovasjon', 'B1', 'no'),
('oppfinnelse', 'B1', 'no'),
('enhet', 'B1', 'no'),
('maskin', 'B1', 'no'),
('dataprogram', 'B1', 'no'),
('nettsted', 'B1', 'no'),
('søknad', 'B1', 'no'),
('Sosiale medier', 'B1', 'no'),
('kommunikasjon', 'B1', 'no'),
('samtale', 'B1', 'no'),
('samspill', 'B1', 'no'),
('forhold', 'B1', 'no'),
('vennskap', 'B1', 'no'),
('ekteskap', 'B1', 'no'),
('familielivet', 'B1', 'no'),
('lykke', 'B1', 'no'),
('sinne', 'B1', 'no'),
('frykt', 'B1', 'no'),
('håp', 'B1', 'no'),
('drøm', 'B1', 'no'),
('ambisjon', 'B1', 'no'),
('motivasjon', 'B1', 'no'),
('tillit', 'B1', 'no'),
('nysgjerrighet', 'B1', 'no'),
('tålmodighet', 'B1', 'no'),
('innovasjon', 'B2', 'no'),
('utvikling', 'B2', 'no'),
('forske', 'B2', 'no'),
('analyse', 'B2', 'no'),
('tolkning', 'B2', 'no'),
('argumentasjon', 'B2', 'no'),
('sammenligning', 'B2', 'no'),
('hypotese', 'B2', 'no'),
('teori', 'B2', 'no'),
('eksperiment', 'B2', 'no'),
('bevis', 'B2', 'no'),
('metode', 'B2', 'no'),
('konklusjon', 'B2', 'no'),
('observasjon', 'B2', 'no'),
('perspektiv', 'B2', 'no'),
('antagelse', 'B2', 'no'),
('kontekst', 'B2', 'no'),
('Kriterier', 'B2', 'no'),
('prinsipp', 'B2', 'no'),
('prioritet', 'B2', 'no'),
('kompleksitet', 'B2', 'no'),
('effektivitet', 'B2', 'no'),
('produktivitet', 'B2', 'no'),
('investering', 'B2', 'no'),
('økonomi', 'B2', 'no'),
('finansiere', 'B2', 'no'),
('forhandling', 'B2', 'no'),
('avtale', 'B2', 'no'),
('kontrakt', 'B2', 'no'),
('politikk', 'B2', 'no'),
('regjering', 'B2', 'no'),
('politikk', 'B2', 'no'),
('valg', 'B2', 'no'),
('demokrati', 'B2', 'no'),
('frihet', 'B2', 'no'),
('rettferdighet', 'B2', 'no'),
('likestilling', 'B2', 'no'),
('lov', 'B2', 'no'),
('kriminalitet', 'B2', 'no'),
('straff', 'B2', 'no'),
('avstraffelse', 'B2', 'no'),
('sikkerhet', 'B2', 'no'),
('konflikt', 'B2', 'no'),
('krig', 'B2', 'no'),
('fred', 'B2', 'no'),
('vold', 'B2', 'no'),
('terrorisme', 'B2', 'no'),
('globalisering', 'B2', 'no'),
('integrering', 'B2', 'no'),
('mangfold', 'B2', 'no'),
('identitet', 'B2', 'no'),
('Migrasjon', 'B2', 'no'),
('flyktning', 'B2', 'no'),
('Fellesskap', 'B2', 'no'),
('nettverk', 'B2', 'no'),
('organisasjon', 'B2', 'no'),
('institusjon', 'B2', 'no'),
('ledelse', 'B2', 'no'),
('ledelse', 'B2', 'no'),
('planlegging', 'B2', 'no'),
('strategi', 'B2', 'no'),
('initiativ', 'B2', 'no'),
('kreativitet', 'B2', 'no'),
('samarbeidet', 'B2', 'no'),
('Teamarbeid', 'B2', 'no'),
('ansvar', 'B2', 'no'),
('ansvarlighet', 'B2', 'no'),
('bærekraft', 'B2', 'no'),
('miljøvern', 'B2', 'no'),
('Fornybar energi', 'B2', 'no'),
('Innovasjonsprosess', 'B2', 'no'),
('kritisk tenking', 'B2', 'no'),
('problemløsning', 'B2', 'no'),
('beslutningstaking', 'B2', 'no'),
('tidsstyring', 'B2', 'no'),
('Selvdisiplin', 'B2', 'no'),
('tilpasning', 'B2', 'no'),
('Motstandskraft', 'B2', 'no'),
('uavhengighet', 'B2', 'no'),
('samarbeid', 'B2', 'no'),
('tillit', 'B2', 'no'),
('respekt', 'B2', 'no'),
('empati', 'B2', 'no'),
('lojalitet', 'B2', 'no'),
('integritet', 'B2', 'no'),
('etikk', 'B2', 'no'),
('moral', 'B2', 'no'),
('filosofi', 'B2', 'no'),
('Psykologi', 'B2', 'no'),
('Sosiologi', 'B2', 'no'),
('biologi', 'B2', 'no'),
('kjemi', 'B2', 'no'),
('Fysikk', 'B2', 'no'),
('kritisk analyse', 'C1', 'no'),
('logisk resonnement', 'C1', 'no'),
('tolkning', 'C1', 'no'),
('dyp sammenligning', 'C1', 'no'),
('vitenskapelig konklusjon', 'C1', 'no'),
('kompleks hypotese', 'C1', 'no'),
('Avansert teori', 'C1', 'no'),
('dyptgående eksperiment', 'C1', 'no'),
('Omfattende evaluering', 'C1', 'no'),
('Filosofisk diskusjon', 'C1', 'no'),
('sterkt argument', 'C1', 'no'),
('håndgripelige bevis', 'C1', 'no'),
('motstridende bevis', 'C1', 'no'),
('abstrakt konsept', 'C1', 'no'),
('etisk stilling', 'C1', 'no'),
('suveren verdi', 'C1', 'no'),
('grunnleggende prinsipp', 'C1', 'no'),
('topp prioritet', 'C1', 'no'),
('hovedansvar', 'C1', 'no'),
('avgjørende beslutning', 'C1', 'no'),
('kompleks ledelse', 'C1', 'no'),
('strategisk planlegging', 'C1', 'no'),
('bærekraftig utvikling', 'C1', 'no'),
('Moderne innovasjon', 'C1', 'no'),
('Avansert kreativitet', 'C1', 'no'),
('Ny oppdagelse', 'C1', 'no'),
('nyskapende oppfinnelse', 'C1', 'no'),
('Økonomisk analyse', 'C1', 'no'),
('Finansiell rapport', 'C1', 'no'),
('Storskala prosjekt', 'C1', 'no'),
('Internasjonale forhandlinger', 'C1', 'no'),
('Formell avtale', 'C1', 'no'),
('Effektiv strategi', 'C1', 'no'),
('Global institusjon', 'C1', 'no'),
('Forskningssenter', 'C1', 'no'),
('Avansert vitenskapelig studie', 'C1', 'no'),
('Kritisk gjennomgang', 'C1', 'no'),
('Filosofisk tolkning', 'C1', 'no'),
('systematisk tilnærming', 'C1', 'no'),
('Moderne teori', 'C1', 'no'),
('Anvendt forskning', 'C1', 'no'),
('Praktisk eksperiment', 'C1', 'no'),
('objektiv evaluering', 'C1', 'no'),
('detaljerte resultater', 'C1', 'no'),
('Avansert debatt', 'C1', 'no'),
('Sammenlignende studie', 'C1', 'no'),
('Feltforskning', 'C1', 'no'),
('Praktisk anbefaling', 'C1', 'no'),
('Avansert ferdighet', 'C1', 'no'),
('Konseptuelle rammer', 'C1', 'no'),
('presis planlegging', 'C1', 'no'),
('Langsiktig strategi', 'C1', 'no'),
('Risikovurdering', 'C1', 'no'),
('Akademisk gjennomgang', 'C1', 'no'),
('Forskningsprosjekt', 'C1', 'no'),
('Vitenskapelig innovasjon', 'C1', 'no'),
('teknologisk utvikling', 'C1', 'no'),
('Litterær analyse', 'C1', 'no'),
('Vitenskapelige funn', 'C1', 'no'),
('Avansert tolkning', 'C1', 'no'),
('Holistisk syn', 'C1', 'no'),
('Implementeringsplan', 'C1', 'no'),
('strategisk beslutning', 'C1', 'no'),
('ressursstyring', 'C1', 'no'),
('komplekse utfordringer', 'C1', 'no'),
('Innovative løsninger', 'C1', 'no'),
('Omfattende tilnærming', 'C1', 'no'),
('Dataanalyse', 'C1', 'no'),
('Hypotesetesting', 'C1', 'no'),
('casestudie', 'C1', 'no'),
('Avansert feltarbeid', 'C1', 'no'),
('Filosofisk gjennomgang', 'C1', 'no'),
('Anvendt forskningsprosjekt', 'C1', 'no'),
('akademisk diskusjon', 'C1', 'no'),
('strategisk evaluering', 'C1', 'no'),
('Praktiske anbefalinger', 'C1', 'no'),
('arbeidsplan', 'C1', 'no'),
('Prosjektledelse', 'C1', 'no'),
('Akademisk publikasjon', 'C1', 'no'),
('Vitenskapelig oppdagelse', 'C1', 'no'),
('Anvendt innovasjon', 'C1', 'no'),
('kontinuerlig utvikling', 'C1', 'no'),
('dyptgående dataanalyse', 'C1', 'no'),
('Forskningserfaring', 'C1', 'no'),
('vitenskapelig tolkning', 'C1', 'no'),
('kritisk perspektiv', 'C1', 'no');
