INSERT INTO words (word, level, language_code) VALUES
('namas', 'A1', 'lt'),
('durys', 'A1', 'lt'),
('langas', 'A1', 'lt'),
('lentelė', 'A1', 'lt'),
('kėdė', 'A1', 'lt'),
('knyga', 'A1', 'lt'),
('rašiklis', 'A1', 'lt'),
('mokykla', 'A1', 'lt'),
('mokytojas', 'A1', 'lt'),
('studentas', 'A1', 'lt'),
('obuolys', 'A1', 'lt'),
('vanduo', 'A1', 'lt'),
('maistas', 'A1', 'lt'),
('automobilis', 'A1', 'lt'),
('autobusas', 'A1', 'lt'),
('gatvė', 'A1', 'lt'),
('drauge', 'A1', 'lt'),
('šeima', 'A1', 'lt'),
('motina', 'A1', 'lt'),
('Tėvas', 'A1', 'lt'),
('sesuo', 'A1', 'lt'),
('brolis', 'A1', 'lt'),
('diena', 'A1', 'lt'),
('naktis', 'A1', 'lt'),
('ryto', 'A1', 'lt'),
('vakaras', 'A1', 'lt'),
('Sveiki', 'A1', 'lt'),
('Sudie', 'A1', 'lt'),
('Prašau', 'A1', 'lt'),
('Ačiū', 'A1', 'lt'),
('taip', 'A1', 'lt'),
('ne', 'A1', 'lt'),
('raudonas', 'A1', 'lt'),
('mėlyna', 'A1', 'lt'),
('žalia', 'A1', 'lt'),
('balta', 'A1', 'lt'),
('juodas', 'A1', 'lt'),
('mažas', 'A1', 'lt'),
('didelis', 'A1', 'lt'),
('gerai', 'A1', 'lt'),
('bloga', 'A1', 'lt'),
('karšta', 'A1', 'lt'),
('šalta', 'A1', 'lt'),
('kava', 'A1', 'lt'),
('arbata', 'A1', 'lt'),
('pinigai', 'A1', 'lt'),
('dirbti', 'A1', 'lt'),
('namai', 'A1', 'lt'),
('apsipirkti', 'A1', 'lt'),
('rinka', 'A1', 'lt'),
('maistas', 'A1', 'lt'),
('gerti', 'A1', 'lt'),
('miestas', 'A1', 'lt'),
('parkas', 'A1', 'lt'),
('gatvė', 'A1', 'lt'),
('Autobusų stotelė', 'A1', 'lt'),
('traukinys', 'A1', 'lt'),
('stotis', 'A1', 'lt'),
('viešbutis', 'A1', 'lt'),
('kambarys', 'A1', 'lt'),
('lova', 'A1', 'lt'),
('gydytojas', 'A1', 'lt'),
('ligoninė', 'A1', 'lt'),
('mokykla', 'A1', 'lt'),
('Universitetas', 'A1', 'lt'),
('kompiuteris', 'A1', 'lt'),
('Telefonas', 'A1', 'lt'),
('televizija', 'A1', 'lt'),
('muzika', 'A1', 'lt'),
('daina', 'A1', 'lt'),
('Filmas', 'A1', 'lt'),
('Žaidimas', 'A1', 'lt'),
('futbolas', 'A1', 'lt'),
('rutulys', 'A1', 'lt'),
('vanduo', 'A1', 'lt'),
('lietus', 'A1', 'lt'),
('saulė', 'A1', 'lt'),
('dangus', 'A1', 'lt'),
('medis', 'A1', 'lt'),
('gėlė', 'A1', 'lt'),
('gyvūnas', 'A1', 'lt'),
('kat', 'A1', 'lt'),
('šuo', 'A1', 'lt'),
('paukštis', 'A1', 'lt'),
('žuvis', 'A1', 'lt'),
('Žmogus', 'A1', 'lt'),
('moteris', 'A1', 'lt'),
('vaikas', 'A1', 'lt'),
('žmonių', 'A1', 'lt'),
('gatvė', 'A1', 'lt'),
('vieta', 'A1', 'lt'),
('laikas', 'A1', 'lt'),
('metai', 'A1', 'lt'),
('mėnuo', 'A1', 'lt'),
('savaitė', 'A1', 'lt'),
('šiandien', 'A1', 'lt'),
('rytoj', 'A1', 'lt'),
('vakar', 'A1', 'lt'),
('vardas', 'A1', 'lt'),
('adresas', 'A1', 'lt'),
('numeris', 'A1', 'lt'),
('oro uostas', 'A2', 'lt'),
('Skrydis', 'A2', 'lt'),
('bilietas', 'A2', 'lt'),
('Pasas', 'A2', 'lt'),
('kelionė', 'A2', 'lt'),
('atostogos', 'A2', 'lt'),
('kelionė', 'A2', 'lt'),
('bagažas', 'A2', 'lt'),
('stotis', 'A2', 'lt'),
('Platforma', 'A2', 'lt'),
('restoranas', 'A2', 'lt'),
('Kavinė', 'A2', 'lt'),
('Pusryčiai', 'A2', 'lt'),
('pietūs', 'A2', 'lt'),
('Vakarienė', 'A2', 'lt'),
('daržovės', 'A2', 'lt'),
('vaisius', 'A2', 'lt'),
('Mėsa', 'A2', 'lt'),
('vištiena', 'A2', 'lt'),
('jautiena', 'A2', 'lt'),
('žuvis', 'A2', 'lt'),
('Duona', 'A2', 'lt'),
('ryžiai', 'A2', 'lt'),
('makaronai', 'A2', 'lt'),
('sriuba', 'A2', 'lt'),
('cukrus', 'A2', 'lt'),
('druska', 'A2', 'lt'),
('pipirai', 'A2', 'lt'),
('aliejus', 'A2', 'lt'),
('apsipirkimas', 'A2', 'lt'),
('drabužiai', 'A2', 'lt'),
('marškinėliai', 'A2', 'lt'),
('kelnės', 'A2', 'lt'),
('Suknelė', 'A2', 'lt'),
('batai', 'A2', 'lt'),
('skrybėlė', 'A2', 'lt'),
('striukė', 'A2', 'lt'),
('paltas', 'A2', 'lt'),
('oras', 'A2', 'lt'),
('sniegas', 'A2', 'lt'),
('vėjas', 'A2', 'lt'),
('audra', 'A2', 'lt'),
('viešbučiai', 'A2', 'lt'),
('svečias', 'A2', 'lt'),
('aptarnavimas', 'A2', 'lt'),
('priėmimas', 'A2', 'lt'),
('raktas', 'A2', 'lt'),
('rezervacija', 'A2', 'lt'),
('Paplūdimys', 'A2', 'lt'),
('jūra', 'A2', 'lt'),
('plaukimas', 'A2', 'lt'),
('baseinas', 'A2', 'lt'),
('kalnas', 'A2', 'lt'),
('kaimas', 'A2', 'lt'),
('šalis', 'A2', 'lt'),
('kalba', 'A2', 'lt'),
('svetimas', 'A2', 'lt'),
('egzaminas', 'A2', 'lt'),
('testas', 'A2', 'lt'),
('Namų darbai', 'A2', 'lt'),
('klasė', 'A2', 'lt'),
('tema', 'A2', 'lt'),
('matematika', 'A2', 'lt'),
('Istorija', 'A2', 'lt'),
('mokslas', 'A2', 'lt'),
('biblioteka', 'A2', 'lt'),
('knygynas', 'A2', 'lt'),
('kompiuteris', 'A2', 'lt'),
('Internetas', 'A2', 'lt'),
('el. Paštas', 'A2', 'lt'),
('pranešimas', 'A2', 'lt'),
('laiškas', 'A2', 'lt'),
('Skelbimas', 'A2', 'lt'),
('bankas', 'A2', 'lt'),
('pinigai', 'A2', 'lt'),
('kreditinė kortelė', 'A2', 'lt'),
('kaina', 'A2', 'lt'),
('pigu', 'A2', 'lt'),
('brangus', 'A2', 'lt'),
('klausimas', 'A2', 'lt'),
('atsakymas', 'A2', 'lt'),
('paaiškinti', 'A2', 'lt'),
('padėti', 'A2', 'lt'),
('problema', 'A2', 'lt'),
('Sprendimas', 'A2', 'lt'),
('sveikata', 'A2', 'lt'),
('vaistas', 'A2', 'lt'),
('gydytojas', 'A2', 'lt'),
('slaugytoja', 'A2', 'lt'),
('pacientas', 'A2', 'lt'),
('paskyrimas', 'A2', 'lt'),
('karščiavimas', 'A2', 'lt'),
('kosulys', 'A2', 'lt'),
('patirtis', 'B1', 'lt'),
('Nuotykis', 'B1', 'lt'),
('nuomonė', 'B1', 'lt'),
('Diskusija', 'B1', 'lt'),
('argumentas', 'B1', 'lt'),
('sprendimas', 'B1', 'lt'),
('Priežastis', 'B1', 'lt'),
('galimybė', 'B1', 'lt'),
('iššūkis', 'B1', 'lt'),
('Sėkmė', 'B1', 'lt'),
('nesėkmė', 'B1', 'lt'),
('tikslas', 'B1', 'lt'),
('suplanuoti', 'B1', 'lt'),
('projektas', 'B1', 'lt'),
('žinios', 'B1', 'lt'),
('Įgūdis', 'B1', 'lt'),
('sugebėjimas', 'B1', 'lt'),
('tobulinimas', 'B1', 'lt'),
('mokymas', 'B1', 'lt'),
('Darbo interviu', 'B1', 'lt'),
('paraiška', 'B1', 'lt'),
('karjera', 'B1', 'lt'),
('vadybininkas', 'B1', 'lt'),
('kolega', 'B1', 'lt'),
('susitikimas', 'B1', 'lt'),
('užduotis', 'B1', 'lt'),
('atsakomybė', 'B1', 'lt'),
('atostogų kelionė', 'B1', 'lt'),
('kultūra', 'B1', 'lt'),
('tradicija', 'B1', 'lt'),
('paprotys', 'B1', 'lt'),
('festivalis', 'B1', 'lt'),
('šventė', 'B1', 'lt'),
('Spektaklis', 'B1', 'lt'),
('koncertas', 'B1', 'lt'),
('teatras', 'B1', 'lt'),
('Paroda', 'B1', 'lt'),
('Tapyba', 'B1', 'lt'),
('Skulptūra', 'B1', 'lt'),
('muziejus', 'B1', 'lt'),
('Istorijos knyga', 'B1', 'lt'),
('Fikcija', 'B1', 'lt'),
('eilėraštis', 'B1', 'lt'),
('romanas', 'B1', 'lt'),
('personažas', 'B1', 'lt'),
('Sklypas', 'B1', 'lt'),
('Istorija', 'B1', 'lt'),
('laikraštis', 'B1', 'lt'),
('Žurnalas', 'B1', 'lt'),
('straipsnis', 'B1', 'lt'),
('pranešti', 'B1', 'lt'),
('Pristatymas', 'B1', 'lt'),
('paskaita', 'B1', 'lt'),
('išsilavinimas', 'B1', 'lt'),
('Universitetas', 'B1', 'lt'),
('laipsnis', 'B1', 'lt'),
('diplomas', 'B1', 'lt'),
('pažymėjimas', 'B1', 'lt'),
('aplinka', 'B1', 'lt'),
('prigimtis', 'B1', 'lt'),
('perdirbimas', 'B1', 'lt'),
('Tarša', 'B1', 'lt'),
('klimato pokyčiai', 'B1', 'lt'),
('Visuotinis atšilimas', 'B1', 'lt'),
('energija', 'B1', 'lt'),
('Technologija', 'B1', 'lt'),
('Naujovės', 'B1', 'lt'),
('išradimas', 'B1', 'lt'),
('prietaisas', 'B1', 'lt'),
('mašina', 'B1', 'lt'),
('Kompiuterių programa', 'B1', 'lt'),
('svetainė', 'B1', 'lt'),
('paraiška', 'B1', 'lt'),
('Socialinė žiniasklaida', 'B1', 'lt'),
('bendravimas', 'B1', 'lt'),
('Pokalbis', 'B1', 'lt'),
('sąveika', 'B1', 'lt'),
('santykiai', 'B1', 'lt'),
('draugystė', 'B1', 'lt'),
('santuoka', 'B1', 'lt'),
('Šeimos gyvenimas', 'B1', 'lt'),
('laimė', 'B1', 'lt'),
('pyktis', 'B1', 'lt'),
('baimė', 'B1', 'lt'),
('Viltis', 'B1', 'lt'),
('Svajok', 'B1', 'lt'),
('ambicija', 'B1', 'lt'),
('motyvacija', 'B1', 'lt'),
('pasitikėjimas', 'B1', 'lt'),
('smalsumas', 'B1', 'lt'),
('kantrybė', 'B1', 'lt'),
('Naujovės', 'B2', 'lt'),
('plėtra', 'B2', 'lt'),
('tyrimai', 'B2', 'lt'),
('analizė', 'B2', 'lt'),
('aiškinimas', 'B2', 'lt'),
('Argumentacija', 'B2', 'lt'),
('palyginimas', 'B2', 'lt'),
('Hipotezė', 'B2', 'lt'),
('teorija', 'B2', 'lt'),
('eksperimentas', 'B2', 'lt'),
('įrodymai', 'B2', 'lt'),
('metodas', 'B2', 'lt'),
('Išvada', 'B2', 'lt'),
('Stebėjimas', 'B2', 'lt'),
('perspektyva', 'B2', 'lt'),
('prielaida', 'B2', 'lt'),
('kontekstas', 'B2', 'lt'),
('kriterijai', 'B2', 'lt'),
('principas', 'B2', 'lt'),
('prioritetas', 'B2', 'lt'),
('Sudėtingumas', 'B2', 'lt'),
('efektyvumas', 'B2', 'lt'),
('produktyvumas', 'B2', 'lt'),
('investicija', 'B2', 'lt'),
('ekonomika', 'B2', 'lt'),
('Finansai', 'B2', 'lt'),
('Derybos', 'B2', 'lt'),
('susitarimas', 'B2', 'lt'),
('sutartis', 'B2', 'lt'),
('politika', 'B2', 'lt'),
('Vyriausybė', 'B2', 'lt'),
('Politika', 'B2', 'lt'),
('rinkimai', 'B2', 'lt'),
('Demokratija', 'B2', 'lt'),
('laisvė', 'B2', 'lt'),
('teisingumas', 'B2', 'lt'),
('lygybė', 'B2', 'lt'),
('įstatymas', 'B2', 'lt'),
('nusikaltimas', 'B2', 'lt'),
('bausmė', 'B2', 'lt'),
('bausmė', 'B2', 'lt'),
('saugumas', 'B2', 'lt'),
('konfliktas', 'B2', 'lt'),
('karas', 'B2', 'lt'),
('taika', 'B2', 'lt'),
('smurtas', 'B2', 'lt'),
('terorizmas', 'B2', 'lt'),
('Globalizacija', 'B2', 'lt'),
('Integracija', 'B2', 'lt'),
('įvairovė', 'B2', 'lt'),
('tapatybė', 'B2', 'lt'),
('migracija', 'B2', 'lt'),
('pabėgėlis', 'B2', 'lt'),
('bendruomenė', 'B2', 'lt'),
('tinklas', 'B2', 'lt'),
('organizacija', 'B2', 'lt'),
('įstaiga', 'B2', 'lt'),
('Lyderystė', 'B2', 'lt'),
('valdymas', 'B2', 'lt'),
('planavimas', 'B2', 'lt'),
('strategija', 'B2', 'lt'),
('iniciatyva', 'B2', 'lt'),
('Kūrybiškumas', 'B2', 'lt'),
('Bendradarbiavimas', 'B2', 'lt'),
('Komandinis darbas', 'B2', 'lt'),
('atsakomybė', 'B2', 'lt'),
('atskaitomybė', 'B2', 'lt'),
('tvarumas', 'B2', 'lt'),
('Aplinkos apsauga', 'B2', 'lt'),
('atsinaujinanti energija', 'B2', 'lt'),
('Inovacijų procesas', 'B2', 'lt'),
('Kritinis mąstymas', 'B2', 'lt'),
('Problemų sprendimas', 'B2', 'lt'),
('sprendimų priėmimas', 'B2', 'lt'),
('laiko valdymas', 'B2', 'lt'),
('Savidisciplina', 'B2', 'lt'),
('adaptacija', 'B2', 'lt'),
('atsparumas', 'B2', 'lt'),
('Nepriklausomybė', 'B2', 'lt'),
('bendradarbiavimas', 'B2', 'lt'),
('pasitikėjimas', 'B2', 'lt'),
('pagarba', 'B2', 'lt'),
('Empatija', 'B2', 'lt'),
('lojalumas', 'B2', 'lt'),
('vientisumas', 'B2', 'lt'),
('etika', 'B2', 'lt'),
('moralė', 'B2', 'lt'),
('Filosofija', 'B2', 'lt'),
('Psichologija', 'B2', 'lt'),
('Sociologija', 'B2', 'lt'),
('Biologija', 'B2', 'lt'),
('Chemija', 'B2', 'lt'),
('fizika', 'B2', 'lt'),
('Kritinė analizė', 'C1', 'lt'),
('loginis samprotavimas', 'C1', 'lt'),
('aiškinimas', 'C1', 'lt'),
('gilus palyginimas', 'C1', 'lt'),
('mokslinė išvada', 'C1', 'lt'),
('Sudėtinga hipotezė', 'C1', 'lt'),
('Išplėstinė teorija', 'C1', 'lt'),
('Gilus eksperimentas', 'C1', 'lt'),
('išsamus įvertinimas', 'C1', 'lt'),
('Filosofinė diskusija', 'C1', 'lt'),
('stiprus argumentas', 'C1', 'lt'),
('apčiuopiami įrodymai', 'C1', 'lt'),
('prieštaringi įrodymai', 'C1', 'lt'),
('Anotacija koncepcija', 'C1', 'lt'),
('etinė padėtis', 'C1', 'lt'),
('Aukščiausia vertė', 'C1', 'lt'),
('Pagrindinis principas', 'C1', 'lt'),
('svarbiausias prioritetas', 'C1', 'lt'),
('Didelė atsakomybė', 'C1', 'lt'),
('esminis sprendimas', 'C1', 'lt'),
('sudėtingas valdymas', 'C1', 'lt'),
('strateginis planavimas', 'C1', 'lt'),
('Tvarus vystymasis', 'C1', 'lt'),
('Šiuolaikinė naujovė', 'C1', 'lt'),
('Pažangi kūrybiškumas', 'C1', 'lt'),
('Naujas atradimas', 'C1', 'lt'),
('novatoriškas išradimas', 'C1', 'lt'),
('ekonominė analizė', 'C1', 'lt'),
('Finansinė ataskaita', 'C1', 'lt'),
('Didelio masto projektas', 'C1', 'lt'),
('Tarptautinės derybos', 'C1', 'lt'),
('oficialus susitarimas', 'C1', 'lt'),
('Veiksminga strategija', 'C1', 'lt'),
('Pasaulinė institucija', 'C1', 'lt'),
('Tyrimų centras', 'C1', 'lt'),
('Išplėstinis mokslinis tyrimas', 'C1', 'lt'),
('Kritinė apžvalga', 'C1', 'lt'),
('Filosofinis aiškinimas', 'C1', 'lt'),
('Sistemingas požiūris', 'C1', 'lt'),
('Šiuolaikinė teorija', 'C1', 'lt'),
('Taikomieji tyrimai', 'C1', 'lt'),
('praktinis eksperimentas', 'C1', 'lt'),
('objektyvus vertinimas', 'C1', 'lt'),
('išsamūs rezultatai', 'C1', 'lt'),
('Pažangios diskusijos', 'C1', 'lt'),
('Lyginamasis tyrimas', 'C1', 'lt'),
('Lauko tyrimai', 'C1', 'lt'),
('praktinė rekomendacija', 'C1', 'lt'),
('Pažangios įgūdžiai', 'C1', 'lt'),
('Konceptuali sistema', 'C1', 'lt'),
('Tikslus planavimas', 'C1', 'lt'),
('Ilgalaikė strategija', 'C1', 'lt'),
('rizikos vertinimas', 'C1', 'lt'),
('Akademinė apžvalga', 'C1', 'lt'),
('tyrimų projektas', 'C1', 'lt'),
('Mokslinė naujovė', 'C1', 'lt'),
('Technologinė plėtra', 'C1', 'lt'),
('Literatūrinė analizė', 'C1', 'lt'),
('mokslinės išvados', 'C1', 'lt'),
('Pažangi aiškinimas', 'C1', 'lt'),
('Holistinis vaizdas', 'C1', 'lt'),
('įgyvendinimo planas', 'C1', 'lt'),
('strateginis sprendimas', 'C1', 'lt'),
('Išteklių valdymas', 'C1', 'lt'),
('Sudėtingi iššūkiai', 'C1', 'lt'),
('novatoriški sprendimai', 'C1', 'lt'),
('išsamus požiūris', 'C1', 'lt'),
('Duomenų analizė', 'C1', 'lt'),
('Hipotezės tikrinimas', 'C1', 'lt'),
('Atvejo analizė', 'C1', 'lt'),
('Išplėstiniai lauko darbai', 'C1', 'lt'),
('Filosofinė apžvalga', 'C1', 'lt'),
('Taikomojo tyrimų projektas', 'C1', 'lt'),
('Akademinė diskusija', 'C1', 'lt'),
('Strateginis vertinimas', 'C1', 'lt'),
('Praktinės rekomendacijos', 'C1', 'lt'),
('darbo planas', 'C1', 'lt'),
('Projekto valdymas', 'C1', 'lt'),
('Akademinis leidinys', 'C1', 'lt'),
('mokslinis atradimas', 'C1', 'lt'),
('Taikomosios naujovės', 'C1', 'lt'),
('Nuolatinis vystymasis', 'C1', 'lt'),
('Išsami duomenų analizė', 'C1', 'lt'),
('Tyrimo patirtis', 'C1', 'lt'),
('mokslinis aiškinimas', 'C1', 'lt'),
('kritinė perspektyva', 'C1', 'lt');
