INSERT INTO words (word, level, language_code) VALUES
('casa', 'A1', 'it'),
('porta', 'A1', 'it'),
('finestra', 'A1', 'it'),
('tavolo', 'A1', 'it'),
('sedia', 'A1', 'it'),
('libro', 'A1', 'it'),
('penna', 'A1', 'it'),
('scuola', 'A1', 'it'),
('insegnante', 'A1', 'it'),
('studente', 'A1', 'it'),
('mela', 'A1', 'it'),
('acqua', 'A1', 'it'),
('cibo', 'A1', 'it'),
('auto', 'A1', 'it'),
('autobus', 'A1', 'it'),
('strada', 'A1', 'it'),
('amico', 'A1', 'it'),
('famiglia', 'A1', 'it'),
('madre', 'A1', 'it'),
('padre', 'A1', 'it'),
('sorella', 'A1', 'it'),
('fratello', 'A1', 'it'),
('giorno', 'A1', 'it'),
('notte', 'A1', 'it'),
('Mattina', 'A1', 'it'),
('sera', 'A1', 'it'),
('Ciao', 'A1', 'it'),
('arrivederci', 'A1', 'it'),
('Per favore', 'A1', 'it'),
('Grazie', 'A1', 'it'),
('SÌ', 'A1', 'it'),
('NO', 'A1', 'it'),
('rosso', 'A1', 'it'),
('blu', 'A1', 'it'),
('verde', 'A1', 'it'),
('bianco', 'A1', 'it'),
('nero', 'A1', 'it'),
('piccolo', 'A1', 'it'),
('grande', 'A1', 'it'),
('Bene', 'A1', 'it'),
('Cattivo', 'A1', 'it'),
('caldo', 'A1', 'it'),
('Freddo', 'A1', 'it'),
('caffè', 'A1', 'it'),
('tè', 'A1', 'it'),
('soldi', 'A1', 'it'),
('lavoro', 'A1', 'it'),
('casa', 'A1', 'it'),
('negozio', 'A1', 'it'),
('mercato', 'A1', 'it'),
('cibo', 'A1', 'it'),
('bere', 'A1', 'it'),
('città', 'A1', 'it'),
('parco', 'A1', 'it'),
('strada', 'A1', 'it'),
('fermata dell''autobus', 'A1', 'it'),
('treno', 'A1', 'it'),
('stazione', 'A1', 'it'),
('hotel', 'A1', 'it'),
('camera', 'A1', 'it'),
('letto', 'A1', 'it'),
('medico', 'A1', 'it'),
('Ospedale', 'A1', 'it'),
('scuola', 'A1', 'it'),
('università', 'A1', 'it'),
('computer', 'A1', 'it'),
('telefono', 'A1', 'it'),
('televisione', 'A1', 'it'),
('musica', 'A1', 'it'),
('canzone', 'A1', 'it'),
('film', 'A1', 'it'),
('gioco', 'A1', 'it'),
('calcio', 'A1', 'it'),
('palla', 'A1', 'it'),
('acqua', 'A1', 'it'),
('piovere', 'A1', 'it'),
('sole', 'A1', 'it'),
('cielo', 'A1', 'it'),
('albero', 'A1', 'it'),
('fiore', 'A1', 'it'),
('animale', 'A1', 'it'),
('gatto', 'A1', 'it'),
('cane', 'A1', 'it'),
('uccello', 'A1', 'it'),
('pescare', 'A1', 'it'),
('Uomo', 'A1', 'it'),
('donna', 'A1', 'it'),
('bambino', 'A1', 'it'),
('persone', 'A1', 'it'),
('strada', 'A1', 'it'),
('posto', 'A1', 'it'),
('tempo', 'A1', 'it'),
('anno', 'A1', 'it'),
('mese', 'A1', 'it'),
('settimana', 'A1', 'it'),
('Oggi', 'A1', 'it'),
('Domani', 'A1', 'it'),
('Ieri', 'A1', 'it'),
('nome', 'A1', 'it'),
('indirizzo', 'A1', 'it'),
('numero', 'A1', 'it'),
('aeroporto', 'A2', 'it'),
('volo', 'A2', 'it'),
('biglietto', 'A2', 'it'),
('passaporto', 'A2', 'it'),
('viaggio', 'A2', 'it'),
('vacanza', 'A2', 'it'),
('viaggio', 'A2', 'it'),
('bagaglio', 'A2', 'it'),
('stazione', 'A2', 'it'),
('piattaforma', 'A2', 'it'),
('ristorante', 'A2', 'it'),
('caffè', 'A2', 'it'),
('colazione', 'A2', 'it'),
('pranzo', 'A2', 'it'),
('cena', 'A2', 'it'),
('verdure', 'A2', 'it'),
('frutta', 'A2', 'it'),
('carne', 'A2', 'it'),
('pollo', 'A2', 'it'),
('manzo', 'A2', 'it'),
('pescare', 'A2', 'it'),
('pane', 'A2', 'it'),
('riso', 'A2', 'it'),
('pasta', 'A2', 'it'),
('minestra', 'A2', 'it'),
('zucchero', 'A2', 'it'),
('sale', 'A2', 'it'),
('pepe', 'A2', 'it'),
('olio', 'A2', 'it'),
('shopping', 'A2', 'it'),
('vestiti', 'A2', 'it'),
('camicia', 'A2', 'it'),
('pantaloni', 'A2', 'it'),
('vestito', 'A2', 'it'),
('scarpe', 'A2', 'it'),
('cappello', 'A2', 'it'),
('giacca', 'A2', 'it'),
('cappotto', 'A2', 'it'),
('tempo atmosferico', 'A2', 'it'),
('nevicare', 'A2', 'it'),
('vento', 'A2', 'it'),
('tempesta', 'A2', 'it'),
('Hotel', 'A2', 'it'),
('ospite', 'A2', 'it'),
('servizio', 'A2', 'it'),
('reception', 'A2', 'it'),
('chiave', 'A2', 'it'),
('prenotazione', 'A2', 'it'),
('spiaggia', 'A2', 'it'),
('mare', 'A2', 'it'),
('nuoto', 'A2', 'it'),
('piscina', 'A2', 'it'),
('montagna', 'A2', 'it'),
('villaggio', 'A2', 'it'),
('Paese', 'A2', 'it'),
('lingua', 'A2', 'it'),
('straniero', 'A2', 'it'),
('esame', 'A2', 'it'),
('test', 'A2', 'it'),
('compiti a casa', 'A2', 'it'),
('classe', 'A2', 'it'),
('soggetto', 'A2', 'it'),
('matematica', 'A2', 'it'),
('storia', 'A2', 'it'),
('scienza', 'A2', 'it'),
('biblioteca', 'A2', 'it'),
('libreria', 'A2', 'it'),
('computer', 'A2', 'it'),
('Internet', 'A2', 'it'),
('e-mail', 'A2', 'it'),
('messaggio', 'A2', 'it'),
('lettera', 'A2', 'it'),
('inviare', 'A2', 'it'),
('banca', 'A2', 'it'),
('soldi', 'A2', 'it'),
('carta di credito', 'A2', 'it'),
('prezzo', 'A2', 'it'),
('economico', 'A2', 'it'),
('costoso', 'A2', 'it'),
('domanda', 'A2', 'it'),
('risposta', 'A2', 'it'),
('spiegare', 'A2', 'it'),
('aiuto', 'A2', 'it'),
('problema', 'A2', 'it'),
('soluzione', 'A2', 'it'),
('salute', 'A2', 'it'),
('medicinale', 'A2', 'it'),
('medico', 'A2', 'it'),
('infermiera', 'A2', 'it'),
('paziente', 'A2', 'it'),
('appuntamento', 'A2', 'it'),
('febbre', 'A2', 'it'),
('tosse', 'A2', 'it'),
('esperienza', 'B1', 'it'),
('avventura', 'B1', 'it'),
('opinione', 'B1', 'it'),
('discussione', 'B1', 'it'),
('discussione', 'B1', 'it'),
('decisione', 'B1', 'it'),
('motivo', 'B1', 'it'),
('opportunità', 'B1', 'it'),
('sfida', 'B1', 'it'),
('successo', 'B1', 'it'),
('fallimento', 'B1', 'it'),
('obiettivo', 'B1', 'it'),
('piano', 'B1', 'it'),
('progetto', 'B1', 'it'),
('conoscenza', 'B1', 'it'),
('abilità', 'B1', 'it'),
('capacità', 'B1', 'it'),
('miglioramento', 'B1', 'it'),
('formazione', 'B1', 'it'),
('colloquio di lavoro', 'B1', 'it'),
('applicazione', 'B1', 'it'),
('carriera', 'B1', 'it'),
('manager', 'B1', 'it'),
('collega', 'B1', 'it'),
('incontro', 'B1', 'it'),
('compito', 'B1', 'it'),
('responsabilità', 'B1', 'it'),
('viaggio di vacanza', 'B1', 'it'),
('cultura', 'B1', 'it'),
('tradizione', 'B1', 'it'),
('costume', 'B1', 'it'),
('festival', 'B1', 'it'),
('celebrazione', 'B1', 'it'),
('prestazione', 'B1', 'it'),
('concerto', 'B1', 'it'),
('teatro', 'B1', 'it'),
('mostra', 'B1', 'it'),
('pittura', 'B1', 'it'),
('scultura', 'B1', 'it'),
('museo', 'B1', 'it'),
('libro di storia', 'B1', 'it'),
('Fiction', 'B1', 'it'),
('poesia', 'B1', 'it'),
('romanzo', 'B1', 'it'),
('carattere', 'B1', 'it'),
('complotto', 'B1', 'it'),
('storia', 'B1', 'it'),
('giornale', 'B1', 'it'),
('rivista', 'B1', 'it'),
('articolo', 'B1', 'it'),
('rapporto', 'B1', 'it'),
('presentazione', 'B1', 'it'),
('lezione', 'B1', 'it'),
('istruzione', 'B1', 'it'),
('università', 'B1', 'it'),
('grado', 'B1', 'it'),
('diploma', 'B1', 'it'),
('certificato', 'B1', 'it'),
('ambiente', 'B1', 'it'),
('natura', 'B1', 'it'),
('riciclaggio', 'B1', 'it'),
('inquinamento', 'B1', 'it'),
('Cambiamento climatico', 'B1', 'it'),
('il riscaldamento globale', 'B1', 'it'),
('energia', 'B1', 'it'),
('tecnologia', 'B1', 'it'),
('innovazione', 'B1', 'it'),
('invenzione', 'B1', 'it'),
('dispositivo', 'B1', 'it'),
('macchina', 'B1', 'it'),
('programma per computer', 'B1', 'it'),
('sito web', 'B1', 'it'),
('applicazione', 'B1', 'it'),
('social media', 'B1', 'it'),
('comunicazione', 'B1', 'it'),
('conversazione', 'B1', 'it'),
('interazione', 'B1', 'it'),
('relazione', 'B1', 'it'),
('amicizia', 'B1', 'it'),
('matrimonio', 'B1', 'it'),
('vita familiare', 'B1', 'it'),
('felicità', 'B1', 'it'),
('rabbia', 'B1', 'it'),
('Paura', 'B1', 'it'),
('Speranza', 'B1', 'it'),
('sogno', 'B1', 'it'),
('ambizione', 'B1', 'it'),
('motivazione', 'B1', 'it'),
('fiducia', 'B1', 'it'),
('curiosità', 'B1', 'it'),
('pazienza', 'B1', 'it'),
('innovazione', 'B2', 'it'),
('sviluppo', 'B2', 'it'),
('ricerca', 'B2', 'it'),
('analisi', 'B2', 'it'),
('interpretazione', 'B2', 'it'),
('argomentazione', 'B2', 'it'),
('confronto', 'B2', 'it'),
('ipotesi', 'B2', 'it'),
('teoria', 'B2', 'it'),
('sperimentare', 'B2', 'it'),
('prova', 'B2', 'it'),
('metodo', 'B2', 'it'),
('conclusione', 'B2', 'it'),
('osservazione', 'B2', 'it'),
('prospettiva', 'B2', 'it'),
('assunzione', 'B2', 'it'),
('contesto', 'B2', 'it'),
('criteri', 'B2', 'it'),
('principio', 'B2', 'it'),
('priorità', 'B2', 'it'),
('complessità', 'B2', 'it'),
('efficienza', 'B2', 'it'),
('produttività', 'B2', 'it'),
('investimento', 'B2', 'it'),
('economia', 'B2', 'it'),
('finanza', 'B2', 'it'),
('negoziazione', 'B2', 'it'),
('accordo', 'B2', 'it'),
('contrarre', 'B2', 'it'),
('politica', 'B2', 'it'),
('governo', 'B2', 'it'),
('politica', 'B2', 'it'),
('elezione', 'B2', 'it'),
('democrazia', 'B2', 'it'),
('libertà', 'B2', 'it'),
('giustizia', 'B2', 'it'),
('uguaglianza', 'B2', 'it'),
('legge', 'B2', 'it'),
('crimine', 'B2', 'it'),
('pena', 'B2', 'it'),
('punizione', 'B2', 'it'),
('sicurezza', 'B2', 'it'),
('conflitto', 'B2', 'it'),
('guerra', 'B2', 'it'),
('pace', 'B2', 'it'),
('violenza', 'B2', 'it'),
('terrorismo', 'B2', 'it'),
('globalizzazione', 'B2', 'it'),
('integrazione', 'B2', 'it'),
('diversità', 'B2', 'it'),
('identità', 'B2', 'it'),
('migrazione', 'B2', 'it'),
('rifugiato', 'B2', 'it'),
('comunità', 'B2', 'it'),
('rete', 'B2', 'it'),
('organizzazione', 'B2', 'it'),
('istituzione', 'B2', 'it'),
('leadership', 'B2', 'it'),
('gestione', 'B2', 'it'),
('pianificazione', 'B2', 'it'),
('strategia', 'B2', 'it'),
('iniziativa', 'B2', 'it'),
('creatività', 'B2', 'it'),
('collaborazione', 'B2', 'it'),
('lavoro di squadra', 'B2', 'it'),
('responsabilità', 'B2', 'it'),
('responsabilità', 'B2', 'it'),
('sostenibilità', 'B2', 'it'),
('Protezione ambientale', 'B2', 'it'),
('energia rinnovabile', 'B2', 'it'),
('processo di innovazione', 'B2', 'it'),
('Pensiero critico', 'B2', 'it'),
('Risoluzione dei problemi', 'B2', 'it'),
('il processo decisionale', 'B2', 'it'),
('Gestione del tempo', 'B2', 'it'),
('autodisciplina', 'B2', 'it'),
('adattamento', 'B2', 'it'),
('resilienza', 'B2', 'it'),
('indipendenza', 'B2', 'it'),
('cooperazione', 'B2', 'it'),
('Fiducia', 'B2', 'it'),
('rispetto', 'B2', 'it'),
('empatia', 'B2', 'it'),
('lealtà', 'B2', 'it'),
('integrità', 'B2', 'it'),
('etica', 'B2', 'it'),
('moralità', 'B2', 'it'),
('filosofia', 'B2', 'it'),
('psicologia', 'B2', 'it'),
('sociologia', 'B2', 'it'),
('biologia', 'B2', 'it'),
('chimica', 'B2', 'it'),
('fisica', 'B2', 'it'),
('Analisi critica', 'C1', 'it'),
('ragionamento logico', 'C1', 'it'),
('interpretazione', 'C1', 'it'),
('Confronto profondo', 'C1', 'it'),
('Conclusione scientifica', 'C1', 'it'),
('ipotesi complessa', 'C1', 'it'),
('teoria avanzata', 'C1', 'it'),
('esperimento approfondito', 'C1', 'it'),
('Valutazione completa', 'C1', 'it'),
('discussione filosofica', 'C1', 'it'),
('forte argomento', 'C1', 'it'),
('prove tangibili', 'C1', 'it'),
('Prove contraddittorie', 'C1', 'it'),
('concetto astratto', 'C1', 'it'),
('posizione etica', 'C1', 'it'),
('valore supremo', 'C1', 'it'),
('Principio fondamentale', 'C1', 'it'),
('priorità assoluta', 'C1', 'it'),
('grande responsabilità', 'C1', 'it'),
('decisione cruciale', 'C1', 'it'),
('gestione complessa', 'C1', 'it'),
('Pianificazione strategica', 'C1', 'it'),
('sviluppo sostenibile', 'C1', 'it'),
('innovazione moderna', 'C1', 'it'),
('creatività avanzata', 'C1', 'it'),
('Nuova scoperta', 'C1', 'it'),
('invenzione innovativa', 'C1', 'it'),
('Analisi economica', 'C1', 'it'),
('Rapporto finanziario', 'C1', 'it'),
('Progetto su larga scala', 'C1', 'it'),
('negoziati internazionali', 'C1', 'it'),
('accordo formale', 'C1', 'it'),
('Strategia efficace', 'C1', 'it'),
('istituzione globale', 'C1', 'it'),
('Centro di ricerca', 'C1', 'it'),
('Studio scientifico avanzato', 'C1', 'it'),
('Revisione critica', 'C1', 'it'),
('Interpretazione filosofica', 'C1', 'it'),
('approccio sistematico', 'C1', 'it'),
('teoria moderna', 'C1', 'it'),
('ricerca applicata', 'C1', 'it'),
('esperimento pratico', 'C1', 'it'),
('Valutazione oggettiva', 'C1', 'it'),
('Risultati dettagliati', 'C1', 'it'),
('dibattito avanzato', 'C1', 'it'),
('studio comparativo', 'C1', 'it'),
('Ricerca sul campo', 'C1', 'it'),
('Raccomandazione pratica', 'C1', 'it'),
('Abilità avanzata', 'C1', 'it'),
('quadro concettuale', 'C1', 'it'),
('Pianificazione precisa', 'C1', 'it'),
('Strategia a lungo termine', 'C1', 'it'),
('valutazione del rischio', 'C1', 'it'),
('Revisione accademica', 'C1', 'it'),
('Progetto di ricerca', 'C1', 'it'),
('innovazione scientifica', 'C1', 'it'),
('Sviluppo tecnologico', 'C1', 'it'),
('Analisi letteraria', 'C1', 'it'),
('Risultati scientifici', 'C1', 'it'),
('interpretazione avanzata', 'C1', 'it'),
('Vista olistica', 'C1', 'it'),
('piano di attuazione', 'C1', 'it'),
('decisione strategica', 'C1', 'it'),
('Gestione delle risorse', 'C1', 'it'),
('sfide complesse', 'C1', 'it'),
('soluzioni innovative', 'C1', 'it'),
('Approccio globale', 'C1', 'it'),
('Analisi dei dati', 'C1', 'it'),
('test di ipotesi', 'C1', 'it'),
('Caso di studio', 'C1', 'it'),
('lavoro sul campo avanzato', 'C1', 'it'),
('Revisione filosofica', 'C1', 'it'),
('Progetto di ricerca applicata', 'C1', 'it'),
('discussione accademica', 'C1', 'it'),
('Valutazione strategica', 'C1', 'it'),
('Raccomandazioni pratiche', 'C1', 'it'),
('piano di lavoro', 'C1', 'it'),
('gestione del progetto', 'C1', 'it'),
('Pubblicazione accademica', 'C1', 'it'),
('scoperta scientifica', 'C1', 'it'),
('innovazione applicata', 'C1', 'it'),
('sviluppo continuo', 'C1', 'it'),
('Analisi dei dati approfonditi', 'C1', 'it'),
('esperienza di ricerca', 'C1', 'it'),
('interpretazione scientifica', 'C1', 'it'),
('prospettiva critica', 'C1', 'it');
