INSERT INTO words (word, level, language_code) VALUES
('dom', 'A1', 'sk'),
('dvere', 'A1', 'sk'),
('okno', 'A1', 'sk'),
('tabuľka', 'A1', 'sk'),
('stolička', 'A1', 'sk'),
('rezervovať', 'A1', 'sk'),
('pero', 'A1', 'sk'),
('školský', 'A1', 'sk'),
('učiteľ', 'A1', 'sk'),
('študent', 'A1', 'sk'),
('jablko', 'A1', 'sk'),
('vodná voda', 'A1', 'sk'),
('jedlo', 'A1', 'sk'),
('auto', 'A1', 'sk'),
('autobus', 'A1', 'sk'),
('ulic', 'A1', 'sk'),
('priateľ', 'A1', 'sk'),
('rodina', 'A1', 'sk'),
('matka', 'A1', 'sk'),
('otca', 'A1', 'sk'),
('sestra', 'A1', 'sk'),
('brat', 'A1', 'sk'),
('deň', 'A1', 'sk'),
('noc', 'A1', 'sk'),
('ráno', 'A1', 'sk'),
('večerný', 'A1', 'sk'),
('ahoj', 'A1', 'sk'),
('zbohom', 'A1', 'sk'),
('prosím', 'A1', 'sk'),
('Ďakujem', 'A1', 'sk'),
('áno', 'A1', 'sk'),
('nie', 'A1', 'sk'),
('červený', 'A1', 'sk'),
('modrý', 'A1', 'sk'),
('zelený', 'A1', 'sk'),
('biely', 'A1', 'sk'),
('čierny', 'A1', 'sk'),
('malý', 'A1', 'sk'),
('veľký', 'A1', 'sk'),
('dobrý', 'A1', 'sk'),
('zlý', 'A1', 'sk'),
('horúci', 'A1', 'sk'),
('zima', 'A1', 'sk'),
('káva', 'A1', 'sk'),
('čaj', 'A1', 'sk'),
('peniaze', 'A1', 'sk'),
('pracovať', 'A1', 'sk'),
('domov', 'A1', 'sk'),
('obchod', 'A1', 'sk'),
('trh', 'A1', 'sk'),
('jedlo', 'A1', 'sk'),
('piť', 'A1', 'sk'),
('mesto', 'A1', 'sk'),
('park', 'A1', 'sk'),
('ulic', 'A1', 'sk'),
('zastávka autobusu', 'A1', 'sk'),
('vlak', 'A1', 'sk'),
('stanica', 'A1', 'sk'),
('hotel', 'A1', 'sk'),
('izba', 'A1', 'sk'),
('posteľ', 'A1', 'sk'),
('lekár', 'A1', 'sk'),
('NEMOCNICA', 'A1', 'sk'),
('školský', 'A1', 'sk'),
('univerzita', 'A1', 'sk'),
('počítač', 'A1', 'sk'),
('telefonovať', 'A1', 'sk'),
('televízia', 'A1', 'sk'),
('hudba', 'A1', 'sk'),
('pieseň', 'A1', 'sk'),
('film', 'A1', 'sk'),
('hra', 'A1', 'sk'),
('futbal', 'A1', 'sk'),
('loptička', 'A1', 'sk'),
('vodná voda', 'A1', 'sk'),
('dážď', 'A1', 'sk'),
('slnko', 'A1', 'sk'),
('obloha', 'A1', 'sk'),
('strom', 'A1', 'sk'),
('kvetina', 'A1', 'sk'),
('zviera', 'A1', 'sk'),
('mačka', 'A1', 'sk'),
('psa', 'A1', 'sk'),
('vták', 'A1', 'sk'),
('rybárstvo', 'A1', 'sk'),
('muž', 'A1', 'sk'),
('žena', 'A1', 'sk'),
('dieťa', 'A1', 'sk'),
('ľudia', 'A1', 'sk'),
('ulic', 'A1', 'sk'),
('miesto', 'A1', 'sk'),
('čas', 'A1', 'sk'),
('rok', 'A1', 'sk'),
('mesiac', 'A1', 'sk'),
('týždeň', 'A1', 'sk'),
('dnes', 'A1', 'sk'),
('zajtra', 'A1', 'sk'),
('včera', 'A1', 'sk'),
('pomenovať', 'A1', 'sk'),
('osloviť', 'A1', 'sk'),
('počet', 'A1', 'sk'),
('LETISKO', 'A2', 'sk'),
('odlet', 'A2', 'sk'),
('lístok', 'A2', 'sk'),
('pas', 'A2', 'sk'),
('cestovať', 'A2', 'sk'),
('dovolenka', 'A2', 'sk'),
('cestovať', 'A2', 'sk'),
('batožina', 'A2', 'sk'),
('stanica', 'A2', 'sk'),
('platforma', 'A2', 'sk'),
('reštaurácia', 'A2', 'sk'),
('kaviareň', 'A2', 'sk'),
('raňajky', 'A2', 'sk'),
('obed', 'A2', 'sk'),
('večera', 'A2', 'sk'),
('zelenina', 'A2', 'sk'),
('ovocie', 'A2', 'sk'),
('mäso', 'A2', 'sk'),
('kuracie mäso', 'A2', 'sk'),
('hovädzie mäso', 'A2', 'sk'),
('rybárstvo', 'A2', 'sk'),
('chlieb', 'A2', 'sk'),
('ryža', 'A2', 'sk'),
('cestovina', 'A2', 'sk'),
('polievka', 'A2', 'sk'),
('cukor', 'A2', 'sk'),
('soľ', 'A2', 'sk'),
('korenie', 'A2', 'sk'),
('olej', 'A2', 'sk'),
('nákup', 'A2', 'sk'),
('oblečenie', 'A2', 'sk'),
('tričko', 'A2', 'sk'),
('nohavice', 'A2', 'sk'),
('šaty', 'A2', 'sk'),
('topánky', 'A2', 'sk'),
('klobúk', 'A2', 'sk'),
('sako', 'A2', 'sk'),
('srsť', 'A2', 'sk'),
('zverenie', 'A2', 'sk'),
('sneh', 'A2', 'sk'),
('vŕtať', 'A2', 'sk'),
('búrka', 'A2', 'sk'),
('hotely', 'A2', 'sk'),
('hosť', 'A2', 'sk'),
('služba', 'A2', 'sk'),
('recepcia', 'A2', 'sk'),
('kľúč', 'A2', 'sk'),
('rezervácia', 'A2', 'sk'),
('pláž', 'A2', 'sk'),
('more', 'A2', 'sk'),
('plávať', 'A2', 'sk'),
('primievať', 'A2', 'sk'),
('hory', 'A2', 'sk'),
('dedina', 'A2', 'sk'),
('krajina', 'A2', 'sk'),
('jazyk', 'A2', 'sk'),
('zahraničný', 'A2', 'sk'),
('skúška', 'A2', 'sk'),
('skúška', 'A2', 'sk'),
('domáca úloha', 'A2', 'sk'),
('učebňa', 'A2', 'sk'),
('predmet', 'A2', 'sk'),
('matematika', 'A2', 'sk'),
('história', 'A2', 'sk'),
('veda', 'A2', 'sk'),
('knižnica', 'A2', 'sk'),
('kníhkupectvo', 'A2', 'sk'),
('počítač', 'A2', 'sk'),
('internet', 'A2', 'sk'),
('e -mail', 'A2', 'sk'),
('správa', 'A2', 'sk'),
('písmeno', 'A2', 'sk'),
('post', 'A2', 'sk'),
('breh', 'A2', 'sk'),
('peniaze', 'A2', 'sk'),
('kreditná karta', 'A2', 'sk'),
('cena', 'A2', 'sk'),
('lacný', 'A2', 'sk'),
('drahý', 'A2', 'sk'),
('spochybniť', 'A2', 'sk'),
('odpoveď', 'A2', 'sk'),
('vysvetliť', 'A2', 'sk'),
('pomoc', 'A2', 'sk'),
('problém', 'A2', 'sk'),
('riešenie', 'A2', 'sk'),
('zdravie', 'A2', 'sk'),
('liek', 'A2', 'sk'),
('lekár', 'A2', 'sk'),
('ošetrovať', 'A2', 'sk'),
('trpezlivý', 'A2', 'sk'),
('schôdzka', 'A2', 'sk'),
('horúčka', 'A2', 'sk'),
('kašeľ', 'A2', 'sk'),
('zážitok', 'B1', 'sk'),
('dobrodružstvo', 'B1', 'sk'),
('názor', 'B1', 'sk'),
('diskusia', 'B1', 'sk'),
('argument', 'B1', 'sk'),
('rozhodnutie', 'B1', 'sk'),
('odôvodniť', 'B1', 'sk'),
('príležitosť', 'B1', 'sk'),
('spochybniť', 'B1', 'sk'),
('úspech', 'B1', 'sk'),
('zlyhanie', 'B1', 'sk'),
('cieľ', 'B1', 'sk'),
('plán', 'B1', 'sk'),
('projekt', 'B1', 'sk'),
('znalosť', 'B1', 'sk'),
('zručnosť', 'B1', 'sk'),
('schopnosť', 'B1', 'sk'),
('zlepšenie', 'B1', 'sk'),
('výcvik', 'B1', 'sk'),
('pohovor', 'B1', 'sk'),
('aplikácia', 'B1', 'sk'),
('kariéra', 'B1', 'sk'),
('manažér', 'B1', 'sk'),
('kolega', 'B1', 'sk'),
('stretnutie', 'B1', 'sk'),
('úloha', 'B1', 'sk'),
('zodpovednosť', 'B1', 'sk'),
('výlet', 'B1', 'sk'),
('kultúra', 'B1', 'sk'),
('tradícia', 'B1', 'sk'),
('zvyk', 'B1', 'sk'),
('festival', 'B1', 'sk'),
('oslava', 'B1', 'sk'),
('výkonnosť', 'B1', 'sk'),
('koncert', 'B1', 'sk'),
('divadlo', 'B1', 'sk'),
('výstava', 'B1', 'sk'),
('maľba', 'B1', 'sk'),
('sochárstvo', 'B1', 'sk'),
('múzeum', 'B1', 'sk'),
('kniha histórie', 'B1', 'sk'),
('fikcia', 'B1', 'sk'),
('báseň', 'B1', 'sk'),
('nový', 'B1', 'sk'),
('znak', 'B1', 'sk'),
('graf', 'B1', 'sk'),
('príbeh', 'B1', 'sk'),
('noviny', 'B1', 'sk'),
('časopis', 'B1', 'sk'),
('článok', 'B1', 'sk'),
('uvádzanie', 'B1', 'sk'),
('prezentácia', 'B1', 'sk'),
('prednáška', 'B1', 'sk'),
('vzdelávanie', 'B1', 'sk'),
('univerzita', 'B1', 'sk'),
('titul', 'B1', 'sk'),
('diplom', 'B1', 'sk'),
('osvedčenie', 'B1', 'sk'),
('prostredie', 'B1', 'sk'),
('povaha', 'B1', 'sk'),
('recyklácia', 'B1', 'sk'),
('znečistenie', 'B1', 'sk'),
('zmena podnebia', 'B1', 'sk'),
('globálne otepľovanie', 'B1', 'sk'),
('energia', 'B1', 'sk'),
('technológia', 'B1', 'sk'),
('inovácia', 'B1', 'sk'),
('vynález', 'B1', 'sk'),
('zariadenie', 'B1', 'sk'),
('stroj', 'B1', 'sk'),
('počítačový program', 'B1', 'sk'),
('webová stránka', 'B1', 'sk'),
('aplikácia', 'B1', 'sk'),
('sociálne médiá', 'B1', 'sk'),
('komunikácia', 'B1', 'sk'),
('konverzácia', 'B1', 'sk'),
('interakcia', 'B1', 'sk'),
('vzťah', 'B1', 'sk'),
('priateľstvo', 'B1', 'sk'),
('manželstvo', 'B1', 'sk'),
('rodinný život', 'B1', 'sk'),
('šťastie', 'B1', 'sk'),
('hnev', 'B1', 'sk'),
('strach', 'B1', 'sk'),
('nádej', 'B1', 'sk'),
('snívať', 'B1', 'sk'),
('ambícia', 'B1', 'sk'),
('motivácia', 'B1', 'sk'),
('dôvera', 'B1', 'sk'),
('zvedavosť', 'B1', 'sk'),
('trpezlivosť', 'B1', 'sk'),
('inovácia', 'B2', 'sk'),
('rozvoj', 'B2', 'sk'),
('výskum', 'B2', 'sk'),
('analýza', 'B2', 'sk'),
('interpretácia', 'B2', 'sk'),
('argumentácia', 'B2', 'sk'),
('porovnanie', 'B2', 'sk'),
('hypotéza', 'B2', 'sk'),
('teória', 'B2', 'sk'),
('experimentovať', 'B2', 'sk'),
('dôkaz', 'B2', 'sk'),
('metóda', 'B2', 'sk'),
('záver', 'B2', 'sk'),
('pozorovanie', 'B2', 'sk'),
('perspektíva', 'B2', 'sk'),
('predpoklad', 'B2', 'sk'),
('kontext', 'B2', 'sk'),
('kritériá', 'B2', 'sk'),
('zásada', 'B2', 'sk'),
('priorita', 'B2', 'sk'),
('zložitosť', 'B2', 'sk'),
('účinnosť', 'B2', 'sk'),
('produktivita', 'B2', 'sk'),
('investícia', 'B2', 'sk'),
('hospodárnosť', 'B2', 'sk'),
('financovať', 'B2', 'sk'),
('vyjednávanie', 'B2', 'sk'),
('dohoda', 'B2', 'sk'),
('zmluva', 'B2', 'sk'),
('politika', 'B2', 'sk'),
('vláda', 'B2', 'sk'),
('politika', 'B2', 'sk'),
('voľby', 'B2', 'sk'),
('demokracia', 'B2', 'sk'),
('sloboda', 'B2', 'sk'),
('spravodlivosť', 'B2', 'sk'),
('rovnosť', 'B2', 'sk'),
('zákon', 'B2', 'sk'),
('zločin', 'B2', 'sk'),
('pokuta', 'B2', 'sk'),
('trest', 'B2', 'sk'),
('zabezpečenie', 'B2', 'sk'),
('konflikt', 'B2', 'sk'),
('vojnový', 'B2', 'sk'),
('pokoj', 'B2', 'sk'),
('násilie', 'B2', 'sk'),
('terorizmus', 'B2', 'sk'),
('globalizácia', 'B2', 'sk'),
('integrácia', 'B2', 'sk'),
('rozmanitosť', 'B2', 'sk'),
('totožnosť', 'B2', 'sk'),
('migrácia', 'B2', 'sk'),
('utečenec', 'B2', 'sk'),
('komunita', 'B2', 'sk'),
('sieť', 'B2', 'sk'),
('organizácia', 'B2', 'sk'),
('inštitúcia', 'B2', 'sk'),
('vedenie', 'B2', 'sk'),
('riadenie', 'B2', 'sk'),
('plánovanie', 'B2', 'sk'),
('stratégia', 'B2', 'sk'),
('iniciatíva', 'B2', 'sk'),
('tvorivosť', 'B2', 'sk'),
('spolupráca', 'B2', 'sk'),
('tímová práca', 'B2', 'sk'),
('zodpovednosť', 'B2', 'sk'),
('zodpovednosť', 'B2', 'sk'),
('udržateľnosť', 'B2', 'sk'),
('ochrana životného prostredia', 'B2', 'sk'),
('obnoviteľná energia', 'B2', 'sk'),
('inovácia', 'B2', 'sk'),
('kritické myslenie', 'B2', 'sk'),
('riešenie problémov', 'B2', 'sk'),
('rozhodovanie', 'B2', 'sk'),
('riadenie času', 'B2', 'sk'),
('sebadisciplína', 'B2', 'sk'),
('prispôsobenie', 'B2', 'sk'),
('odolnosť', 'B2', 'sk'),
('nezávislosť', 'B2', 'sk'),
('spolupráca', 'B2', 'sk'),
('dôverovať', 'B2', 'sk'),
('úcta', 'B2', 'sk'),
('empatia', 'B2', 'sk'),
('lojalita', 'B2', 'sk'),
('integrita', 'B2', 'sk'),
('etika', 'B2', 'sk'),
('morálka', 'B2', 'sk'),
('filozofia', 'B2', 'sk'),
('psychológia', 'B2', 'sk'),
('sociológia', 'B2', 'sk'),
('biológia', 'B2', 'sk'),
('chémia', 'B2', 'sk'),
('fyzika', 'B2', 'sk'),
('kritická analýza', 'C1', 'sk'),
('logické zdôvodnenie', 'C1', 'sk'),
('interpretácia', 'C1', 'sk'),
('hlboké porovnanie', 'C1', 'sk'),
('vedecký záver', 'C1', 'sk'),
('komplexná hypotéza', 'C1', 'sk'),
('pokročilá teória', 'C1', 'sk'),
('hĺbkový experiment', 'C1', 'sk'),
('komplexné hodnotenie', 'C1', 'sk'),
('filozofická diskusia', 'C1', 'sk'),
('silný argument', 'C1', 'sk'),
('hmatateľný dôkaz', 'C1', 'sk'),
('protichodné dôkazy', 'C1', 'sk'),
('koncept', 'C1', 'sk'),
('etická poloha', 'C1', 'sk'),
('najvyššia hodnota', 'C1', 'sk'),
('zásadný princíp', 'C1', 'sk'),
('najvyššia priorita', 'C1', 'sk'),
('hlavná zodpovednosť', 'C1', 'sk'),
('rozhodujúce rozhodnutie', 'C1', 'sk'),
('komplexné riadenie', 'C1', 'sk'),
('strategické plánovanie', 'C1', 'sk'),
('udržateľný rozvoj', 'C1', 'sk'),
('moderná inovácia', 'C1', 'sk'),
('pokročilá kreativita', 'C1', 'sk'),
('nový objav', 'C1', 'sk'),
('inovatívny vynález', 'C1', 'sk'),
('hospodárska analýza', 'C1', 'sk'),
('finančná správa', 'C1', 'sk'),
('rozsiahly projekt', 'C1', 'sk'),
('medzinárodné rokovania', 'C1', 'sk'),
('formálna dohoda', 'C1', 'sk'),
('efektívna stratégia', 'C1', 'sk'),
('globálna inštitúcia', 'C1', 'sk'),
('výskumné centrum', 'C1', 'sk'),
('pokročilé vedecké štúdium', 'C1', 'sk'),
('kritický prehľad', 'C1', 'sk'),
('filozofická interpretácia', 'C1', 'sk'),
('systematický prístup', 'C1', 'sk'),
('moderná teória', 'C1', 'sk'),
('aplikovaný výskum', 'C1', 'sk'),
('praktický experiment', 'C1', 'sk'),
('objektívne hodnotenie', 'C1', 'sk'),
('podrobné výsledky', 'C1', 'sk'),
('pokročilá debata', 'C1', 'sk'),
('porovnávacia štúdia', 'C1', 'sk'),
('terénny výskum', 'C1', 'sk'),
('praktické odporúčanie', 'C1', 'sk'),
('pokročilá zručnosť', 'C1', 'sk'),
('koncepčný rámec', 'C1', 'sk'),
('presné plánovanie', 'C1', 'sk'),
('dlhodobá stratégia', 'C1', 'sk'),
('hodnotenie rizika', 'C1', 'sk'),
('akademický prehľad', 'C1', 'sk'),
('výskumný projekt', 'C1', 'sk'),
('vedecká inovácia', 'C1', 'sk'),
('technologický rozvoj', 'C1', 'sk'),
('literárna analýza', 'C1', 'sk'),
('vedecké zistenia', 'C1', 'sk'),
('pokročilá interpretácia', 'C1', 'sk'),
('holistický pohľad', 'C1', 'sk'),
('implementačný plán', 'C1', 'sk'),
('strategické rozhodnutie', 'C1', 'sk'),
('riadenie zdrojov', 'C1', 'sk'),
('komplexné výzvy', 'C1', 'sk'),
('inovatívne riešenia', 'C1', 'sk'),
('komplexný prístup', 'C1', 'sk'),
('analýza údajov', 'C1', 'sk'),
('testovanie hypotéz', 'C1', 'sk'),
('prípadová štúdia', 'C1', 'sk'),
('pokročilé terénne práce', 'C1', 'sk'),
('filozofické preskúmanie', 'C1', 'sk'),
('aplikovaný výskumný projekt', 'C1', 'sk'),
('akademická diskusia', 'C1', 'sk'),
('strategické hodnotenie', 'C1', 'sk'),
('praktické odporúčania', 'C1', 'sk'),
('pracovný plán', 'C1', 'sk'),
('riadenie projektov', 'C1', 'sk'),
('akademická publikácia', 'C1', 'sk'),
('vedecký objav', 'C1', 'sk'),
('aplikovaná inovácia', 'C1', 'sk'),
('nepretržitý rozvoj', 'C1', 'sk'),
('hĺbková analýza údajov', 'C1', 'sk'),
('výskumné skúsenosti', 'C1', 'sk'),
('vedecký výklad', 'C1', 'sk'),
('kritická perspektíva', 'C1', 'sk');
