INSERT INTO words (word, level, language_code) VALUES
('casa', 'A1', 'es'),
('puerta', 'A1', 'es'),
('ventana', 'A1', 'es'),
('mesa', 'A1', 'es'),
('silla', 'A1', 'es'),
('libro', 'A1', 'es'),
('bolígrafo', 'A1', 'es'),
('escuela', 'A1', 'es'),
('maestro', 'A1', 'es'),
('alumno', 'A1', 'es'),
('manzana', 'A1', 'es'),
('agua', 'A1', 'es'),
('alimento', 'A1', 'es'),
('auto', 'A1', 'es'),
('autobús', 'A1', 'es'),
('calle', 'A1', 'es'),
('amigo', 'A1', 'es'),
('familia', 'A1', 'es'),
('madre', 'A1', 'es'),
('padre', 'A1', 'es'),
('hermana', 'A1', 'es'),
('hermano', 'A1', 'es'),
('día', 'A1', 'es'),
('noche', 'A1', 'es'),
('mañana', 'A1', 'es'),
('noche', 'A1', 'es'),
('Hola', 'A1', 'es'),
('adiós', 'A1', 'es'),
('por favor', 'A1', 'es'),
('gracias', 'A1', 'es'),
('Sí', 'A1', 'es'),
('No', 'A1', 'es'),
('rojo', 'A1', 'es'),
('azul', 'A1', 'es'),
('verde', 'A1', 'es'),
('blanco', 'A1', 'es'),
('negro', 'A1', 'es'),
('pequeño', 'A1', 'es'),
('grande', 'A1', 'es'),
('bien', 'A1', 'es'),
('malo', 'A1', 'es'),
('caliente', 'A1', 'es'),
('frío', 'A1', 'es'),
('café', 'A1', 'es'),
('té', 'A1', 'es'),
('dinero', 'A1', 'es'),
('trabajar', 'A1', 'es'),
('hogar', 'A1', 'es'),
('comercio', 'A1', 'es'),
('mercado', 'A1', 'es'),
('alimento', 'A1', 'es'),
('beber', 'A1', 'es'),
('ciudad', 'A1', 'es'),
('parque', 'A1', 'es'),
('calle', 'A1', 'es'),
('parada de autobús', 'A1', 'es'),
('tren', 'A1', 'es'),
('estación', 'A1', 'es'),
('hotel', 'A1', 'es'),
('habitación', 'A1', 'es'),
('cama', 'A1', 'es'),
('doctor', 'A1', 'es'),
('hospital', 'A1', 'es'),
('escuela', 'A1', 'es'),
('universidad', 'A1', 'es'),
('computadora', 'A1', 'es'),
('teléfono', 'A1', 'es'),
('televisión', 'A1', 'es'),
('música', 'A1', 'es'),
('canción', 'A1', 'es'),
('película', 'A1', 'es'),
('juego', 'A1', 'es'),
('fútbol americano', 'A1', 'es'),
('pelota', 'A1', 'es'),
('agua', 'A1', 'es'),
('lluvia', 'A1', 'es'),
('sol', 'A1', 'es'),
('cielo', 'A1', 'es'),
('árbol', 'A1', 'es'),
('flor', 'A1', 'es'),
('animal', 'A1', 'es'),
('gato', 'A1', 'es'),
('perro', 'A1', 'es'),
('pájaro', 'A1', 'es'),
('pez', 'A1', 'es'),
('hombre', 'A1', 'es'),
('mujer', 'A1', 'es'),
('niño', 'A1', 'es'),
('gente', 'A1', 'es'),
('calle', 'A1', 'es'),
('lugar', 'A1', 'es'),
('tiempo', 'A1', 'es'),
('año', 'A1', 'es'),
('mes', 'A1', 'es'),
('semana', 'A1', 'es'),
('hoy', 'A1', 'es'),
('mañana', 'A1', 'es'),
('ayer', 'A1', 'es'),
('nombre', 'A1', 'es'),
('DIRECCIÓN', 'A1', 'es'),
('número', 'A1', 'es'),
('aeropuerto', 'A2', 'es'),
('vuelo', 'A2', 'es'),
('boleto', 'A2', 'es'),
('pasaporte', 'A2', 'es'),
('viajar', 'A2', 'es'),
('día festivo', 'A2', 'es'),
('viaje', 'A2', 'es'),
('equipaje', 'A2', 'es'),
('estación', 'A2', 'es'),
('plataforma', 'A2', 'es'),
('restaurante', 'A2', 'es'),
('cafetería', 'A2', 'es'),
('desayuno', 'A2', 'es'),
('almuerzo', 'A2', 'es'),
('cena', 'A2', 'es'),
('verduras', 'A2', 'es'),
('fruta', 'A2', 'es'),
('carne', 'A2', 'es'),
('pollo', 'A2', 'es'),
('carne de res', 'A2', 'es'),
('pez', 'A2', 'es'),
('pan', 'A2', 'es'),
('arroz', 'A2', 'es'),
('pastas', 'A2', 'es'),
('sopa', 'A2', 'es'),
('azúcar', 'A2', 'es'),
('sal', 'A2', 'es'),
('pimienta', 'A2', 'es'),
('aceite', 'A2', 'es'),
('compras', 'A2', 'es'),
('ropa', 'A2', 'es'),
('camisa', 'A2', 'es'),
('pantalones', 'A2', 'es'),
('vestido', 'A2', 'es'),
('zapatos', 'A2', 'es'),
('sombrero', 'A2', 'es'),
('chaqueta', 'A2', 'es'),
('abrigo', 'A2', 'es'),
('clima', 'A2', 'es'),
('nieve', 'A2', 'es'),
('viento', 'A2', 'es'),
('tormenta', 'A2', 'es'),
('hoteles', 'A2', 'es'),
('invitado', 'A2', 'es'),
('servicio', 'A2', 'es'),
('recepción', 'A2', 'es'),
('llave', 'A2', 'es'),
('reserva', 'A2', 'es'),
('playa', 'A2', 'es'),
('mar', 'A2', 'es'),
('nadar', 'A2', 'es'),
('piscina', 'A2', 'es'),
('montaña', 'A2', 'es'),
('aldea', 'A2', 'es'),
('país', 'A2', 'es'),
('idioma', 'A2', 'es'),
('extranjero', 'A2', 'es'),
('examen', 'A2', 'es'),
('prueba', 'A2', 'es'),
('tarea', 'A2', 'es'),
('aula', 'A2', 'es'),
('sujeto', 'A2', 'es'),
('matemáticas', 'A2', 'es'),
('historia', 'A2', 'es'),
('ciencia', 'A2', 'es'),
('biblioteca', 'A2', 'es'),
('librería', 'A2', 'es'),
('computadora', 'A2', 'es'),
('Internet', 'A2', 'es'),
('correo electrónico', 'A2', 'es'),
('mensaje', 'A2', 'es'),
('carta', 'A2', 'es'),
('correo', 'A2', 'es'),
('banco', 'A2', 'es'),
('dinero', 'A2', 'es'),
('tarjeta de crédito', 'A2', 'es'),
('precio', 'A2', 'es'),
('barato', 'A2', 'es'),
('caro', 'A2', 'es'),
('pregunta', 'A2', 'es'),
('respuesta', 'A2', 'es'),
('explicar', 'A2', 'es'),
('ayuda', 'A2', 'es'),
('problema', 'A2', 'es'),
('solución', 'A2', 'es'),
('salud', 'A2', 'es'),
('medicamento', 'A2', 'es'),
('doctor', 'A2', 'es'),
('enfermero', 'A2', 'es'),
('paciente', 'A2', 'es'),
('cita', 'A2', 'es'),
('fiebre', 'A2', 'es'),
('tos', 'A2', 'es'),
('experiencia', 'B1', 'es'),
('aventura', 'B1', 'es'),
('opinión', 'B1', 'es'),
('discusión', 'B1', 'es'),
('argumento', 'B1', 'es'),
('decisión', 'B1', 'es'),
('razón', 'B1', 'es'),
('oportunidad', 'B1', 'es'),
('desafío', 'B1', 'es'),
('éxito', 'B1', 'es'),
('falla', 'B1', 'es'),
('meta', 'B1', 'es'),
('plan', 'B1', 'es'),
('proyecto', 'B1', 'es'),
('conocimiento', 'B1', 'es'),
('habilidad', 'B1', 'es'),
('capacidad', 'B1', 'es'),
('mejora', 'B1', 'es'),
('capacitación', 'B1', 'es'),
('entrevista de trabajo', 'B1', 'es'),
('solicitud', 'B1', 'es'),
('carrera', 'B1', 'es'),
('gerente', 'B1', 'es'),
('colega', 'B1', 'es'),
('reunión', 'B1', 'es'),
('tarea', 'B1', 'es'),
('responsabilidad', 'B1', 'es'),
('viaje de vacaciones', 'B1', 'es'),
('cultura', 'B1', 'es'),
('tradición', 'B1', 'es'),
('costumbre', 'B1', 'es'),
('festival', 'B1', 'es'),
('celebración', 'B1', 'es'),
('actuación', 'B1', 'es'),
('concierto', 'B1', 'es'),
('teatro', 'B1', 'es'),
('exhibición', 'B1', 'es'),
('cuadro', 'B1', 'es'),
('escultura', 'B1', 'es'),
('museo', 'B1', 'es'),
('libro de historia', 'B1', 'es'),
('ficción', 'B1', 'es'),
('poema', 'B1', 'es'),
('novedoso', 'B1', 'es'),
('personaje', 'B1', 'es'),
('trama', 'B1', 'es'),
('historia', 'B1', 'es'),
('periódico', 'B1', 'es'),
('revista', 'B1', 'es'),
('artículo', 'B1', 'es'),
('informe', 'B1', 'es'),
('presentación', 'B1', 'es'),
('conferencia', 'B1', 'es'),
('educación', 'B1', 'es'),
('universidad', 'B1', 'es'),
('grado', 'B1', 'es'),
('diploma', 'B1', 'es'),
('certificado', 'B1', 'es'),
('ambiente', 'B1', 'es'),
('naturaleza', 'B1', 'es'),
('reciclaje', 'B1', 'es'),
('contaminación', 'B1', 'es'),
('cambio climático', 'B1', 'es'),
('calentamiento global', 'B1', 'es'),
('energía', 'B1', 'es'),
('tecnología', 'B1', 'es'),
('innovación', 'B1', 'es'),
('invención', 'B1', 'es'),
('dispositivo', 'B1', 'es'),
('máquina', 'B1', 'es'),
('programa de computadora', 'B1', 'es'),
('sitio web', 'B1', 'es'),
('solicitud', 'B1', 'es'),
('redes sociales', 'B1', 'es'),
('comunicación', 'B1', 'es'),
('conversación', 'B1', 'es'),
('interacción', 'B1', 'es'),
('relación', 'B1', 'es'),
('amistad', 'B1', 'es'),
('casamiento', 'B1', 'es'),
('vida familiar', 'B1', 'es'),
('felicidad', 'B1', 'es'),
('enojo', 'B1', 'es'),
('miedo', 'B1', 'es'),
('esperanza', 'B1', 'es'),
('sueño', 'B1', 'es'),
('ambición', 'B1', 'es'),
('motivación', 'B1', 'es'),
('confianza', 'B1', 'es'),
('curiosidad', 'B1', 'es'),
('paciencia', 'B1', 'es'),
('innovación', 'B2', 'es'),
('desarrollo', 'B2', 'es'),
('investigación', 'B2', 'es'),
('análisis', 'B2', 'es'),
('interpretación', 'B2', 'es'),
('argumentación', 'B2', 'es'),
('comparación', 'B2', 'es'),
('hipótesis', 'B2', 'es'),
('teoría', 'B2', 'es'),
('experimento', 'B2', 'es'),
('evidencia', 'B2', 'es'),
('método', 'B2', 'es'),
('conclusión', 'B2', 'es'),
('observación', 'B2', 'es'),
('perspectiva', 'B2', 'es'),
('suposición', 'B2', 'es'),
('contexto', 'B2', 'es'),
('criterios', 'B2', 'es'),
('principio', 'B2', 'es'),
('prioridad', 'B2', 'es'),
('complejidad', 'B2', 'es'),
('eficiencia', 'B2', 'es'),
('productividad', 'B2', 'es'),
('inversión', 'B2', 'es'),
('economía', 'B2', 'es'),
('finanzas', 'B2', 'es'),
('negociación', 'B2', 'es'),
('acuerdo', 'B2', 'es'),
('contrato', 'B2', 'es'),
('política', 'B2', 'es'),
('gobierno', 'B2', 'es'),
('política', 'B2', 'es'),
('elección', 'B2', 'es'),
('democracia', 'B2', 'es'),
('libertad', 'B2', 'es'),
('justicia', 'B2', 'es'),
('igualdad', 'B2', 'es'),
('ley', 'B2', 'es'),
('delito', 'B2', 'es'),
('pena', 'B2', 'es'),
('castigo', 'B2', 'es'),
('seguridad', 'B2', 'es'),
('conflicto', 'B2', 'es'),
('guerra', 'B2', 'es'),
('paz', 'B2', 'es'),
('violencia', 'B2', 'es'),
('terrorismo', 'B2', 'es'),
('globalización', 'B2', 'es'),
('integración', 'B2', 'es'),
('diversidad', 'B2', 'es'),
('identidad', 'B2', 'es'),
('migración', 'B2', 'es'),
('refugiado', 'B2', 'es'),
('comunidad', 'B2', 'es'),
('red', 'B2', 'es'),
('organización', 'B2', 'es'),
('institución', 'B2', 'es'),
('liderazgo', 'B2', 'es'),
('gestión', 'B2', 'es'),
('planificación', 'B2', 'es'),
('estrategia', 'B2', 'es'),
('iniciativa', 'B2', 'es'),
('creatividad', 'B2', 'es'),
('colaboración', 'B2', 'es'),
('trabajo en equipo', 'B2', 'es'),
('responsabilidad', 'B2', 'es'),
('responsabilidad', 'B2', 'es'),
('sostenibilidad', 'B2', 'es'),
('protección ambiental', 'B2', 'es'),
('energía renovable', 'B2', 'es'),
('proceso de innovación', 'B2', 'es'),
('pensamiento crítico', 'B2', 'es'),
('resolución de problemas', 'B2', 'es'),
('Toma de decisiones', 'B2', 'es'),
('gestión del tiempo', 'B2', 'es'),
('autodisciplina', 'B2', 'es'),
('adaptación', 'B2', 'es'),
('resiliencia', 'B2', 'es'),
('independencia', 'B2', 'es'),
('cooperación', 'B2', 'es'),
('confianza', 'B2', 'es'),
('respeto', 'B2', 'es'),
('empatía', 'B2', 'es'),
('lealtad', 'B2', 'es'),
('integridad', 'B2', 'es'),
('ética', 'B2', 'es'),
('moralidad', 'B2', 'es'),
('filosofía', 'B2', 'es'),
('psicología', 'B2', 'es'),
('sociología', 'B2', 'es'),
('biología', 'B2', 'es'),
('química', 'B2', 'es'),
('física', 'B2', 'es'),
('análisis crítico', 'C1', 'es'),
('razonamiento lógico', 'C1', 'es'),
('interpretación', 'C1', 'es'),
('comparación profunda', 'C1', 'es'),
('conclusión científica', 'C1', 'es'),
('hipótesis compleja', 'C1', 'es'),
('teoría avanzada', 'C1', 'es'),
('experimento en profundidad', 'C1', 'es'),
('evaluación integral', 'C1', 'es'),
('discusión filosófica', 'C1', 'es'),
('argumento fuerte', 'C1', 'es'),
('evidencia tangible', 'C1', 'es'),
('evidencia contradictoria', 'C1', 'es'),
('concepto abstracto', 'C1', 'es'),
('posición ética', 'C1', 'es'),
('valor supremo', 'C1', 'es'),
('principio fundamental', 'C1', 'es'),
('prioridad', 'C1', 'es'),
('mayor responsabilidad', 'C1', 'es'),
('decisión crucial', 'C1', 'es'),
('gestión compleja', 'C1', 'es'),
('planificación estratégica', 'C1', 'es'),
('desarrollo sostenible', 'C1', 'es'),
('innovación moderna', 'C1', 'es'),
('creatividad avanzada', 'C1', 'es'),
('Nuevo descubrimiento', 'C1', 'es'),
('invención innovadora', 'C1', 'es'),
('análisis económico', 'C1', 'es'),
('informe financiero', 'C1', 'es'),
('proyecto a gran escala', 'C1', 'es'),
('negociaciones internacionales', 'C1', 'es'),
('acuerdo formal', 'C1', 'es'),
('estrategia efectiva', 'C1', 'es'),
('institución global', 'C1', 'es'),
('centro de investigación', 'C1', 'es'),
('Estudio científico avanzado', 'C1', 'es'),
('revisión crítica', 'C1', 'es'),
('interpretación filosófica', 'C1', 'es'),
('enfoque sistemático', 'C1', 'es'),
('teoría moderna', 'C1', 'es'),
('investigación aplicada', 'C1', 'es'),
('experimento práctico', 'C1', 'es'),
('evaluación objetiva', 'C1', 'es'),
('Resultados detallados', 'C1', 'es'),
('debate avanzado', 'C1', 'es'),
('estudio comparativo', 'C1', 'es'),
('investigación de campo', 'C1', 'es'),
('recomendación práctica', 'C1', 'es'),
('habilidad avanzada', 'C1', 'es'),
('marco conceptual', 'C1', 'es'),
('planificación precisa', 'C1', 'es'),
('Estrategia a largo plazo', 'C1', 'es'),
('Evaluación de riesgos', 'C1', 'es'),
('revisión académica', 'C1', 'es'),
('proyecto de investigación', 'C1', 'es'),
('innovación científica', 'C1', 'es'),
('desarrollo tecnológico', 'C1', 'es'),
('análisis literario', 'C1', 'es'),
('hallazgos científicos', 'C1', 'es'),
('interpretación avanzada', 'C1', 'es'),
('visión holística', 'C1', 'es'),
('plan de implementación', 'C1', 'es'),
('decisión estratégica', 'C1', 'es'),
('gestión de recursos', 'C1', 'es'),
('Desafíos complejos', 'C1', 'es'),
('soluciones innovadoras', 'C1', 'es'),
('enfoque integral', 'C1', 'es'),
('análisis de datos', 'C1', 'es'),
('prueba de hipótesis', 'C1', 'es'),
('estudio de caso', 'C1', 'es'),
('trabajo de campo avanzado', 'C1', 'es'),
('revisión filosófica', 'C1', 'es'),
('Proyecto de investigación aplicada', 'C1', 'es'),
('discusión académica', 'C1', 'es'),
('evaluación estratégica', 'C1', 'es'),
('Recomendaciones prácticas', 'C1', 'es'),
('plan de trabajo', 'C1', 'es'),
('gestión de proyectos', 'C1', 'es'),
('publicación académica', 'C1', 'es'),
('descubrimiento científico', 'C1', 'es'),
('innovación aplicada', 'C1', 'es'),
('desarrollo continuo', 'C1', 'es'),
('Análisis de datos en profundidad', 'C1', 'es'),
('experiencia de investigación', 'C1', 'es'),
('interpretación científica', 'C1', 'es'),
('perspectiva crítica', 'C1', 'es');
