INSERT INTO words (word, level, language_code) VALUES
('ev', 'A1', 'tr'),
('kapı', 'A1', 'tr'),
('pencere', 'A1', 'tr'),
('masa', 'A1', 'tr'),
('sandalye', 'A1', 'tr'),
('kitap', 'A1', 'tr'),
('dolma kalem', 'A1', 'tr'),
('okul', 'A1', 'tr'),
('Öğretmen', 'A1', 'tr'),
('öğrenci', 'A1', 'tr'),
('elma', 'A1', 'tr'),
('su', 'A1', 'tr'),
('yiyecek', 'A1', 'tr'),
('araba', 'A1', 'tr'),
('otobüs', 'A1', 'tr'),
('sokak', 'A1', 'tr'),
('arkadaş', 'A1', 'tr'),
('aile', 'A1', 'tr'),
('anne', 'A1', 'tr'),
('baba', 'A1', 'tr'),
('kız kardeş', 'A1', 'tr'),
('Erkek kardeş', 'A1', 'tr'),
('gün', 'A1', 'tr'),
('gece', 'A1', 'tr'),
('Sabah', 'A1', 'tr'),
('akşam', 'A1', 'tr'),
('Merhaba', 'A1', 'tr'),
('Güle güle', 'A1', 'tr'),
('Lütfen', 'A1', 'tr'),
('Teşekkürler', 'A1', 'tr'),
('Evet', 'A1', 'tr'),
('HAYIR', 'A1', 'tr'),
('kırmızı', 'A1', 'tr'),
('mavi', 'A1', 'tr'),
('yeşil', 'A1', 'tr'),
('beyaz', 'A1', 'tr'),
('siyah', 'A1', 'tr'),
('küçük', 'A1', 'tr'),
('büyük', 'A1', 'tr'),
('iyi', 'A1', 'tr'),
('kötü', 'A1', 'tr'),
('sıcak', 'A1', 'tr'),
('soğuk', 'A1', 'tr'),
('Kahve', 'A1', 'tr'),
('çay', 'A1', 'tr'),
('para', 'A1', 'tr'),
('iş', 'A1', 'tr'),
('Ev', 'A1', 'tr'),
('mağaza', 'A1', 'tr'),
('pazar', 'A1', 'tr'),
('yiyecek', 'A1', 'tr'),
('içmek', 'A1', 'tr'),
('şehir', 'A1', 'tr'),
('park', 'A1', 'tr'),
('sokak', 'A1', 'tr'),
('otobüs durağı', 'A1', 'tr'),
('tren', 'A1', 'tr'),
('istasyon', 'A1', 'tr'),
('otel', 'A1', 'tr'),
('oda', 'A1', 'tr'),
('yatak', 'A1', 'tr'),
('doktor', 'A1', 'tr'),
('hastane', 'A1', 'tr'),
('okul', 'A1', 'tr'),
('üniversite', 'A1', 'tr'),
('bilgisayar', 'A1', 'tr'),
('telefon', 'A1', 'tr'),
('televizyon', 'A1', 'tr'),
('müzik', 'A1', 'tr'),
('şarkı', 'A1', 'tr'),
('film', 'A1', 'tr'),
('oyun', 'A1', 'tr'),
('futbol', 'A1', 'tr'),
('top', 'A1', 'tr'),
('su', 'A1', 'tr'),
('yağmur', 'A1', 'tr'),
('güneş', 'A1', 'tr'),
('gökyüzü', 'A1', 'tr'),
('ağaç', 'A1', 'tr'),
('çiçek', 'A1', 'tr'),
('hayvan', 'A1', 'tr'),
('kedi', 'A1', 'tr'),
('köpek', 'A1', 'tr'),
('kuş', 'A1', 'tr'),
('balık', 'A1', 'tr'),
('Adam', 'A1', 'tr'),
('kadın', 'A1', 'tr'),
('çocuk', 'A1', 'tr'),
('insanlar', 'A1', 'tr'),
('sokak', 'A1', 'tr'),
('yer', 'A1', 'tr'),
('zaman', 'A1', 'tr'),
('yıl', 'A1', 'tr'),
('ay', 'A1', 'tr'),
('hafta', 'A1', 'tr'),
('Bugün', 'A1', 'tr'),
('Yarın', 'A1', 'tr'),
('Dün', 'A1', 'tr'),
('isim', 'A1', 'tr'),
('adres', 'A1', 'tr'),
('sayı', 'A1', 'tr'),
('havalimanı', 'A2', 'tr'),
('uçuş', 'A2', 'tr'),
('bilet', 'A2', 'tr'),
('pasaport', 'A2', 'tr'),
('seyahat', 'A2', 'tr'),
('tatil', 'A2', 'tr'),
('seyahat', 'A2', 'tr'),
('bagaj', 'A2', 'tr'),
('istasyon', 'A2', 'tr'),
('platform', 'A2', 'tr'),
('restoran', 'A2', 'tr'),
('kafe', 'A2', 'tr'),
('kahvaltı', 'A2', 'tr'),
('öğle yemeği', 'A2', 'tr'),
('akşam yemeği', 'A2', 'tr'),
('sebze', 'A2', 'tr'),
('meyve', 'A2', 'tr'),
('et', 'A2', 'tr'),
('tavuk', 'A2', 'tr'),
('biftek', 'A2', 'tr'),
('balık', 'A2', 'tr'),
('ekmek', 'A2', 'tr'),
('pirinç', 'A2', 'tr'),
('makarna', 'A2', 'tr'),
('çorba', 'A2', 'tr'),
('şeker', 'A2', 'tr'),
('tuz', 'A2', 'tr'),
('biber', 'A2', 'tr'),
('yağ', 'A2', 'tr'),
('alışveriş', 'A2', 'tr'),
('kıyafetler', 'A2', 'tr'),
('gömlek', 'A2', 'tr'),
('pantolonlar', 'A2', 'tr'),
('elbise', 'A2', 'tr'),
('ayakkabı', 'A2', 'tr'),
('şapka', 'A2', 'tr'),
('ceket', 'A2', 'tr'),
('kaban', 'A2', 'tr'),
('hava durumu', 'A2', 'tr'),
('kar', 'A2', 'tr'),
('rüzgâr', 'A2', 'tr'),
('fırtına', 'A2', 'tr'),
('otel', 'A2', 'tr'),
('misafir', 'A2', 'tr'),
('hizmet vermek', 'A2', 'tr'),
('resepsiyon', 'A2', 'tr'),
('anahtar', 'A2', 'tr'),
('rezervasyon', 'A2', 'tr'),
('sahil', 'A2', 'tr'),
('deniz', 'A2', 'tr'),
('yüzme', 'A2', 'tr'),
('havuz', 'A2', 'tr'),
('dağ', 'A2', 'tr'),
('köy', 'A2', 'tr'),
('ülke', 'A2', 'tr'),
('dil', 'A2', 'tr'),
('yabancı', 'A2', 'tr'),
('sınav', 'A2', 'tr'),
('test', 'A2', 'tr'),
('Ev ödevi', 'A2', 'tr'),
('sınıf', 'A2', 'tr'),
('ders', 'A2', 'tr'),
('matematik', 'A2', 'tr'),
('tarih', 'A2', 'tr'),
('bilim', 'A2', 'tr'),
('kütüphane', 'A2', 'tr'),
('kitapçı', 'A2', 'tr'),
('bilgisayar', 'A2', 'tr'),
('internet', 'A2', 'tr'),
('e -posta', 'A2', 'tr'),
('mesaj', 'A2', 'tr'),
('mektup', 'A2', 'tr'),
('postalamak', 'A2', 'tr'),
('banka', 'A2', 'tr'),
('para', 'A2', 'tr'),
('kredi kartı', 'A2', 'tr'),
('fiyat', 'A2', 'tr'),
('ucuz', 'A2', 'tr'),
('masraflı', 'A2', 'tr'),
('soru', 'A2', 'tr'),
('cevap', 'A2', 'tr'),
('açıklamak', 'A2', 'tr'),
('yardım', 'A2', 'tr'),
('sorun', 'A2', 'tr'),
('çözüm', 'A2', 'tr'),
('sağlık', 'A2', 'tr'),
('ilaç', 'A2', 'tr'),
('doktor', 'A2', 'tr'),
('hemşire', 'A2', 'tr'),
('hasta', 'A2', 'tr'),
('randevu', 'A2', 'tr'),
('ateş', 'A2', 'tr'),
('öksürük', 'A2', 'tr'),
('deneyim', 'B1', 'tr'),
('macera', 'B1', 'tr'),
('fikir', 'B1', 'tr'),
('tartışma', 'B1', 'tr'),
('argüman', 'B1', 'tr'),
('karar', 'B1', 'tr'),
('sebep', 'B1', 'tr'),
('fırsat', 'B1', 'tr'),
('meydan okumak', 'B1', 'tr'),
('başarı', 'B1', 'tr'),
('arıza', 'B1', 'tr'),
('amaç', 'B1', 'tr'),
('planlamak', 'B1', 'tr'),
('proje', 'B1', 'tr'),
('bilgi', 'B1', 'tr'),
('yetenek', 'B1', 'tr'),
('yetenek', 'B1', 'tr'),
('gelişim', 'B1', 'tr'),
('eğitim', 'B1', 'tr'),
('iş görüşmesi', 'B1', 'tr'),
('başvuru', 'B1', 'tr'),
('kariyer', 'B1', 'tr'),
('müdür', 'B1', 'tr'),
('iş arkadaşı', 'B1', 'tr'),
('toplantı', 'B1', 'tr'),
('görev', 'B1', 'tr'),
('sorumluluk', 'B1', 'tr'),
('tatil gezisi', 'B1', 'tr'),
('kültür', 'B1', 'tr'),
('gelenek', 'B1', 'tr'),
('gelenek', 'B1', 'tr'),
('festival', 'B1', 'tr'),
('kutlama', 'B1', 'tr'),
('performans', 'B1', 'tr'),
('konser', 'B1', 'tr'),
('tiyatro', 'B1', 'tr'),
('sergi', 'B1', 'tr'),
('tablo', 'B1', 'tr'),
('heykel', 'B1', 'tr'),
('müze', 'B1', 'tr'),
('tarih kitabı', 'B1', 'tr'),
('kurgu', 'B1', 'tr'),
('şiir', 'B1', 'tr'),
('roman', 'B1', 'tr'),
('karakter', 'B1', 'tr'),
('komplo', 'B1', 'tr'),
('hikaye', 'B1', 'tr'),
('gazete', 'B1', 'tr'),
('dergi', 'B1', 'tr'),
('madde', 'B1', 'tr'),
('rapor', 'B1', 'tr'),
('sunum', 'B1', 'tr'),
('konferans', 'B1', 'tr'),
('eğitim', 'B1', 'tr'),
('üniversite', 'B1', 'tr'),
('derece', 'B1', 'tr'),
('diploma', 'B1', 'tr'),
('sertifika', 'B1', 'tr'),
('çevre', 'B1', 'tr'),
('doğa', 'B1', 'tr'),
('geri dönüşüm', 'B1', 'tr'),
('kirlilik', 'B1', 'tr'),
('iklim değişikliği', 'B1', 'tr'),
('küresel ısınma', 'B1', 'tr'),
('enerji', 'B1', 'tr'),
('teknoloji', 'B1', 'tr'),
('yenilik', 'B1', 'tr'),
('buluş', 'B1', 'tr'),
('cihaz', 'B1', 'tr'),
('makine', 'B1', 'tr'),
('bilgisayar programı', 'B1', 'tr'),
('web sitesi', 'B1', 'tr'),
('başvuru', 'B1', 'tr'),
('sosyal medya', 'B1', 'tr'),
('iletişim', 'B1', 'tr'),
('konuşma', 'B1', 'tr'),
('etkileşim', 'B1', 'tr'),
('ilişki', 'B1', 'tr'),
('dostluk', 'B1', 'tr'),
('evlilik', 'B1', 'tr'),
('aile hayatı', 'B1', 'tr'),
('mutluluk', 'B1', 'tr'),
('kızgınlık', 'B1', 'tr'),
('korku', 'B1', 'tr'),
('umut', 'B1', 'tr'),
('rüya', 'B1', 'tr'),
('tutku', 'B1', 'tr'),
('motivasyon', 'B1', 'tr'),
('kendinden emin', 'B1', 'tr'),
('merak', 'B1', 'tr'),
('sabır', 'B1', 'tr'),
('yenilik', 'B2', 'tr'),
('gelişim', 'B2', 'tr'),
('araştırma', 'B2', 'tr'),
('analiz', 'B2', 'tr'),
('tercüme', 'B2', 'tr'),
('tartışma', 'B2', 'tr'),
('karşılaştırmak', 'B2', 'tr'),
('hipotez', 'B2', 'tr'),
('teori', 'B2', 'tr'),
('deney', 'B2', 'tr'),
('kanıt', 'B2', 'tr'),
('yöntem', 'B2', 'tr'),
('çözüm', 'B2', 'tr'),
('gözlem', 'B2', 'tr'),
('perspektif', 'B2', 'tr'),
('varsayım', 'B2', 'tr'),
('bağlam', 'B2', 'tr'),
('kriterler', 'B2', 'tr'),
('ilke', 'B2', 'tr'),
('öncelik', 'B2', 'tr'),
('karmaşıklık', 'B2', 'tr'),
('yeterlik', 'B2', 'tr'),
('verimlilik', 'B2', 'tr'),
('yatırım', 'B2', 'tr'),
('ekonomi', 'B2', 'tr'),
('finans', 'B2', 'tr'),
('müzakere', 'B2', 'tr'),
('anlaşma', 'B2', 'tr'),
('sözleşme', 'B2', 'tr'),
('politika', 'B2', 'tr'),
('devlet', 'B2', 'tr'),
('siyaset', 'B2', 'tr'),
('seçim', 'B2', 'tr'),
('demokrasi', 'B2', 'tr'),
('özgürlük', 'B2', 'tr'),
('adalet', 'B2', 'tr'),
('eşitlik', 'B2', 'tr'),
('kanun', 'B2', 'tr'),
('suç', 'B2', 'tr'),
('penaltı', 'B2', 'tr'),
('ceza', 'B2', 'tr'),
('güvenlik', 'B2', 'tr'),
('anlaşmazlık', 'B2', 'tr'),
('savaş', 'B2', 'tr'),
('barış', 'B2', 'tr'),
('şiddet', 'B2', 'tr'),
('terörizm', 'B2', 'tr'),
('küreselleşme', 'B2', 'tr'),
('entegrasyon', 'B2', 'tr'),
('çeşitlilik', 'B2', 'tr'),
('kimlik', 'B2', 'tr'),
('göç', 'B2', 'tr'),
('mülteci', 'B2', 'tr'),
('toplum', 'B2', 'tr'),
('ağ', 'B2', 'tr'),
('organizasyon', 'B2', 'tr'),
('kurum', 'B2', 'tr'),
('liderlik', 'B2', 'tr'),
('yönetmek', 'B2', 'tr'),
('planlama', 'B2', 'tr'),
('strateji', 'B2', 'tr'),
('girişim', 'B2', 'tr'),
('yaratıcılık', 'B2', 'tr'),
('işbirliği', 'B2', 'tr'),
('ekip çalışması', 'B2', 'tr'),
('sorumluluk', 'B2', 'tr'),
('hesap verebilirlik', 'B2', 'tr'),
('sürdürülebilirlik', 'B2', 'tr'),
('Çevre Koruma', 'B2', 'tr'),
('yenilenebilir enerji', 'B2', 'tr'),
('inovasyon süreci', 'B2', 'tr'),
('eleştirel düşünme', 'B2', 'tr'),
('problem çözme', 'B2', 'tr'),
('karar verme', 'B2', 'tr'),
('zaman yönetimi', 'B2', 'tr'),
('öz disiplin', 'B2', 'tr'),
('uyarlama', 'B2', 'tr'),
('esneklik', 'B2', 'tr'),
('bağımsızlık', 'B2', 'tr'),
('işbirliği', 'B2', 'tr'),
('güven', 'B2', 'tr'),
('Saygı', 'B2', 'tr'),
('empati', 'B2', 'tr'),
('bağlılık', 'B2', 'tr'),
('bütünlük', 'B2', 'tr'),
('etik', 'B2', 'tr'),
('ahlak', 'B2', 'tr'),
('felsefe', 'B2', 'tr'),
('psikoloji', 'B2', 'tr'),
('sosyoloji', 'B2', 'tr'),
('biyoloji', 'B2', 'tr'),
('kimya', 'B2', 'tr'),
('fizik', 'B2', 'tr'),
('eleştirel analiz', 'C1', 'tr'),
('mantıksal akıl yürütme', 'C1', 'tr'),
('tercüme', 'C1', 'tr'),
('derin karşılaştırma', 'C1', 'tr'),
('bilimsel sonuç', 'C1', 'tr'),
('karmaşık hipotez', 'C1', 'tr'),
('gelişmiş teori', 'C1', 'tr'),
('derinlemesine deney', 'C1', 'tr'),
('Kapsamlı değerlendirme', 'C1', 'tr'),
('felsefi tartışma', 'C1', 'tr'),
('güçlü tartışma', 'C1', 'tr'),
('somut kanıt', 'C1', 'tr'),
('çelişkili kanıt', 'C1', 'tr'),
('soyut kavram', 'C1', 'tr'),
('etik konum', 'C1', 'tr'),
('yüce değer', 'C1', 'tr'),
('temel ilke', 'C1', 'tr'),
('Birinci Öncelik', 'C1', 'tr'),
('büyük sorumluluk', 'C1', 'tr'),
('önemli karar', 'C1', 'tr'),
('karmaşık yönetim', 'C1', 'tr'),
('Stratejik Planlama', 'C1', 'tr'),
('Sürdürülebilir Kalkınma', 'C1', 'tr'),
('Modern Yenilik', 'C1', 'tr'),
('Gelişmiş Yaratıcılık', 'C1', 'tr'),
('Yeni keşif', 'C1', 'tr'),
('Yenilikçi Buluş', 'C1', 'tr'),
('ekonomik analiz', 'C1', 'tr'),
('finansal rapor', 'C1', 'tr'),
('büyük ölçekli proje', 'C1', 'tr'),
('Uluslararası Müzakereler', 'C1', 'tr'),
('resmi anlaşma', 'C1', 'tr'),
('Etkili strateji', 'C1', 'tr'),
('küresel kurum', 'C1', 'tr'),
('araştırma merkezi', 'C1', 'tr'),
('Gelişmiş Bilimsel Çalışma', 'C1', 'tr'),
('Eleştirel İnceleme', 'C1', 'tr'),
('felsefi yorum', 'C1', 'tr'),
('sistematik yaklaşım', 'C1', 'tr'),
('modern teori', 'C1', 'tr'),
('Uygulamalı Araştırma', 'C1', 'tr'),
('pratik deney', 'C1', 'tr'),
('nesnel değerlendirme', 'C1', 'tr'),
('Ayrıntılı sonuçlar', 'C1', 'tr'),
('Gelişmiş Tartışma', 'C1', 'tr'),
('karşılaştırmalı çalışma', 'C1', 'tr'),
('saha araştırması', 'C1', 'tr'),
('Pratik öneri', 'C1', 'tr'),
('Gelişmiş Beceri', 'C1', 'tr'),
('kavramsal çerçeve', 'C1', 'tr'),
('kesin planlama', 'C1', 'tr'),
('uzun vadeli strateji', 'C1', 'tr'),
('risk değerlendirmesi', 'C1', 'tr'),
('akademik inceleme', 'C1', 'tr'),
('araştırma projesi', 'C1', 'tr'),
('bilimsel yenilik', 'C1', 'tr'),
('teknolojik gelişim', 'C1', 'tr'),
('edebi analiz', 'C1', 'tr'),
('bilimsel bulgular', 'C1', 'tr'),
('gelişmiş yorum', 'C1', 'tr'),
('bütünsel bakış', 'C1', 'tr'),
('uygulama planı', 'C1', 'tr'),
('stratejik karar', 'C1', 'tr'),
('kaynak yönetimi', 'C1', 'tr'),
('karmaşık zorluklar', 'C1', 'tr'),
('Yenilikçi çözümler', 'C1', 'tr'),
('Kapsamlı yaklaşım', 'C1', 'tr'),
('veri analizi', 'C1', 'tr'),
('hipotez testi', 'C1', 'tr'),
('vaka çalışması', 'C1', 'tr'),
('gelişmiş saha çalışması', 'C1', 'tr'),
('Felsefi İnceleme', 'C1', 'tr'),
('Uygulamalı Araştırma Projesi', 'C1', 'tr'),
('akademik tartışma', 'C1', 'tr'),
('stratejik değerlendirme', 'C1', 'tr'),
('Pratik Öneriler', 'C1', 'tr'),
('iş planı', 'C1', 'tr'),
('proje yönetimi', 'C1', 'tr'),
('akademik yayın', 'C1', 'tr'),
('bilimsel keşif', 'C1', 'tr'),
('Uygulamalı İnovasyon', 'C1', 'tr'),
('sürekli gelişim', 'C1', 'tr'),
('derinlemesine veri analizi', 'C1', 'tr'),
('araştırma deneyimi', 'C1', 'tr'),
('bilimsel yorum', 'C1', 'tr'),
('eleştirel bakış açısı', 'C1', 'tr');
